### ISSUE TITLE
BeeSourceful 

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#1]
So I love your mod, I like the idea of the hives, expansion box and even the bees that create resources. I even love the fact that you added some compatibility to BeeSourceful as I prefer the idea of the centrifuge to to get resources over the Bees generating them by themselves.

Though I like to test mods before dropping them into my server, I noticed an issue. His Bees still generate which wouldn't be an issue except they wont use the hives from your mod, Also your bees wont use his Iron Hive. Is this a limitation of Minecraft or Bee's from other mods can't use other hives/nests?

**Comment by JaisDK** [comment]
Hi, thank you for your feedback. I'm glad you like the mod :)
BeeSourceful bees are unfortunately coded to only enter BeeSourceful beehive types and the Iron Beehive is coded to only accept BeeSourceful bee entities. It's on my todo list to get better integration, but it will requires changes to BeeSourceful which I haven't had the time to talk to the author about. Bees and hive from that mod also don't work with vanilla bees.
There is also a bug/limitation in vanilla MC which prevents vanilla bees from staying in modded hives, but I have an open PR in Forge to change that.

**Comment by mouse0270** [comment]
Yeah I assumed it was that. I did find out that he generates a config that allows you to disable his bee generation. Which means I can disable his mod from generating his Nests and just use your Bees and your mod still picks his up which means the bees generate the honeycombs resource instead of the resource,

Speaking of which, I would suggest you add a config that toggles which bees are enabled, its really useful for server admins to be able to control what will spawn in the work.

**Comment by JaisDK** [comment]
Not a bad idea, it would be a config to disable which nests are created, but maybe I can also configure which bees spawn in which nests.
There are around 22 different bees and 17 nests naturally spawning. Disabling the wrong ones might mess up the progression and make it impossible to obtain certain resource producing bees.
