### ISSUE TITLE
Crash Around Bees

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#10]
Assuming its when we try to make the Diamond Bees Breed, but we have had two crashes back to back when interacting with the bees. Here is the crash log

[crash-2020-05-10_23.11.42-server.txt](https://github.com/JDKDigital/productive-bees/files/4607391/crash-2020-05-10_23.11.42-server.txt)

**Comment by JaisDK** [comment]
Is this on 0.1.4 and which two bees were you trying to breed?

**Comment by JaisDK** [comment]
It seems to happen with all bees that do not have any breeding rules to create a new offspring.
