### ISSUE TITLE
Productive Bees do not recognize Beehive or Advanced beehive

### ISSUE THREAD

**Issue by SirSmuggler** [JDKDigital/productive-bees#100]
Version: 1.16.3-0.4.1.4
Issue: Only vanilla bees go into beehive or advanced beehive. The productive bees will only go into the various "nest" variants.

**Comment by JaisDK** [comment]
The bees you are finding are solitary bees, the will not live in hives. You need to find the wild bees in the nether and start breeding to get hive bees.
The recipes should all be in JEI, if you can't find them then the command /reload might help get them to show.
