### ISSUE TITLE
[1.15.2] Source missing build properties (and maybe target for 'mods' directory)

### ISSUE THREAD

**Issue by Wabbit0101** [JDKDigital/productive-bees#102]
Howdy, there seems to be a missing 'build.properties' or equivalent file from the public source code. git cloning and running `./gradlew build` (to generate basic jar) generates error at line: 
```
Build file 'U:\home\me\softdev\...\mods\debug\productive_bees\build.gradle' line: 24
```
I also see a few properties like '`${top_version}`' that are also missing along w/ `mods` directory (assuming there is a build target for 'mods')?

**Comment by JaisDK** [comment]
I put them in the readme. Loaded mods you can comment out or add them yourself if you want to dev with them.
