### ISSUE TITLE
Withered Bee dies while harvesting

### ISSUE THREAD

**Issue by DrGuantanamo** [JDKDigital/productive-bees#104]
First of all: I love this Mod. I love the Bees. :)

From the code (productivebees/entity/bee/hive/WitherBeeEntity.java) it seems that it is intended, that a withered bee should not be(e) affected by the wither effect:
    public boolean isInvulnerableTo(@Nonnull DamageSource source) {
        return source.equals(DamageSource.WITHER) || super.isInvulnerableTo(source);
    }
I guess this should make sure, that you can have more than one bee in a hive and that they can harvest wither roses. But still, they get damaged when approaching the wither rose. Since wither roses are the only food source, I guess this is a bug.

**Comment by JaisDK** [comment]
Glad you like the mod. Which version are you using?

**Comment by DrGuantanamo** [comment]
Sorry. Forgot to mention: productivebees-1.16.3-0.4.0.1

**Comment by JaisDK** [comment]
Can you update to the latest and see if it's still a problem? I think in the version you are having the withered bees also look really weird right?

**Comment by DrGuantanamo** [comment]
Sorry. I am so stupid. I thought that I have the most recent version. 

They look like skeleton bees with black eyes.
Since we are using a modpack-server, updating is not that easy. I will ask the respective admin.

I guess, I can close this issue with the cause: Stupid user does not install latest version before bothering the developer. :)

**Comment by JaisDK** [comment]
Don't worry about it :)

**Comment by DrGuantanamo** [comment]
We updated the server and clients. The Issue is fixed. The withered bees are black now (and not yellow anymore).

**Comment by JaisDK** [comment]
Good to hear :D
