### ISSUE TITLE
Crystalline Bees do not produce comb, but do produce honey

### ISSUE THREAD

**Issue by EDFDarkAngel1** [JDKDigital/productive-bees#107]
Crystalline bees were some of the first bees I used in my 1.16 world, and for a while they did produce crystalline comb. Then one day, they just completely stopped. I changed up everything, and now I have an apiary with nearly all the bees in the game and all are happily producing. Except for the crystalline ones.

They have their own enclosure, with an expanded advanced hive. There are five of them in there, and if I put glass bottles in there, they will produce honey just fine. However, they never produce comb anymore.

They do leave the hive, feed on the nether quartz ore that I have, and their texture changes to the pollinated bee, and they go back into the hive. Everything appears as it should be, just never any crystalline comb.

Furthermore, attempts at breeding the crystalline bee with a compatible bee only produces the other bee. For example, if I breed a crystalline bee with an Ashy Mining Bee, I will get another Ashy Mining Bee. I did this eight times before I realized it wasn't going to produce anything else.

I did kill off all the bees once, and then summoned more by going into creative, but no change. 

Please let me know if you need me to do anything to help diagnose/resolve.

**Comment by JaisDK** [comment]
Most bee entities have been changed to a different type in the last updates. I'm guessing the conversion did not go well for those bees. If you spawn some new ones from a Nether Quartz Nest they should work as expected.
You can speed up the spawning by using Honey Treats on the nest.

**Comment by JaisDK** [comment]
If you're playing 1.16.3, the new update might also fix the bees for you.

**Comment by EDFDarkAngel1** [comment]
Sorry it took me so long to reply to this. I was not able to upgrade my server to 1.16.3 due to other mods, but I was able to use the nests and the honey treats to spawn two bees. From there, I can could breed them and eventually found that they were producing comb. 

Thank you for your help on this.

**Comment by EDFDarkAngel1** [comment]
I also wanted to mention that it didn't work at first, but after I updated Immersive Engineering it worked successfully.

**Comment by JaisDK** [comment]
I don't think IE had anything to do with it, but you never know. Glad you got them working!
