### ISSUE TITLE
[1.16.3] Too many bees!

### ISSUE THREAD

**Issue by lulabyte** [JDKDigital/productive-bees#108]
We're having lag issues and one of the server players was zooming around and found a whole field of bees just hanging out over the ocean. Could be causing our lag issue and the fact that passive mobs don't seem to be spawning, but either way it's no good! Help! Haha, let me know if I can give you any more info.

Forge 1.16.3-34.1.42
Minecraft 1.16.3

We do have quite a few other mods, so it could be a conflict, clearly.

Screenshot:
![2020-11-08_20 21 33](https://user-images.githubusercontent.com/70821058/98500421-4e5d9680-2201-11eb-942b-34c178cbc4f3.png)

**Comment by JaisDK** [comment]
Which version of the mod are you using?

It could very well be the bees, in previous versions of the mod, solitary bees were spawning a lot and then flying out to unloaded chunks getting stuck. In the latest version this spawning has been removed, but the bees that generated will still linger in unloaded chunks.

**Comment by lulabyte** [comment]
Oh boy that is a doozie. Is there any way to fix the world then?

We are using productivebees-1.16.3-0.4.1.4

**Comment by JaisDK** [comment]
flamethrower or kill command would be the fastest options, I'll list the kill commands for the solitary bees ordered by what you are most likely finding out there.

/kill @e[type=productivebees:blue_banded_bee]
/kill @e[type=productivebees:green_carpenter_bee]
/kill @e[type=productivebees:yellow_black_carpenter_bee]
/kill @e[type=productivebees:chocolate_mining_bee]
/kill @e[type=productivebees:ashy_mining_bee]
/kill @e[type=productivebees:digger_bee]
/kill @e[type=productivebees:leafcutter_bee]
/kill @e[type=productivebees:mason_bee]
/kill @e[type=productivebees:reed_bee]
/kill @e[type=productivebees:resin_bee]
/kill @e[type=productivebees:sweaty_bee]
/kill @e[type=productivebees:neon_cuckoo_bee]
/kill @e[type=productivebees:nomad_bee]

**Comment by lulabyte** [comment]
Hey thanks friend

**Comment by NillerMedDild** [comment]
This issue still hasn't been fixed, we've been using the Productive Bees version with the fix on our dev server and has to cull thousands of bees.

**Comment by JaisDK** [comment]
Just to make sure, which version are you on?

**Comment by NillerMedDild** [comment]
To be honest none at the moment, we had to remove it to mitigate lag :/
I believe it was 1.16.1-0.4.0: https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3072824

**Comment by JaisDK** [comment]
that version did not have the fix, it still produced bee eggs in nests

**Comment by JaisDK** [comment]
the specific version where it was removed is not listed, you will need 0.4.1.4

**Comment by NillerMedDild** [comment]
0.4.0 was just a guess, it might've been 0.4.1.4 :P But alright then.

**Comment by JaisDK** [comment]
I'm gonna load up a new world and let it sit for a few days, see if I get the same problem. Do you know if chunks are loaded on a server around spawn when no players are logged in?

**Comment by NillerMedDild** [comment]
Yep they are. The bees I found were scattered in a ~300 block radius around worldspawn.

**Comment by JaisDK** [comment]
Awesome, that makes the test easier

**Comment by lulabyte** [comment]
If I just remove the mod it should take care of the problem though, yeah?

**Comment by JaisDK** [comment]
It will remove all PB entities and blocks from the world

**Comment by JaisDK** [comment]
Had a server running overnight, there's definitely still a problem. I'm guessing bees living in nests right at the border of loaded chunks fly into the unloaded chunks and then the nest repopulate.

I'm gonna disable the automatic repopulation and make it so nests only repopulate if you activate it with a Honey Treat

**Comment by JaisDK** [comment]
In 0.5.x releases the automatic bee repopulation has been disabled. You now have to use a honey treat on an empty nest to make it attract a new bee.
