### ISSUE TITLE
Can't pick up soul sand nests

### ISSUE THREAD

**Issue by vickersk** [JDKDigital/productive-bees#109]
I'm experiencing an issue with picking up soul sand nests, where whenever I try to break them (generated or crafted) with a shovel, pickaxe, fist, or even with silk touch no item is dropped. I am playing on a server with other mods installed which could be part of the problem, but I have yet to come across a similar issue when breaking other nests. I'm playing with the 1.16.3-0.4.1.4 version of the mod.

**Comment by JaisDK** [comment]
It's fixed in dev, the block is missing a loot table.
