### ISSUE TITLE
Does the Centrifuge have inputs/outputs?

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#11]
Basically is it possible to hopper stuff into the centrifuge? I would expect to be able to use either the back or top for glass bottles or the sides for honey combs. Also, can I hopper content out of it via the bottom. I am not sure was I was trying to do this and it wasn't working. Not sure if a bug or something simply not implemented.

**Comment by JaisDK** [comment]
Hopper should work on the bottom and will mitigate the issue described in #12 
Working on getting hoppers to input properly, right now the items just disappear...

**Comment by mouse0270** [comment]
Thanks, I feel like I am just finding all the bugs. Starting to feel like a bother. Great work on the mod so far though!

**Comment by JaisDK** [comment]
Not a bother at all, you are speeding up development a lot. Thank you for reporting what you find!
I'll get a new version up within a few hours with fixes.
