### ISSUE TITLE
All wooden nests face east, no matter placement.

### ISSUE THREAD

**Issue by Withergaming101** [JDKDigital/productive-bees#110]
All wood nests **except for Acacia** face east no matter what direction you are facing.
![image](https://user-images.githubusercontent.com/73364651/99141975-780e2780-261e-11eb-97cc-1f2ac6ca9969.png)

I was facing east while placing these nests. Despite this, only acacia faced back at me. the rest are facing east.

**Comment by JaisDK** [comment]
Thanks for reminding me. The acacia placement is not perfect either, but it's an improvement that I forgot to copy to the others.

**Comment by JaisDK** [comment]
Newest release has the models from Acacia on all the wood nests.
