### ISSUE TITLE
Game crashing when opening Advanced Beehive

### ISSUE THREAD

**Issue by Kvarts1** [JDKDigital/productive-bees#112]
Playing on a modpack: TNP Limitless 3 (https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3)
Playing on a server
Mod Version: 0.4.2.0
Crash log: 
[crash-2020-11-14_19.04.15-client.txt](https://github.com/JDKDigital/productive-bees/files/5541279/crash-2020-11-14_19.04.15-client.txt)

**Comment by JaisDK** [comment]
This happens if you open a hive not having an expansion box and with more than 3 bees. It can happen if you break the expansion box. I have it fixed in dev.

**Comment by Kvarts1** [comment]
But I never had any expansion boxes connected to the beehive.
And it was in an enclosed room where I would assume bees wouldn't be able to go into the beehive.

**Comment by JaisDK** [comment]
I talked with your friend on Discord and as I understand it was fixed by clearing the hive?
The newest version also has a contingency for that part of the code so it won't crash again.
