### ISSUE TITLE
[1.16.4] (.3)

### ISSUE THREAD

**Issue by nanonestor** [JDKDigital/productive-bees#113]
Hi there - I've been including Productive Bees in my modpack and also running said pack on a dedicated server.  Currently it's running 1.16.4 with Forge version 35.0.17.

With the mods currently installed something keeps occurring to worlds where they work great and very smoothly for awhile, and then at some point after a day or two playing the server develops a 5000-15,000 'ticks behind' lag.  I'm not certain but from the logs etc i've seen productive bees show up more than not.  I tried reverting to a previous version of the mod but the server refuses to load and crashes.

Crash log with productive bees 0.5.0.5 rolled back attempt to 0.4.1.4
[https://pastebin.com/PiRSTYr3](url)

I took the same world and booted it up without Productive Bees mod present.  I rebooted the server a few times.  These are the resulting logs.  It does run and load up but still laggy and now has constant running error (below) - where I would have thought anything to do with productive bees would have been removed from the world.

> "[19Nov2020 07:09:05.355] [Server thread/WARN] [net.minecraft.tileentity.TileEntity/]: Skipping BlockEntity with id productivebees:solitary_nest"

Latest.log
[https://pastebin.com/zzxUrNMc](url)
[debug (5).log](https://github.com/JDKDigital/productive-bees/files/5565573/debug.5.log)

Could you have a look and let me know what you think?  Thanks.

**Comment by JaisDK** [comment]
I would expect, after removing the mod, that "Skipping BlockEntity with id productivebees:solitary_nest" will happen every time a chunk, where a solitary nest used to be, is loaded.

Rolling back versions of mods can always be a bit hairy, loading a backup would be better.

As to why it gets so laggy I can't say without running a profiler on the server. I know of this one if you can use that https://www.curseforge.com/minecraft/mc-mods/spark
I don't know how to use it, but If you make a report with it, let me see and I can probably find out what i causing the lag.

**Comment by nanonestor** [comment]
Ok thanks - i'll see about that.  Looks like Spark is Fabric however.

**Comment by JaisDK** [comment]
It's for both, but I can see that they are not uploading they jar files, they are all on their jenkins server. The latest build i for 1.16.4
https://ci.lucko.me/job/spark/

**Comment by nanonestor** [comment]
Ohhh ok! Thanks for the help.

**Comment by nanonestor** [comment]
[https://spark.lucko.me/#H9vS7xEx9H](url)

From the looks of it and monkeying around with removing the mod from the server - looks like it was mostly the 'more living things' mod that was causing entity spam issues or something?  [https://www.curseforge.com/minecraft/mc-mods/living-things](url)

**Comment by JaisDK** [comment]
Thanks for the log, I find it very interesting to see the resource use. You are correct that Living Things use a lot of resources, the Mantaray entity alone is responsible for 9%, most of which seems to be AI related. Sheep and Chickens together also take up 9%, I'm guessing you are having animal farms.

Solitary bees from PB (the ones naturally spawning) take up 1.51%, mostly from pathing.

**Comment by nanonestor** [comment]
Actually no I did not have any large scale mob farms going on.  I mean I had a pen of like 8 sheep or something.  Thanks alot for recommending that 'Spark' utility!  Sending my logs and info to the More Living Things authors.
