### ISSUE TITLE
crash server with productivebees-1.16.3-0.5.0.5

### ISSUE THREAD

**Issue by lampyr** [JDKDigital/productive-bees#115]
hi my server crash but i don't have a crash log.

in the log i can read productive bee.

Can you help me.

https://gist.github.com/lampyr/22b64721c265569ce792e23dffd91531

**Comment by agentwolf88** [comment]
Same problem. Need help!

**Comment by JaisDK** [comment]
@agentwolf88 Can you please provide your debug log from the crashed client/server

@lampyr My nofications completely failed for this issue, if you are still crashing can you also provide a debug log? The one you posted is the latest.log.

**Comment by agentwolf88** [comment]
Sure.

https://gist.github.com/agentwolf88/7da92fb840ff4a3ac6ad48668770a33d

**Comment by lampyr** [comment]
hi for the moment i don't crash with the files you give me on discord.

**Comment by JaisDK** [comment]
ah that was you, excellent :)

@agentwolf88 I have uploaded a fix on my discord that you can also apply if you want until I get a release out. Look in #known-issues to find the link https://discord.com/channels/756513972282195969/779382381571473408

**Comment by JaisDK** [comment]
Fixed in 0.5.1
