### ISSUE TITLE
crash when throwing ender pearls [1.15.2]

### ISSUE THREAD

**Issue by mahjerion** [JDKDigital/productive-bees#116]
Hey, tbh I don't know if this is on your end or The Bumblezone's. it happens anytime an enderpearl is thrown.

https://pastebin.com/W558ym6w

**Comment by JaisDK** [comment]
also when it's not thrown on a hive or nest?

**Comment by mahjerion** [comment]
yeah, it seems to crash anytime it's used. sorry I can't really provide more details, I'm just going off of player reports and server crashes

**Comment by mahjerion** [comment]
Also, this may be related but a player entered the bumblezone, and upon exiting gets kick. upon rejoining they're faced with an internal server error. this is what i get on the server side
https://pastebin.com/e43pissf

**Comment by JaisDK** [comment]
Yea it's related. Let me check with him and ask if he will update his mod for older versions.

**Comment by JaisDK** [comment]
Bumblezone is not updating for 1.15 anymore, so I might have to revert some changes to prevent the crashing.

**Comment by mahjerion** [comment]
Hey thanks so much for being so reponsive. I feared it would be on bumblezone's end since 1.15 isn't receiving support anymore. Appreciate what you're doing!

Recently swapped out beesourceful for your mod and besides not being able to use Ender Pearls, it's great :)

**Comment by JaisDK** [comment]
I put up a new file, hope it works for you https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3128852

**Comment by JaisDK** [comment]
Found your modpack, that explains the sudden increase in downloads for that version :) Thanks for the nice description in your changelog.

**Comment by mahjerion** [comment]
:) Not a problem, thanks for being so quick to fix the issue - I tested it and it works great!
