### ISSUE TITLE
After turning a minecraft bee into an explosive bee every other right click interaction with bees turns them into explosive bees

### ISSUE THREAD

**Issue by Lazlol** [JDKDigital/productive-bees#117]
Minecraft version: 1.15.2 Multiplayer
Modpack: Craft to Exile: Dissonance 2.7.0b

I was trying to make an explosive bee by using tnt on a regular minecraft bee, after that i tried to pick up that bee with a bee cage, the cage got used up and it looked like a bee respawned(it changed the Mine and Slash mob prefix) and i didn't get the bee into my inventory. After that anytime i right click any bee(minecraft and from your mod) with any item it uses up that item and turns that bee into an explosive one.
Relogging onto the server and dying doesn't fix the issue.

**Comment by Lazlol** [comment]
Server restart helped though

**Comment by JaisDK** [comment]
I've seen some weird stuff with 1.15 servers, this is up there with them. It is probably the same problem as the other times where the recipe cache gets fucked.
I'm not sure if you are experiencing two different issues, but I can have a look at fixing at least the one where the bees gets converted with any right click.

**Comment by JaisDK** [comment]
Solved in 0.5.1.3
