### ISSUE TITLE
[Suggestion] Disabling Bee Disables Comb and Block Spawn In Bumblezone

### ISSUE THREAD

**Issue by mahjerion** [JDKDigital/productive-bees#118]
Apologies if it already is somehow possible, but I can't seem to turn off the spawning of combs/blocks that I've disabled bees for.

I've disabled most of the Immersive Engineering bees but their blocks, such as lead, nickel, steel, still spawn in The Bumblezone.

Is it possible to have the datapack configuration (specifically) data/productivebees/productivebees disable the block generation too? Thanks!

1.15.2, your latest update

**Comment by JaisDK** [comment]
The block generation in the Bumblezone is done by them, I have no control over it.

**Comment by JaisDK** [comment]
There seems to be a config called `spawnProductiveBeesHoneycombVariants` which I guess will disable PB comb spawns in the bumblezone.

**Comment by JaisDK** [comment]
and I got to say, your modpack is infuriating :)

**Comment by mahjerion** [comment]
My god I'm an idiot, I kept scouring the_bumblezone server config and couldn't find this, but my server config I have in the default configs is an old version... Thanks for pointing that out!

Haha you're trying out the pack or do you mean with the bugs? :P

**Comment by JaisDK** [comment]
I'm on one of your servers right now trying out how it works with the mod and I didn't realize that the mob level scaled with how far away from spawn you went...

**Comment by mahjerion** [comment]
Oh god, I hope you didn't travel too far lol

Gonna close this since it's more or less resolved!
