### ISSUE TITLE
1.15.2 BUG bee cage

### ISSUE THREAD

**Issue by e4710765** [JDKDigital/productive-bees#119]
Use bee cage to catch bees, it will be automatically converted into creeper bee.
![螢幕擷取畫面 2020-12-06 210904](https://user-images.githubusercontent.com/75571224/101280967-52cc9d80-3807-11eb-8db0-791fe9e2255a.png)

Version productivebees-1.15.2-0.5.1.2.jar

**Comment by JaisDK** [comment]
I am unable to recreate it, but I am having some trouble with bees caught in the bumblezone. Can you try with vanilla bees from the overworld and see if you have the same problem?

**Comment by JaisDK** [comment]
Tracked here https://github.com/mahjerion/Craft-to-Exile-Dissonance/issues/173
