### ISSUE TITLE
1.16.3 Crash from silk touching a Hive with a extension box and five bees, placing it without the box

### ISSUE THREAD

**Issue by LewisEmilyR** [JDKDigital/productive-bees#120]
Not that it's surprising that rendering five bees in a three bee hive would crash the game, but here's your crash report. 

[crash-2020-12-06_17.06.21-client.txt](https://github.com/JDKDigital/productive-bees/files/5649885/crash-2020-12-06_17.06.21-client.txt)

**Comment by JaisDK** [comment]
Thanks, this has already been patched in the newer versions :)
