### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by MrSarux** [JDKDigital/productive-bees#123]
Hello, I'm currently playing on a pack called TNP Limitless 3 which has your mod installed and for some reason there seems to be a duplication glitch with the bee genetics. You put the gentics into your inventories crafting table then you craft it which should be all but it lets you pull more out the results part of the crafting table.

**Comment by JaisDK** [comment]
I am unable to reproduce this in my dev env. Which gene are you crafting?

**Comment by MrSarux** [comment]
IL create a little giff when I'm home soon, maybe that will help identify the issue. Just currently away from my pc atm though to clarify I think iv managed to do this with multiple types but I will confirm the exact ones shortly

**Comment by JaisDK** [comment]
That would be awesome, thank you

**Comment by MrSarux** [comment]
Ok so to clarify the version of your mod used within this pack is (productivebees-1.16.3-0.5.1.1). It seems to work with any genetics i can get my hands on though if i try to shift click this dupe item it causes the game to crash. Also i tried making a giff but had an issue so heres a short video showing me doing the duplication glitch https://drive.google.com/file/d/1kobDGR5qniL2iYf9vw9dnzkFvm5PiVps/view

**Comment by JaisDK** [comment]
there must be something in the pack creating the issue

what if you craft two together, does it also do it?

**Comment by MrSarux** [comment]
Appologies for the wait, since my game crashed i had to relaunch it and that sadly takes a little time. as for your question it seems that when you put two into the crafting slots nothing happens but it memorisies whichever is left in when one is removed. at this point with one left in you are able to proceed duping the item.
