### ISSUE TITLE
Double Feeding Slab Error w/ Double Slabs

### ISSUE THREAD

**Issue by WenXin20** [JDKDigital/productive-bees#124]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Productive Bees v0.5.2.1`
`Double Slabs v3.4.10`

When a Feeding Slab is made into a double slab with the Double Slabs mod installed, the gui won't open and instead prints an error. 
[Error Log](https://gist.github.com/WenXin20/1855b1d51e8e1cf73caa4c6412934aad)

**Comment by JaisDK** [comment]
Thanks for reporting. It's a problem with Double Slabs mod though. They are overriding my TileEntity with their own.

**Comment by WenXin20** [comment]
Ok, I'll report it to them
