### ISSUE TITLE
Broken Recipes

### ISSUE THREAD

**Issue by WenXin20** [JDKDigital/productive-bees#126]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Productive Bees v0.5.2.1`

According to the log starting on line 195, there are two broken recipes. Do these two require thermal to be installed? 
If it does, a conditional check can be added to the recipe json to stop the errors.
[Error Log](https://gist.github.com/WenXin20/75fbc4ce1b3cc0313f02cf36e8d47345)
```
"conditions":
[
	{
		"type":"forge:mod_loaded",
		"modid":"thermal"
	}
]
```

**Comment by JaisDK** [comment]
Yea I found them yesterday, forgot to add the condition.

**Comment by WenXin20** [comment]
Yeah, there are so many in the log, that I decided to report them all.

**Comment by JaisDK** [comment]
New version is up with fixed recipes
