### ISSUE TITLE
3000+ Bees in 4 chunks

### ISSUE THREAD

**Issue by Asbestos4Lyf** [JDKDigital/productive-bees#127]
Have had this issue in a couple of worlds and now a server. When I returned to a chunk that was generated at the start of the world, that no one had been to since, the chunk and those around it where absolutely overloaded with bees to the point where the game can barely handle it. Again the chunks in question havent been loaded since the start of the server one week ago, so I have no clue how the bees would still be able to breed/spawn(?) in them. But this issue has now caused multiple crashes on my server. 
I have no other mods that change anything bee related, etc.

![2020-12-26_23 35 10](https://user-images.githubusercontent.com/76638071/103163517-29cf7500-47d5-11eb-87f3-5f227fc297a6.png)

**Comment by JaisDK** [comment]
This was a problem in older versions of the mod, you need to update. See #108 for more info.

**Comment by JaisDK** [comment]
I've never seen this many :D
Which pack are you running?
