### ISSUE TITLE
[1.15.2] mod references recipe types that don't exist

### ISSUE THREAD

**Issue by tlsctf2** [JDKDigital/productive-bees#129]
sorry to bother you, but according to a team member on the Forge forums (diesieben07), the 1.15.2 build of this mod has invalid recipes that reference recipe type(s) that don't exist and I was wondering if you could take a look into that. [here's](https://forums.minecraftforge.net/topic/95696-1152-every-world-generated-chest-is-empty/) the thread where I got this information from after I asked about world-generated chests being empty

**Comment by JaisDK** [comment]
Yes the current version is missing a condition in two of the recipes. The upcoming release (later today) will fix that.
