### ISSUE TITLE
[Suggestion][1.15.2]Honey Fluid should slow mobs down greatly

### ISSUE THREAD

**Issue by TelepathicGrunt** [JDKDigital/productive-bees#13]
Just an idea for the honey fluid. When making fluids, you can make a fluid without specifying the actual block but in order to do the speed slowing effect, you may have to make the block itself. 

Here's an example from my mod where my fluids has an associated block as well:
https://github.com/TelepathicGrunt/Bumblezone/blob/master/src/main/java/net/telepathicgrunt/bumblezone/blocks/BzBlocks.java#L56

Then you can add properties to that block to add new behaviors to the fluid and you also get access to the block's other methods for more interesting stuff such as heal bees on collision. 

I hope this helps!

**Comment by JaisDK** [comment]
Cool idea. I wasn't sure if I was gonna keep the honey fluid in, as it had no use, but with some behaviors like you describe it could be good.
