### ISSUE TITLE
FTB Chunks not detecting fake player with Productive Bees

### ISSUE THREAD

**Issue by wheelsfire** [JDKDigital/productive-bees#130]
[crash-2020-12-29_16.25.39-server.txt](https://github.com/JDKDigital/productive-bees/files/5751140/crash-2020-12-29_16.25.39-server.txt)
Already contacted mod dev, and told me to post the issue here.

**Comment by JaisDK** [comment]
And what do they expect me to do about it? It's their mod crashing.

**Comment by wheelsfire** [comment]
Oops Sorry! - Wrong Github XD
