### ISSUE TITLE
Crash due to two Points of Interest for Draconic Nests/Hives ?

### ISSUE THREAD

**Issue by Soundofdarkness** [JDKDigital/productive-bees#131]
Hey,
I'm not exactly sure if this crash should even happen and if it is actually caused by this mod, or if its caused by a forge change between version 35.1.18 and 35.1.28. It doesn't happen on 35.1.18 for me currently. Considering that the crash is actually happening inside Minecraft's renderer code it seems like the crash shouldn't happen, but it would be an error in any case.
In any way, thank you for your work on this mod ! 

---
Productive Bees Version: productivebees-1.16.3-0.5.1.1
MC Version: 1.16.4
Forge Version: Forge-1.16.4-35.1.28

Crash Report: [crash-2020-12-29_22.51.36-client.txt](https://github.com/JDKDigital/productive-bees/files/5752360/crash-2020-12-29_22.51.36-client.txt)

Full Log: [2020-12-29-3.log](https://github.com/JDKDigital/productive-bees/files/5752361/2020-12-29-3.log)

**Comment by JaisDK** [comment]
It's fixed in the latest version
