### ISSUE TITLE
fps drop when a lot of centrifuges are running

### ISSUE THREAD

**Issue by Lazlol** [JDKDigital/productive-bees#133]
When builing a medium/large production line with dozens of centrifuges the spinning animation of combs inside centrifuges causes a noticable fps drop(with 60 centrifuges fps drops from a 100 to 10). It also seems to render even if you are far away and/or have blocks in the way (but i guess it may just be how minecraft chooses what to render). Would be great if you could add an option to enable/disable spinning animation and maybe replace it with the static one.

**Comment by JaisDK** [comment]
I'll see what I can do 👍

**Comment by Lazlol** [comment]
Thank you. 
Also found that you can place combs into bottle output slot of the centrifuge in ver.0.5.2.3, is it already fixed or should i open another issue?

**Comment by JaisDK** [comment]
This is intentional for now, that slot can accept anything to make it possible to fill any container

**Comment by Lazlol** [comment]
But then it's harder to automate with just vanilla, because hoppers will take everything out of that slot.

**Comment by JaisDK** [comment]
is it not OK to empty the bottle output slot?

**Comment by JaisDK** [comment]
0.5.2.5 did do some changes with the inventory

**Comment by Lazlol** [comment]
The problem is that if you don't control the combs entering the centrifuge, then they can just pass through that slot and it seems counterintuitive. Could that also happen to containers? And maybe there is a way to filter that slot for containers?
Sorry if i'm too demanding

**Comment by JaisDK** [comment]
No it's good to get feedback. So the bottle output slot gets filled with comb from the input hopper and then the output hopper pulls them out immediately...that's not really effective. What I can do is not allow anything that can be processed in the centrifuge to enter that slot.

**Comment by Lazlol** [comment]
Either that or making that slot accessible from the sides only.

**Comment by JaisDK** [comment]
I don't handle sidedness at all, but maybe I should look into it.

What you can do now is chain the centrifuges together, the output from one to the input of another :)

**Comment by Lazlol** [comment]
yeah, i already solved that problem, but that's a nice solution :smile:

**Comment by JaisDK** [comment]
I added a client config to disable inventory rendering in the latest version, 0.5.2.6

I also did some changes to the inventory slot so it wont accept combs and bottles.

**Comment by Lazlol** [comment]
Thank you :)
