### ISSUE TITLE
Bee cage converts bee to last created type.

### ISSUE THREAD

**Issue by Minothor** [JDKDigital/productive-bees#134]
I've encountered the same issue as mentioned in #119 except the pack I'm using does not include the Bumble zone.

In my case, both vanilla bees as well as productive bees (carpenter and slimy) were converted into the last bee I converted (skeletal + wither rose) and the cage is used up with no item returned.

Nothing out of the ordinary appeared in the client logs concerning the cage.

Video and modpack profile (curse/multiMC) attached, running MC 1.16.4 and Forge 35.1.13
[I see a Bear and Seal Modifying a Server Pack.zip](https://github.com/JDKDigital/productive-bees/files/5762124/I.see.a.Bear.and.Seal.Modifying.a.Server.Pack.zip)

https://user-images.githubusercontent.com/2125437/103486824-0160ff80-4e01-11eb-8107-71767e637d99.mp4

**Comment by JaisDK** [comment]
What kind of filename is "I see a Bear and Seal Modifying a Server Pack" 👍 

Anyways, you need to update the mod. 1.16.4-0.5.1.1 still had that issue.

**Comment by Minothor** [comment]
Cheers, we'll update our server this week and check back.
(it stems from the Family & Friends group the pack's for: "I see a Bear and Seal high-fiving" - yes, a spin on a Fallout 3 reference. )
