### ISSUE TITLE
Serialization Error on LAN connect

### ISSUE THREAD

**Issue by NoRestWhenWicked** [JDKDigital/productive-bees#137]
Sorry, I messed up. Already fixed. _Cannot connect to LAN with productive bees installed. Error message reads as "Serialization error around byte # <--" this changes. Console spits out productive bees errors of various types. Went through 142 mods to discover removing productive bees resolved LAN connection issue. Will comment with a gist server log asap._

**Comment by JaisDK** [comment]
Which version of MC and the mod are you using?

**Comment by NoRestWhenWicked** [comment]
Was using 2.7, just updated to 2.8 and this is fixed. (1.16.4, 142 mods.)

**Comment by NoRestWhenWicked** [comment]
Thank you for the prompt reply, sorry it was my error.

**Comment by JaisDK** [comment]
excellent :)
