### ISSUE TITLE
cant play privately with friends anymore.

### ISSUE THREAD

**Issue by BreazyLantern** [JDKDigital/productive-bees#139]
The latest version that got released 3 days ago makes it so that my modlist cant be played in multiplayer with my friend but reverting to a previous version fixes this. The latest version is still playable in single player which is why there is no crash list.
this here is the list of mods im using for private gameplay with a friend.
[list of mods.txt](https://github.com/JDKDigital/productive-bees/files/5798863/list.of.mods.txt)

**Comment by JaisDK** [comment]
Which version of MC are you on?

**Comment by BreazyLantern** [comment]
sorry forgot to mention it is 1.16.4

**Comment by BreazyLantern** [comment]
using latest forge

**Comment by JaisDK** [comment]
could you send the server debug.log, even without a crash it will have useful info?

**Comment by BreazyLantern** [comment]
this it?
[debug.log](https://github.com/JDKDigital/productive-bees/files/5798877/debug.log)

**Comment by JaisDK** [comment]
Yes, thank you.

Can you tell me which mod adds zinc and bismuth?

**Comment by BreazyLantern** [comment]
should not be any mods adding that

**Comment by JaisDK** [comment]
From the log I can see that both bees have been loaded, so there must be something adding them. Did you search JEI?

**Comment by BreazyLantern** [comment]
hold on for me to check

**Comment by BreazyLantern** [comment]
nothing in jei other than productive bees items

**Comment by BreazyLantern** [comment]
wait thier is ex nihilo if i search deeper through recipes

**Comment by BreazyLantern** [comment]
weird that it is not in jei

**Comment by BreazyLantern** [comment]
still nothing on bismuth

**Comment by BreazyLantern** [comment]
nevermind also on ex nihilo if i search through centrifuge

**Comment by JaisDK** [comment]
Looks like they add both https://github.com/NovaMachina-Mods/ExNihiloSequentia/tree/1.16/src/main/resources/data/forge/tags/items/ingots

The trouble then is that there's no block when there is an ingot. I can make you a datapack which should fix it until I get a new version out.

**Comment by BreazyLantern** [comment]
thats cool

**Comment by JaisDK** [comment]
[zinc_bismuth_datapack.zip](https://github.com/JDKDigital/productive-bees/files/5798937/zinc_bismuth_datapack.zip)

Throw this in the servers world/datapacks folder and enable. It will remove the need for zinc and bismuth blocks.
Let me know if it works!

**Comment by BreazyLantern** [comment]
thank you it seemed to have worked perfectly
