### ISSUE TITLE
[1.15.2] Nest blocks generated in world may face the wrong way.

### ISSUE THREAD

**Issue by TelepathicGrunt** [JDKDigital/productive-bees#14]
Everything looks good but I noticed that bees seem to appear in Dark Oak Forests but I couldn't find the hole. When I go into debug mode and look at the logs, I found the nest block but it was facing the wrong way so that the hole was hidden inside the trunk of the Dark Oak tree.

Here's a pic with the seed and coordinate for easy testing and reproducing.
![image](https://user-images.githubusercontent.com/40846040/81756399-a3eefb80-9489-11ea-8e2f-9215498b2471.png)

Just a quick check for where an air space is and place the block with said rotation towards the air block will fix this. Otherwise, good job! I really like your mod so far

**Comment by JaisDK** [comment]
The problem is with my damn model, I can only get it to face west (or any other specific/hardcoded direction). I could however check if there's a wood block in front and then replace that one instead so it would be moved all the way to western side of the tree.

**Comment by TelepathicGrunt** [comment]
I see what you mean. I did gave it a shot myself and got most of the blockstates working for you here! You can use this for your logs and all. Notice how you can specify multiple blockstate properties to target certain rotations. However, I couldn't get the bottom 4 entries to work because the rotations are always applied in a certain order. You'll have to make a new model for up and down but once you do that, all the states should work! (for the states where the directions are invalid due to the axis, i just copy/pasted the topmost rotation for that axis) 

```
{
    "variants": {
        "axis=y,facing=north":   { "model": "productivebees:block/nest/acacia_wood_nest", "y": 270 },
        "axis=y,facing=east":    { "model": "productivebees:block/nest/acacia_wood_nest"  },
        "axis=y,facing=south":   { "model": "productivebees:block/nest/acacia_wood_nest", "y": 90  },
        "axis=y,facing=west":    { "model": "productivebees:block/nest/acacia_wood_nest", "y": 180  },
        "axis=y,facing=up":   { "model": "productivebees:block/nest/acacia_wood_nest", "y": 270 },
        "axis=y,facing=down":   { "model": "productivebees:block/nest/acacia_wood_nest", "y": 270 },
        
        "axis=z,facing=east":   { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90 },
        "axis=z,facing=west":   { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90, "y": 180 },
        "axis=z,facing=north":   { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90 },
        "axis=z,facing=south":   { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90 },
        
        "axis=x,facing=north":    { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90, "y": 90, "z": 90  },
        "axis=x,facing=south":    { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90, "y": 270, "z": 90  },        
        "axis=x,facing=east":    { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90, "y": 90, "z": 90  },        
        "axis=x,facing=west":    { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90, "y": 90, "z": 90  },
        
        "axis=z,facing=up":    { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90},
        "axis=z,facing=down":    { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90},
        "axis=x,facing=up":   { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90, "y": 90, "z": 90},
        "axis=x,facing=down":   { "model": "productivebees:block/nest/acacia_wood_nest", "x": 90, "y": 90, "z": 90}
    }
}
```

**Comment by JaisDK** [comment]
Thank you! I'll give this a try for the next version. For now I'm pushing the nest to the eastern edge of thick trees so the bees don't get stuck in trunks.
