### ISSUE TITLE
Static item models for JEI

### ISSUE THREAD

**Issue by ChloeDawn** [JDKDigital/productive-bees#143]
It would be nice if there was a client config option to use static item models for the bees in JEI, as the animated models have a significant impact on the game's framerate when rendering.

**Comment by JaisDK** [comment]
I don't think stopping the animation would improve anything, I would have to replace them with images like in the old days.

**Comment by JaisDK** [comment]
![image](https://user-images.githubusercontent.com/15868585/104852081-545aac80-5901-11eb-9500-ae65c1b84884.png)

**Comment by ChloeDawn** [comment]
Sounds fine to me, would just be nice to have something for players on slower PCs. Heck, I have a GTX970 and they drop me to 20FPS in my modpack lmao.

**Comment by JaisDK** [comment]
0.6.x beta has static image option and also performance improvements to the normal rendering.
