### ISSUE TITLE
block.productivebees.nether_gold_nest missing translation in dev-1.16.3 branch

### ISSUE THREAD

**Issue by D0CTOR-ZED** [JDKDigital/productive-bees#146]
dev-1.16.3 appears to be the current branch used for 1.16 development, so I'm going based on that.

block.productivebees.nether_gold_nest appears that way in game since it doesn't have an entry in either lang file.

Also, unrelated, was it intended for all of the various advanced nests to fall into the block tag productivebees:nether_gold_nests?  This seems like an odd choice since they aren't nether_gold_nests, yet that is how the tag is defined:
https://github.com/JDKDigital/productive-bees/blob/dev-1.16.3/src/main/resources/data/productivebees/tags/blocks/nether_gold_nests.json

**Comment by JaisDK** [comment]
I didn't really finish implementing that nest, not sure if I want to keep it or not. The tag is defined correctly to allow the nest inhabitor to also live in hives. The same is done for the other "wild" bee nests.
