### ISSUE TITLE
quartz nests are missing

### ISSUE THREAD

**Issue by Ultimum-Aeternum** [JDKDigital/productive-bees#148]
Quartz nests are missing from neteher.
They just seem to don't generate.
Well thats it i guess, all I can say.

**Comment by JaisDK** [comment]
You could say which version you are playing on and how you've determined that they are not generating. They usually generate in nether quartz clusters underground, so you will have to dig them out. You can use a nest locator to find them a little easier.

**Comment by Ultimum-Aeternum** [comment]
I play on 1.16.4, tried with 0.5.2.11 and 0.5.2.13.
Only your mod is installed.
I've determined that they are not generating by flying aroun in nether in total for 13min with nest locator.
1.16.4 is almost identical with 1.16.5, so I hope it's not the issue.

**Comment by JaisDK** [comment]
Take a look at your debug log, it will mention every time a nest is spawned. Or upload it here for me to see.

**Comment by Ultimum-Aeternum** [comment]
Oh well sorry my bad, I interprited your nest locator wrong.
I tought somehow of compass when I saw nest locator, then taught about flat plane and afterward taught that it searches in all 256 blocks on y cooridnate, but well that would be expensive cause java, you know...(I mean if minecraft would be written on C, it would take approxsimately 4 or 5 milliseconds instead)
Sorry for wasting your time. ¯\_(ツ)_/¯

**Comment by JaisDK** [comment]
I am working on making it better so it can search more blocks, but right now it's 16 blocks out in all directions.
