### ISSUE TITLE
Bees wont go into advanced hive

### ISSUE THREAD

**Issue by CrazedslawDev** [JDKDigital/productive-bees#151]
initially i chalked it upto the fact i had 4 nests in the same bee dome as the advanced hive BUT i caged some bees and moved them to a seperate room with flowers and just the hives yet they still refuse to go into it

**Comment by joklbash** [comment]
I'm having a similar issue. I read somewhere about shift right clicking to release the bee on the hive and that appears to reset their home or something and they more or less work most of the time then.

**Comment by JaisDK** [comment]
If they are still close to their old hives, they will not forget them and will need to be release as described above (while sneaking). If you were running version 0.5.2.10 at some point, you will need to break and place all your hives for them to work again
