### ISSUE TITLE
Recipe size with server

### ISSUE THREAD

**Issue by joklbash** [JDKDigital/productive-bees#152]
0.5.2.14 is working ok on a server I've got. I tried to update to 0.6.1 and the client and server are no longer able to handshake on the recipes because of the size. On the server, there are no error messages that would indicate an issue until a client attempts to connect. The only message that shows when a client tries to connect (that is unusual) is:
[Netty Server IO #2/ERROR] [cy.jdkdigital.productivebees.ProductiveBees/]: Bee breeding recipe ingredient missing productivebees:bee_breeding/integrateddynamics/menril_bee - net.minecraftforge.common.util.Lazy$Fast@1a801d1e

On the client side, you get the usual error of the buffer size exceeding the limit.

I copied down the server world to local and it loaded ok.

**Comment by JaisDK** [comment]
Do you have Integrated Dynamics installed as well?

**Comment by JaisDK** [comment]
Can I see the server debug log?

**Comment by joklbash** [comment]
Yes, I have it installed and I'm running 1.16.4 still (not all of the mods I'm using have 1.16.5 yet). I usually run the Recipe Buffers mod because it helped decrease the client connection time, so I tried with and without it installed. Without it installed, I get the above error. With it installed, I get an index out of range exception on the client side when it tries to decipher the recipes. Same messages on server.

Attached log is with Recipe Buffers installed - I thought it might be helpful to see the sizes it reports - log looks similar without it, minus the size lines.
[2021-02-02-1.log](https://github.com/JDKDigital/productive-bees/files/5911508/2021-02-02-1.log)

**Comment by JaisDK** [comment]
Productive Bees does not seem to be installed. Are you having a datapack installed with some old recipes?

**Comment by JaisDK** [comment]
oh sorry, you sent the latest log, not debug log. Can you provide the debug log as well? It has much more info.

**Comment by joklbash** [comment]
I'm sorry - I've updated the server so many times going back and forth trying things that I've lost my mind. Debug log attached. And btw, I've not tried to customize bees any yet. It's all default generation. I did delete the server config for it when I updated to the newest version. Thanks for looking into this.

[debug-1.log](https://github.com/JDKDigital/productive-bees/files/5911555/debug-1.log)

**Comment by joklbash** [comment]
Makes sense. Thank you for the help. Having fun with the mod.

**Comment by JaisDK** [comment]
Thanks for reporting :) The new version is up
