### ISSUE TITLE
Honeylogged feeding slab issues with effect and placement.

### ISSUE THREAD

**Issue by NolanSyKinsley** [JDKDigital/productive-bees#156]
Three minor issues with the honeylogged feeding slab.

 The first is that you cannot place a feeeding slab into honey to honeylog is as you would a vanilla waterlogged block, it deletes the honey instead of placing the feeding slab in the honey. 

The second has to do with the fluid interaction with the honeylogged feeding slab itself. If you place and remove blocks on the edges of the honeylogged feeding slab, when you remove the blocks it does not cause the block update that would normally cause the fluid to flow again. The honey does not flow again so you can create a freestanding honeylogged slab without flowing liquid around it. 

That is only a minor issue (It does allow some more creative block construction options), but it exposed the third issue which is that only the flowing honey around the honeylogged feeding slab applies the healing effect to the bees. The still honey on top of the slab when isolated or surrounded by other slabs does not apply the healing effect to the bees when they feed, even though they visibly dip themselves in the honey above the slab.

**Comment by JaisDK** [comment]
Thanks for the report, I'll look into the issues.
