### ISSUE TITLE
[suggestion][1.15.2] 

### ISSUE THREAD

**Issue by raffycaccia** [JDKDigital/productive-bees#16]
I tried your mod and at the moment I really see it as a new start for bees in minecraft (a new forestry like)

I would advise you to make the fuel centrifuge (whichever you prefer) [it would be fantastic if it can also support upgrades]

not to make the bees ingots but nuggets or dust to be cooked (they seem really op now)

and the bees at the moment seem to me extremely productive, you could divide them into production tiers

**Comment by mouse0270** [comment]
Instead of adding nuggets or dust for each object, another suggestion would make the centrifuge require to process 9 combs to produce one ingot/item. (Though I could see how this might be difficult, because if you only have 7 combs you basically waste them).

I do also agree that once you get 5 bees, you are producing way more resources than you could need. But making it harder to convert honey combs into ingots/items would make it seem less "OP"

**Comment by JaisDK** [comment]
Thank you for your feedback :) By fuel centrifuge, do you mean to have it require some sort of fuel or power to operate? I was thinking to have it require FE if another mod providing it is installed as I am not going to make a generator in this mod.
I agree that the bees are quite OP compared to other resource mods, so I will definitely reduce the output. Changing it to dust would not make a big difference as the amount is the same, and using nuggets is, to me at least, just annoying, so I will play around with reducing the amount of combs produced or lowering the chance of getting resources from them.

What would be a balanced production rate for diamonds in your opinions? I don't want to encourage getting too many bees to increase production as this will tank TPS on bigger servers with all the path finding, but if I make everything configurable then it's up to each server admin to pick a balance.

**Comment by JaisDK** [comment]
I'll make a change to have the bees produce only 1 comb per pollination (configurable), similar to how honey is produced, so they don't produced combs all through the night and I will make the comb output from the centrifuge based on a configurable percentage instead of the 100% it is now.

If the production rate is problem right now, it can already be configured to some degree by changing the number of ticks between comb production attempts and the chance of the bee producing a comb.

**Comment by JaisDK** [comment]
Production tiers are already a thing, just not fully implemented. Right now a bee is assigned a production rate at random, but later it will be based on it's parents and maybe I'll add the possibility to improve it in other ways.
There are also attributes for weather tolerance, nocturnal behavior, food source, temper and breeding item, but they are also not all implemented.

**Comment by raffycaccia** [comment]
if you can it would be really nice to have a basic centrifuge that goes to coal and only if there was a mod with FE have a centrifuge that goes to FE

the fact that the accruals are configurable is perfect, you can set a lower basic value and then if someone wants to change it, it does it from config


The fact that the bees already have all these characteristics is spectacular and subsequently allowing them to be modified would be like having a built-in gendustry, all this brings me an exaggerated hype

you are doing a great job

**Comment by raffycaccia** [comment]
When it comes to diamonds to put a 40% chance of having a diamond from a comb?

**Comment by JaisDK** [comment]
With a 40% rate for diamond combs and if they only produce 1 comb per pollen trip it would make it 0.8 diamonds per bee per Minecraft day/night cycle (2 trips out per day). 
With the current implementation you can get 9 diamonds per day/night cycle, so it's quite a change, probably for the better.

**Comment by raffycaccia** [comment]
By making quick calculations, to reduce the production of diamonds and not impose the need to spam them you could set the percentage of 60% for the comb in the centrifuge so as to produce 5.4 diamonds in a day / night cycle

**Comment by raffycaccia** [comment]
a further idea is that the obsidian nest produces obsidian bees and not the draconic ones, I would take the draconic ones to the end and I would make them produce or dragon's breath instead of honey or chorus fruit or whatever you like


I apologize for all these tips but I'm really uphoric
 : P

also because I can't wait to be able to take full advantage of it in a technical modpack

**Comment by JaisDK** [comment]
Keep them coming, I can't have all the good ideas myself :)

Draconic bees are still very much in development, but the plan was for them to produce dragon egg fragments/dust like the Draconic bees from Forestry which could be crated into new eggs. Having them create dragons breath instead of honey is a great idea, this could work well for the Dragon Egg hive.

**Comment by raffycaccia** [comment]
you are a great 

I look forward to the update

**Comment by raffycaccia** [comment]
Hey hello it's me again, who would have thought!


I noticed that bees bugged when trying to cross blocks with smaller hitbox (e.g. refined storage cables)


Another thing you can make comb a single object with different metadata? automating them is difficult, since all the comb must be inserted in the filters and not just one with a filter on the metadata

![2020-05-15](https://user-images.githubusercontent.com/45554975/82032427-77123280-969b-11ea-89d5-0599078490e7.png)

**Comment by JaisDK** [comment]
Hello again :)

The bees are based on the vanilla bee model, unfortunately I can't help if they get stuck. For the comb automation, does Refined Storage have a way to filter on item tag? All my combs are in the "honeycombs" itemtag and also in their own individual tags to be compatible with other mods combs.

The effects can certainly be a trait, I'll note that down. I was thinking to also have positive effects that are granted to nearby players, not just negative ones that are used when attacking.

**Comment by raffycaccia** [comment]
The refined storage unlike the applied does not allow to put a filter on the name of the object so I have no way to filter them if not putting them all in the filter

I am very interested in the issue of positive effects

especially if an effect could be the drop of experience or the regeneration

**Comment by JaisDK** [comment]
I'm pretty sure tags are the future, not NBT, but I'll look into it.

**Comment by raffycaccia** [comment]
it's not really a problem but an optimization let's say, don't worry

**Comment by raffycaccia** [comment]
I saw that you have fixed the description of the moles for the end bee, it could be interesting to put a bee with the cage in an "analyzer" that consumes honey bottles so as to show you the further traits:

like FOOD_SOURCE, APHRODISIACS, WEATHER_TOLERANCE etc.

**Comment by JaisDK** [comment]
I will definitely need some kind of beealyzer for when I implement the system for altering and improving bee attributes. I just need to figure out how that system will work. I would like it to be in world, not just inside a block, like leashing a bee outside in the rain could make it rain tolerant (or kill it)

**Comment by raffycaccia** [comment]
Really nice as a system, HYPE
