### ISSUE TITLE
[1.16.5] Gene recipe crafting disrupts Polymorph behavior

### ISSUE THREAD

**Issue by TheIllusiveC4** [JDKDigital/productive-bees#161]
**Versions**:
- Productive Bees: 1.16.5-0.6.5
- Polymorph: 1.16.5-0.24
- Forge: 35.1.36

**Observed Behavior**:
When attempting to use Polymorph's recipe toggle feature while installed with Productive Bees, the button will either disappear after several crafts or not appear at all. No further attempts nor switching the recipe inputs can bring the button up again.

**Expected Behavior**:
The recipe toggle feature from Polymorph should still appear and function normally while installed with Productive Bees.

**Steps to Reproduce**:
1. Create an environment where a recipe conflict exists
2. Use a Crafting Table to place the ingredients for the recipe conflict
3. If the button appears, take out the ingredients and replace them multiple times.
4. The button disappears and is no longer reachable.

**Further Information**:
For context, I am the Polymorph developer so I can answer questions or concerns about the issue from my end. This was the original issue as presented to me, where a user found the conflict between our mods: https://github.com/TheIllusiveC4/Polymorph/issues/50

I believe the source of the problem, as stated in the title, stems from the `CombineGeneRecipe` crafting code here:
https://github.com/JDKDigital/productive-bees/blob/8f550b22eb648c34aa4bd3e216d37a1dfaf25d56/src/main/java/cy/jdkdigital/productivebees/recipe/CombineGeneRecipe.java#L31-L52

This code will return `true` whenever it doesn't find an invalid item. However, that means that the recipe will match empty crafting states where there are no ingredients at all. This should probably be changed so that it will only return `true` if it has found the required number of items necessary to be considered a match for the recipe.

**Comment by JaisDK** [comment]
Good catch, I've made the change. Thanks for reporting.
