### ISSUE TITLE
Thermal's Hive Hopper Compatibility

### ISSUE THREAD

**Issue by ChloeDawn** [JDKDigital/productive-bees#162]
**Mod version:** 1.16.5-0.6.8.1

It would be nice to see compatibility with [Thermal's](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation) Hive Hopper. Their current implementation [checks the level property of vanilla beehives and resets the level, simulating an extraction](https://github.com/KingLemming/1.16/blob/895cb1dface763e8f50044151532fe5cfbfaa32b/ThermalCore/src/main/java/cofh/thermal/core/tileentity/device/DeviceHiveExtractorTile.java#L57-L77). This results in effective duplication of outputs, as the advanced beehive still outputs to its internal honeycomb inventory ~~, and duplication of honey fluid too if bottles are present in the slot~~. There are two options for compatibility here that I see: Either the advanced beehive could skip its item/bottling behaviour if the hopper is below, *or* it could avoid using the honey level property to track its state so that the hive hopper does not "extract" from it.

**Comment by JaisDK** [comment]
Last time I check it does not work with advanced hives at all. I did a PR for Thermal for it, but he said he was gonna rewrite it anyway, so kind of waiting for that to happen.

**Comment by ChloeDawn** [comment]
On second look that code wouldn't apply to the advanced bee hives... Yet it is generating items and fluids for it in my world 🤔 ...Looking at the current build JAR it appears it was migrated to check for the property as you had wanted. So now it's just an issue of duplication heh.

**Comment by JaisDK** [comment]
He fixed, nice. I was looking at some old code then. It looks like the Hive Hopper checks the honey level every tick while I check every 23 ticks and fill a bottle from that. The duplication should only happen if the hive is filled on a tick that I hit, which is unlikely. The comb production from the bees is not affected by the honey level at all, they leave a comb behind when they leave as well as increase the honey level.
I don't think I need to change anything with how it's working.
