### ISSUE TITLE
[1.16.4] Crash When Accessing Advanced Hive

### ISSUE THREAD

**Issue by SgtRalphie** [JDKDigital/productive-bees#164]
Forge 1.16.4-35.1.37 and Productive Bees 1.16.5-0.6.8.6
When I open a certain hive, the game freezes and crashes. Only one hive that I'm pretty sure is full
[crash-2021-02-27_15.00.47-client.txt](https://github.com/JDKDigital/productive-bees/files/6055331/crash-2021-02-27_15.00.47-client.txt)

**Comment by JaisDK** [comment]
So you know which bees are in there?

**Comment by SgtRalphie** [comment]
from further testing it was the skeleton bee crashing, every other bee I was using is fine

**Comment by JaisDK** [comment]
ok, I'll add an extra check so it wont crash there in the future

**Comment by radiocrack** [comment]
had the same problem. confirmed  fixed in 1.16.5-0.6.9.1.
