### ISSUE TITLE
Amethyst ans Sapphire Bee don't have a flowering block with Ice And Fire

### ISSUE THREAD

**Issue by Urias0** [JDKDigital/productive-bees#166]
Just saw that on JEI while looking at bees (and yes i did go over the empty case to check) 
![image](https://user-images.githubusercontent.com/73038418/110560233-edf64b80-8145-11eb-856f-c0fbd35d8fbe.png)

![image](https://user-images.githubusercontent.com/73038418/110560254-f8184a00-8145-11eb-97de-21964fcc26ee.png)

**Comment by Anhilowasntavailabewhotookit** [comment]
i dont think it has support for those mods, as someone said it only has a few gem mods supported rn.

**Comment by JaisDK** [comment]
Fixed for next version. I&F does not tag their blocks in the blocks forge tag, only the items tag, but I can add the tag for them so the flowering blocks work.
