### ISSUE TITLE
Strange hive

### ISSUE THREAD

**Issue by Apollon-Theos** [JDKDigital/productive-bees#167]
If only your mod extend standard bees, bees not use "advanced hive" as hive. Flay away and disappear.
I make closed room with glass roof, two "advanced hive" and 3 bees (flowers exist, different colors) - bees only fly and drop drops.
Advanced hive is empty.

MC: 1.16.5
Forge: 36.0.44 
Mods:
jei-1.16.4-7.6.1.71.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
mcjtylib-1.16-5.0.18.jar
Patchouli-1.16.4-50.jar
productivebees-1.16.5-0.6.9.2.jar
repurposed_structures-1.16.5-2.4.8.jar
rftoolsbase-1.16-2.0.10.jar
rftoolsbuilder-1.16-3.0.16.jar
rftoolscontrol-1.16-4.0.8.jar
rftoolspower-1.16-3.0.8.jar
rftoolsstorage-1.16-2.0.11.jar
rftoolsutility-1.16-3.0.24.jar
tl_skin_cape_forge_1.16.5-1.17.jar
XaerosWorldMap_1.12.2_Forge_1.16.5.jar
Xaeros_Minimap_21.4.2_Forge_1.16.5.jar

**Comment by Apollon-Theos** [comment]
Update to 1.16.5-0.6.9.4 don't resolve problem.
https://www.4shared.com/img/ARuJLHGYea/s25/1781cf23290/2021-03-10_191739
https://www.4shared.com/img/O-JOA1XViq/s25/1781cf22ac0/2021-03-10_191611

**Comment by JaisDK** [comment]
The update was not to address this.

You can try two things
1. Break and place the hive again (it retains the bees inside)
2. Pick up the stubborn bees in a bee cage and place them down again while sneaking (it's important to be sneaking, this will reset their home position)

**Comment by Apollon-Theos** [comment]
I paste "advanced hive" to ground (dirt), to oak log, to acacia log, with extension and without.
In picture - this is third attempt to allocate hives (in closer space, that prevent bees from fly away).
Try to release bee from cage with "sneak" and without.
Now I try to give honeycomb (very far point) and build standard hive, because one bee die without hive.

**Comment by JaisDK** [comment]
Having a loot at the picture again I can see that these are Solitary bees, they will never live in hives

**Comment by Apollon-Theos** [comment]
And Chocolate and Mason ? Ashy? Full of honey, continue fly without "parking" into hive.  If problem only with one kind of bee, this can be my error, but with 4 different kind.
In youtube cinema - release bee around hive, 5 second and bee live in hive. In my cause 10 game days bees fly around empty "advanced hive".

**Comment by Apollon-Theos** [comment]
Ok, how view different between "Solitaire" and "non-Solitaire" bees "in real outerworld" ?
Standard Minecraft's bee now live in "advanced hive".

**Comment by JaisDK** [comment]
When you put the bee in a bee cage the item description will tell you what type it is. Most of the bees found in the overworld are solitary bees, only the Slimy and Sugarbag will live in a hive. To get more hive bees you need to get wild bees from the nether (Crystalline, Glowing, Magmatic etc.) and start breeding the resource bees. JEI should tell you what the breeding combinations are.

**Comment by Apollon-Theos** [comment]
What way to convert "Solitary" to "non-Solitary" ?
For example "with Empty Nest and secret attractant"

**Comment by JaisDK** [comment]
You can't, the solitary don't produce anything, they are used for breeding the hive bees.

**Comment by Apollon-Theos** [comment]
Ok.
Maybe someone can place information from this conversation to "Productive Bees WIKI" ?

**Comment by JaisDK** [comment]
It is, in the top. It could be more visible though and should also be mentioned in the solitary bees section.
