### ISSUE TITLE
Empty Nest - what next?

### ISSUE THREAD

**Issue by Apollon-Theos** [JDKDigital/productive-bees#168]
What can do with empty nests, after bee transferred to hive? Remain in world? Bee can return to him.
Exist recipe "Empry nest" -> "Nest". Use this nest as attractant? 9 nests - too many for attractant :)
Refarbish?

**Comment by JaisDK** [comment]
The recipe is to empty out a nest. With an empty nest you can place it down and right click it with Honey Treats, this will attract a new bee if the nest is in a suitable biome. If you don't need any of the bees the nest can attract, you can just store it.

**Comment by Apollon-Theos** [comment]
Thank you for comment and new page to "Productive Bees Guide" :)
