### ISSUE TITLE
Bees wont go into advanced hives even when sneak clicking 

### ISSUE THREAD

**Issue by Faln98** [JDKDigital/productive-bees#170]
I have multiple advanced beehives and expansion boxes above hoppers and centrifuge's, and several mason and reed bees flying around that have been released from a bee cage by shift right clicking on the hives. 
They have been flying around for several in game days with pollen on them and not one has gone into a hive.
I also know that for at least 2 of them their hives dont exist anymore since i deleted them. and the rest have their hives several chunks away.

**Comment by JaisDK** [comment]
mason and reed bees are solitary bees and do not live in hives only in nests
