### ISSUE TITLE
[1.16.5] Bee Conversion not working

### ISSUE THREAD

**Issue by kerenon** [JDKDigital/productive-bees#171]
A number of players on my multiplayer server reported that bee conversion not working at all. Tested it myself, and literally nothing happens, and there is nothing suspicious in the logs. Tried multiple mod and forge version combinations, with or without optifine, nothing seems to work.

**Comment by JaisDK** [comment]
Thanks for reporting. Which conversion recipes have been tested? I checked Skeletal to Withered yesterday without problems, but I was also not on the latest forge.
I'll update and try again later.

**Comment by kerenon** [comment]
Just tried the latest forge (36.1.0) for myself, and tried ProsperiBee (Crystalline Bee + Prosperity Block) and Hoarder Bee (Bee + Purple Hopper). Nothing happens. Forgot to mention that everything works just fine in single player worlds. Only multiplayer is affected.

**Comment by JaisDK** [comment]
Found the problem for both issues, the event handler doing both the data sync and item interaction was not being initialized. Gonna upload a fresh version soon.

**Comment by kerenon** [comment]
Thank you. 0.6.9.5 fixes this, and #172 too.

**Comment by JaisDK** [comment]
sweet
