### ISSUE TITLE
[1.16.5] Missing bees on multiplayer server

### ISSUE THREAD

**Issue by kerenon** [JDKDigital/productive-bees#172]
Most of the bees are invisible ingame and missing from JEI. Issuing a `/reload` command seem to fix this, but only until a client is restarted. Singleplayer worlds are not affected. Tested multiple mod and forge version combinations, with or without optifine.

Before `/reload`
![image](https://user-images.githubusercontent.com/4417798/111342587-e3beda80-867a-11eb-9ef8-9bcefdb5a798.png)

After `/reload`
![image](https://user-images.githubusercontent.com/4417798/111339917-714cfb00-8678-11eb-8faa-05b1a80db866.png)

**Comment by JaisDK** [comment]
That they are often missing in JEI is a known issue, but are they also invisible in game?

**Comment by kerenon** [comment]
The bees are there in game, but are invisible and you can't interact with them. The combs are generated, the bees are working, you just can't see or do anything.
