### ISSUE TITLE
[1.16.5] v0.6.9.4 Insane FPS drop when placing Honey Generator adjacent to any block that accepts RF

### ISSUE THREAD

**Issue by shortybsd** [JDKDigital/productive-bees#173]
Forge: 36.0.55
Productive Bees: 0.6.9.4

Massive lag when Honey Generator is placed adjacent to a machine that takes power. Example: Placed next to a Redstone Furnace from Thermal Series. Insane FPS drop on high end hardware. It even does it next to a Powered Centrifuge.

**Comment by JaisDK** [comment]
Sorry to take so long to get back to you on this, I completely missed it. Does this happen when the machine it's connected to is using power or when idling, or both?

**Comment by shortybsd** [comment]
Both. During charging said machine there is massive tick lag from the machine even when it is not charging. I am not home now but could send you a screenshot of JVM debugger I was running on server to track the source. The funny thing is, if it isn't hooked up to anything via wire or direct side input, the lag goes away. Mainly when it is connected to any RF machines charging or not insane tick lag. I haven't had a chance to look at your code but probably could spot the cause pretty easily if it is current.

**Comment by JaisDK** [comment]
Sounds like it's in the method responsible for sending out power.

https://github.com/JDKDigital/productive-bees/blob/dev-1.16.5/src/main/java/cy/jdkdigital/productivebees/common/tileentity/HoneyGeneratorTileEntity.java#L118
