### ISSUE TITLE
[1.6.15] World corruption

### ISSUE THREAD

**Issue by kerenon** [JDKDigital/productive-bees#174]
Forge: 36.1.0
Mod: 0.6.9.5

It seems almost all of the chunks on my server that contain a bee (or a bee house) became corrupted. Every player in the vicinity got kicked, and are unable to log back in. The server itself starts, but every player approaching the location gets kicked permanently. It seems the NBT tag data is too large. The error message is always some variation of this:

![image](https://user-images.githubusercontent.com/4417798/111916534-bcea1500-8a7b-11eb-9a2e-23c8ff68efd2.png)

I tried removing every single chunk one by one, but only after removing them all at once, was it possible for affected players to log back in. I've made backups from all the affected region files, can provide them if it helps. Log does not seem to contain any information about the problem: [https://pastebin.com/3fwMNPXh](https://pastebin.com/3fwMNPXh)

**Comment by JaisDK** [comment]
Try with this mod https://www.curseforge.com/minecraft/mc-mods/xl-packets

**Comment by kerenon** [comment]
Just tried it. No luck. Same error on all clients. The latest version of xl-packets is for 1.16.4... that is probably the reason. Long story short, it's Mojang's fault.

**Comment by JaisDK** [comment]
1.16.4 versions of mods will work on 1.16.5 too, not much changed between the two.

Try asking in the TNP discord and see if they have another solution to try.

**Comment by JaisDK** [comment]
Just to be sure, you installed the XL Packets mod in all the clients right?

**Comment by kerenon** [comment]
Yes. Even checked the modlist to see that it is actually loaded.

**Comment by kerenon** [comment]
Managed to fix this using the [RandomPatches](https://www.curseforge.com/minecraft/mc-mods/randompatches-forge) mod. [One of the patches](https://github.com/TheRandomLabs/RandomPatches/tree/1.16-forge#packet-size-limits) it applies is the same as the xl-packets mod tries to fix. Thank you for making me aware of this problem.

**Comment by JaisDK** [comment]
Sweet, didn't know there was another mod for the same thing, I'll keep that in mind. Thanks for letting me know.
