### ISSUE TITLE
[1.16.5] Bees causing oversized chunk files

### ISSUE THREAD

**Issue by Water-Cat1** [JDKDigital/productive-bees#176]
A player on our server has a bee farm going and the chunk it is held in is now saving to an external file as seen in the console:
`[17:19:06] [IO-Worker-104/WARN] [minecraft/RegionFile]: Saving oversized chunk [9, -41] (1162012 bytes} to external file ./world/region/c.9.-41.mcc`

Shown here is an NBT editor look at the chunk showing the a bee with 246 modifiers, multiple instances of "random spawn chance"
![image](https://user-images.githubusercontent.com/10862949/112429651-ca680d80-8da1-11eb-90f0-816594427a15.png)
![image](https://user-images.githubusercontent.com/10862949/112429892-36e30c80-8da2-11eb-95f5-49cbc9ad6d19.png)

The number of bees they have is ~90, and multiple types seem to be exhibiting this "random spawn chance" duplication

**Comment by JaisDK** [comment]
"Random spawn bonus" looks to be a vanilla attribute modifier.  It's certainly not something I'm setting myself. Can you zip and attach the chunk file?

**Comment by Water-Cat1** [comment]
[c.9.-41.zip](https://github.com/JDKDigital/productive-bees/files/6202749/c.9.-41.zip)
Attached

**Comment by JaisDK** [comment]
my NBTExplorer can't open it

**Comment by JaisDK** [comment]
is there an mca file for that chunk instead?

**Comment by Water-Cat1** [comment]
[c.9.-42.mcc.zip](https://github.com/JDKDigital/productive-bees/files/6202806/c.9.-42.mcc.zip)
Sorry its a server admin whos provided the files, try this one? If that doesn't work I will try get a new file when I can.

**Comment by JaisDK** [comment]
it works

**Comment by JaisDK** [comment]
I found the problematic code, now I just need to figure out why I call it.

Thanks for pointing it out to me!

**Comment by JaisDK** [comment]
[Uploading productivebees-1.16.5-0.6.9.6.zip…]()

**Comment by JaisDK** [comment]
I think it's fixed, can you check if it's good for you?

The bees have to load for them to be fixed, so hopefully you can still load the chunks.

**Comment by Water-Cat1** [comment]
New version causes a server crash alongside immersive pipes. Seems similar to #177 

"Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_142049_d()V"

[crash-2021-03-26_03.18.55-server.txt](https://github.com/JDKDigital/productive-bees/files/6210104/crash-2021-03-26_03.18.55-server.txt)

**Comment by JaisDK** [comment]
Yep got that report from others too, I've uploaded a fixed version to CurseForge
