### ISSUE TITLE
[1.16.5] Dedicated Server hangs up upon load attempt with 0.6.9.6

### ISSUE THREAD

**Issue by nanonestor** [JDKDigital/productive-bees#177]
Productive Bees Version:  0.6.9.6
Minecraft Version:  1.16.5
Forge Version:  36.1.2

Updating to this version of Productive Bees has dedicated server hang up with errors when trying to load.  Looking over the text of what is going on - it surely has to do with the issues mentioned in the patch notes in the attempt to resolve an issue which is also currently active in another thread (#176).  latest.log file link below.

I've downgraded my modpack's current release version to 0.6.9.5 until issue is addressed.

server latest.log
[https://paste.gg/p/anonymous/b201ecd87eb546f9930741eda0a7aa1f](url)

**Comment by JaisDK** [comment]
Damn Minecraft and their client only methods. In any case, new version is up on Curseforge.
