### ISSUE TITLE
[1.15.2]Bee Cage disappearing when used on a bee.

### ISSUE THREAD

**Issue by SebastianTillema** [JDKDigital/productive-bees#18]
When using a single _Bee Cage_ on a bee, both the bee and the bee cage disappears. 

This is **NOT** the case if multiple _Bee Cages_  are in the same inventory slot when used, in this case everything seams to work fine.

**Comment by JaisDK** [comment]
Thank you! This was reported before but without the details about the single item and I was unable to reproduce.
