### ISSUE TITLE
Craft bee eggs with different genes causes crash

### ISSUE THREAD

**Issue by Naturaspell** [JDKDigital/productive-bees#181]
Craft bee eggs with a honey treat having any gene besides type gene causes crash.
https://pastebin.com/TSt7AsLd

I think the mod assumes there's only type genes and tries to get a bee from a gene that is not a type gene.

**Comment by JaisDK** [comment]
hmm, I have a specific check for that which must be failing. Did you swap out the honey treat after it had started incubating?

**Comment by Naturaspell** [comment]
No, the honey treat stayed all the time in the incubator.
