### ISSUE TITLE
[1.16.5] Incubator crashes server when placed down.

### ISSUE THREAD

**Issue by Gbergz** [JDKDigital/productive-bees#182]
Title^

A player on our TNP Limitless 3 server crashed it when placing an incubator down.

**Minecraft**: 1.16.5
**Forge**: 36.1.2
**Productive Bees**: [0.6.9.7](https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3251589)

**Crash-Report**: https://gist.github.com/Gbergz/22b9f4bd4bbfe89b8dc66a5692e83c18

Edit: It seems it doesnt crash when placed down, rather it crashes when you try to make an egg from it.

From the discord user who caused it:
`i placed an egg and a 100% minecraft:bee  honeycomb to make a minecraft bee spawn egg, with 4 speed upgrades`
`it only crashed as soon as it hit the last tick`

**-** Gbergz

**Comment by JaisDK** [comment]
Sounds like it's the same as #181
