### ISSUE TITLE
[1.16.5] Crash in inventory with Pokecube

### ISSUE THREAD

**Issue by Elec0** [JDKDigital/productive-bees#183]
#### Issue Description:
Client crashes when searching 'Bee' in JEI with Pokecube and Productive Bees installed.

[crash-2021-04-12_16.25.41-client.txt](https://github.com/JDKDigital/productive-bees/files/6299868/crash-2021-04-12_16.25.41-client.txt)

It looks like productive bees is trying to do some custom rendering or something with the bees pokecube adds without proper type checking.

#### What happens:
Client crashes unexpectedly .

java.lang.ClassCastException: pokecube.core.entity.pokemobs.GenericPokemob cannot be cast to net.minecraft.entity.passive.BeeEntity
	at cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredient.getCachedEntity(BeeIngredient.java:43) ~[productivebees:1.16.5-0.6.9.8] {re:classloading}

#### What you expected to happen:
No crash

#### Steps to reproduce:

1. Have Pokecube, Productive Bees, and JEI installed
2. Search 'Bee'
3. Observe crash

____
#### Affected Versions:

- Pokecube AIO: 1.16.5-3.11.4
- Productive Bees: 1.16.5-0.6.9.8
- Minecraft: 1.16.5
- Forge: 36.1.0

**Comment by JaisDK** [comment]
Thanks for the report. I am rendering any entity added to the beehive_inhabitors tag and it looks like pokecube is adding non-bee entity entities, which I suppose is allowed. I'll need to add some more checks.
