### ISSUE TITLE
Bad things are happening

### ISSUE THREAD

**Issue by Anhilowasntavailabewhotookit** [JDKDigital/productive-bees#185]
for some reason, when this mod is combined with buzzier bees and the bumblezone, it becomes VEERY selective on what mod actually works with forge. if it for some reason dosent work, it will load up the game properly, however, it will crash upon world creation. i have no idea if its this mod, or the other ones, but i want to know how to fix it.

**Comment by JaisDK** [comment]
I will need some more info, crash report, debug log, mod versions etc.

**Comment by Anhilowasntavailabewhotookit** [comment]
i dont exactly know where to find those, but i will look into it.

**Comment by JaisDK** [comment]
they are in your .minecraft/log folder
