### ISSUE TITLE
Unfinished bees?

### ISSUE THREAD

**Issue by Anhilowasntavailabewhotookit** [JDKDigital/productive-bees#186]
i know i just posted something else here, but i found something interesting. so, i downloaded a mod called gems++, and, as you can guess, it adds a lot of gems to the game. the thing is, is that, while looking through jei, i saw that the majority of the gems that got added have a corresponding bee! They mostly work, i can craft comb blocks from the respective combs, and the combs spit out the right thing when put in the centrifuge. thing is, i cant figure out what they flower from! ive tried the ore blocks, the ore itself, basic flowers, etc., but nothing seems to work. and they arent in the guidebook. are these unfinished bees?

**Comment by JaisDK** [comment]
If the respective gem block does not work then I will have to add specific support for that mod. The bees were made with Silent Gems and gemandjewels in mind, I didn't know there were even more gem mods.

**Comment by Anhilowasntavailabewhotookit** [comment]
Yeah, i figured, considering that some gems didnt have a bee, and that some of the bees were a different color compared to the gems, makes sense. hope to see support for that mod soon, no rush tho!
