### ISSUE TITLE
speed upgrade barely help centrifuge.

### ISSUE THREAD

**Issue by demethan** [JDKDigital/productive-bees#187]
I am currently playing Engineers Life 2 pack and I was wondering what is the way to really speed up the centrifuge.  So far, no upgrade seems to make a difference. 

I looked in the config to see if the modpack author changed something, I don't see any centrifuge config. 

thank you for the mod. I love the new bees.

**Comment by JaisDK** [comment]
I have no problem with the speed upgrades, they work fine for me. There is a config for the speed upgrade called `timeBonus` found in the bottom under "Upgrades", but as far as I can tell it is not changed in Engineers Life 2.

**Comment by demethan** [comment]
Ok, I was expecting a 20% x 4 cumulative not a 20% decrease of 20% of 20% of 20% ...   if we take a value of 1000ms -80%=200ms vs ((((1000ms -20%)-20%)-20%)-20%) = 409.6ms

it would still take multiple seconds per comb.  Maybe my expectation is the problem here. 

Top tier upgrade usually means 1 item per tick or close.  I compare to Mekanism, TE, or other bee mods.  

thanks for taking the time to answer.  I enjoy your mod.

**Comment by JaisDK** [comment]
I don't know where you got the ms measurements from, it's all calculated in ticks. Normal centrifuge has a base processing time of 300 ticks (15s) while the powered is 100 ticks (5s). The time modifier is cumulative so 4 speed upgrades gives an 80% reduction, 300 * 0.2 = 60 (3s) and 100 * 0.2 = 20 (1s).

You can change the values in the config if you want them faster ;) (or use the thermal centrifuge)
