### ISSUE TITLE
Nest Locator never points forward

### ISSUE THREAD

**Issue by ghost** [JDKDigital/productive-bees#188]
From https://github.com/JDKDigital/productive-bees/issues/142#issuecomment-762032996 :
>  ... if you stand in front of some nest that the locator is seeking it shows the arrow to back.

This is happening for me as well, on version 0.6.9.11. I think the problem is in [src/main/resources/assets/productivebees/models/item/nest_locator](https://github.com/JDKDigital/productive-bees/tree/5839c4e0fe1555e5f3831686f07b44cd3e730dd3/src/main/resources/assets/productivebees/models/item/nest_locator). File "16.json" is missing. Image [16.png](https://github.com/JDKDigital/productive-bees/blob/dev-1.16.5/src/main/resources/assets/productivebees/textures/item/nest_locator/16.png) is the forward-pointing image. That image never appears for me when playing.

**Comment by JaisDK** [comment]
yea 16 should be the default layer in the top instead of 00

**Comment by JaisDK** [comment]
────────────────────░███░
───────────────────░█░░░█░
──────────────────░█░░░░░█░
─────────────────░█░░░░░█░
──────────░░░───░█░░░░░░█░
─────────░███░──░█░░░░░█░
───────░██░░░██░█░░░░░█░
──────░█░░█░░░░██░░░░░█░
────░██░░█░░░░░░█░░░░█░
───░█░░░█░░░░░░░██░░░█░
──░█░░░░█░░░░░░░░█░░░█░
──░█░░░░░█░░░░░░░░█░░░█░
──░█░░█░░░█░░░░░░░░█░░█░
─░█░░░█░░░░██░░░░░░█░░█░
─░█░░░░█░░░░░██░░░█░░░█░
─░█░█░░░█░░░░░░███░░░░█░
░█░░░█░░░██░░░░░█░░░░░█░
░█░░░░█░░░░█████░░░░░█░
░█░░░░░█░░░░░░░█░░░░░█░
░█░█░░░░██░░░░█░░░░░█░
─░█░█░░░░░████░░░░██░
─░█░░█░░░░░░░█░░██░█░
──░█░░██░░░██░░█░░░█░
───░██░░███░░██░█░░█░
────░██░░░███░░░█░░░█░
──────░███░░░░░░█░░░█░
──────░█░░░░░░░░█░░░█░
──────░█░░░░░░░░░░░░█░
──────░█░░░░░░░░░░░░░█░
──────░█░░░░░░░░░░░░░█░
