### ISSUE TITLE
[1.16.5] Crash when picking up a Sugar Cane Nest (on server, might happen on SP too.)

### ISSUE THREAD

**Issue by Gbergz** [JDKDigital/productive-bees#190]
Title ^

When picking up a Reed Nest(sugar cane nest) the server closes, might also happen in singleplayer too, though I haven't tested that.

### Versions:
**Minecraft**: 1.16.5
**Forge**: 36.1.31
**Productive Bees**: [0.6.9.12](https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3346920)

**Crash-Report**: https://gist.github.com/Gbergz/0404e98239cf2517ff6bab39261b5630

**Comment by JaisDK** [comment]
Thanks, I'll get a fix out soon

**Comment by JaisDK** [comment]
Seems to be happening when the reed nest is broken by something else than a player like being in an invalid location, sugar cane broken under it or a piston. Don't know if you can prevent that until the fix is out.
