### ISSUE TITLE
Broken recipe for Ichor Slimy Bee Spawn Egg (Tinker's Construct bee)

### ISSUE THREAD

**Issue by ghost** [JDKDigital/productive-bees#191]
The JEI info for Ichor Slimy Bee says the bee is created from its spawn egg. However, there is no JEI recipe for Ichor Slimy Bee Spawn Egg except for the common genetics one:

![image](https://user-images.githubusercontent.com/83793683/123527135-ba164600-d6a2-11eb-8442-802d3c2fb9fd.png)

Log Message:
```
[26Jun2021 16:04:19.869] [Render thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe productivebees:tconstruct/ichor_slimy_bee

com.google.gson.JsonSyntaxException: Unknown fluid 'tconstruct:magma_cream'

	at slimeknights.mantle.recipe.FluidIngredient$FluidMatch.deserialize(FluidIngredient.java:318) ~[?:1.16.5-1.6.109]
```

Recipe Problem:

https://github.com/JDKDigital/productive-bees/blob/d8c6ddfd0e1ddf2a8281c102876d34e453d4a282/src/main/resources/data/productivebees/recipes/tconstruct/ichor_slimy_bee.json#L10

Changing `tconstruct:magma_cream` to `tconstruct:magma` fixes the recipe:

![image](https://user-images.githubusercontent.com/83793683/123527099-5ab83600-d6a2-11eb-83bf-1062d9617b60.png)

**Comment by ghost** [comment]
Minecraft 1.16.5
Mod productivebees-1.16.5-0.6.9.14

**Comment by JaisDK** [comment]
Thanks, I'll get that changed for the next version
