### ISSUE TITLE
Placing Gene Sample in crafting table with similar Honey Treat modifies the Sample (even though no crafting occurs)

### ISSUE THREAD

**Issue by ghost** [JDKDigital/productive-bees#192]
productivebees-1.16.5-0.6.9.14

There's a problem adding a gene sample to a honey treat that has that type of sample already on it. If the crafting is canceled, the sample is modified.

**Steps to reproduce:**
1. Create a honey treat.
2. Apply a gene sample to the honey treat.
3. Place that honey treat back in the crafting table with another gene sample, the same type that was applied in step 2.
4. Cursor over the expected output honey treat.
5. Pull out the original, input honey treat and sample (i.e., don't perform the crafting).

In step 4, the output honey treat shows the wrong gene sample percent. It doesn't add the value of the sample.
After step 5, the sample is modified. It has the original sample percent plus the honey treat sample percent. (This is the value that should have appeared in step 4.)

Video:

https://user-images.githubusercontent.com/83793683/124339656-8db46b00-db75-11eb-9c49-733b77d361a9.mp4

**Comment by ghost** [comment]
The problem may be in `HoneyTreat.addGene`. It is adding the purity value to the incoming gene, not to the HoneyTreat's existing gene (line 61 below):

https://github.com/JDKDigital/productive-bees/blob/27b8df3636989b9ddaec0ad5e5d875822fe6bc81/src/main/java/cy/jdkdigital/productivebees/common/item/HoneyTreat.java#L52-L72

Changing line 61's `gene` to `insertedGene` appears to fix the problem (although this video is the full extent of testing I've done):

https://user-images.githubusercontent.com/83793683/124342247-2a800400-db88-11eb-84c6-ae73013b8ce7.mp4

**Comment by JaisDK** [comment]
Thanks a lot for the extensive testing. I'll add the fix to the next update.
