### ISSUE TITLE
Ender bee causes a crash

### ISSUE THREAD

**Issue by DreiPixel** [JDKDigital/productive-bees#193]
we recently updated the modpack on my server and now we sometimes get a crash related to the Ender bee.
says java.lang.NoSuchMethodError: net.minecraftforge.event.ForgeEventFactory.onEnderTeleport
is a forge update needed?

Mod version is: productivebees-1.16.5-0.6.9.14.jar
crash log: https://gist.github.com/DreiPixel/8024b9b6ba39e7f8af41b043e049fb41

**Comment by JaisDK** [comment]
Updating forge will fix it

**Comment by DreiPixel** [comment]
ok thank you. i wonder why the server boots up fine even it doesnt have the right forge version for this mod.
