### ISSUE TITLE
Nether Gold Nest not populating (with fix!)

### ISSUE THREAD

**Issue by ghost** [JDKDigital/productive-bees#195]
productivebees-1.16.5-0.6.9.15

I created a Nether Gold Nest, placed it in the Nether, and stuffed it with a Honey Treat. The cooldown timer initialized as expected, but did not count down. Adding a large number of Honey Treats brought the timer down to 0, but no bee appeared.

Nest looks okay before adding treats:
![2021-07-07_22 29 52](https://user-images.githubusercontent.com/83793683/124862957-e15ef400-df7b-11eb-8366-6e92f2554200.png)

Nest sits at 0 cooldown:
![2021-07-07_22 30 59](https://user-images.githubusercontent.com/83793683/124862964-e3c14e00-df7b-11eb-8d4a-d1f1f9dc9d82.png)

The other Nether nests count down as expected.

A wild Magmatic Bee moved into one of the test Nether Gold Nests. Its cooldown timer is stuck at 2400:

![2021-07-07_22 41 22](https://user-images.githubusercontent.com/83793683/124863598-fa1bd980-df7c-11eb-86a2-399fc2c19ba7.png)

Fix: The nest is missing from the `SOLITARY_NEST` registration list in `ModTileEntityTypes.java`:

https://github.com/JDKDigital/productive-bees/blob/27b8df3636989b9ddaec0ad5e5d875822fe6bc81/src/main/java/cy/jdkdigital/productivebees/init/ModTileEntityTypes.java#L55-L77

Adding a reference to `NETHER_GOLD_NEST` appears to fix the issue:

``` java
    public static final RegistryObject<TileEntityType<SolitaryNestTileEntity>> SOLITARY_NEST = TILE_ENTITY_TYPES.register("solitary_nest", () ->
            TileEntityType.Builder.of(SolitaryNestTileEntity::new,
                    ModBlocks.SAND_NEST.get(),
                    ModBlocks.SNOW_NEST.get(),
                    ModBlocks.STONE_NEST.get(),
                    ModBlocks.COARSE_DIRT_NEST.get(),
                    ModBlocks.GRAVEL_NEST.get(),
                    ModBlocks.SUGAR_CANE_NEST.get(),
                    ModBlocks.SLIMY_NEST.get(),
                    ModBlocks.NETHER_QUARTZ_NEST.get(),
                    ModBlocks.NETHER_GOLD_NEST.get(), // added
                    ModBlocks.NETHER_BRICK_NEST.get(),
                    ModBlocks.GLOWSTONE_NEST.get(),
                    ModBlocks.SOUL_SAND_NEST.get(),
                    ModBlocks.END_NEST.get(),
                    ModBlocks.OBSIDIAN_PILLAR_NEST.get(),
                    ModBlocks.OAK_WOOD_NEST.get(),
                    ModBlocks.JUNGLE_WOOD_NEST.get(),
                    ModBlocks.BIRCH_WOOD_NEST.get(),
                    ModBlocks.DARK_OAK_WOOD_NEST.get(),
                    ModBlocks.ACACIA_WOOD_NEST.get(),
                    ModBlocks.SPRUCE_WOOD_NEST.get()
            ).build(null)
    );
```

Adding the line starts the timers and populates the nests with Gold Bees as expected. (I lost track of the nest with the Magmatic Bee, so I don't know if it fixed that timer problem.)

**Comment by JaisDK** [comment]
Thanks :)
