### ISSUE TITLE
[BUG] Farmer Bee Unable To Harvest In Force Loaded Chunks (FTB Chunks)

### ISSUE THREAD

**Issue by Zacxalot** [JDKDigital/productive-bees#196]
As the title says, the Farmer bee seems unable to harvest crops when it is trying to do so in an a force loaded chunk (FTB Chunks).
I'm unsure as to what other information I can provide regarding the issue. 

Apologies if this has already been raised/fixed.
Thanks

**Comment by JaisDK** [comment]
is everything the bee needs within the chunk and do you prevent it from flying outside the chunk border? If it dips outside the border, it will stop ticking.

**Comment by Zacxalot** [comment]
This is while watching the bee directly, all of its chunks are loaded by being nearby anyway. From watching it, it seemed to bump into the crops as if it was going to harvest it, but the crops did not break.

I will double check to see if it's related to the chunks being claimed through FTB Chunks, or if it was only when it was force loaded through it.
