### ISSUE TITLE
How to add recipe to default bees

### ISSUE THREAD

**Issue by LOfuyo** [JDKDigital/productive-bees#197]
Am trying to add recipes to default bees but not showing up in game/jei, particularly in conversion.
Getting errors.
What am I doing wrong?

N/B: search "coal" in the latest.log for error
[latest.log](https://github.com/JDKDigital/productive-bees/files/6806437/latest.log)
[ProductiveBees.zip](https://github.com/JDKDigital/productive-bees/files/6806441/ProductiveBees.zip)

**Comment by JaisDK** [comment]
You just have an extra comma at the end. You can use this tool to verify your JSON https://jsonlint.com/

```
{
    "type": "productivebees:bee_conversion",
    "source": "minecraft:bee",
    "result": "productivebees:coal",
    "item": {
        "item": "minecraft:coal_ore"
    }
}
```

**Comment by LOfuyo** [comment]
Wow, ok. I'll try once I get back home. 
Really hoping it's the one.
This actually made me feel really silly thinking
I'm just not getting it.

**Comment by JaisDK** [comment]
nah it's a common error, if you don't have an editor that highlights it, it's really easy to miss

**Comment by LOfuyo** [comment]
Finally working nicely. Trying my own made up pack on a GoG skyblock and this is just what I needed.
