### ISSUE TITLE
amber bee no flower

### ISSUE THREAD

**Issue by BasiliskL** [JDKDigital/productive-bees#199]
I have the better end mod in a pack with this and I bred the amber bee but when I went to use it it doesn't have anything for  a flower, the tab is there but it doesn't have anything where the flower block should be

**Comment by JaisDK** [comment]
Hi,
I don't see any amber added by Better End https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port

Can you please verify which mod the amber is from

**Comment by BasiliskL** [comment]
Odd, it's definitely from the betterend mod. I just loaded up a world with just betterend, productive bees, and JEI and the betterend mod did add amber ore, raw amber, amber gems, and amber ore. But yes that is the mod.

**Comment by JaisDK** [comment]
betterend does have amber, but they haven't tagged it in a way that would enable the bee, do you have another mod adding amber as well?

I am looking at their 1.16.4-1.6.0 version, is this the one you're using?

**Comment by BasiliskL** [comment]
ah it seems that the modpack I added this too has added tags to the better end amber,
forge:gems/amber to the amber gem
forge:storage_blocks/amber to the amber block
forge:ores/amber to the amber ore
although I don't understand why it would activate the amber bee but not give it any flowering option

**Comment by JaisDK** [comment]
the tags are acting a little weird sometimes, which pack are you playing?

**Comment by BasiliskL** [comment]
enigmatica 6

**Comment by JaisDK** [comment]
Doesn’t Enigmatica have Resourceful Bees? Did you add Productive Bees yourself?

**Comment by JaisDK** [comment]
Reread you previous comment, you already answered that :)

**Comment by BasiliskL** [comment]
I don't really like resourceful bees so I'm gonna do just enough to finish the quests with them and then just use productive bees
