### ISSUE TITLE
World Gen Crash w/ BYG

### ISSUE THREAD

**Issue by WenXin20** [JDKDigital/productive-bees#2]
`Minecraft v1.15.2`
`Forge v31.1.61`
`Productive Bees v0.1.2`
[`Biomes You'll Go v0.3.3-Beta`](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[`Terraforged v0.0.13`](https://www.curseforge.com/minecraft/mc-mods/terraforged)

My server world has both Biomes You'll Go and Terraforged installed, which may be causing a crash with Productive Bees.
[Crash Report](https://gist.github.com/WenXin20/4535e7b7cbad94ec1e764a2a0fdc2d69)

**Comment by JaisDK** [comment]
Thank you for the report. I've recreated the issue just with BYG when using the BYG world type.

**Comment by JaisDK** [comment]
Issue seems best fixed in BYG. Opened an issue there https://github.com/Voronoiii/BYG/issues/28
