### ISSUE TITLE
Suggestion: Some way to configure which item is produced

### ISSUE THREAD

**Issue by Partonetrain** [JDKDigital/productive-bees#20]
For example, let's say I have multiple Copper Ingots in my pack. The Centrifuge (or just bees if enableCombProduce = false) seems to give the first type of copper it can find. A config option to specify which mod's items to prefer to use would be great.

**Comment by raffycaccia** [comment]
But with the use of the ore dictionary the ingots are equivalent

**Comment by Partonetrain** [comment]
Correct. However, multiple types of Copper ingots don't stack. It's a hassle to convert them all.

**Comment by JaisDK** [comment]
Hello, do you know of a mod that handles this in a good way? As you say, I just pick the first available item in the tag, but I would like it better if there's a "correct" way to handle this.

**Comment by Partonetrain** [comment]
[JAOPCA](https://github.com/TheLMiffy1111/JAOPCA) is the only mod I know of that does something like that. Hope this helps.

**Comment by Partonetrain** [comment]
On closer observation, I see all of your recipes are indeed data-driven and can be replaced. It might be better to just leave this up to modpack authors.

**Comment by JaisDK** [comment]
Had a look at JAOPCA (thanks for the hint) and they are doing the same thing by taking the first item in the tag. https://github.com/TheLMiffy1111/JAOPCA/blob/1.15/src/main/java/thelm/jaopca/utils/MiscHelper.java#L127

I try to make all my recipes data driven, even the bee spawns in the nests, so they can indeed be altered by modpack authors.

I don't know if it works in 1.15 and tags, but in previous versions with OreDict, you could convert the ingots to nugget and back to ingots to get them all to be the same type.
