### ISSUE TITLE
Netherite Scrap not produced after processing Ancient Comb in Powered Centrifuge

### ISSUE THREAD

**Issue by AndrewR73** [JDKDigital/productive-bees#201]
Playing in Engineer's Life 2
Modpack Version: 1.06

Productive Bees
Mod Version: productivebees-1.16.5-0.6.9.16.jar

**Describe the bug**
The Ancient Comb, produced from the Ancient Bee, produces no Netherite scrap when processed by the Powered Centrifuge. A powered centrifuge by itself, no output connections, only being provided power, will slowly process the Ancient Comb, but when the arrow completes, the comb is gone and no scrap is in the inventory of the centrifuge... just gone. Level of honey in the Powered Centrifuge appears to have no effect

All other combs (Coal, Iron, Diamond, Gold, Aluminum, etc.) produce the output as seen in JEI.

**To Reproduce**
1 - Steps to reproduce the behavior:
2 - Craft a Powered Centrifuge
3 - Place an Ancient Comb in the Powered Centrifuge
4 - Wait for comb to be processed
5 - Observe comb get consumed yet no scrap in Centrifuge's inventory

**Expected behavior**
An Ancient Comb is processed by the Powered Centrifuge and one Netherite Scrap is produced, along with a little honey, as shown in JEI.

**Screenshots**
Here are three screenshots... (Minecraft day timestamp at the right side)
Before:
![EL2 - PwrCtfg Before](https://user-images.githubusercontent.com/8558973/127383904-5921cfea-d1bb-4c9b-b38e-85d7825926af.png)
During:
![EL2 - PwrCtfg During](https://user-images.githubusercontent.com/8558973/127383925-4c09fd51-90e0-4986-a757-f3d961bde888.png)
After:
![EL2 - PwrCtfg After](https://user-images.githubusercontent.com/8558973/127383935-dbdf44f1-0413-4389-acc8-eed2d8a54a23.png)
It can be seen the centrifuge has power, processed a Quartz comb just fine, is processing an Ancient Comb, but after processing, no scrap is in the Inventory.

**Comment by JaisDK** [comment]
it's a 10% chance of output, you can see the chance for output in the tooltip when looking at the recipe in JEI
