### ISSUE TITLE
Advanced hives spawning zombees/skelebees in well lit areas.

### ISSUE THREAD

**Issue by PasixTheValkyrie** [JDKDigital/productive-bees#202]
Four weird cases for this one;

- Zombees / Skelebees spawn in the near vicinity of the well-lit hive
- They well override the hive's limit (One case of 20 zombees/skelebees in one singular hive)
- They sometimes spawn quite far away from the hives (One case was well over 50 blocks away from the nearest hive)
- They sometimes spawn invisible or without really existing (No movement on the map, particles on the spots they presumably shold be)

At the moment this is quite gamebreaking as it somehow also halts mob spawning to a grind

**Comment by JaisDK** [comment]
Thanks for reporting. I know about the first one
Do you have flowers near the hives? and have any of the bees moved in?

**Comment by JaisDK** [comment]
There is a config to chance the spawn rate or disable it completely if it's problematic for your playthrough

**Comment by PasixTheValkyrie** [comment]
Yes, I have a mix of 

> 
> 
> Thanks for reporting. I know about the first one
> Do you have flowers near the hives? and have any of the bees moved in?

Yes, I have a mix of Botania and vanilla flowers near the hives in the case those bees also use those to breed (Bit of thematic styling, so to speak) The bees that are supposed to be there move in, the zombees and skelebees don't.

**Comment by JaisDK** [comment]
So there are bees living in the hives that spawn skeletal and zombees?

**Comment by PasixTheValkyrie** [comment]
Yessir, specifically 4 different hives, one with draconic, one with ender, one with ashy mining and one with hoarder bees

**Comment by JaisDK** [comment]
The new update should take care of the problems
