### ISSUE TITLE
Idioma es_es pachouli, y lang es_es

### ISSUE THREAD

**Issue by Vicus6** [JDKDigital/productive-bees#203]
Ola, me gustaria aportar esta traduccion para futuras actualizaciones, asi no tendre que estar moviendo el archivo y comprobandolo en cada una de ellas, gx por anticipado.
La abeja CuBee, o Cupido, no realiza la funcion de alimentar animales, cambie la azada por wheat, y tampoko, y ya puestos para cualquier tipo de animal se podria realizar?. Para alimentar a un zoo extenso no me vale de nada que alimente solo a unos tipos de animales.
No se puede asignar las abejitas a una determinada colmena? no hacen mas que cambiarse, con lo que depositan los peines en lugares erroneos.
El BumBee nest no atrae abejas.
La abeja Farmer en los cultivos de dos alturas no los recoge, a las sandias, calabazas, melon de la miel, calabaza squash, y cantalupo, no los deja crecer el fruto, rompe la planta antes de que aparezca, incluso cuando aun no ha crecido, no recoge bayas ni arboles frutales, los cultivos que son silvestres, los que aparecen como plantas o no necesitan tierra de cultivo, no los recoge, tampoko los frutos del coro del end.
Las abejas introduccidas en un frasco, hacen de tolva y conducto?
En JEI al pasar el puntero por encima de las abejas, nos dice el lugar donde debe estar la informacion, pero no la muestra.
El 1º es la Carpeta de pachouli, copiar en la carpeta Guide.
El 2º es el archivo para copiarlo en la carpeta lang.
Gracias por la atencion 
Un Saludo
[es_es.zip](https://github.com/JDKDigital/productive-bees/files/6909883/es_es.zip)

**Comment by JaisDK** [comment]
Thanks for the translation, I'll add it.

I know about the CuBee having issues, I just haven't had time to look into it.

Once a bee has chosen a hive it should not be moving around to other hives. You can use a filter upgrade to limit what type of bees go into which hive.

The bumblebee nest attracts bumblebees the same way the other nests work, by using one or more honey treats on it.

I don't understand the JEI issue described, can you send a screenshot?
