### ISSUE TITLE
Weather Tolerance ineffective

### ISSUE THREAD

**Issue by akeiflin70** [JDKDigital/productive-bees#205]
Hello,
I play on the ModPack **Chroma Technology 2**.
I'have trained all my bees with the attribute "_Weather Tolerance: Any_", but none of them leave the nest when it's raining.
The modpack currently use the last version of the mod: `productivebees-1.16.5-0.6.9.18.jar`.

**Comment by JaisDK** [comment]
I think it only helps them stay outside if they are already out when the weather changes. I'll add to my list to get it fixed.
