### ISSUE TITLE
1.17 Server Login Error

### ISSUE THREAD

**Issue by whatthedrunk** [JDKDigital/productive-bees#206]
Hey there I went to add this mod to ATM7 and single player worked great and the server loaded just fine but getting this issue on joining. 
https://paste.in/Jht9XN

**Comment by JaisDK** [comment]
Which version of Forge is the pack using and which mod adds constantan?

**Comment by whatthedrunk** [comment]
37.0.44 and we added the thermal series ingots and blocks to All The Ores https://www.curseforge.com/minecraft/mc-mods/ato/files/3439307

**Comment by JaisDK** [comment]
I pushed a new version fixing tags related to copper. Realized I can just remove them since it's not a vanilla resource :S
