### ISSUE TITLE
[1.17.1] All advancements trigger on first world creation.

### ISSUE THREAD

**Issue by ProsperCraft** [JDKDigital/productive-bees#207]
productivebees-1.17.1-0.7.0.3
1.17.1 - 37.0.51
![2021-09-01_19 18 57](https://user-images.githubusercontent.com/4427684/131767535-8f584352-3fda-4a24-b0c6-9ea6d7bb3584.png)

**Comment by JaisDK** [comment]
This is a Forge bug
