### ISSUE TITLE
[Chroma Technology 2] Nest Locator Shift Click crashes server.

### ISSUE THREAD

**Issue by V2LenKagamine** [JDKDigital/productive-bees#208]
[crash-2021-09-10_15.12.18-server.txt](https://github.com/JDKDigital/productive-bees/files/7146099/crash-2021-09-10_15.12.18-server.txt)
Modlist and configs default for modpack [Chroma Technology 2] Version 1.1.2

**Comment by JaisDK** [comment]
Thanks :) I'm working on the release that will fix it. It should be ready relatively soon
