### ISSUE TITLE
Configurable combs no longer have a name (1.16.5)

### ISSUE THREAD

**Issue by Naturaspell** [JDKDigital/productive-bees#209]
Mod version : productivebees-1.16.5-0.6.9.21

Configurable combs no longer have a name in the latest version of the mod : 
![image](https://user-images.githubusercontent.com/80199784/135872107-e2cda3fa-b080-4bc9-a200-9650c4a08914.png)

While configurable comb blocks still have their name :
![image](https://user-images.githubusercontent.com/80199784/135872334-3aeb1140-aef4-42e7-9ad6-694e79de7a92.png)

**Comment by JaisDK** [comment]
What about the comb blocks? Are you on server of is it also a problem in single player?

**Comment by Naturaspell** [comment]
These screenshots have been made in single player. I didn't check on server.
