### ISSUE TITLE
How do you make use of ender bees?

### ISSUE THREAD

**Issue by saintnostalgic** [JDKDigital/productive-bees#21]
I've been trying to figure it out for the past 20 minutes, and still can't get them to at least get into Advanced Hive. Can somebody help me with this?

**Comment by JaisDK** [comment]
If they don't want to get into the hive, they might be bugged. I'll look into that.
Can you try with a freshly spawned ender bee and see if it behaves differently?

**Comment by saintnostalgic** [comment]
Tried to: Breed an ender bee and just put tons upon tons of flowers (mainly poppies) around the Advanced Hive - Did not work
Spawn ender bee from spawn egg and do the same with flowers - did not work
Tried to spawn ender bee with commands and to the same with flowers - did not work
Tried everything above but on super flat world - did not work too
So yeah, definitely bugged. But thanks for responding! Hope working on the mod goes well!

**Comment by JaisDK** [comment]
I see what the error is now, they only feed on chorus flowers and probably wont get into the hive without filling their bellies.
