### ISSUE TITLE
Gene Indexer

### ISSUE THREAD

**Issue by returnofnm** [JDKDigital/productive-bees#210]
Hey, 
After a few of the gene vials go through the indexer, it seems to break. It will no longer sequence the vials until I make a brand new one, breaking the old indexer in the process. I am not sure what is causing this problem, but i have had to make 3 new indexers so far.

**Comment by JaisDK** [comment]
Could you send me your latest.log file from when it broke?

**Comment by returnofnm** [comment]
> Could you send me your latest.log file from when it broke?

I am unfortunately not the server owner in this case. I did ask them to clear the logs and check when I placed a sample into the indexer. They said that nothing popped up on the logs, no errors or code at all.

**Comment by JaisDK** [comment]
ok, which version of the mod are you on and does the gene indexer have a redstone signal?

**Comment by returnofnm** [comment]
I did not realize that it needed redstone, i added a redstone torch and the problem resolved. Thank you!
