### ISSUE TITLE
Attempting to breed an Iron Bee results in a Tin Bee offspring.

### ISSUE THREAD

**Issue by kralyerg** [JDKDigital/productive-bees#211]
Trying to breed an Iron Bee, but I got a Tin Bee baby.

iron_bee.json snippet:

    "type": "productivebees:bee_breeding",
    "parent1": "productivebees:crystalline",
    "parent2": "productivebees:ashy_mining_bee",
    "offspring": [
        "productivebees:iron"
    ],

and tin_bee.json snippet:

   "type": "productivebees:bee_breeding",
    "parent1": "productivebees:crystalline",
    "parent2": "productivebees:ashy_mining_bee",
    "offspring": [
        "productivebees:tin"
    ],

Are they both supposed to have the exact same parent pairs and I'm just doing something wrong?

Editing to add additional info:
I bred them again and did get an Iron Bee baby this time.
And I happened to notice that the Copper Bee also has the same parent pair as Iron and Tin.

**Comment by iMahco** [comment]
I do believe this is intentional, a few of them you'll need to keep retrying to get the bee you're looking for!

**Comment by JaisDK** [comment]
It's intentional
