### ISSUE TITLE
[1.15.2] Crash with Incubator

### ISSUE THREAD

**Issue by mahjerion** [JDKDigital/productive-bees#213]
Hey man, long time. Just got back into pack dev after a break. Not sure if you're still down to push fixes for 1.15.2, but I thought I'd let you know if this crash.

If not, don't worry to much about it, but would appreciate it if you could fix it!

[crash-2021-10-27_23.09.24-server.txt](https://github.com/JDKDigital/productive-bees/files/7430373/crash-2021-10-27_23.09.24-server.txt)

**Comment by JaisDK** [comment]
Hello mate,
Unfortunately I don't do 1.15 anymore, but it looks like someone is incubating a bee which no longer exists. Maybe they got the gene before the bee was removed?

**Comment by mahjerion** [comment]
Seems like the player took a long break and came back - probably related. Probably won't see it again, first time we've see it. See you 1.16.5 :)))
