### ISSUE TITLE
[1.16.5] Tag was used before it was bound (ticking entity)

### ISSUE THREAD

**Issue by drakray** [JDKDigital/productive-bees#215]
MC 1.16.5
Forge 36.2.9
Productive Bees 0.6.9.23
BunchaOthers(see logs for list)

Server crash a couple a second after starting.
There is not suppose to be any Osmium Bees, but it look like Configurable Bees change nature sometime, as I saw Tungsten Bee in my building, but did not breed them(also, my Ender Bee was missing)

~~oldLink~~ to zipped logs+crashes

**Comment by JaisDK** [comment]
Hi,
the link to the logs is not working.

**Comment by drakray** [comment]
The link sould work now, but just in case:
[logs.zip](https://github.com/JDKDigital/productive-bees/files/7563638/logs.zip)

**Comment by JaisDK** [comment]
From the logs I can see that both osmium and tungsten bees are loaded, so there must be osmium in your pack. Are you playing a pack or is it a custom selection of mods?

**Comment by drakray** [comment]
Custom selection, available ~~oldLink~~
You can also download may latest world backup(i'm making one right now)
~~oldLink~~ is the modPack
~~oldLink~~ latest map backup(big)

**Comment by drakray** [comment]
Command to start my server, which is on Linux ~~oldLink~~
using jre1.8.0_271 for the client, on Windows
jvm args: -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=64M

**Comment by drakray** [comment]
I found in JEI that Osmium Bees have no flower attributed, Osmium Block exist from NeverNeededOrWanted

<details><summary>JEI Images(from a solo test world)</summary>

![2021-11-19_14 09 42](https://user-images.githubusercontent.com/4303126/142678269-d26c265f-4e11-4b5f-be51-155eb705ed71.png)
![2021-11-19_14 09 47](https://user-images.githubusercontent.com/4303126/142678270-62d36a95-02d5-4022-947a-643ff1170046.png)

</details>

Bismuth and Pearl have no flower either.
Bismuth is available from NNoW too. Bismuth Comb centrifuge to NNoW.BismuthIngot@90%
Pearl is from MysticalWorld. MW.PearlBlock is used to convert Diamond to Pearl. Pearl Comb centrifuge to MW.LustrousPearl@100%
Osmium Comb centrifuge to JAOPCA.OsmiumDust@90%

I still don't understand where an Osmium Bee could come from, unless there is a mutating ability?
Because there was no NeonCuckoo in my enclosure, so, weird :/

**Comment by JaisDK** [comment]
I think I know what the problem is, NNoW adds item tags for osmium, but not the equivalent block tags, this is why the bee shows up but can't find it's flowering block and causing a crash.
I'll prep a datapack for you to put on the server which should fix it.

**Comment by JaisDK** [comment]
[nnow.zip](https://github.com/JDKDigital/productive-bees/files/7572529/nnow.zip)

see if this helps

**Comment by drakray** [comment]
Server is staying up, I'm booting my client to test, but it looks good for this(osmium) specific crash
Don't know if Pearl will do the same, and it doesn't explain WHERE the Osmium Bee is coming from(nor the Tungsten), but at least it seems playable again lol ( I REALLY didn't want to lose the world XD )

**Comment by JaisDK** [comment]
If you acquire a pearl bee and there are no other pearl blocks in the pack, then yes it will also crash it.

I have no idea how the osmium bee has showed up, there's only the breeding recipe for it. Do you have some sort of auto feeder that get's the bees in the mood?

**Comment by drakray** [comment]
Does the Feeding Slab count?

**Comment by JaisDK** [comment]
no, the only auto breeding in the mod is the upgrade (which should not be the culprit since neon cuckoos don't live in hives) and the cubee

**Comment by drakray** [comment]
Don't have either of those

I just checked, and the Pearl Block have the following id/tags(using the "/ct hand" command after "/give @s mysticalworld:pearl_block"):
<item:mysticalworld:pearl_block>
<block:mysticalworld:pearl_block>
<blockstate:mysticalworld:pearl_block>
<tag:items:forge:storage_blocks/pearl>
<tag:items:productivebees:flowers/gems/pearl>
<tag:blocks:forge:storage_blocks/pearl>
<tag:blocks:forge:storage_blocks>
<tag:blocks:minecraft:beacon_base_blocks>

And yet JEI shows no flowers for the Pearl Bee

**Comment by drakray** [comment]
I counted 1 Osmium, at least 1 Lead, and 3 Tungsten, all of which should not be there, but I can't find my Ender not Crystaline, at least

**Comment by JaisDK** [comment]
there's one tag missing and it's a mystery why, I've seen the problem on one other server before

`tag:blocks:productivebees:flowers/gems/pearl`

**Comment by drakray** [comment]
it has the `tag:ITEMS:productivebees:flowers/gems/pearl` though, may be a lead?

**Comment by JaisDK** [comment]
it just makes it extra weird, the items tag should be the one used to display the recipe in JEI while the block tag is what the bee is searching for in the world

**Comment by drakray** [comment]
yeah, I have no idea XD

**Comment by JaisDK** [comment]
at least mysticalworld has their tags in order, I will need to add the fix for NNoW into the mod

as for the transforming bees.... :man_shrugging:

**Comment by drakray** [comment]
I just found something: `/tp @e[type=productivebees:ender] @s`, it does not show ender as an autocompleteable choice
I see it in my JEI though(but it might be a desync thing, since I open a solo world before)

EDIT: I'm trying something

**Comment by JaisDK** [comment]
the bees are not individual entities, you'll have to summon like this

`/summon productivebees:configurable_bee ~ ~ ~ {"type":"productivebees:ender"}`

**Comment by JaisDK** [comment]
not sure how you would tp to one

**Comment by JaisDK** [comment]
`/tp @e[type=productivebees:configurable_bee, name="Ender Bee"] @s`

maybe this

**Comment by drakray** [comment]
`/tp @e[type=productivebees:configurable_bee] @s` should then bring all bees to me
I was not sure if this command would bring them to me, in case if they got away somehow

**Comment by drakray** [comment]
Using `/tp @e[type=productivebees:configurable_bee,name="Ender Bee"] @s` is working

Tungsten brought me 10
Lead 3
Osmium 3
Crystaline 0
Ender 0
Iron 0

And I'm suppose to have those lol
So unless they reproduce by another mean and I lose the others, there is something going on there XD

**Comment by drakray** [comment]
Iron I got 1(must've been in a hive)

**Comment by drakray** [comment]
I am now at 13 tungsten, so they might just reproduce somehow XD
EDIT: 6 Lead and 6 Osmium, 17 Tungsten :O, so yeah

**Comment by JaisDK** [comment]
I'm guessing you get more as they pop out of the hives? Do you have BaBee upgrades installed in any of the hives?

**Comment by drakray** [comment]
I only have 1 hive with Anti-Teleport inside, all others have no upgrade

I now have 19 Tungsten, 9 Lead, 9 Osmium, all in isolation(can't access hive, can't access other bees)
It's been a while since those numbers, so at least they seems to no longer "reproduce"

**Comment by drakray** [comment]
I don't seems to get more of the other bees though. Gold, Silver, Iron, Redstone, Ancient, Diamond, Prismarine, Coal, all are stable number

**Comment by drakray** [comment]
I'm using Oak, DarkOak, River, and Driftwood Advanced Hives (2firts:vanilla wood, 2last:UpgradeAquatic wood)
22 of each, all with expansion box on the side

**Comment by JaisDK** [comment]
anything from another mod that gets them in the mood? like a block or enchant

**Comment by drakray** [comment]
I don't think so, here is a screenShot of the enclosure:
<details><summary>Enclosure</summary>

![2021-11-19_16 12 57](https://user-images.githubusercontent.com/4303126/142692432-a0cc31a1-afb9-4c4c-90ad-27bd5f5d6a81.png)

</details>

**Comment by drakray** [comment]
Yellow spots are Inset Lights from Engineers Decor, fluid is Honeylogged FeedingSlab, other holes are FeedingSlabs

**Comment by JaisDK** [comment]
that's a big area :) you should close the entrance so they don't wander off, open areas tend to make them wander around more

it doesn't offer any clue to the tungsten bees though

**Comment by drakray** [comment]
entrance is "closed" by XReliquary's Interdiction Torch, and the structure is a half-sphere

**Comment by drakray** [comment]
I can say that the missing bees is not an issue, because my friend put them in a Bee Cage and I didn't knew.

So only the Tungsten/Osmium/Lead bee mystical reproduction needs investigation lol

**Comment by drakray** [comment]
Could it be caused by The Bumblezone?
The dimension spawn those, and I have a chunkLoader there(I checked, `/tp` does not work interdimension, so it's not that, I think)

**Comment by JaisDK** [comment]
Bumblezone does spawn a variety of the productive bees, so if there's a way back from that dimension, they could be coming from there
The place you have chunk loaded, does it have a way to exit?

**Comment by drakray** [comment]
No, it's a Waystone to come back.

Unless they get out by the opened ceiling, but they should then spawn far away, not inside the half-bubble

**Comment by JaisDK** [comment]
they will spawn near a hive on the position that best matches

you could load up a bunch of the bees in cages, release them in the chunk loaded chunk and see if they find their way back

**Comment by drakray** [comment]
Ok so, test done, and `/tp` DOES work across dimension with chunk loader
So my `/tp` test wherre skewed by that
I simply killed all Tungsten, Lead, and Osmium bees, and I'll see if they still spawn in the bubble

Thank you for your help with the crash, what could I do to prevent the Pearl from crashing, just adding `tag:blocks:productivebees:flowers/gems/pearl` with CraftTweaker?

**Comment by JaisDK** [comment]
yes you could add `mysticalworld:pearl_block` to that tag and it should be fine

**Comment by drakray** [comment]
good thank you, we can close this, at least until another bee crash with that lol

If I really have Tungsten/Osmium/Lead spawning in the bubble I'll recheck with you, but it might have been caused by my chunkLoader and `/tp` usage >_< XD
