### ISSUE TITLE
Book misleading for 1.17.1, missing lots of bees it talks about

### ISSUE THREAD

**Issue by Corosauce** [JDKDigital/productive-bees#216]
Mentions things like ghostly bees, but they don't seem to be added for the 1.17.1 version.

https://github.com/JDKDigital/productive-bees/blob/dev-1.17.1/src/main/java/cy/jdkdigital/productivebees/init/ModEntities.java#L32-L55

**Comment by JaisDK** [comment]
How are you determining that they are missing? The list you've linked to are only the individually registered bees, all the rest are based on NBT https://github.com/JDKDigital/productive-bees/blob/dev-1.17.1/src/main/java/cy/jdkdigital/productivebees/init/ModEntities.java#L57

**Comment by Corosauce** [comment]
Ah my bad, I started poking around after we were failing to find any bees in the nether after hours of searching.

**Comment by JaisDK** [comment]
There's a nest locator which can help and you can always craft the nests yourself for the bees you are looking for. Use honey treats on an empty nest to start attracting a new bee. (more treats = faster spawning)
