### ISSUE TITLE
[1.18.1] Advancement Spam on First Join

### ISSUE THREAD

**Issue by Boomflex** [JDKDigital/productive-bees#217]
ProdBee: productivebees-1.18-0.8.0.2.jar
Forge: 39.0.0 (but also previous versions)

Upon first join to SSP and SMP, chat gets spammed with advancements.

This is a screenshot from the message spam that shows all advancements achieved,

https://i.imgur.com/kgxQNps.png

**Comment by SteadEXE** [comment]
I got the same issue, it unlocks on first join.
