### ISSUE TITLE
Bees seem to duplicate UUIDs (Skipping Entity with id)

### ISSUE THREAD

**Issue by Doublebass91** [JDKDigital/productive-bees#219]
Modpack: All in One [Modded OneBlock] 1.16.5
Running: productivebees-1.16.5-0.6.9.23.jar

In our server we noticed an issue in the console that was spamming "[Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id" pictured here : `https://gyazo.com/57a76401cd2f23ca92fe0edfa74dec3c`
After alot of trying to diagnose the problem I found a Productive Bees hive with a bee that was invisible but there as pictured here : `https://gyazo.com/a67b692056aa4bdd3b3a22d99ea290d7`
After picking up any hives in the area that contained a "Ghost Bee" the console spam stopped. My guess is that the bee is a duplicated UUID causing the entity to not render , but I'm no pro.

Hope this info helps solve any one elses issue with the same console spam.

**Comment by JaisDK** [comment]
Can you send me a list of mods you're having?

**Comment by Doublebass91** [comment]
Sure thing heres the list for the All In One [Modded OneBlock] Pack.
[modlist.txt](https://github.com/JDKDigital/productive-bees/files/7738120/modlist.txt)

**Comment by JaisDK** [comment]
did you add optifine or make any other changes to the pack?

**Comment by Doublebass91** [comment]
Sorry for the late response , no we havent. the pack is as default on the server.

**Comment by HueboWasTaken** [comment]
same thing happening on my server

**Comment by TheRealDadbeard** [comment]
Okay so I am not alone. Any ideas how to fix that? Using Valhelsia 3

Edit: Yeah only way to pick up a Hive with an inv bee.

**Comment by JaisDK** [comment]
the fix is to find the hive that makes noise, break it and reset it in a crafting grid, but I still don't know why it happens.

have you guys had server crashes or restarts where it was rolled back a few minutes?

**Comment by TheRealDadbeard** [comment]
No nothing, the console just gets flooded the whole time.

**Comment by JaisDK** [comment]
start chopping hives (they retain the bees inside), when the output stops you've found the right one

**Comment by TheRealDadbeard** [comment]
Yeah but still have to wait for them to get out and other players do not see the console.

**Comment by JaisDK** [comment]
you can hit the hive with a stick to force them out
