### ISSUE TITLE
silicon bees not producing

### ISSUE THREAD

**Issue by jsiber** [JDKDigital/productive-bees#221]
hello I'm sorry to bother you. I am just wondering how some of the bees produce the honey comb I have them in the advanced hives but nothing happens.  several bees I am having issues with and I can not find a guide anywhere

**Comment by esotericist** [comment]
a) be sure they're hive bees, and not solitary bees.
b) if they are hive bees, use jei to determine what their 'flower' is. sometimes it's something a little unusual. jei is really not optional for getting work done in this mod, unless you just want to guess at all of the materials needed.
c) they won't produce until they have 1. interacted with their flowers enough to have 'pollen' particles, 2. returned to the hive. 3. finished resting; the output happens AFTER they're done resting in the hive, not before.

**Comment by JaisDK** [comment]
which version are you on and as esotericist mentioned, they have to have pollinated first and then they leave the comb on their way out of the hive after the resting period
