### ISSUE TITLE
Using stick on bee hive expansion hard crashes client

### ISSUE THREAD

**Issue by TheDyreBanana** [JDKDigital/productive-bees#222]
minecraft vers: 1.18.1 
mod vers: 0.8.0.3

steps to repeat: 
1: have bees in hive (not sure if necessary) 
2: have expansion 
3: do the destroy action with a stick on the expansion block
4: hard crash

https://pastebin.com/KuBBBrdY

**Comment by JaisDK** [comment]
Thanks, hitting the hive instead should be safe until I get it fixed

**Comment by TheDyreBanana** [comment]
yeah I just had my setup in a way where only the top of the multiblock could be accessed xD
