### ISSUE TITLE
Gravel Nest not Taking Treats

### ISSUE THREAD

**Issue by ninjacm** [JDKDigital/productive-bees#223]
1.18.1-0.8.0.3 forge 39.0.9 
Gravel Nest doesn't show timer on bee spawning and honey treats get used up not sure if its a visual bug or the nest is just not taking the treats

**Comment by JaisDK** [comment]
Gravel nests have to be placed in beach or river biomes

**Comment by ninjacm** [comment]
Indeed, i thought i was in river biome seems i was off by 1 block
