### ISSUE TITLE
Bee Jars?

### ISSUE THREAD

**Issue by WickedWhims** [JDKDigital/productive-bees#226]
I put a mason bee into a bee jar but I'm not sure how I let the bee out? I shift clicked, broke it, tried the hopper again but with a cage. Is this a bug or am I missing the solution?

Minecraft version: 1.16.5
Mod version: 0.6.9.25
No modpack

**Comment by JaisDK** [comment]
put a hopper under the jar to pull it out again

**Comment by WickedWhims** [comment]
> put a hopper under the jar to pull it out again

Thank you! Completely new to GitHub so I don't know how to close this thread.

**Comment by WickedWhims** [comment]
Nevermind, found the button.
