### ISSUE TITLE
[1.18.1] Players cannot join server on new update 8.0.4

### ISSUE THREAD

**Issue by itsdinkd** [JDKDigital/productive-bees#227]
![image](https://user-images.githubusercontent.com/35115304/148658104-c46f9702-bcfc-48e5-b892-338fddd83f35.png)

Players are shown this when trying to connect to a server with the latest version of Productive Bees 8.0.4

**Comment by JaisDK** [comment]
can I get a server log and a client log? which pack are you playing?

**Comment by JaisDK** [comment]
fixed release coming now
