### ISSUE TITLE
Nests Dont spawn bees

### ISSUE THREAD

**Issue by Shadow212121** [JDKDigital/productive-bees#228]
latest version nests dont seem to be spawing bees. May just be because im in biomeoplenty biomes but the nests im using say any overworld biome. So far only tested with oak nest and bumblebee nest.

**Comment by JaisDK** [comment]
Nests needs to be primed with honey treats in order for them to spawn new bees. Bumblebee nests have to be placed in a plains biome, but the wood nests should work in any overworld biome
