### ISSUE TITLE
1.16.5 - ProdBee Update changes Experience Output from Centrifuge

### ISSUE THREAD

**Issue by papaworld** [JDKDigital/productive-bees#229]
MC: 1.16.5
FML: 36.2.20
ProdBee: 0.6.9.15 and 0.6.9.25

0.6.9.15 - Experience Comb > Centrifuge > Bottle O Enchanting - Build works great.

0.6.9.25 - Experience Comb > Centrifuge > Liquid XP (in my case from Mob Grinding Utils)... this updage broke my built system.

Is there an option to get Bottle O Enchanting from the Centrifuge without rolling back your Mod Version or changing my build to a fluid system?

**Comment by JaisDK** [comment]
you can change the production output with a datapack, but it is probably just easier to put a bottler next to the centrifuge and put bottles in there to bottle up the fluid

**Comment by papaworld** [comment]
Thank you, JaisDK, for your quick response and solution. I have absolutely no idea how to construct a datapack after many tries with nothing but crashes or loading errors.

My solution was to remove the item hoppers completely and install XP Taps on each Centrifuge with XP Block (Global XP mod)  picking up the orbs. This actually works out much nicer and efficient too.

BTW, really an exceptional mod. Well done! Thank you.
