### ISSUE TITLE
Shift-clicking putting items in wrong slots

### ISSUE THREAD

**Issue by Partonetrain** [JDKDigital/productive-bees#23]
For example:
![image](https://user-images.githubusercontent.com/19861808/82582955-6a3c8580-9b58-11ea-804f-e1c7585a85b7.png)

You can't put glass bottles by normal-clicking.

![image](https://user-images.githubusercontent.com/19861808/82583169-86402700-9b58-11ea-95ba-cf6c9189f9b8.png)

Same with combs in the Centrifuge.

**Comment by JaisDK** [comment]
Thanks again.
