### ISSUE TITLE
Glowing bees dont seem to be spawning

### ISSUE THREAD

**Issue by IntivG** [JDKDigital/productive-bees#230]
Hello.
I am on the newest version at the moment, but I can't find any glowing bees in the nether. I have found multiple other bees like magmatic and crystalline. Also placing down a self-made glowstone nest doesn't seem to work. I am fairly new to productive bees, but are they very rare or am I doing something wrong?

**Comment by JaisDK** [comment]
when placing your homemade nests you need to use honey treats on them to attract a new bee

the naturally spawning glowtone nests do seem to be super rare in 1.18

**Comment by IntivG** [comment]
Thanks so much for the fast help. It is already working
