### ISSUE TITLE
1.18.1 - Recipe error thrown in logs

### ISSUE THREAD

**Issue by nanonestor** [JDKDigital/productive-bees#233]
Greetings - I see the recipe for productivebees:centrifuge/ae2/honeycomb_spacial is coded with 
    "conditions": [
        {
            "type": "forge:mod_loaded",
            "modid": "ae2"
            
And you do have recipes for both ae2 and applied energistics 2 as they renamed their modID space, however it still throws an error message in logs
[Paste.gg of log snip](https://paste.gg/p/anonymous/1001034df5e342dcacbc481f62be6506)

This is using-
Forge 39.0.44
Productive bees - productivebees-1.18.1-0.8.0.5.jar
Applied energistics 2 - appliedenergistics2-10.0.0.jar

**Comment by JaisDK** [comment]
thanks, looks like I got the name wrong of the quarts dust item
