### ISSUE TITLE
[1.18.1] Ticking Entity Bee

### ISSUE THREAD

**Issue by ArchieBeepBoop** [JDKDigital/productive-bees#234]
Seems a productive bee caused a server crash when it tried to check if something was a flower block.

Here's a crash log:

https://pastebin.com/hHUtS6KH

**Comment by JaisDK** [comment]
it's a compat problem with electrodynamics, add this datapack to the server

[electrodynamics_fix.zip](https://github.com/JDKDigital/productive-bees/files/7900875/electrodynamics_fix.zip)

**Comment by ArchieBeepBoop** [comment]
> it's a compat problem with electrodynamics, add this datapack to the server
> 
> [electrodynamics_fix.zip](https://github.com/JDKDigital/productive-bees/files/7900875/electrodynamics_fix.zip)

Interesting, did you make this datapack?
Is this something that is happening ever since electrodynamics updated all of their tags in the last few updates?

**Comment by JaisDK** [comment]
yes, a few days ago when someone else had the same problem?
