### ISSUE TITLE
[1.18.1] - Crash with Mana and Artifice

### ISSUE THREAD

**Issue by PhoenixSmith** [JDKDigital/productive-bees#235]
Runs fine without M&A, but with both enabled gives this error:
https://pastebin.com/rDrkU683

**Comment by JaisDK** [comment]
Can you check that you don't have duplicate mod files in you installation? Like two versions of the same mods.

**Comment by PhoenixSmith** [comment]
Ah, that was it. Sorry and thanks for the help!
