### ISSUE TITLE
Accepting All Planks for Oak Beehive 1.16.5

### ISSUE THREAD

**Issue by MtnDrew** [JDKDigital/productive-bees#238]
Mod Version 0.6.9.25

In JEI, it says there is a recipe added by this mod that accepts all planks for crafting the Oak Beehive. Meaning that any of the other beehive options added by other mods are uncraftable because it all defaults to the oak beehive. I'm stuck in 1.16.5 because I really like the abnormal's mods, that's why I haven't upgraded to newer versions yet.  

I did a search on this github and was not able to find any other issues talking about this, which is confusing because you'd think someone would have mentioned it, I don't think that recipe should be there, _and was wondering how to remove it._

**Comment by JaisDK** [comment]
Didn't know it would overwrite their recipes, you can either disable the recipe with the included datapack below or maybe try out https://www.curseforge.com/minecraft/mc-mods/polymorph

[disable_beehive_recipe.zip](https://github.com/JDKDigital/productive-bees/files/7933572/disable_beehive_recipe.zip)
