### ISSUE TITLE
Bees get stuck/frozen, when using glass pane for housing

### ISSUE THREAD

**Issue by cholio** [JDKDigital/productive-bees#239]
Modpack: ATM7 0.2.32
Forge: 39.0.43
Productive Bees: 1.18.1-0.8.0.5

Problem:
Bees get stuck on the wall, if one doe not use full blocks for housing. In my case this would be glass panes.

Can you reproduce this problem?
Use non-full blocks for the housing of your bees - not talking about the hives.
Put a flower outside of the housing and see the bee get stuck/frozen, most of the times not even getting into the hive over night.
Bee is not modified by gene samples and expected to get into hive over night.

I had this with multiple bees now.
Picking them up into a cage and replacing them fixed this most of the time for a short period, until getting stuck again.
Changing to a full block always solved getting stuck/freezed permanently.

**Comment by JaisDK** [comment]
This is an issue with vanilla bee AI, I probably won't be fixing it, but thanks for reporting it.

**Comment by cholio** [comment]
Oh, ok haven't been aware of that. i will close this issue then. thanks for this mod. having a great time using it :)
