### ISSUE TITLE
Suggestion - Config comment

### ISSUE THREAD

**Issue by Partonetrain** [JDKDigital/productive-bees#24]
It's not immediately obvious what the [Bees] config does in productivebees-server.toml -
```[Bees]
	#Range: 0.0 ~ 1.0
	"productivebees:glowing_bee" = 0.85
	#Range: 0.0 ~ 1.0
	spawnUndeadBeesChance = 0.01
```
and so on. Does it change spawn rates? Or breeding results? Can a description be added here?

**Comment by JaisDK** [comment]
I'll add some info to the configs, it also looks like they end up in a weird order.
