### ISSUE TITLE
Skeletal Bee/ZomBee do not care about light level

### ISSUE THREAD

**Issue by cholio** [JDKDigital/productive-bees#240]
Modpack: ATM7 0.2.32
Forge: 39.0.43
Productive Bees: 1.18.1-0.8.0.5

Problem:
Skeletal Bee, just as ZomBee spawn into an empty hive, even if the light level of the block infront ist >= 9 - in my case it's 13.

Expected behavior:
Only spawn skeletal-/zom-bee when light level in front of the hive is <= 8, as in the sourcecode implemented

Can you reproduce?
Yes, just leave a well lit hive empty, don't sleep over night. after a short time skeletal-/zom-bee do spawn.

**Comment by JaisDK** [comment]
Server or single player?

**Comment by cholio** [comment]
We have a dedicated server running atm7

**Comment by cholio** [comment]
So, i have a well lit hive for five days in a loaded chunk. only thing changed had been a server restart, since opening this issue.
i cannot reproduce this anymore. therefore closing this issue.

**Comment by JaisDK** [comment]
Thanks for following up on it
