### ISSUE TITLE
Antiteleport upgrade not preventing enderbee tps

### ISSUE THREAD

**Issue by aerialspring** [JDKDigital/productive-bees#241]
Using AQM3 modpack for 1.18.1

As title suggests, using the antiteleport upgrade in an advanced beehive with the expansion hive is not preventing Enderbees from tping away. I have also tried the Brazier from Essentials with soulsand (meant to stop e-man tps), as well as reinforced blocks from SecurityCraft (also prevents e-man tps). None of these things are working. Bee apparently has limitless tp range no matter what blocks are in it's way. Built a special room deep underground and it zooped clear through 30 levels of solid stone to the surface. Very frustrating.

**Comment by JaisDK** [comment]
the bee has to have the hive as it's home for the upgrade to work. place the bee next to the hive while sneaking at night to ensure that it goes into the hive (at night, going into a hive has first priority). the bees also need chorus fruits

**Comment by aerialspring** [comment]
Thank you so much!
