### ISSUE TITLE
does not enter the world

### ISSUE THREAD

**Issue by AWDiSt** [JDKDigital/productive-bees#244]
Hello, I made my modpack in which I added some new crafts, after which I stopped entering the worlds, with the words "Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode" ) or go back to title screen and fix it manually".
At the same time, when I changed the crafts, I didn’t crash, when I re-entered, it started to fly out. (if anything, the translation may be strange, since I am from Russia and use a translator)
 

LOGS:[https://paste.gemwire.uk/view/f5b79751

**Comment by JaisDK** [comment]
doesn't seem to have anything to do with productive bees, but rather that you've added to many mods now that the packet size limit has been reached. Try adding a mod like randompatches (https://www.curseforge.com/minecraft/mc-mods/randompatches-forge) which fixes that
