### ISSUE TITLE
Bee's are not loading in a claimed chunk. (Inside Compact Machines Mod) (FTB Chunk Loader)

### ISSUE THREAD

**Issue by Remn1c** [JDKDigital/productive-bees#245]
I have my bees moved to a compacting machine to reduce lag, but the bees only are producing combs when I am in the compact machine. This might be another mod problem, but it appears as if the bees only work if there is an actual person present in the active chunk. Idk if this the right place to put this, but its a start. I just want to be able to get my combs without having to deal with the frame drops.

**Comment by JaisDK** [comment]
there is nothing I can do about it, I am not messing with any chunk loading nor is there anything I can do about other mods chunkloading behavior.

**Comment by Nekosity12** [comment]
Are you chunk loading the actual space inside the machine? Or just the chunk the compact machine is in? From what someone else said in the discord they had this same issue but chunk loading the actual space inside the machine allowed it to work

**Comment by Remn1c** [comment]
@Nekosity12 I have the chunk loaded inside the machine and it still didn't work. Idk what's going on. Had to install a chunk loading mod to fix it.

**Comment by Nekosity12** [comment]
If another chunk loader mod fixed it then this is likely something to report to FTB Chunks, as the dev said they cant do anything about this issue as he doesn't handle anything about chunk loading
