### ISSUE TITLE
[BUG] [1.18.1] Quarry Bees can't generate chips or blocks of certain blocks

### ISSUE THREAD

**Issue by Hangukkid** [JDKDigital/productive-bees#247]
In All the mods 7, the quarry bees seem to not generate any chips but only generate honey. Tried using Upgrade: Block but the blocks don't generate either. I have tested with stone and sand with no results. However I had stone bricks lying around and I had it working for a second but soon after they stopped generating stone bricks. Tried in both creative and survival worlds. Productive Bees version: 1.18.1-0.8.0.7

**Comment by JaisDK** [comment]
I know, use a feeding slab for now

**Comment by JaisDK** [comment]
I have a fixed version ready, but I haven't had time to test the release yet
