### ISSUE TITLE
Leaden comb missing recipe

### ISSUE THREAD

**Issue by NightmareElmo** [JDKDigital/productive-bees#25]
The leaden comb has no recipe in the centrifuge, can't use it for anything.
Minecraft Version 15.2
Mod version 0.1.7
Forge version 31.2.0

**Comment by JaisDK** [comment]
Thank you for reporting.
Which lead providing mod are you using?

**Comment by JaisDK** [comment]
nvm, I can see that I called it lead instead of leaden in the recipe. It will be fixed in the next version.
