### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by AForsythe916** [JDKDigital/productive-bees#250]
I am using the mod version 1.18.1-0.8.0.8 and it crashes on startup after I installed JEI. I also have Optifine and a few other mods. Any help is appreciated :) Crash Report: https://www.toptal.com/developers/hastebin/xitexazelo.yaml

This is the error message: Productive Bees (productivebees) encountered an error during the sided_setup event phase
		java.util.ConcurrentModificationException: null

**Comment by JaisDK** [comment]
Does it happen consistently when you start or just once?
Check that you mod folder does not have duplicate mod files with different versions and also check if it happens without optifine

**Comment by AForsythe916** [comment]
The issue only occurs when all three mods (productive-bees, optifine, jei) are installed. If I remove either jei or optifine, the issue does not happen. When all three mods are installed, it happens consistently. I also do not have any duplicate versions of mods.
Thanks for the help.

**Comment by JaisDK** [comment]
If you're looking for shaders you can try with the mod Oculus

**Comment by AForsythe916** [comment]
Thanks for the suggestion. I use Optifine because I like the more options in configuration as well as shaders. I ended up upgrading  from the recommended forge version (39.1.0) to the latest (39.1.2). That seems to have solved the issue. Shall I close this issue?

**Comment by JaisDK** [comment]
;)
