### ISSUE TITLE
Glowing Bee

### ISSUE THREAD

**Issue by mjordan67** [JDKDigital/productive-bees#251]
I can't seem to get a glowing bee to breed.  I have fed it several types of dye and multiple flowers including ones that have glowing in the tag and still wont breed...is this broken or am I doing something wrong?  I started a new world and this problem still exists.

**Comment by JaisDK** [comment]
which version are you using?

**Comment by mjordan67** [comment]
kind of dumb....when I looked at the version I realized im using resourceful bees ATM6
