### ISSUE TITLE
Mason bee causes tps lag spikes

### ISSUE THREAD

**Issue by engazed** [JDKDigital/productive-bees#252]
Whilst playing All The Mods 7-0.2.45 today i got some tps lag spikes. They appeared when i placed a mason bee in my base and after collecting it with a sturdy bee cage they were gone.

**Comment by JaisDK** [comment]
Can you run a spark profile while the bee is placed please.
https://spark.lucko.me/docs/Command-Usage

**Comment by engazed** [comment]
sry for taking so long, https://spark.lucko.me/d2IlzzWhPn those are the resulsts. But after a few mor lag spikes, the lags were gone. I dont know why but theyre gone.

**Comment by JaisDK** [comment]
Thanks! Did the bee find a nest to live in when the lag spikes disappeared? I see a lot of resources spent on finding a nest for some reason, most of which is to query blockstates which was put on hold by the server (maybe there wasn't enough resources available).
I'll see if I can improve that part of the code.

**Comment by engazed** [comment]
ah ok , nah it didnt have a nest. I guess that was the problem

**Comment by JaisDK** [comment]
I think it must have has a nest location from where you found it and it still hadn't given up on trying to get home. Maybe the lag comes from accessing blocks in what I assume would now be an unloaded location. If this is the case, there's certainly something I can do about it by resetting the home position of the bee if it's existing home position is not loaded. Thanks again for the report.

**Comment by engazed** [comment]
np and good luck with fixin it
