### ISSUE TITLE
[1.18.2] No Class Def Found error

### ISSUE THREAD

**Issue by PiDay314** [JDKDigital/productive-bees#255]
Hello,

I just updated to the newest 1.18.2 version of Productive Bees, 9.0.4.  On booting up, it crashes almost right away, stating there is no class definition found.  It looks like something with crafting, involving the Honeycomb item?  At least, this is what I could gather from the crash log (it is attached).

java.lang.NoClassDefFoundError: net/minecraftforge/common/crafting/conditions/ICondition$IContext
	at cy.jdkdigital.productivebees.common.item.Honeycomb.m_6787_(Honeycomb.java:62) ~[productivebees-1.18.2-0.9.0.4.jar%23111!/:1.18.2-0.9.0.4] {re:classloading}

I removed Productive Bees and the game did boot up normally.  I also tried Productive Bees without The Bumblezone, since I thought they two could be having a bad interaction, and it still did not load.

I am using the recommended Forge version, 40.0.34, I did not see any new recommendations past that in the text box.

[crash-2022-04-18_17.52.14-client.txt](https://github.com/JDKDigital/productive-bees/files/8508614/crash-2022-04-18_17.52.14-client.txt)

**Comment by JaisDK** [comment]
Use latest Forge, there's no recommended build for Forge 1.18.2 yet.
