### ISSUE TITLE
[1.18.2] Skeleton Bees not outputting any items

### ISSUE THREAD

**Issue by stevenhay** [JDKDigital/productive-bees#256]
What is the intended behaviour of Skeleton bees? I have 5 in an advanced hive underground with flowers in a 5x5 area (see: https://i.imgur.com/bvC1bmD.jpg) but they do not attempt to pollinate or produce any kind of output. They simply just fly around and no nothing, eventually they'll all go back into the hive and repeat day after day.

Zero output five Skeleton bee hive: https://i.imgur.com/KjggtN8.png

Zombie bees, which I only have a single one of in the exact same setup in the room next to the one shown in the picture above, frequently comes out of the hive, goes to flowers to pollinate and generates the correct output.

Normal output single Zombie bee hive: https://i.imgur.com/5K5Qk7i.png

Am I doing something wrong or are the Skeleton bees bugged?

**Comment by JaisDK** [comment]
They need some bone blocks mate

Check the uses for the bee in JEI to see which flower block it needs

**Comment by stevenhay** [comment]
Oh! That's what I was missing, alright I'm just not smart, thanks!
