### ISSUE TITLE
1.18.2 Vanilla Bees can't be altered with genes and show no stats

### ISSUE THREAD

**Issue by Meatball88** [JDKDigital/productive-bees#257]
I'm trying to modifiy vanilla bees for more productivity but they don't change after feeding them the 100% honey treat. 
Hovering over a vanilla bee inside the beehive shows no stats at all.

The stats of moded bees change just fine after feeding them the treats.(exept when trying to change species this way)

**Comment by JaisDK** [comment]
I don't change vanilla bees, it would require some core modding which I am not willing to do in this mod.
