### ISSUE TITLE
Passive mobs spawning

### ISSUE THREAD

**Issue by DoctorMage** [JDKDigital/productive-bees#258]
Passive mobs spawning in peaceful and normal difficulty

Passive mobs do not seem to respawn when the followings mods are involved 
After doing /kill @e in both difficulties after loading some chunks passive mobs will not spawn back 
This was an issue originally found in another modpack but narrowed down to 7 mods other 3 are confirmed to clash with eachother
but i'm on sure of which of these 3 involved clash with productive bees

Forge Version
36.2.33

Mods invovled

alexsmobs-1.12.1
environmental-1.16.5-1.1.1
productivebees-1.16.5-0.6.9.25.jar
upgrade_aquatic-1.16.5-3.1.2

(xaeros is just so i dont have to play spot the mob)
Xaeros_Minimap_22.5.0_Forge_1.16.5
XaerosWorldMap_1.20.6_Forge_1.16.5

**Comment by JaisDK** [comment]
I don't touch mob spawning at all

**Comment by DoctorMage** [comment]
I assume its productive bees clashing with another mod as when it was disabled mobs were respawning

**Comment by JaisDK** [comment]
without the other mods and only PB, does the problem persist?

**Comment by DoctorMage** [comment]
nope

**Comment by DoctorMage** [comment]
mobs respawning fine with just productive bees

**Comment by JaisDK** [comment]
can you share a full log, debug and latest for the run where the problem is present and PB is installed? preferably with as few mods installed as possible

**Comment by DoctorMage** [comment]
no debug logs
anyway to enable it?
[2022-04-23-7.log](https://github.com/JDKDigital/productive-bees/files/8546960/2022-04-23-7.log)

alexsmobs-1.12.1
environmental-1.16.5-1.1.1
productivebees-1.16.5-0.6.9.25.jar
upgrade_aquatic-1.16.5-3.1.2

**Comment by DoctorMage** [comment]
I'm doing another test to clear things up as i've been working on this for the 2 days

**Comment by JaisDK** [comment]
Using curseforge?


![image](https://user-images.githubusercontent.com/15868585/164896189-841a7113-c97f-4e3f-ab55-f2cd1cbb015e.png)

![image](https://user-images.githubusercontent.com/15868585/164896179-29b4359b-f3e1-4a84-a508-2a52d573a69a.png)

**Comment by DoctorMage** [comment]
gdlauncher  and mmc but i do have cf installed so i'll install the test instance their

**Comment by DoctorMage** [comment]
[debug.log](https://github.com/JDKDigital/productive-bees/files/8547038/debug.log)
[latest.log](https://github.com/JDKDigital/productive-bees/files/8547039/latest.log)

**Comment by JaisDK** [comment]
Does it happen in single player or only on server?

**Comment by DoctorMage** [comment]
i've tested in singleplayer and it was happening their 
issue originally was noticed in a modpack on a server

**Comment by JaisDK** [comment]
Not surprisingly I can recreate the issue with only Alex's Mobs installed. It does spawn some of it's own mobs, but all other animals do no spawn.

**Comment by DoctorMage** [comment]
Thank you so much that helps alot with finally narrowing down the last problematic mods
