### ISSUE TITLE
Large amounts of bees create significant stutters

### ISSUE THREAD

**Issue by NightmareElmo** [JDKDigital/productive-bees#26]
I know this is indiscript and maybe unavoidable but after about 30 bees spawned in performance decreases, to the point where the server has ~2sec hangs at around 100 bees. It might be due to too much pathfinding, but vanilla bees do not seem to cause the same amount of lag.
Minecraft Version 15.2
Mod version 0.1.7
Forge version 31.2.0

**Comment by JaisDK** [comment]
Pathfinding is not great, but 100 bees is not that much. I just tested with 300 and didn't notice any drop in performance. Can you send a mod list and also a rough list of which bees you are having around? The solitary bees all behave the same, so no need to distinguish between those.

I also just uploaded a new version, the one I tested on, can you please check if it's still an issue for you on that version?

**Comment by NightmareElmo** [comment]
I tested my game with no mods, just with productive bees and a couple of others and performance was not that affected, therefore it must be some interaction with another mod, no idea which one though

**Comment by JaisDK** [comment]
Thank you for testing. This must be an issue inherited from vanilla bees, but I can probably do something about it for my bees.
