### ISSUE TITLE
1.18.1 No undead bee spawn 

### ISSUE THREAD

**Issue by Nonen7** [JDKDigital/productive-bees#260]
I have light level 0 and 3x3x3 space for my adv behive but no undead bees are spawning. 
Didnt see any undead bees until now in my version on my server.

**Comment by JaisDK** [comment]
can you show a screenshot of your setup and tell me which version you are on?

**Comment by Nonen7** [comment]
https://gyazo.com/af1eca107569b306be20d8720c272a70
version: https://gyazo.com/e9b14a6d21b39e5188e1ebee3f4c5413
The mod is included inside the ATM 7.

Btw. i changed it now to 5x5x3 but still nothing..

**Comment by JaisDK** [comment]
How long have you left it there and are you leaving it at night too? The conditions are no light, empty advanced hive, night time and the entrance can't be blocked. You can put down 10 hives for a night and something should surely spawn.

**Comment by Nonen7** [comment]
My bad. I closed the entry. Now it is working. Thanks!
