### ISSUE TITLE
Thermal Series Cinnabar compatibility.

### ISSUE THREAD

**Issue by NullMagic** [JDKDigital/productive-bees#264]
Came across this issue while playing around with Productive Bees and the Thermal Series in 1.18.2, apparently the Cinnabar Bee outputs Cinnabar _dust_ instead of the item form. The problem is there's no way to turn the dust into the item, making it a useless output that has no benefit at all.

My suggestion would be to switch the comb output to the cinnabar item.

**Comment by JaisDK** [comment]
Which version are you playing on and which pack?

**Comment by Legorfyr** [comment]
I have the same issue in ATM7 0.4.4
Version is productivebees-1.18.2-0.9.0.4
