### ISSUE TITLE
[INFO] Are the upgrades stacked additively or multiplicatively?

### ISSUE THREAD

**Issue by leopupin** [JDKDigital/productive-bees#265]
Just a question from a  min-max player kind, I could lookup the code, but decided to ask here. plus if it's the mod intentions to mix and match these upgrades, since right now, seems like going all prod or all speed upgrades is the best (the kind depending on how they stack)

**Comment by JaisDK** [comment]
depends on the upgrade, so better look at the code https://github.com/JDKDigital/productive-bees/blob/dev-1.18/src/main/java/cy/jdkdigital/productivebees/common/block/entity/AdvancedBeehiveBlockEntity.java

**Comment by leopupin** [comment]
Looks to me like both of them are additive, both **time in hive** and **production**, is that right? If so, them time in hive is, at max upgrades, close to double the efficiency of the production one.

**Comment by JaisDK** [comment]
Interesting, I haven't done any calculations on it but most say it's the other way around. Remember that it's only the time spent in the hive, not the time for a full production cycle which includes the time it takes to pollinate on a block.
