### ISSUE TITLE
Thermal bees

### ISSUE THREAD

**Issue by Legorfyr** [JDKDigital/productive-bees#266]
I'm playing ATM 0.4.4 with productivebees-1.18.2-0.9.0.4
As a fun project I'm trying to get all obtainable bees.
Sadly when doing the last 3 thermal bees: Energized Glowstone, Resonant Ender and Destabilized Redstone I found an issue.
No matter what egg you put in the Induction Smelter, every egg turns into a Destabilized Redstone egg, making Energized Glowstone and Resonant Ender impossible to get.

**Comment by Nekosity12** [comment]
Unfortunately that's an issue on thermal's part. They do not support nbt ingredients it seems. I think the dev was however working on a solution where the bees are made from different machines or something though 🤔

**Comment by JaisDK** [comment]
they promised me NBT support :(

if they don't get it soon I might change up the recipes, but this also means that combs can't be processed in their centrifuge anymore

**Comment by JaisDK** [comment]
alternative recipes provided until NBT support is added
