### ISSUE TITLE
1.16.5 Updating server from 0.6.9.25 to 0.6.9.26 causes crash when going near existing bee farm

### ISSUE THREAD

**Issue by SumaniPardia** [JDKDigital/productive-bees#267]
[crash-2022-06-05_00.30.42-server.txt](https://github.com/JDKDigital/productive-bees/files/8840353/crash-2022-06-05_00.30.42-server.txt)

When we updated the server to version 1.16.5-0.6.9.26 the server started crashing consistently when going to an area where someone had set up a bee farm.  Rolling the server back to 1.16.5-0.6.9.25 fixed the issue.

**Comment by JaisDK** [comment]
Uploading a new file
