### ISSUE TITLE
All resource bees are not loading properly on my 1.16.5 server

### ISSUE THREAD

**Issue by Dedicated-RAM** [JDKDigital/productive-bees#269]
All resource bees are not loading properly on my 1.16.5-36.2.33 forge server.  I tried spawning in a crystalline bee and the bee entity is invisible and is marked as a productivebee._bee (or something along those lines).  Once it enters a hive or nest, it registers as a crystalline bee, but once it leaves the nest, it becomes invisible and an unknown entity again.  The same issue happens with all the other bees that are bred from the crystalline bee. I found glow bees also have this issue though I have not tried all of the bees.  Some bees work fine as well, such as the carpenter and mason bee.  The bees work fine in singleplayer as well and I also checked to make sure I'm running the most recent version of the mod of both the server and client (productivebees-1.16.5-0.6.9.25).

**Comment by JaisDK** [comment]
Can I see your latest.log file from the client?

**Comment by Dedicated-RAM** [comment]
[latest.log](https://github.com/JDKDigital/productive-bees/files/8938288/latest.log)
Had to trim the later half b/c the file was too large

**Comment by JaisDK** [comment]
You are missing some mods on the server


`[00:06:56] [Netty Client IO #0/INFO]: Client has mods that are missing on server: [hiddenrecipebook, betteranimals, zerocore, minecraft, ftbquests, immersiveengineering, durability101, masterfulmachinery, backpacker, pamhc2foodcore, notenoughbreeding, autoreglib, backpacked, floormats, puzzleslib, aquaculture, byg, konkrete, natural-progression, titanium, movingelevators, quark, storagedrawers, fins, transport, engineersdecor, flowerseeds, refinedstorageaddons, drinkbeer, penguinlib]`

**Comment by Dedicated-RAM** [comment]
Weird it says that because all/most of the mods listed above work on the server.  I'm running the Engineer's Life 2 modpack on my server and downloaded the latest serverpack for it.

**Comment by JaisDK** [comment]
there is some kind of discrepancy between the server and client because your logs is full of lines like this

[00:07:16] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 14 on entity ZombieEntity['Zistonian Zombie'/72303, l='ClientLevel', x=143.73, y=94.00, z=-290.73]: old=0(class java.lang.Integer), new={}(class net.minecraft.nbt.CompoundNBT)

Check that the version of Forge is the same on server and client and also verify the mod versions, maybe something is messed up there.

**Comment by Dedicated-RAM** [comment]
Okay, will do! Thank you so much!  I'll update you when I find time to look through and see if that fixes anything.

**Comment by JaisDK** [comment]
caused by cavesandcliffs
