### ISSUE TITLE
Broken with Pollen Library

### ISSUE THREAD

**Issue by brisingraerowing** [JDKDigital/productive-bees#271]
[Latest Log](https://gist.github.com/brisingraerowing/d1d9d97f86c897a5bc738d580166ccb3)

Not sure who's side this is on.

**Comment by JaisDK** [comment]
This is Pollen messing up some data in a vanilla class that I rely on...great

**Comment by brisingraerowing** [comment]
This seems to be a major issue with them. The last several versions of Pollen have had this kind of bug in various ways, all resulting in datapack errors.

ETA: I've removed Pollen and its dependent mod I was using. It just breaks far too often.

**Comment by JaisDK** [comment]
I'll change my reliance on that piece of data as well, but a library mod should not be messing this much with vanilla data. When you do mixins they have to be as few and small as possible where a library mod aims to be as broad and "useful" as possible.
