### ISSUE TITLE
Bee wont go in advanced beehive

### ISSUE THREAD

**Issue by Nazakk** [JDKDigital/productive-bees#273]
Hey, so i'm playing with a friend with a bunch of mods and we are trying to do bees, the problem is that normal bees or breeded bees won't go in advanced beehive, but in normal beehive from vanilla minecraft it works just fine, so i don't know if we are missing something or not.

**Comment by JaisDK** [comment]
Which version of the mod are you using and do you have the correct flower blocks for the bees?

**Comment by Nazakk** [comment]
We were using 1.18.2-0.9.0.5 and we just updated to 1.18.2-0.9.0.6

**Comment by JaisDK** [comment]
Try breaking the hive and place then again. You am an also pick up the bees in a cage and sneak release them on the hive to set their home position

**Comment by Nazakk** [comment]
I did what you said but the bees dont care

**Comment by JaisDK** [comment]
Have they pollinated? Which bees are you having?

**Comment by Nazakk** [comment]
I have normal bees and inferium bees (from mystical agriculture), they seem to pollinate (dont know if this is the word sorry) and after they are just flying around doing nothing

**Comment by JaisDK** [comment]
Can you show a picture of you setup?

**Comment by Nazakk** [comment]
![image](https://user-images.githubusercontent.com/76503537/175566157-53b8e518-0dfa-4c0f-9285-0698f7184f3e.png)

**Comment by JaisDK** [comment]
The hive is facing the wrong way

**Comment by Nazakk** [comment]
it is facing the left side but now it's facing to the door

**Comment by Nazakk** [comment]
I just tried in singleplayer and it works perfectly with normal bees

**Comment by Nazakk** [comment]
So any ideas ?

**Comment by JaisDK** [comment]
If the same setup works in single player, then there must be something wrong with the server
the things I mentioned earlier are the only fixes usually needed to resolve problems with bees entering hives

**Comment by SeriousWall117** [comment]
I have the same problem as you but no bees period will enter the hives, either types advance, base, and no even bee nest in the wild. 

version 1.19

other mods: 
Advance FInders
Advance ore Lods
Advanced Netherite
Advanced X-ray
Biome locator
XP Clumps
fast leaf decay
ForgeEndertech
Ore Excavation
Straw Golem
Xaeros Minimap
Xaeros WorldMap

I don't believe it could be these mods inferring with the bees but not sure. Was wondering if anyone else had this problem to this level

**Comment by JaisDK** [comment]
@SeriousWall117 I need the exact mod version please

**Comment by SeriousWall117** [comment]
1.19-0.10.0.2 
forge version. 
Updated three days ago.
for Minecraft 1.19

(of the bee mod) if that is what you meant or do you mean the other mods?

**Comment by JaisDK** [comment]
which bees are you having trouble with?

**Comment by SeriousWall117** [comment]
I was setting up my farm with the base game bees. Putting the hive in the middle of the farms and flowers on the outsides. Then i would incase the whole thing. The bees would pollenate the flowers enough to where they would normally fly back to the hive but instead they continue to fly around non stop, never going to the hive. Then I switched to creative to see what it wrong. 

I placed base game hives, advance hives, even the wild nests. I used spawn eggs for the base game bees. none of them took to a hive. So I went to then internet and found someone saying spawned one act strange with the mod. 

So I made a new world and found some natural Blue Barbed bees and tried them. Placed a hive nearby, used flowers to lead them to it and nothing. They flew off into the sun set without me.

Im trying to figure out if its on my end because i really like the way this mods is.

**Comment by JaisDK** [comment]
found the issue for 1.19, I'll put up a fixed version soon

**Comment by SeriousWall117** [comment]
So its not on my end?

**Comment by JaisDK** [comment]
no, I deleted the wrong tag in the latest 1.19 update. uploading a new version now

**Comment by Nazakk** [comment]
well i'm guessing my problem is coming from my server not from the mod sorry for the disturbance

**Comment by SeriousWall117** [comment]
It works!!! Thank you so much. Thank you for making this mod

**Comment by JaisDK** [comment]
@Nazakk I will check on a server tomorrow if I also have problems

**Comment by Nazakk** [comment]
ok ty

**Comment by Nazakk** [comment]
this check is slow

**Comment by shikyo13** [comment]
We seem to be having the same issue with bees not going into hives on 1.18.2 - 0.9.0.6 

Forge - 40.1.48

Modpack TNP Limiteless

**Comment by JaisDK** [comment]
@shikyo13 which bees and have they pollinated? Did you try the aforementioned actions to fix it?

**Comment by shikyo13** [comment]
Yes the previously mentioned fixes of re-placing the hives and setting home position have not worked unfortunately. Gold Bees, Tin Bees, ProsperiBees are just a few examples of many.

**Comment by JaisDK** [comment]
do any of you have radium reforged installed on the server?

**Comment by Nazakk** [comment]
Yes i think i have it on the server

**Comment by JaisDK** [comment]
add
`mixin.ai.poi=false`
to the radium config file

**Comment by Nazakk** [comment]
my server hoster doesnt allow me to edit files, if i delete the mod entirely will it work/ do the same ?

**Comment by JaisDK** [comment]
yes

**Comment by Nazakk** [comment]
Yes it's working thank you, you saved me

**Comment by shadeaux83** [comment]
Sorry to just tack onto this issue, but it seems to be the same problem I'm having.  I'm on the Engineer's Life 2 mod pack (1.16.5), but that does not have Radium Reforged.
It's using productivebees-1.16.5-0.6.9.25.
Any ideas for a mod in that pack that would be causing an AI issue like Radium was?

**Comment by JaisDK** [comment]
which bees are you having that won't go into the hive?

**Comment by shadeaux83** [comment]
Yellow Carpenter Bee and Resin Bee at the moment.

**Comment by JaisDK** [comment]
they are solitary and do not live in hives

**Comment by shadeaux83** [comment]
I knew they wouldn't breed with others, but I didn't realize that meant they also wouldn't even go into a hive.  Thank you :)  Is there a place that says which ones can and cannot live in hives?

**Comment by JaisDK** [comment]
when you pock them up in a cage you can see what type they are
in general, anything you find in the overworld is solitary except the slimy bee and vanilla bees

**Comment by shadeaux83** [comment]
Oh ok, I see.  Thank you for the quick response. :)
