### ISSUE TITLE
productivebees-1.19-0.10.0.1 "CreeBee"

### ISSUE THREAD

**Issue by MatthewDVance** [JDKDigital/productive-bees#274]
can't seem to get the CreeBee to pollenate with anything, and it does not render in the advanced hives

productivebees-1.19-0.10.0.1

**Comment by JaisDK** [comment]
Are you having the same issue with 0.10.0.3?

**Comment by MatthewDVance** [comment]
running TNP Limitless 6. so ill have to manually update the mod.
figured out it does pollenate over TNT blocks.
just got my first powdery comb. but this guy isn't listed in JEI, at least not in TNP6 at the moment.

its "working"... mostly.
thanks for responding!

**Comment by JaisDK** [comment]
JEI was not released for 1.19 when 0.10.0.1 was released, so you won't find any JEI integration in that version.

**Comment by MatthewDVance** [comment]
sorry. I meant REI.

**Comment by JaisDK** [comment]
same deal, just update the mod
