### ISSUE TITLE
Ticking entities with flowers/cupric used before it was bound

### ISSUE THREAD

**Issue by DoctorMage** [JDKDigital/productive-bees#275]
Unsure why this happened but this is another players world in which I had the crash in
Ticking entities in forge was unable to work according to them
So I manually removed bee within the region files had to do it twice unsure if i did correctly the first time so that might have been an error on my end

Modpack
Life in the village 2

Mod Version 
productivebees-1.16.5-0.6.9.26

Crash report
[crash-2022-06-28_10.33.25-server.txt](https://github.com/JDKDigital/productive-bees/files/8999882/crash-2022-06-28_10.33.25-server.txt)

Logs
[2022-06-28-2.log](https://github.com/JDKDigital/productive-bees/files/8999944/2022-06-28-2.log)
[debug-3_1.log](https://github.com/JDKDigital/productive-bees/files/8999946/debug-3_1.log)

**Comment by JaisDK** [comment]
copper bee I suppose, you just need to update the mod

**Comment by DoctorMage** [comment]
Alright I'll get them to do that and see if that fixes the issue thanks

**Comment by DoctorMage** [comment]
forgot to update but issue is fixed after updating
