### ISSUE TITLE
Babee Upgrade doesnt seem to work

### ISSUE THREAD

**Issue by Saphirius** [JDKDigital/productive-bees#276]
Im currently playing the All in One Modpack (1.16.5) and installed 2 Babee Upgrades in a Hive with 3 Prosperity Bees. After 2 Hours of continuous production of Honey and emptying the hive no baby has spawned so far.

**Comment by JaisDK** [comment]
Bees that can't breed do not work with the babee upgrade.

**Comment by Saphirius** [comment]
Maybe this could be added as info in the book, or on the upgrade? I thought this upgrade was supposed to be used to breed bees that cant be manually bred.

**Comment by JaisDK** [comment]
it's meant to automate breeding
