### ISSUE TITLE
[Bug] Bee nest invalid for ticking

### ISSUE THREAD

**Issue by TheonlyTazz** [JDKDigital/productive-bees#277]
**Mod Version**

productivebees-1.18.2-0.9.0.7.jar

**Description**
Console gets spammed full with WARNs

**Screenshots**
![image](https://user-images.githubusercontent.com/3908847/176672777-fb730262-3668-4395-aa08-bd9aa9b15eab.png)

**Comment by JaisDK** [comment]
[productivebees-1.18.2-0.9.0.7.zip](https://github.com/JDKDigital/productive-bees/files/9019892/productivebees-1.18.2-0.9.0.7.zip)

Does this behave better?

**Comment by TheonlyTazz** [comment]
will test it and report back

**Comment by TheonlyTazz** [comment]
Seems to be fixed with the provided jar thanks alot!
