### ISSUE TITLE
[1.18.2] Adding Ghostly bee via datapack isn't working

### ISSUE THREAD

**Issue by Saereth** [JDKDigital/productive-bees#278]
I'm trying to add a conversion recipe for the ghostly bee, Im not entirely sure if my script is right but all the other bees I've added seem to be working except this one. Am I doing something wrong here?

```
{
  "type": "productivebees:bee_conversion",
  "source": "minecraft:bee",
  "result": "productivebees:ghostly",
  "item": {
    "item": "minecraft:soul_lantern"
  },
  "conditions": [
    {
      "type": "productivebees:bee_exists",
      "bee": "minecraft:bee"
    },
    {
      "type": "productivebees:bee_exists",
      "bee": "productivebees:ghostly"
    }
  ]
}
```
Thanks for the info

**Comment by JaisDK** [comment]
looks correct, does your log say anything about errors? if you post the latest.log here I can take a look

you can remove the first condition since the vanilla bee is always present

**Comment by Saereth** [comment]
So oddly enough, removing the conditional check made it start working...

**Comment by JaisDK** [comment]
it was only meant to be used with nbt bees anyway since they can be disabled

**Comment by Saereth** [comment]
gotcha, ok thanks for the info!
