### ISSUE TITLE
No Crystalline Bees In The Nether

### ISSUE THREAD

**Issue by ChrisLTheNerd** [JDKDigital/productive-bees#28]
I'm unable to find Crystalline Bees or their nest in the nether. I've seen the other bees like the Glowstone Bee and Magma Bees. I tried to even put the spawn rate way up and it worked for all the bees, but it didn't make Crystalline Bees spawn either.

**Comment by JaisDK** [comment]
Hello,

They can be very hard to find as the nests usually spawn in quarts veins covered in Netherrack, not on the surface. I find that turning on subtitles and looking for the buzzing sound event can help locate them or simple craft a quartz nest and place it in the nether. An empty nest will attract a bee in 3 days time (36000 ticks).
I'm annoyed by this myself, so I have a note to make the nests spawn more on the surface in a later version.

**Comment by JaisDK** [comment]
Note that the bees don't spawn on their own, only inside a nest so upping the spawn rate will not have an effect.

**Comment by ChrisLTheNerd** [comment]
Ahhh that's where they are, I was just trying to find them naturally. Thanks for clearing up everything, including how the bee spawn rates work. Also you have a great mod with potential, I just reviewed the mod and hopefully more people might download your mod :)

**Comment by JaisDK** [comment]
You reviewed it? Can you send a link? :)

**Comment by ChrisLTheNerd** [comment]
Yeah sure, it's not perfect but I tried my best :D I mostly just reviewed
the basic stuff like capturing the bees breeding them (my example was the
diamond bee), and extracting materials from their combs. https
://youtu.be/O2Ynp1JeLg0 <https://youtu.be/O2Ynp1JeLg0>

**Comment by JaisDK** [comment]
Nice, your bee garden is so much prettier than my test world! :)

also I fixed the honey treats for next release, hadn't noticed they stopped working.

**Comment by ChrisLTheNerd** [comment]
Thanks, took me a while to make the garden. Also yeah, I forgot to mention the honey treats in this issue page, glad it's getting fixed. See you around if I come across any bugs or even if I just have some suggestions to make your mod better. Bye for now and have a great day 👋
