### ISSUE TITLE
 the bees do not appear!

### ISSUE THREAD

**Issue by GonzaloGamenara** [JDKDigital/productive-bees#281]
1.18.2 (forge 40.1.60)

I have a server with about 160 mods, the bees do not appear in the world, should I modify something in the files related to the biomes? I have the "oh the biomes you'll go" 

All the mods:

[Nuevo documento de texto.txt](https://github.com/JDKDigital/productive-bees/files/9145197/Nuevo.documento.de.texto.txt)
d

**Comment by GonzaloGamenara** [comment]
![image](https://user-images.githubusercontent.com/103406044/180048810-c74c7af7-59d3-4439-8983-610a920982a8.png)

**Comment by GonzaloGamenara** [comment]
I think the problem could be an incompatibility with the "Dynamic Trees" mod, this prevents honeycombs from being generated

**Comment by JaisDK** [comment]
Yea that would be the problem. Just craft the nests yourself and use honey treats on them to spawn the missing bees.
