### ISSUE TITLE
Bee Cages which stack only release one bee when used in world, but delete entire stack of cages.

### ISSUE THREAD

**Issue by togreglove** [JDKDigital/productive-bees#282]
Version: ProductiveBees-1.18.2-0.9.0.9
Pack: TNP Limitless 5
Server: FeedTheCraft

I have had bee overruns from the BaBee augment and gather the excess bees in bee cages (normal, not sturdy).
Some of them will stack, others won't.
When I have a stack in hand and click in the world to release the bee, it releases one (1) bee and deletes the entire stack of cages.

**Comment by JaisDK** [comment]
they are not really supposed to stack when filled
I guess it happens now that I've started stripping almost all extra data from them to save on data

**Comment by TheCommensuratePup** [comment]
To be honest, it's a lot easier if they do stack. They would be easier to carry & drop if it didn't delete the whole stack. That & the gene treats give a better experience if they stack in my admittedly limited experience

**Comment by JaisDK** [comment]
it's fixed in the latest release

all the stuff stacks if the NBT data is the exact same, it's just rare to get those items with the same NBT
