### ISSUE TITLE
[Minor Issue] Shift clicking bottles into hive has extras go into output slots

### ISSUE THREAD

**Issue by togreglove** [JDKDigital/productive-bees#283]
If I have a hive with empty bottles in it and shift-click a stack (or more than enough to overflow the bottle slot) it put the extras into the output slots.
In most cases this isn't an issue, but I automatically process all items that are in the output slots and the extra bottles clog the system.

Preferred behavior: Bottle slot in hive fills to full and excess are left in inventory as partial stack.

**Comment by togreglove** [comment]
Also, shift clicking a stack of treats into the incubator puts the excess in the output slot. Same issue.

**Comment by JaisDK** [comment]
I don't really want to look at that code again. Maybe some day

**Comment by togreglove** [comment]
Ya, it's really just a polishing step. Very low priority, but I wanted to mention it anyway, because if I didn't, I would feel bad cursing under my breath every time it happened :)  Great mod. Love your work.

**Comment by JaisDK** [comment]
hehe, there's definitely a bunch of polishing to do here and there
