### ISSUE TITLE
Bees doesn't appear on 1.16.5 forge server

### ISSUE THREAD

**Issue by ZanovelloMattia** [JDKDigital/productive-bees#286]
The crystalline bees doesn't appear when i use the honey treat on the quarz nest in a 1.16.5 forge server, this is the logs of the client and the server:
client, [latest.log](https://github.com/JDKDigital/productive-bees/files/9244029/latest.log)
server, [latest.log](https://github.com/JDKDigital/productive-bees/files/9244037/latest.log)

thanks.

**Comment by JaisDK** [comment]
Are all the bees invisible? this is caused by the cavesandcliffs mod you have installed.

**Comment by ZanovelloMattia** [comment]
No not all the bees are invisibile. I'm playing in a
modpack that in single player I can see the
crystalline bee but in the server i can't.

**Comment by JaisDK** [comment]
the problem is still the mod I mentioned

**Comment by ZanovelloMattia** [comment]
Ok, thanks

**Comment by JaisDK** [comment]
There's a better (real) mod here for the backport https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport
The one you have installed is an MCreator mod, which is just something you should steer clear of in general.

**Comment by ZanovelloMattia** [comment]
Thanks you i solved just downgrading the cavesancliffs mod from version 7 to 6.3.
Thanks a lot.

**Comment by JaisDK** [comment]
Cool, good to know there's a solution for it.
