### ISSUE TITLE
Bees not exiting hive and not becoming adults

### ISSUE THREAD

**Issue by PmanAce** [JDKDigital/productive-bees#288]
ATM7 using productivebees-1.18.2-0.9.0.10.jar

Obtained 4 baby allthemodium bees, they entered an advanced hive with expansion box and they have not left it or matured to adults. Other bees have not been affected. This is after several hours. Noticed withered bees (skeletal and zombie) experiencing the same behaviour, they won't leave hive. Happened since the latest update to ATM7.

Thanks!

**Comment by JaisDK** [comment]
Can you show the setup where they live?

**Comment by PmanAce** [comment]
Vibranium bee there not affected:

![image](https://user-images.githubusercontent.com/3279523/183425529-1aefb9ad-72ca-4a28-83c5-a30337c0d07e.png)

![image](https://user-images.githubusercontent.com/3279523/183425684-adf3e001-00d0-43f4-b29f-c240b2d961b2.png)

Hard to see in image but they have stayed as child without leaving. 

Same thing for withered bee, ancient bees not affected
![image](https://user-images.githubusercontent.com/3279523/183426614-5ab7fa62-f491-4b85-b622-e1abbb95e426.png)

These also will not exit anymore:
![image](https://user-images.githubusercontent.com/3279523/183426963-711d590f-86f2-459d-9b3d-fc8d8d908cc7.png)

**Comment by JaisDK** [comment]
I need to see the hive they live in. They don’t age while inside only when leaving or being outside. 
it looks like you have them inside a compact machine, I don’t know what weather and day cycle that thing have. Can you try putting them outside to see if they work as expected?

**Comment by PmanAce** [comment]
Had a diamond bee with them that exited like normal once being put outside:

![image](https://user-images.githubusercontent.com/3279523/183431931-c88d78b6-789c-492a-b776-e022a371d42c.png)

![image](https://user-images.githubusercontent.com/3279523/183432106-f71ffc81-beff-442f-a16f-d449820187e7.png)

**Comment by JaisDK** [comment]
Hit the hive with a stick now that you're outside while daytime, it should evacuate them if they are able to

**Comment by JaisDK** [comment]
if they still don't come out, then they are broken

**Comment by PmanAce** [comment]
Sorry for all this, they exited during the night, must be compact machines never register the night time state. :(

Will try the same thing with the withered bees.

**Comment by JaisDK** [comment]
glad it's working, it should have ignored the night state though if the dimension the hive is in does not have a day night cycle

maybe compact machines don't register that properly in their dims

**Comment by PmanAce** [comment]
thx for help!
