### ISSUE TITLE
Dragon egg hive with Expansion Box

### ISSUE THREAD

**Issue by raffycaccia** [JDKDigital/productive-bees#29]
![2020-06-05](https://user-images.githubusercontent.com/45554975/83916408-6f631c80-a775-11ea-9c65-2d9869813b52.png)
![2020-06-05 (1)](https://user-images.githubusercontent.com/45554975/83916411-70944980-a775-11ea-893e-8bc1a7456dd4.png)

It works but it seems a little unsightly

**Comment by JaisDK** [comment]
:D Never thought to try that. This is certainly unintended.

**Comment by JaisDK** [comment]
Fixed in the new upload
