### ISSUE TITLE
Bees refuse to even touch the hive.

### ISSUE THREAD

**Issue by Pineappleguy03** [JDKDigital/productive-bees#290]
Been doin this for a few days and the bees still refuse to go into the hive. And I dunno what the hell it is. I tried removing Radium. But that didn't work either. Kinda need help.

**Comment by JaisDK** [comment]
Need a log

**Comment by Pineappleguy03** [comment]
Here's Both
[latest.log](https://github.com/JDKDigital/productive-bees/files/9305698/latest.log)
[debug.log](https://github.com/JDKDigital/productive-bees/files/9305699/debug.log)
.

**Comment by JaisDK** [comment]
Forgot to ask which bees you’re having trouble with

**Comment by Pineappleguy03** [comment]
It is literally ANY BEE. Spawned with an egg. Or from a bee nest,

**Comment by JaisDK** [comment]
Just checking it’s not solitary bees you’re trying with. Try breaking the hives and place them again to re register the POi

**Comment by Pineappleguy03** [comment]
Tried with a blue ashy mining bee. And broke the hive. It’s just flying around doing nothing at all.

**Comment by JaisDK** [comment]
Ashy mining is a solitary bee, try with a vanilla or other hive bee

**Comment by Pineappleguy03** [comment]
What about a Creebee

**Comment by JaisDK** [comment]
That one should go in the hive yes, if you make sure to put a coal ore near it as flower

**Comment by Pineappleguy03** [comment]
Ok I did that... it’s all like pollinated and what not. AND IT JUST. Flies away.

**Comment by Pineappleguy03** [comment]
Like it’s blind to it. It sees vanilla hives. But that’s it

**Comment by JaisDK** [comment]
Are you in single player?

**Comment by Pineappleguy03** [comment]
Er. No. Server but it’s only me

**Comment by Pineappleguy03** [comment]
Also another thing. Is Radium causing huge issues with productive bees still?

**Comment by JaisDK** [comment]
Yes, they haven’t fixed anything. Remove it from the server as well

**Comment by Pineappleguy03** [comment]
It is removed. But the bees don’t do anything

**Comment by JaisDK** [comment]
Can I have a log from the server too then?

**Comment by Pineappleguy03** [comment]
The two that I sent were from the server btw.

**Comment by JaisDK** [comment]
Then I don't know what the problem is, haven't come across this in 1.16 before. Try removing that bee fix mod you have.

**Comment by Pineappleguy03** [comment]
OHHHHHH! THAT MIGHT HELP ACTUALLY.

**Comment by Pineappleguy03** [comment]
OH MY GOD. WRONG CONFIG. Need Help. It's 1.18
[latest.log](https://github.com/JDKDigital/productive-bees/files/9312011/latest.log)

[debug.log](https://github.com/JDKDigital/productive-bees/files/9312010/debug.log)
8

**Comment by JaisDK** [comment]
I see you're spawning in solitary bees, you won't get any results with those. Do the following

Remove Create Confectionery (you can add it back once things work)
Place a new advanced beehive with flowers nearby
Spawn vanilla bee

Check if it pollinates and goes into the hive.

If it flies away, pick it up in a cage and sneak while releasing it on the hive.

Report back your findings.

**Comment by Pineappleguy03** [comment]
Before I do that. Why remove create confectionary? And do I keep Radium out of the pack

**Comment by JaisDK** [comment]
it's an MCreator mod, they can mess anything up

**Comment by Pineappleguy03** [comment]
Oh can you tell me what others are MCCreator mods?

**Comment by JaisDK** [comment]
it's the only one I know of from your modlist

**Comment by Pineappleguy03** [comment]
Ok Man! They went in! Should I try A modded Bee?

**Comment by Pineappleguy03** [comment]
OH. THEY ALSO WENT IN.

**Comment by JaisDK** [comment]
nice, you can add back confectionary and see if it still works

**Comment by Pineappleguy03** [comment]
Question. Do I still keep out Radium?

**Comment by JaisDK** [comment]
you can try adding it with the config `mixin.ai.poi=false`  and see if it still works

they should come out with a fixed version soon too

**Comment by Pineappleguy03** [comment]
Thanks
