### ISSUE TITLE
[1.18.2] Weird issue with bees not leaving hivve

### ISSUE THREAD

**Issue by Saereth** [JDKDigital/productive-bees#291]
I've added in a custom ghostly and skeletal bee recipe, those work fine. You give a vanilla bee a ghost lantern, and it transforms. The problem is (And to preface this, the entire pack takes place in the nether) Once they go into the hive they don't come back out. They are nocturnal when you make them and never come out even if I /time set night. I also nbtedited the hive and their time in hive never goes past 1 more than their min duration

https://cdn.discordapp.com/attachments/908073397689393212/1008097847956230164/unknown.png

not sure if that's relevant but noted anyway
if I forcibly set the bee_behavior to 1 (diurnal) they start working again and what's more odd is if I use a spawn egg instead of the recipe to summon them they are diurnal by default and always work fine. 

This is a very confusing issue for me to try to troubleshoot, so if I can provide any additional data let me know.

The datapack recipe for the bee is as follows:

```
{
        "type": "productivebees:bee_conversion",
        "source": "minecraft:bee",
        "result": "productivebees:ghostly",
        "item": {
            "item": "minecraft:soul_lantern"
        },
        "conditions": [
        ]
    }
```

**Comment by JaisDK** [comment]
could you tell me what version of the mod you are using, if it's not the latest try updating

**Comment by Saereth** [comment]
productivebees-1.18.2-0.9.0.11 which I believe is the latest

**Comment by JaisDK** [comment]
what hive are you using?

**Comment by Saereth** [comment]
advanced oak and advanced warped hives were both used for the testing

**Comment by JaisDK** [comment]
lol I think I made a big mistake

what is the value of the gamerule `playersSleepingPercentage` in your world?

**Comment by Saereth** [comment]
100, default I believe

**Comment by JaisDK** [comment]
the bug I made means that weather and day/night cycle counts in the nether and end which it is not supposed to do

I'm guessing it never become "night" in the nether and this is why they stay inside

**Comment by Saereth** [comment]
ah interesting

**Comment by JaisDK** [comment]
since you're messing around in a dev environment, would you like a test version to see if I got it fixed correctly?

**Comment by Saereth** [comment]
sure np

**Comment by JaisDK** [comment]
[productivebees-1.18.2-0.9.0.12-beta.zip](https://github.com/JDKDigital/productive-bees/files/9332551/productivebees-1.18.2-0.9.0.12-beta.zip)

sweet

**Comment by Saereth** [comment]
sorry for the delay, I checked it out but this is actually worse now. No bees are existing now regardless of the setting. I also tried setting player sleep to 1% and 100%, no effect

**Comment by Saereth** [comment]
this seems resolved with the latest release, ty!
