### ISSUE TITLE
[1.18.2] [ATM7 0.4.23] Productive Bees behavior wander off and missing honeycomb items

### ISSUE THREAD

**Issue by MPacitto** [JDKDigital/productive-bees#292]
I realize this may be more a modpack compatibility problem and not a Productive Bees problem, however I wanted to flag this issue anyway if it helps troubleshooting the issue further. And besides, modpack compatibility is great!

Noticed behaviour on ATM7 0.4.23 server, which uses Productive Bees 0.9.0.9, may try upgrading ATM7 version later although nothing in changelogs for update 24 or 25 mention fixing bee issue.

Modded bees of any kind (solitary nest bees such as Leafcutter Bee, or hive bees such as Iron Bee) simply wander off once they spawn. They will shelter in a nest or hive if it's night time or raining, which is proper behaviour. In optimal conditions, they exit nest/hive and will endlessly wander away with no flower interaction.

In the quest log, taking the Iron Bee as an example, clicking the Iron Honeycomb item results in a "No valid items!" pop up and suggests reporting a bug. Searching JEI (mod), the iron honeycomb is not listed. Hypothesis: Perhaps the modded bees have improper behaviour because their items do not exist / did not load properly?

Vanilla MC bees behave normally. Enter/exit nests or beehives, produce honeycomb/honey bottle, gather from flowers, breed, etc.

Tried a very quick fix by updating Productive Bees mod to 0.9.0.11 (backing up 0.9.0.9 and replacing in /mods folder), this generated a warning in the server log, generated no crash, and changed no behaviours.

**Comment by Legorfyr** [comment]
Uhm, that's just the quest mod being odd. I'm on 0.4.25 and have none of those issues. 
Iron comb shows perfectly in jei as well.
The only bees with wanderlust I have are the magmatic, blazing and sometimes the bazbee.

**Comment by MPacitto** [comment]
It's not just the quest log, there is no iron honeycomb in my JEI.
Made a second installation with ATM7 0.4.25 and the issue persists. Could be on my end but no idea why. Nothing strange in the log regarding productive bees either.

**Comment by JaisDK** [comment]
The quests have been fixed in newer versions of the modpack. What do you see if you look up the uses for the iron bee? there should be a hive production tab where it shows the iron comb.

What warning did you get when you updated to the latest version?

**Comment by JaisDK** [comment]
Have you added anything to the pack like Radium?

**Comment by MPacitto** [comment]
> Have you added anything to the pack like Radium?

No, I did not add anything. v0.4.23 was a basic ATM7 install using CurseForge App, and server files downloaded from CurseForge.

The v0.4.25 was a server "update", so I got the new server files from CurseForge, made a copy of the v0.4.23 server, installed new forge libraries, deleted configs/mods/defaultconfigs and so on, and replaced with the updated server files.

> What do you see if you look up the uses for the iron bee? there should be a hive production tab where it shows the iron comb.

When I look up the Iron Bee, this is what I see (sorry, not sure how to make the embedded image small):
![image](https://user-images.githubusercontent.com/16651470/184712431-356d28f5-efd0-47d8-b1b8-6d15d1e90dc6.png)

**Comment by JaisDK** [comment]
these are the recipes, look up the uses for the bee (right click)

**Comment by MPacitto** [comment]
> What warning did you get when you updated to the latest version?

When I forced that mod update on ATM v0.4.23 from PB 0.9.0.9 to 0.9.0.11 (against some judgment) just to see what would happen, the log produced this:

`[15Aug.2022 11:58:13.533] [main/WARN] [net.minecraftforge.common.ForgeHooks/WP]: This world was saved with mod productivebees version 1.18.2-0.9.0.9 and it is now at version 1.18.2-0.9.0.11, things may not work well`

In-game, didn't notice any difference.

**Comment by JaisDK** [comment]
ah, that's a standard mod update warning, your log will be full of that every time you update the pack

the only problem in the newest version is that day/night cycle and weather is counted in the nether, so bees might stay at home for too long

**Comment by MPacitto** [comment]
Hey again, it looks like this is no longer a problem. Took some time to let players gather data on the new server v0.4.25 and the bees are all behaving normally again.

I am thinking maybe it was related to the upgrade to PB v0.9.0.10, in particular:
`-- Fixed bees forgetting where they live when leaving for work in the morning`

In the older server version using v0.4.23 the modded bees were all just wandering off and losing connection to their hives
