### ISSUE TITLE
Fishing rod unusable

### ISSUE THREAD

**Issue by fa-fur** [JDKDigital/productive-bees#295]
In Minecraft 1.19.2 with Forge 43.1.2 the mod's versions 0.10.1.0 and 0.10.1.1 prevent the usage of any fishing rod. 

When the bobber sinks during fishing, it is impossible to reel in the catch. The player may only reel in the bobber when it is no longer under water - at which point that action no longer yields any loot. The issue persists without any other mods installed and regardless of enchantments on the fishing rod or which biome you're in.

**Comment by JaisDK** [comment]
Thanks, uploaded a new version https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3954109

**Comment by fa-fur** [comment]
That fixed it, thank you for the quick response!

**Comment by drakray** [comment]
~~I have a very similar problem with 1.18.2 0.9.3.0, where sometime it work, sometime not, and I got a LOT of sponge bees, and some prismarine, almost more than actual fish and loot
Also, those 2 are not configurable in configs?, I tried disabling them see if it fixes the problem~~
Seems to be from another mod, sorry for that(LostAndFished when configuring the blacklist)
