### ISSUE TITLE
1.19 Crash while generating new chunks

### ISSUE THREAD

**Issue by Raidobw2** [JDKDigital/productive-bees#296]
Hi! I'm relaying this from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1298.

There is a crash that happened for a player when they were exploring the world. They were in a Savanna, and suddenly the server crashed while generating new chunks.
Crash log: https://paste.feed-the-beast.com/view/5bfaa384
Text file in case you prefer it: [crash-2022-08-28_10.43.25-server.txt](https://github.com/JDKDigital/productive-bees/files/9451819/crash-2022-08-28_10.43.25-server.txt)

Versions:
Minecraft `1.19`
Forge `41.0.63`
Productive Bees `productivebees-1.19-0.10.0.3.jar`
Modpack `FTB One 1.3.0`

Additional information:
- The server running the mods has 2G max allocated (this is a small-medium pack, 2 players online)
- The server is running on Gentoo Linux

Thanks a lot in advance! Let me know if I can be of any help

**Comment by JaisDK** [comment]
The pack is a bit behind behind, it's already fixed in a mod update.

**Comment by Raidobw2** [comment]
Ahh I see, thanks for the info c: I saw you commented in the linked issue, we'll use the config in that case.

Assuming PB is supported on future 1.19.2+ versions, we could deal with the config for now and have the pack jump from 1.19 to 1.19.2.
Since that's probably the best route for us as well, I hope this is alright with you if I close my ticket as resolved.

Have a good day and thanks again!
