### ISSUE TITLE
Skeletal bee not producing anything

### ISSUE THREAD

**Issue by Nevrai** [JDKDigital/productive-bees#298]
Even with four speed upgrades, my skeletal bee is not producing anything. It originally spawned because there was no light in the area. It goes in and out of the beehive without producing any honey, skeletal combs, or bones.

I’m not sure whether I’m doing something wrong or this is a bug, but I can’t figure out why it’s not producing anything. I tried both having no light in the area and having light, but neither makes it produce honey or items. I tried breaking the beehive and expansion box and replacing them, but that didn’t work either. Also tried having no upgrades in the hive.

![2022-09-01_14 21 43](https://user-images.githubusercontent.com/59761487/187913187-d539d54d-e141-4f17-81e3-43fe9e6a1bb7.png)

### Versions

* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.29 [latest])
* **Minecraft:** 1.18.2
* **Forge:** 40.1.69
* **Mekanism:** 0.9.0.11 (latest for 1.18.2)

**Comment by JaisDK** [comment]
you need a bone block as flower

**Comment by DeleteMetaInf** [comment]
Oh, I see. I tried using bone blocks, but it still doesn’t seem to produce anything, though. It stayed in the hive for a long time, and then it left the hive, and nothing had been produced. What am I doing wrong? Does it need to be in darkness?

![2022-09-01_14 50 19](https://user-images.githubusercontent.com/59761487/187917911-29ced92e-5d04-4460-b8b1-498344116f21.png)

**Comment by Nevrai** [comment]
Oh, sweet, it does work now that I’m using bone blocks. Thank you!

![2022-09-01_14 50 19](https://user-images.githubusercontent.com/59761487/187918020-bb80af6f-342f-4cd7-a51b-b7b915a7c301.png)
