### ISSUE TITLE
Bee's turning into zombie/skeleton bees

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#3]
So we are noticing that all of our bees our turning into Zombie/Skeleton Bees? For example we went to the nether a 2 days ago and got a magmatic and brought it back, replaced all the bee hives with advanced bee hives and logged off the server. Came back to the server yesterday and all of our normal bees were gone included our magmatic bee and instead we had 2 zombie bees and 1 skeleton bee. We assumed the normal bees flew away because they didn't like the new hives, but were not sure what happened to the magmatic bee.

So we said, whatever and went out and caught a few different types of bees. Today when we logged back in, we had just more zombie and skeleton bees and all of our other one's were gone again. Assuming this is a WIP, is this a bug or intended feature? Do zombie/skeleton bee's kill other bees? They are not listed on your readme, so I am trying to dig through the source code today to see if I can determine whats happening and way, but figured I would post this here too.

**Comment by JaisDK** [comment]
Hello,
Unfortunately, vanilla bees don't stay in modded hives at the moment. There's a patch for Forge pending to fix this. The skeletal and zombie bees move into available hives during night time, they don't kill off other bees. Next update will have this configurable to prevent them spawning and I'll also change it so they will not move in if the hive is fully lit.
The other bees you caught and the magmatic bee are all solitary bees and will not live in hives. You can bring their nests home with you or craft new ones for them.

**Comment by mouse0270** [comment]
So just a lack of knowledge on our end. Do you have this information listed anywhere? Also do they need special hives or just hives with no other bee's in them? Do I need silk touch to get their hives? Because the magmatic bee did stay in the advanced hive for quite some time. Can other magmatic bee's be in the same hive? Or just one bee per hive? Is there a way to limit the hive to just one bee to help prevent this from happening?

**Comment by JaisDK** [comment]
There's no limit on the number of the same type of bees in a hive. I just looked through my notes and the magmatic and other nether bees are supposed to be in the hive (in the future they can be trained to live in hives), but there's a little bug with that so they might move out if they get too far away. You don't need silk touch, I personally hate that requirement from vanilla, but in the current version some of the nests are missing loot tables, so they wont drop as items.
A new version will be up soon with fixes for that.
Another thing I haven't documented yet is that solitary nests when left uninhabited will have solitary bees move in on their own, so you can craft the nests and leave them for 30 minutes to get new bees. This is very handy for nether bees. Recipes can be found in JEI.
