### ISSUE TITLE
Quarry Bees not creating chips or blocks when simulating

### ISSUE THREAD

**Issue by 2lgit2quit** [JDKDigital/productive-bees#301]
quarry bees inside an advanced hive are unable to produce blocks or chips, they are still able to produce honey and comb but they will not create blocks or chips, I assume this is because the bee is unable to select a block for pollination. I presumed it would collect the block in the pollination position (foot of hive) but that's definitely not the case as I have tried multiple different types of blocks in multiple different positions to no avail.

**Comment by 2lgit2quit** [comment]
quarry bees only simulate using feeding slab

**Comment by JaisDK** [comment]
no need to close it, it's real issue
will be fixed next version

**Comment by 2lgit2quit** [comment]
my bad, thought it was designed to be like that
