### ISSUE TITLE
genetic attributes not passed down to offspring when using breeding chamber

### ISSUE THREAD

**Issue by 2lgit2quit** [JDKDigital/productive-bees#302]
The traits very high productivity and metaturnal cannot be passed on through breeding when the breeding chamber is used. I have tried breeding bees without the breeding chamber and there is no issue with passing on attributes. At the moment I have tried breeding 2 bees with identical attributes (very high and metaturnal)  and 1 bee with very high and metaturnal along side a bee that has lower attributes, both producing no bees with either superior attribute present after 10 attempts of breeding each.

**Comment by JaisDK** [comment]
fixed
