### ISSUE TITLE
Breeding chamber randomises bee stats

### ISSUE THREAD

**Issue by 2lgit2quit** [JDKDigital/productive-bees#304]
The stats of bees born through breeding chamber are entirely random from what I can tell. I have used 2 bees that are identical in all stats other than max health in a breeding chamber under the assumption that genes have a higher likely hood of being the same as the parent bees but as you will see in the screenshots the most prominent gene found through breeding the bees is a gene that neither bee has, that being the high production gene. I'm not sure if this is intended as a nerf to the breeding chamber as it already removes breeding delay but as far as I can see it is a bug.
![OffspringSet1](https://user-images.githubusercontent.com/112800734/189899052-33aa9003-4ac4-4eaf-880d-805fd78d79d5.png)
![OffspringSet2](https://user-images.githubusercontent.com/112800734/189899056-b6482fae-f781-4ee6-9454-e6bd72dece0e.png)
![OffspringSet3](https://user-images.githubusercontent.com/112800734/189899061-17cfe3b4-5312-43e0-ac2c-6b533fbc1dca.png)
![OffspringSet4](https://user-images.githubusercontent.com/112800734/189899063-74998a6d-1734-4a0c-ae4b-24617fcf0fc2.png)
![OffspringSet5](https://user-images.githubusercontent.com/112800734/189899064-926cd692-3d69-4796-a952-f8ae081f2da6.png)
![OffspringSet6](https://user-images.githubusercontent.com/112800734/189899070-bd9b1142-6d2f-4c16-8a0f-993ab63b10cf.png)
![OffspringSet7](https://user-images.githubusercontent.com/112800734/189899072-5d42bb67-a10f-40f1-bc64-60783c11329c.png)
![OffspringSet8](https://user-images.githubusercontent.com/112800734/189899074-05fc3cc7-f5a5-49ec-9cb9-ab8bcc11dd45.png)
![Parent 1](https://user-images.githubusercontent.com/112800734/189899075-b8f3c44c-a0b4-461a-a365-e39317b84c75.png)
![Parent 2](https://user-images.githubusercontent.com/112800734/189899082-eb84da91-0ff9-4a70-ab18-ea6d71db1150.png)

**Comment by JaisDK** [comment]
fixed
