### ISSUE TITLE
[Feature Request] Client config option to set loot box drop rate for cages

### ISSUE THREAD

**Issue by AngleWyrm10** [JDKDigital/productive-bees#305]
In my playthrough, I've gotten rather a lot of bee cages in chest loot drops -- more than I'll ever need.

Would it be possible to add a loot drop chance weight for bee cages?

**Comment by JaisDK** [comment]
it's possible to override the loot modifier with a datapack

while it does not have support for changing the chance (50%) you can remove some of the chests it spawns in

maybe I'll move the chance to the json file so it can be overwritten too some time in the future
