### ISSUE TITLE
The can’t exit from the advanced beehive

### ISSUE THREAD

**Issue by Silversnake1256** [JDKDigital/productive-bees#306]
I’m playing ATM 7 to the sky version 1.0.7 and my problem is that the bees can’t exit from the advanced beehive, I tried with a stick, breaking them and they don’t work so there’s any solution or is broken?

**Comment by JaisDK** [comment]
which version of the mod does the pack have? you probably just need a newer version or wait for them to update

**Comment by Silversnake1256** [comment]
Productivebees-1.18.2-0.9.1.3 is the latest version?

**Comment by JaisDK** [comment]
no that's the broken one, but in that one they should work fine in compact machines and most other dimensions

**Comment by Silversnake1256** [comment]
So in the overworld don’t work?

**Comment by Rykee** [comment]
Which one would be the correct version?
