### ISSUE TITLE
creebee bread in breeding chamber causing crash

### ISSUE THREAD

**Issue by 2lgit2quit** [JDKDigital/productive-bees#308]
if you place 2 creebees in a breeding chamber it crashes your game with this error 

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128471_(String)" because "beeData" is null

**Comment by JaisDK** [comment]
Fixed in 0.9.1.5
