### ISSUE TITLE
CurseForge launcher exports an override

### ISSUE THREAD

**Issue by AngleWyrm10** [JDKDigital/productive-bees#309]
When exporting a modpack from CurseForge, this mod gets packaged into the zip file at /overrides/mods/productivebees-1.18.2-0.9.1.4.jar The modpack is then rejected by CurseForge.

> [The status of the file AngleWyrm's Collection-22.9.18.zip (AngleWyrm's Collection) has been changed to Rejected](https://www.curseforge.com/minecraft/modpacks/anglewyrms-collection/files/3995688)
> Notes:
> The following files belong to CurseForge-hosted projects, and should therefore not be added directly to zip files:
overrides/mods/productivebees-1.18.2-0.9.0.11.jar
> These files should, instead, be referenced in the manifest.json file generated by the Twitch Desktop App during a profile export. If you have any questions please contact our support team https://support.curseforge.com/.

**Comment by JaisDK** [comment]
you have two different versions there, which one are you trying to add and do you perhaps have it twice?

**Comment by AngleWyrm10** [comment]
Aha! Thanks, that's where I've somehow gone wrong.
