### ISSUE TITLE
Centrifuge only shows one output in JEI

### ISSUE THREAD

**Issue by Darkiceflame** [JDKDigital/productive-bees#31]
I've been messing around with centrifuge recipes and noticed that if a recipe has multiple outputs, JEI will only show one of them. For example, if I change the Powdery Comb item to have multiple possible outputs (in this particular case, the sulfur and nitrate dusts from Immersive Engineering) JEI will show one or the other depending on their order in the file, but never both.

**Comment by JaisDK** [comment]
Thank you, I'll look into it! It will still produce the items defined in the recipe right?

**Comment by Darkiceflame** [comment]
Right, the items are all still produced, they just don't show in JEI

**Comment by JaisDK** [comment]
I like the idea of having secondary outputs from other mods, maybe I'll add them as part of the mod. What kind of percentages are you setting for them? and are you adding other recipe changes?

**Comment by Darkiceflame** [comment]
Currently the only change I've made is that instead of getting gunpowder directly from powdery combs, they instead have a chance to output either nitrite dust or sulfur dust. In Immersive Engineering these are ingredients in the recipe to make gunpowder, so it's just an extra step.
