### ISSUE TITLE
Bees wont go into hive

### ISSUE THREAD

**Issue by cookieman222** [JDKDigital/productive-bees#310]
Hey guys bees are not going into hives on my server or clientany ideas on how to fix it?

Info:
Link to what is happening: https://youtu.be/Lfq5ktQGVJU

Minecraft version 1.18.2
Mod version: Was 9.1.2 tried updating the mod to see if that would fix it so currently 9.1.5
ModPack: Its my own custom modpack no issues other than this. Great frames, no lag, no other mod bugs.

Possible mod issues I'm guessing: I have a lot of server mods to help with lag some that might be causing problems could be Radium, Radon, Rubidium, FerriteCore, Better FPS I tried both adding the mixin.ai.poi=false to the config on both client and server and when that didn't work I tried removing Radium from the server and that didn't work either.

Also odd thing before I tried anything I tried a singleplayer client and it worked then I removed and reinstalled stuff to test things (basically put it back to exactly as it was) but now it doesn't even work in single player

Thank you for any help!

**Comment by JaisDK** [comment]
Radium is the problem

add mixin.ai.poi=false to the radium config file found in your instance folder config/radium.properties

**Comment by dyachoksa** [comment]
The same issue but for MC 1.19.2, mod version 0.10.2.0

**Comment by JaisDK** [comment]
if you have the same issue then do the same fix

**Comment by dyachoksa** [comment]
No `Radium` or similar mods installed

**Comment by JaisDK** [comment]
- Most of the bees found in the overworld are solitary bees and will not live in a hive. They need nests to live in, don't produce resources and are mostly used for breeding other bees.
- Each bee has specific flower requirements, make sure they are met. Flower requirements can bee seen in JEI by right clicking or pressing 'U' on the bee
- If your bees were living in a different hive, they might still remember it as their home. Put the bee in a cage and release it while sneaking next to the new hive.
- If all else fails, try breaking the hive and place it again. Bees stay in the hive when broken, no need for silk touch.

**Comment by dyachoksa** [comment]
Ok, will try it.

**Comment by cookieman222** [comment]
Ok so I had already tried the mixin.ai.poi=false and it didn't work and i tried a couple of things to no avail so what I finally did was removed radium and productive bees from both my server and client ran the server/world let it delete everything related to the mods then re-installed everything and used the mixin.ai.poi=false line in the config and finally it worked. Very odd error I was haveing but thankfully it was resolved bees are back in the hive for me, thanks for the help, Ill leave this issue open for Dyachoksa hopefully you find a solution to your problem aswell.

**Comment by JaisDK** [comment]
I imagine that breaking and placing the hives would also have fixed it and is probably required after applying the config fix. I’ll add that part to the suggested fix for next time.

**Comment by cookieman222** [comment]
> I imagine that breaking and placing the hives would also have fixed it and is probably required after applying the config fix. I’ll add that part to the suggested fix for next time.

No prob at all, thanks again for your help!

**Comment by cookieman222** [comment]
> > I imagine that breaking and placing the hives would also have fixed it and is probably required after applying the config fix. I’ll add that part to the suggested fix for next time.
> 
> No prob at all, thanks again for your help!

Also when i tested it after adding the config file even creating a new single player world and making a new hive and spawning new bees wouldn't work something in the reinstall did it for me. I made sure after every test i made a new world to insure it wasn't an interaction problem.

**Comment by JaisDK** [comment]
Damn Radium :D 

thanks for the comprehensive testing!
