### ISSUE TITLE
Can't figure out simulation upgrade. Is it bugged?

### ISSUE THREAD

**Issue by togreglove** [JDKDigital/productive-bees#311]
Pack: All The Mods 7 : To The Sky 1.0.8
Productive Bees version: productivebees-1.18.2-0.9.1.5
Forge Version: forge-1.18.2-40.1.80

Setup: 
  Advanced Hive with Oak Expansion Box on top, forming a 2 tall multiblock.
  In the blockspace just in front of the opening, there is a feeding block with a flower in it (in this case, an insanium block)
  Inside the hive is one simulation upgrade and 3 productivity upgrades.

Replication:
   I place 5 cages, one at a time, with insanium bees into the hive.
   The bees show up in the internal inventory and seem fine.
   I put a stack of bottles in bottle slot.
   I wait....nothing happens.
   I accelerate with acceleration wand....buzzing intensifies.....nothing happens.

Notes:
   This is my first time using the simulation upgrade, so I might be using it incorrectly.
   I have tried this in the overworld and in the compact dimension because I know there have been entering/leaving issues recently.
   I tried moving the feeding slab one block away, placing it to the side, placing the insanium block physically in the world in multiple locations.
   Since this is a new feature, there is very little if any information on the simulation upgrade or how to use it properly on the net.

**Comment by JaisDK** [comment]
Move the flower block 1 down

**Comment by togreglove** [comment]
That did it.  The wording on the simulation upgrade had me very confused.  I place my hives at ground level and place flower blocks around it.  It did not occur to me to place them in the floor.  Thanks for the quick reply.

**Comment by togreglove** [comment]
Followup question:
    Since the bees do not actually leave the hive, can I pack them more compactly, putting them right next to each other?  I don't see why this wouldn't work, since they don't need blockspace to leave hive, but just wanted to verify before I rebuilt my entire setup in a more compact form.

**Comment by JaisDK** [comment]
you only need the flower block in the front, all other space you can pack with whatever you want

**Comment by togreglove** [comment]
Oh my, this is going to be powerful. Thanks for all your work!
