### ISSUE TITLE
1.19.2 bugs

### ISSUE THREAD

**Issue by Legorfyr** [JDKDigital/productive-bees#313]
1) all bees that are bred are just plain white/black texture
2) since ae2 has changed, crystal seeds don't exist anymore, so the combs can't be processed.

**Comment by JaisDK** [comment]
Do you have any interesting graphics or performance mods installed?

**Comment by Legorfyr** [comment]
It's ATM8 so Radon is in by default aswell as Rubidium

**Comment by JaisDK** [comment]
could you try without radon, rubidum, rubidium extra and oculus if they are also in?

**Comment by Legorfyr** [comment]
Nvm, next update removed oculus and the bees have color again lol, now only the spatial bee needs a fix xD

**Comment by JaisDK** [comment]
nice

I have a version ready for test with a fix for the spacial comb as well, just need some time to test it before release.

**Comment by Superabi** [comment]
2. ... for night's and night's in a row i been trying to figure out what i did wrong .... good to know you are working on a fix .. 
What is the plan ? just output Certus Crystals?

Let me know where i can buy you a coffee

**Comment by JaisDK** [comment]
Yea just the crystal now since they have the new geode thing going.

If you're looking to donate, there's a button on the project page https://www.curseforge.com/minecraft/mc-mods/productivebees
Much appreciated :)

**Comment by Superabi** [comment]
seen you updated 2 day's ago ... are the quartz bee's fixed in this one?

**Comment by JaisDK** [comment]
that was for 1.18, 1.19 update coming soon
