### ISSUE TITLE
Advanced Hive Bug

### ISSUE THREAD

**Issue by MacDiggyDwarf** [JDKDigital/productive-bees#314]
Using 1.18.2

No matter what Bees refuse to enter the Advanced Hive. If there are vanilla beehives nearby they will opt for those, despite shift-right-clicking on the Advanced Hive. If no other hives are present the bees will stay in the open until they die.

**Comment by JaisDK** [comment]
If you have Radium installed, add `mixin.ai.poi=false` to the radium config file found in your instance folder `config/radium.properties`. You may have to completely remove both Radium and PB from the world and then add them back in to fix the broken POI after correcting the config
