### ISSUE TITLE
Nether Hives won't let the spawned Bees out.

### ISSUE THREAD

**Issue by rav3nqu33n** [JDKDigital/productive-bees#315]
It will spawn the bee but then it will stay inside the hive. I did so with the Glow Stone nest, the Nether Quartz Crystal Nest, and the Nether Brick Nest. They will leave for like a millisecond and then immediately pop back into their nest. I can't catch them or do anything with them. Even when I break the nest no bee comes out. It just vanishes. Is there any other way to get those bees? Or a way to fix it? I am on 1.19 I believe, and through FTB One.

**Comment by JaisDK** [comment]
The version in FTB One is behind since they haven't updated in ages. When you break the nest, the bee stays inside and you can transport it to your base. In the version you have it will probably work better after being moved to the overworld.

**Comment by rav3nqu33n** [comment]
That also did not work. I ended up being able to just grab them really fast
for the millisecond they would come out of the nest in the nether. When I
tried to bring it to the overworld they would just stay inside their nests.
They would however leave in the nether for a very fast time. Just pop out
and then in. For that split second you can grab them with a cage. So it
still ended up working out.

**Comment by tomascryogen** [comment]
Hi. I have the same issue in FTB Inferno.

**Comment by rav3nqu33n** [comment]
If they still come out, you can quickly use the cages to grab them. That's
the only way I managed to do it. Eventually they would come out of the
hive, I think you have to try and be in the Nether during "Day" it's just
annoying. For being quick I would be right in front of the hive and click
right as the timer hit 1 and it was a 50/50 for me.

**Comment by Cherberu** [comment]
> Hi. I have the same issue in FTB Inferno.

I have this issue  too, but seems to be mainly affecting vanilla bees. I used advanced warp hives for them and the bees don't come out. If I break the hive they disappear.

**Comment by JaisDK** [comment]
please open a new issue
