### ISSUE TITLE
Unable to disable beehive spawning.

### ISSUE THREAD

**Issue by DelviousCrafts** [JDKDigital/productive-bees#321]
Setting the beehive spawn chance to 0.0 in the server config file does not remove the spawning of hives. This may cause issues with changing the number to anything else as well, but this was not tested to be honest.

Testing method: set spawn chance of all hives to 0.0 in server config file from generated world. Placed edited config file in default config folder. Then created fresh test world and verified that the server config of that world contained the changes made from the default config folder.

**Comment by JaisDK** [comment]
which version are you using?

**Comment by DelviousCrafts** [comment]
My apologies for not putting that in to begin with

Productive Bees Version: 1.18.2-0.9.1.6
Forge version: 40.1.80

**Comment by DelviousCrafts** [comment]
During continued work with the config file, appears that config file is not following mod order list under preferredTagSource config option either. Simply moved around the mod order with names posted exactly as written in the default config, and product are still following default config file after updating server config file in world folder. Created new world with updated config file in defaultconfig folder to verify even occurring in new world. May be an issue with reading config file in general.

**Comment by JaisDK** [comment]
Can you provide a debug.log or latest.log from one of the runs?

**Comment by DelviousCrafts** [comment]
was just about to do this. Will upload when in a few moments.

**Comment by DelviousCrafts** [comment]
[pastebin](https://pastebin.com/2DnX2pk8l) of direct copy from server config file placed in default config file.

[pastebin](https://pastebin.com/FQkHJma8) of direct copy from server config file found in serverconfig file of freshly generated world

Cannot copy complete log file or upload as file is to large (over 9k MB) cannot paste to paste bin for same reason. A lot of Open GL errors when opened with large Text file opener and copied all information before long list of Open GL errors. Hopefully that has what you need. 

[pastebin](https://pastebin.com/gUtHu7uk) of log file before long list of Open GL errors. No information after all the open GL errors to copy.

![2022-10-13_07 39 01](https://user-images.githubusercontent.com/46658624/195627437-fb9fd1b4-8539-4fbf-bf64-f34ba2f6b0f9.png) Screenshot showing bee nest spawn in new world


![2022-10-13_07 40 09](https://user-images.githubusercontent.com/46658624/195627670-1f88d1a3-6ec9-4946-a0ae-eb205c180faf.png) Screenshot showing JEI with Minecraft as default for copper

**Comment by DelviousCrafts** [comment]
Through further testing, I have found that disabling of spawning of nests only happens to some nests. So far I have found this to be the case for spruce and jungle nests. Will continue to test to see if any other nests are still spawning with nests disabled.

**Comment by DelviousCrafts** [comment]
Through thorough testing here is the list of nests I found to ignore or at least not be disabled by the config being set to 0.0

Spruce nest
Jungle nest
Sand nest
Bumble Bee Nest
Slimy Nests
Nether Brick Nest
Quartz Nest
Obsidian Nest

All other nests seem to either conform and be disabled by setting to 0.0, or are so rare they might as well be considered disabled. 

Also still spawning:
Warped Bee nest (no config option so this makes sense. Request to add config option to disable this)
Crimson Bee nest (no config option so this makes sense. Request to add config option to disable this)
Sugarbag nest (no config option so this makes sense. Request to add config option to disable this)

**Comment by JaisDK** [comment]
thanks for the thorough test, I'll look into it as soon as I have the time

there should be a config called nether_bee_nest or similar which covers the warped and crimson nests

**Comment by DelviousCrafts** [comment]
I do see that option. Didn't know it fixed both of those based on the wording. Thank you for the info. With that knowledge, they seem to be ignoring this config.

**Comment by tillasiren** [comment]
I have encountered this issue as well
Forge: 40.2.8
Productive Bees: 1.18.2-0.9.3.0.jar
I have noticed at least bumblebee spawns (didn't find the nest) and a spruce wood nest.
