### ISSUE TITLE
Productive bees not working at all

### ISSUE THREAD

**Issue by madbadteacher** [JDKDigital/productive-bees#322]
Bees go in and out of bee hives, but I can't use a glass bottle or shears on them to collect honey or honeycomb . ATM8 Recent version and latest version of productive bees installed

**Comment by JaisDK** [comment]
it's 5 bee trips for the hive to have enough to bottle

**Comment by madbadteacher** [comment]
I've watched them go in and out several times... They have the right flowers also. Thanks

**Comment by JaisDK** [comment]
are you actually having a hive or are you having nests? The solitary bees living in nests don't produce anything.

**Comment by madbadteacher** [comment]
Ah ok . I'll check. thanks
