### ISSUE TITLE
[1.18.2] Frozen at 100%

### ISSUE THREAD

**Issue by itsdinkd** [JDKDigital/productive-bees#323]
![image](https://user-images.githubusercontent.com/35115304/195956349-59e89f59-ff19-4c0e-b7e4-8cee4c26fcc8.png)
![image](https://user-images.githubusercontent.com/35115304/195956356-8c2ced2d-8da1-4057-aa10-0a3639852601.png)

when a nest is generated on world join or creation, the game will lock at 100% load. 

version: 
productivebees-1.18.2-0.9.1.6.jar

I downgraded to the version AQM3 used prior to the update I'm working on, productivebees-1.18.2-0.9.1.0.jar and the 100% issue went away.

**Comment by JaisDK** [comment]
Downgrading is not a real solution, I'll keep this open

**Comment by JaisDK** [comment]
Do you know what the Forge version is on those two versions of the pack?

**Comment by itsdinkd** [comment]
I closed because it happened again, not sure if its productive bee's. probably not because I saw the nest still generate while I was able to join the world without getting frozen after downgrading. i then created a new world again and it occurred again on same version. 

But the forge version is 40.1.80
