### ISSUE TITLE
Hacktoberfest and italian localization

### ISSUE THREAD

**Issue by ZeroKun265** [JDKDigital/productive-bees#324]
I was wondering if the owner(s) would be willing to opt the repo in the hacktoberfest program.
I want to submit a PR translating the tips in Italian, and I will do so regardless of whether it counts for hacktoberfest or not, but it would be nice if it did :)

**Comment by JaisDK** [comment]
what is hacktoberfest?

**Comment by JaisDK** [comment]
like that?

**Comment by ZeroKun265** [comment]
Exactly, you only need to add the "hacktoberfest" topic to GitHub, it's an event sponsored by Digital Ocean to promote Open Source Contributions.
Thank you for adding the topic, I'll start translating as soon as possible
