### ISSUE TITLE
Indexer sometimes stops combining gene samples

### ISSUE THREAD

**Issue by kotoroshinoto** [JDKDigital/productive-bees#325]
I don't know how to recreate it, but I have samples in mine that just aren't being combined.

I was using the pipez mod to pull from other inventories and insert into the indexer, so that might be relevant.

**Comment by kotoroshinoto** [comment]
![image](https://user-images.githubusercontent.com/1337560/196039636-1481a0cf-209b-42eb-8e95-e5b85c914cad.png)

**Comment by Nekosity12** [comment]
The gene indexer requires a redstone signal in order to run, do you have anything that could be enabling/disabling redstone signals? Also what mc version & mod version are you using

**Comment by kotoroshinoto** [comment]
I didn't realize it, when I first put it down it was receiving one passively, and when i moved it, and it stopped working ,I had no idea what i'd done XD sorry to bother you.
