### ISSUE TITLE
Soul Lava Bee

### ISSUE THREAD

**Issue by e30Birdy** [JDKDigital/productive-bees#329]
I have a soul lava bee and it is in an advanced hive with simulation upgrade and 3 productivity with feeding slab in front. What do I put into the feeding slab since the bucket of soul lava is not working? What am I doing wrong or do they not work with simulation upgrade since they need a fluid to pollinate?

**Comment by JaisDK** [comment]
Instead of the feeding slab, just place the soul lava block

**Comment by e30Birdy** [comment]
thanks, didnt know one could do that
