### ISSUE TITLE
[1.19.2] Unregistred fluid type from ender combs

### ISSUE THREAD

**Issue by olapola85** [JDKDigital/productive-bees#331]
![2022-11-06_20 26 26](https://user-images.githubusercontent.com/35819757/200190856-bba229fc-bd91-4d78-a17e-c80628b63f1b.png)
![2022-11-06_20 26 30](https://user-images.githubusercontent.com/35819757/200190860-dfcc3a61-5015-4c82-bb3c-9b8df7a601b8.png)

Modpack: All The Mods 8 0.1.10

**Comment by JaisDK** [comment]
You probably have honey in the output tank even though it's not showing in the GUI. Hover over the area to see. Ender combs output a different fluid so you have to clear the output tank or use a dedicated centrifuge for them.

**Comment by olapola85** [comment]
> You probably have honey in the output tank even though it's not showing in the GUI. Hover over the area to see. Ender combs output a different fluid so you have to clear the output tank or use a dedicated centrifuge for them.

Well that was the issue. Doh 

Big thanks!

**Comment by olapola85** [comment]
![2022-11-06_20 40 07](https://user-images.githubusercontent.com/35819757/200191430-3c85ac31-8374-4fd7-909d-84a2576ffb9c.png)

**Comment by JaisDK** [comment]
I don't know what that is, what output does JEI say it should make? what comb is it?

**Comment by olapola85** [comment]
> I don't know what that is, what output does JEI say it should make? what comb is it?

![2022-11-06_21 26 24](https://user-images.githubusercontent.com/35819757/200193394-b561bda0-04cd-459f-9f20-4493bff2965f.png)

Seems like a modpack issue?

**Comment by JaisDK** [comment]
I don't know, it's supposed to be integrateddynamics:liquid_chorus fluid, maybe they don't have that anymore in 1.19?
