### ISSUE TITLE
BaBee upgrade with simulator upgrade create an infinite amount of bees

### ISSUE THREAD

**Issue by TiphaineLAURENT** [JDKDigital/productive-bees#332]
I am not sure this is a bug but it certainly feel like it.

From what I understand from [the code, ](https://github.com/JDKDigital/productive-bees/blob/dev-1.18.2/src/main/java/cy/jdkdigital/productivebees/common/block/entity/AdvancedBeehiveBlockEntity.java#L276) the hive only checks for nearby entities. But with the simulator upgrade, bees never go out and never trigger this checks.
I would simply suggest checing first for bees inside the hive then around it. It would fix that strange behaviour and be lighter too.

**Comment by JaisDK** [comment]
yes that's an oversight

**Comment by JaisDK** [comment]
Looking into this I can see that it checks around the hive, not the bee, so the correct check is already in place. I'll bump it up though to look a little bit further out.
