### ISSUE TITLE
Inferno and productive Bees: Vanilla bees not leaving advanced warped hives

### ISSUE THREAD

**Issue by Cherberu** [JDKDigital/productive-bees#333]
I am playing the Inferno mod. I was trying to raise bees in the nether under the roof and made a house for them. Also I used an advanced hive with one expansion mode. The regular bees would fly around a bit and when they went inside would never come out. Breaking the hive resulted in no bees.

**Comment by JaisDK** [comment]
The bees stay inside the hive when you break it, take a look at the tooltip of the hive to see if it's still in there.

**Comment by Cherberu** [comment]
Ok. I will try that when I can check on them. I realize they would stay, but looking in it looks like there is none.

**Comment by JaisDK** [comment]
sounds like it may have gotten messed up, maybe with an improper shutdown

better to reset the hive by putting it in a crafting grid and try again

**Comment by Cherberu** [comment]
ok. I will do that. thank you for your help!
