### ISSUE TITLE
[1.18.2-0.9.1.6] Indexer inconsistent

### ISSUE THREAD

**Issue by Zigian** [JDKDigital/productive-bees#334]
The gene indexer doesn't consistently combine genes.  I have supplied it with a redstone signal via lever on top.  If I use my sort inventory hotkey, it will sometimes kick off combining again.  Most of the time this take several presses of the hotkey as it will stop before all are combined.  Even then, as seen in the screenshot, genes won't always combine.  Sometimes flicking the lever of then on gets it going, but it's similarly inconsistent to the inventory sorting hotkey.  I checked to make sure there were no other redstone sources that could be causing an issue.  The only source is the lever on top.

Playing All The Mods 7 To the Sky 1.1.6 on an MP server.  Running the current version of PB 1.18.2-0.9.1.6.

![GeneIndexer](https://user-images.githubusercontent.com/32234823/205457645-fdd7bc28-1735-4e71-b452-c9f367e9b5e1.png)

**Comment by JaisDK** [comment]
maybe the latest update helps

**Comment by Zigian** [comment]
Oh nice, it updated a few hours ago and it says fixed inconsistencies with indexer.  I might load it or I might just wait for ATM7 to vet it with their pack.  Thanks dev.
