### ISSUE TITLE
Bees Stacking in Inventory creates lost bees upon release

### ISSUE THREAD

**Issue by Tyyni707** [JDKDigital/productive-bees#336]
When you have bees with all the same traits, they stack in your inventory. If you release while holding stack, it releases 1 bee and the stack is then emptied. Perhaps disabling stacking will solve?

**Comment by JaisDK** [comment]
pretty sure I fixed that already, which version of the mod are you on?

**Comment by Tyyni707** [comment]
productivebees-1.19.2-0.10.3.1 playing in ATM8 only noticed when mass breeding radioactive bees to get wasted bees

**Comment by kalutro** [comment]
Posting here as I am having the exact same issue. I will open a new Issue if you would like.

Stacked Sturdy Bee Cages release only one bee.
Mod: productivebees-1.18.2-0.9.3.0
Pack: SkyT 1.1.1

**Comment by JaisDK** [comment]
I'm not doing anything with 1.18 anymore
