### ISSUE TITLE
piston cannot bottle grown bees if there is a baby bee as well

### ISSUE THREAD

**Issue by Quezler** [JDKDigital/productive-bees#338]
If you for whatever reason have any amount of bees you wish to bottle up and steal their genes, babies can block it entirely:
![2022-12-13_22 15 04](https://user-images.githubusercontent.com/3179271/207445109-a145c3eb-996b-4938-b610-3479eaa1dc5b.png)

This is due to only the first found bee beeing checked if its not a baby, it doesn't continue iterating if it fails:
https://github.com/JDKDigital/productive-bees/blob/fe45e90a284356e521475c338a6483b2a253b5e6/src/main/java/cy/jdkdigital/productivebees/common/block/entity/BottlerBlockEntity.java#L85

Admittedly the attached screenshot is a little extreme, but even a small disposal room that still has a baby can be annoying.

**Comment by Nekosity12** [comment]
Why not use the catcher then?

**Comment by Quezler** [comment]
That puts them in cages right? yet the book says only bee entities can be bottled into genes.

And the babies will be getting squished as soon as they grow up, catching them and making a bee-grow-up-daycare only to then catch adults and move them back to where they came from sounds like a bit of a hastle.

Also (did notice this prior to posting, but didn't look more deeply into it & the block yet), this looks like a relic:
![Screenshot 2022-12-13 at 22 25 33](https://user-images.githubusercontent.com/3179271/207446755-5d1df5fa-b2df-4be2-a386-5c55ee85355a.png)

**Comment by Nekosity12** [comment]
It does put them into cages, dispensers can un-cage them. This was the intended use for the catcher afaik is to separate bees

**Comment by Quezler** [comment]
But why not just skip baby bees in the piston check to let it bottle up any grown bees? they'll all meet this same fate \:D

**Comment by Nekosity12** [comment]
🤷 That'd be a question for the dev. Just thought I'd throw out there that the catcher works fine for this purpose

**Comment by Quezler** [comment]
Oh sorry, i was under the impression that you were the dev since you've responded basically instantly, and was defending a design choice about why you want to enforce separating them with a catcher, even though young and old both get bottled up since all bees in my screenshot are just a gene overflow. 😅

**Comment by Nekosity12** [comment]
Nah, the dev has github linked to the discord so any new github comments/posts are sent there hence my fast response. I just wasn't sure if you knew about the catcher and the ability to filter bees so I brought it up :)

**Comment by JaisDK** [comment]
easy fix for next version
