### ISSUE TITLE
Dragonmounts and Productive Bees problem

### ISSUE THREAD

**Issue by Alriandi** [JDKDigital/productive-bees#340]
Mods 
 - Dragon Mounts Legacy
 - Productive bees
 
 Forge, any version, Minecraft any version. I am currently on 1.18

As productive bees changes the dragon egg, it makes it impossible to hatch anything from Dragon Mounts Legacy without having to change the egg type. I don't know if this needs to go to Dragon Mounts Legacy or here, but it would be nice to see if there was some kind of work around.

**Comment by JaisDK** [comment]
I don't change the dragon egg at all, I just use it as a flowering block. If you're having problems because the egg hatches in your bee setup, try putting it in a feeding slab instead.

**Comment by Alriandi** [comment]
Its more trying to hatch the Eggs as part of Dragon mounts Legacy vs feeding. I cant hatch the dragon egg via right click because its apparently called Inactive dragon egg via JEI and Jade or something along those lines and the only two mods I know that affect the dragon egg is productive bees and dragon mounts

**Comment by JaisDK** [comment]
the Inactive dragon egg is a new block, not a replacement for the dragon egg, use some dragon breath on it to get a real egg

**Comment by Alriandi** [comment]
Oh well that explains it. I never go to that stage in past mod packs and this is the first one that I had both mods in. Good to know its just me being new to it and not an actual bug. Locking it now. TY anyway
