### ISSUE TITLE
ATM8 Server Crash by PB

### ISSUE THREAD

**Issue by LiveSide** [JDKDigital/productive-bees#342]
good morning friends,

my all the mods 8 server crashed 
here the logs after restart,
https://mclo.gs/vFfeX8V
https://mclo.gs/KeIFBcY
i dont have the log from the crash.

one mate on the server placed a ``Imperium Comb Block``.
He is not sure, he placed it on a ``White Elevator``

I restarted the server and we still can`t connect 

https://gyazo.com/06cee4519ad25838715d2965ba57edb4
---------------------
so i tryed to open the world in single player
that not working, too.
here is the crash report https://mclo.gs/2WmWZ5m

i talked to the guys from all the mods and CoFH

``try in the file path <savename>\serverconfig\ the file forge-server.toml and try setting removeErroringBlockEntities to true``
that was not working (crash report https://mclo.gs/v18Xz8n)

``I can make you a build of PB that won't crash so you can get it in remove the offending comb block``
i got a modified PB mod file to remove that blocks

https://gyazo.com/bc63649900db56ddbf5defcd28097cb8
my mate was changeing "white concreet" to "Imperium Comb Block" with an "exchanging gadget"
and then was the server stoped.

**Comment by JaisDK** [comment]
I gave you the modified PB mod. Thanks for finding out how your mate broken it :)

**Comment by LiveSide** [comment]
i hope it help to reproduce the bug to fix it
