### ISSUE TITLE
Productive Bees / Sophisticated Storage (sort of) duping issue.

### ISSUE THREAD

**Issue by jursamaj** [JDKDigital/productive-bees#346]
I'm not sure where the issue is, so I'm reporting this to both mods.

Sophisticated Storage & Sophisticated Backpacks can add a crafting grid to storage items (chests, barrels, & backpacks).  This grid includes a button for "Balance Grid"/"Spread Grid", which attempts to arrange multiple of an item on the grid in even stacks.

Productive Bees has a Gene Sample item, which uses NBT tags to show what type of gene it contains, as well as a percentage value for that gene.

If I put multiple stacks of Gene Samples in the grid, with different genes and/or percentages, then use the balance/spread button, it will treat all of the samples as if they were interchangeable, and just change the quantity of each.  Thus, if I have a stack of 1 sample of "Weather Tolerance: Any (100%)" in the 1st grid slot, and 1 stack of 10 samples of "Productivity: High (1%)" in the 2nd slot, and "balance" them, I will end up with a stack of 6 "Weather Tolerance: Any (100%)" and a stack of 5 "Productivity: High (1%)".

Mod pack is ATM7
Soph. Storage 1.18.2-0.5.17.152
Soph. Backpacks 1.18.2-3.18.29.718
Soph. Core 1.18.2-0.5.13.132
Productive Bees 1.18.2-0.9.1.6

Cross reference: https://github.com/P3pp3rF1y/SophisticatedStorage/issues/118

**Comment by JaisDK** [comment]
That sounds like an issue in Sophisticated Backpacks, they are just NBT items, nothing special about that so they should be able to handle it.

**Comment by jursamaj** [comment]
I was leaning that way myself, but I don't know a lot about modding MC, so I figured I'd cover both bases.

**Comment by P3pp3rF1y** [comment]
@jursamaj if you try doing the same in regular crafting table do you get the same issue? as far as I can see I am only calling crafting tweaks compat code to get this done

**Comment by jursamaj** [comment]
Closing, as P3pp3rF1y fixed the issue and closed the issue on his end.
