### ISSUE TITLE
All The Mods 8 - Bees automatically change their hive position

### ISSUE THREAD

**Issue by SimonLyke** [JDKDigital/productive-bees#354]
i have 4 advanced beehives in a room, with collector and farmer bees, i assign one collector and farmer to each hive, yet after a while i see 2 of the same bees entering the same hive, capturing them shows that they are going into different hives despite all 4 hives being accessible so it should not reset their hive. it is causing some farmer bees to not harvest certain sections of the farm

**Comment by JaisDK** [comment]
Unfortunately this is just how the bee AI works, I would have to write my own to get a better behavior and I simply don't have the time.
Best you can do is put a glass wall between the different farms to physically prevent them from going to other hives.

**Comment by SimonLyke** [comment]
That is okay, i was not sure whether this was intended or a bug, if it is a limitation of the existing AI behaviour then i cannot fault the mod. however it does break my plans but it is what it is, id be fine with it if the metaturnal bees never entered a hive unless their functionality needed to. or if the range upgrades were not so expensive, as requiring 3 emeralds a diamond and 36 iron is a bit steep per upgrade when it is early on for me, however as its part of modpacks i can understand that its not meant to be too cheap. Thankyou for the swift response, i appreciate it!
