### ISSUE TITLE
Rose gold Bee

### ISSUE THREAD

**Issue by Dunkel32** [JDKDigital/productive-bees#356]
Rose gold bee has no recipe in atm8

**Comment by JaisDK** [comment]
what mod adds rose gold?

**Comment by Nekosity12** [comment]
I only know of TiCon that does, dunno if ATM8 has any mods that have other rose gold

**Comment by JaisDK** [comment]
ticon is not in the pack, that's why I'm asking

**Comment by Legorfyr** [comment]
Thermal Integration adds it, the bee sees the flower block, gives nuggets too, the only thing missing is the recipe for the egg.
