### ISSUE TITLE
End crystal seem to remove all draconic bees?

### ISSUE THREAD

**Issue by Pultex** [JDKDigital/productive-bees#357]
I could be completely wrong but I seem to not have any  draconic bees in my end

All I can think of is I never got the hives out of the pillars after killing the dragon
then had to go through the end portal

I then resummoned the dragon for another mod not thinking about the hive/nest in the pillars

Now returning all pillars seem to have no nest I even mined out the pillars with a pick to see if
the hive/nest was in them found none

I know there were bees in the end before when I first entered

Just want to know if the mod if by itself should the hives return on crystal summon or will it remove all hives/nests

**Comment by JaisDK** [comment]
They are only to be found on the first world gen and not even always. You can craft an obsidian hive yourself and use honey treats on it to spawn new bees.

**Comment by Pultex** [comment]
oh thank you
I was doing to tell you what version it was forgot to mention it
will try this
