### ISSUE TITLE
[1.18.2] Not showing bees in advanced beehive 

### ISSUE THREAD

**Issue by kpakenyga** [JDKDigital/productive-bees#358]
Now showing any bees in adv beehive
![image](https://user-images.githubusercontent.com/125918160/220186243-74f83767-5ec9-4699-8635-82b67df72641.png)

Version - productivebees-1.18.2-0.9.3.0.jar

Also have rubidium, radium

**Tried remove debugify, radium**

**Comment by kpakenyga** [comment]
![image](https://user-images.githubusercontent.com/125918160/220187004-ea69ad77-f13a-4a7f-a10d-0558dcc60ea0.png)
**full mod list**

**Comment by JaisDK** [comment]
I could use a log

Which bees are supposed to be there and are you sure they are in the hive? do you have other hives that are working and which bees are in those?

**Comment by kpakenyga** [comment]
[2023-02-20-6.log.gz](https://github.com/JDKDigital/productive-bees/files/10787484/2023-02-20-6.log.gz)
[latest.log](https://github.com/JDKDigital/productive-bees/files/10787485/latest.log)
i dont know what log is needed, i send lastest and common

and yes, there are bees in the hive, they can fly out of it, at one moment just all the hives broke down (translated,sorry)

**Comment by JaisDK** [comment]
can you try without oculus and rubidium?

**Comment by kpakenyga** [comment]
oculus-flywheel-compat-1.18.2-0.1.8-BETA.jar caused this, thanks
