### ISSUE TITLE
Pure Daisy Bee Overrides Normal Pure Daisy Recipe

### ISSUE THREAD

**Issue by Roboox12** [JDKDigital/productive-bees#359]
When I'm trying to make a normal pure daisy from Botania it won't let me. When I put in the 4 mystical white petals into the petal apothecary the only option comes up is to make the pure daisy bee spawn egg. There's no option to make the pure daisy. I tried to add a seed into the apothecary but it only added it to the recipe like another ingredient instead of making the pure daisy. 
![2023-02-21_22 33 57](https://user-images.githubusercontent.com/126041121/220514856-6d984de6-533f-456f-94a7-c8daa17037ba.png)
![2023-02-21_22 33 59](https://user-images.githubusercontent.com/126041121/220514862-5effe202-cbbd-4244-9574-e96c619b5c36.png)

**Comment by JaisDK** [comment]
I changed the recipe in the latest 1.19.2 version
