### ISSUE TITLE
Blazing Bee spawns naturally in the End

### ISSUE THREAD

**Issue by VallenFrostweaver** [JDKDigital/productive-bees#36]
Minecraft 1.15.2
Forge 31.2.19
Productive Bees 0.1.11
Found floating around on the main End island.

**Comment by JaisDK** [comment]
I've been flying around the end for a while now and I am not finding any blazing bees. Did your end generate with a previous version? Bees only spawn within a nest and the end stone nest does not produce blazing bees.
I don't know where the blazing bee came from, but I guess you are just lucky to get one without breeding it.

**Comment by VallenFrostweaver** [comment]
I flew around for a long time (30min) and saw no others. Just the one on the main island. All others were ender bees or Draconic bees.
