### ISSUE TITLE
[1.16.5] centrifuge not processing items only honey

### ISSUE THREAD

**Issue by fex3760** [JDKDigital/productive-bees#360]
i have this problem where whenever i try to process the combs it never shows the item. i dont think its supposed to do that bcs it was never mentioned in the guide vid. im using the latest ver for 1.16.5 of the mod. 
(affect blazing comb most of the time)

**Comment by JaisDK** [comment]
you mean that you're not getting any output? some combs don't output 100% of the time
if you look up the centrifuge recipe in JEI it will show the rate
