### ISSUE TITLE
Missing bee exists conditions for block conversion

### ISSUE THREAD

**Issue by Nibato** [JDKDigital/productive-bees#361]
In `data\productivebees\recipes\block_conversion`

the following json files were missing the `productivebees:bee_exists` condition checks to see if the bee actually exists.

`obsidian_to_crying_obsidian.json`
`blackstone_to_gilded_blackstone.json`

Without these conditions, disabling the gold bee or draconic bee through datapacks will make the game crash when quarry bees finish pollinating.
[crash-2023-02-23_15.10.10-server.txt](https://github.com/JDKDigital/productive-bees/files/10819551/crash-2023-02-23_15.10.10-server.txt)

**Comment by JaisDK** [comment]
thanks, until I get that fixed you should just disable those recipes together with the bees
