### ISSUE TITLE
[1.19.2] Productive Bees don't work with Simulation Upgrade + Feeding Slab

### ISSUE THREAD

**Issue by DmitryScaletta** [JDKDigital/productive-bees#364]
Modpack: All the Mods 8-1.0.13
Productive Bees version: 1.19.2-0.10.5.2

Version 0.10.4.0 worked fine.

Not sure, probably there is something wrong with this commit https://github.com/JDKDigital/productive-bees/commit/5a1a950fa583aa7bd607a2e4d5dbc0b45295d7e4 

![image](https://user-images.githubusercontent.com/5096735/221936638-18279887-c741-4fdc-bd01-5f710b1b15ee.png)

Related issue: https://github.com/AllTheMods/ATM-8/issues/977

**Comment by JaisDK** [comment]
I've identified the issue and will upload a fixed version soon. Until then you can get around the issue by putting the flower block in the last slot of the feeder (or maybe just fill all 3 slots to be sure)
