### ISSUE TITLE
[1.19.2] Blazing bee hangs after pollination and doesn't fly back to hive unless within one block range. 

### ISSUE THREAD

**Issue by maximjohnson** [JDKDigital/productive-bees#365]
My current bee set up is an advanced hive with an extension box on top. Below the hive are two storage drawers which I use to automate combs within the centrifuge. My problem is that the blazing bee will pollinate on a magma block, but then won't return to the hive. It freezes on top of the block and wings do not flap. I have found a fix by putting the hive right next to the magma block, but would prefer to keep it consistent with everything else. The blazing bee is the only bee with this problem. All other bees are able to float 2 blocks down to their repsective pollination block before returning to the hive.

**Comment by Nekosity12** [comment]
Stuff like magma blocks like to break bee AI for some reason, try putting the magma block in a feeding slab and you should not have any issues

**Comment by maximjohnson** [comment]
Perfect! The feeding block worked great. Thanks for the assistance.
