### ISSUE TITLE
[1.19.3] Performance with bees in the nether - 3-4 TPS 3798 bees.

### ISSUE THREAD

**Issue by ProsperCraft** [JDKDigital/productive-bees#366]
There are too many bees in the nether, it appears to be Crimson Shoombees there are dozens of nests around every cluster of Crimson Shooms.

Here is a spark profile -
https://spark.lucko.me/uT48CAOR4g

Here is a screenshot of /forge entities list showing 3798 bees.  Also showing 2.2 TPS
![image](https://user-images.githubusercontent.com/4427684/222927194-55bbdc1e-9417-4fc5-8bcf-89344998bae0.png)

On returning to the overworld, here is a screenshot showing 20 TPS
![image](https://user-images.githubusercontent.com/4427684/222927309-aa1f1071-b445-4dfc-b53d-3b2dd11ed0b2.png)

**Comment by JaisDK** [comment]
The worldgen must have gotten fucked in the 1.19.3. update. Thanks for reporting it, I'll have a look into it.

**Comment by dm8mydog** [comment]
Apologies for interjecting with an off topic question, my google-foo is totally failing to give me an answer.
What's the command/mod to get the statistics you've shown for the tps?

**Comment by ProsperCraft** [comment]
The performance profiles are from the mod Spark
https://www.curseforge.com/minecraft/mc-mods/spark
/spark healthreport
   is also incredibly helpful.

The TPS is from /forge tps
the entities list is from /forge entities list

**Comment by ImVexed** [comment]
Also observing this issue on my ATM8 server. Dropping to ~10 TPS in the nether. Spark shows `ConfigurableBee.tick` as the highest consumer, nothing else is even close

**Comment by JaisDK** [comment]
Can you provide your sparks profile? ATM8 is on 1.19.2 so it might not be the same issue

**Comment by JaisDK** [comment]
an entity count would also be nice

**Comment by ImVexed** [comment]
https://spark.lucko.me/NFIN7GUnJ9
Seems to be the Bee's `aiStep`
![image](https://user-images.githubusercontent.com/10090878/228032831-a0584c84-b6f5-40ac-85f1-2b5672fd0e60.png)

**Comment by JaisDK** [comment]
42 bees is not uncommon and they use 14% of the resources flying around which _is_ bad but that's just Minecraft pathing being shit.

**Comment by ImVexed** [comment]
It's more of a problem when we have multiple people running around in the nether, that profile was just me in the nether. But last night we had 2-3 people in there and were dropping to ~10 tps. I didn't manage to catch a profile of that sadly.

Is there any way I can just stop the bees from spawning as a temporary fix?

**Comment by JaisDK** [comment]
you can run a kill command if you're not interested in keeping the bees

/kill @e[type=productivebees:configurable_bee, name="Warped Shroombee"]
/kill @e[type=productivebees:configurable_bee, name="Crimson Shroombee"]

there's also a config option to disable the nether nest spawns, but some say it doesn't work but worth a try

**Comment by ImVexed** [comment]
Setting:
```
 #Disable the wander goal in bees to increase performance
        disableWanderGoal = true
 ```
 Fixed the AIStep usage

**Comment by JaisDK** [comment]
forgot I had added that, it makes the bees a little bit wonky :D

**Comment by JaisDK** [comment]
1.19.3 support is dropped
