### ISSUE TITLE
More bees in the chunk

### ISSUE THREAD

**Issue by faustyu1** [JDKDigital/productive-bees#367]
![image-3.png](https://user-images.githubusercontent.com/104709162/222966013-b5885ad8-5e42-4686-81f9-bed858b5a202.png)

![image.png](https://user-images.githubusercontent.com/104709162/222966010-c22d64a5-c6a7-437b-a321-7ee36f916629.png)

![image-1.png](https://user-images.githubusercontent.com/104709162/222966011-76a90da4-8c74-45ef-a54c-e5a3a322cf1b.png)

![image-2.png](https://user-images.githubusercontent.com/104709162/222966012-a46b3f10-6ed3-418a-90ad-751f1c8356b7.png)

Тростниковая пчела - Reed bee

When I arrive in the chunks I have a ton of bees spawning and in the logs about the exit of the bee from the chunk.

Example: [MCMT-Pool-Thread-12/WARN] [net.minecraft.world.server.ServerWorld/]: Entity BeeEntity[Bee'/1882, l='ServerLevel[тест новый сборки]', x=209.72, y=67.06, z=-457.37] left loaded chunk area

**Comment by JaisDK** [comment]
wow

**Comment by JaisDK** [comment]
what version is this on?

**Comment by faustyu1** [comment]
1.16.5

**Comment by JaisDK** [comment]
do a kill command and see if you can find the source, they don't spawn on their own

**Comment by faustyu1** [comment]
As soon as I kill them, they spawn. This is most likely a restriction of the mine on the submerged terrain. And if it hadn't been there, the mine would have died right away.![image-5.png](https://user-images.githubusercontent.com/104709162/222967138-6d584daf-262d-4ec1-a6e9-80d2191c85d9.png)

![image-4.png](https://user-images.githubusercontent.com/104709162/222967137-da2a73ea-4c23-4205-91de-46190b113eda.png)

**Comment by faustyu1** [comment]
Уничтожено - kill

**Comment by JaisDK** [comment]
destroy the reed nest they're coming from and then kill again

**Comment by faustyu1** [comment]
> destroy the reed nest they're coming from and then kill again

Every time I kill them they are reborn.

**Comment by JaisDK** [comment]
destroy the sugar canes, that's where the nest is

**Comment by faustyu1** [comment]
Is it possible to turn off these bees?

**Comment by faustyu1** [comment]
Потомучто происходит из-за этих пчел

**Comment by faustyu1** [comment]
Because it's because of the reed bees.

**Comment by JaisDK** [comment]
did you destroy the sugar cane and the nest in the sugar cane?

**Comment by faustyu1** [comment]
I didn't find a nest

**Comment by faustyu1** [comment]
They appeared when I was looking at other blocks from another mod and they appeared. And yes sugar cane I broke too.

**Comment by JaisDK** [comment]
if there's no nest and they are just popping into existence from nothing, then you have a mod that messes things up big time
can you send me a log?

**Comment by JaisDK** [comment]
these bees only spawn from nests, so there's either a nest nearby being super funky for whatever reason, or someone set up a spawner in that area.

you can use a nest locator to check if there's a nest nearby

**Comment by faustyu1** [comment]
i delete this mod
