### ISSUE TITLE
Farmer bee causes ticking entity crash harvesting wheat.

### ISSUE THREAD

**Issue by DocTran** [JDKDigital/productive-bees#369]
in the modpack Roguelike Adventures and Dungeons 2 by Dreams. I have on two separate worlds run into a crash by a ticking entity pointing at the farmer bee. I was able to observe the last time the game crashed it was at the moment a farmer bee tried to harvest wheat. Currently in SSP

[crash-2023-03-25_15.34.26-server.txt](https://github.com/JDKDigital/productive-bees/files/11069939/crash-2023-03-25_15.34.26-server.txt)

**Comment by JaisDK** [comment]
This is an incompatibility with Majruszs Accessories. Not much to do unless they change their code or I have time to change mine.

**Comment by DocTran** [comment]
Thank you, I will let the modpack author know of the incompatibility of the two in a link to this post. 
Thank you for your work on the mod!

**Comment by JaisDK** [comment]
I just let them know as well
