### ISSUE TITLE
Zinc bee impossible to breed in Create

### ISSUE THREAD

**Issue by selened** [JDKDigital/productive-bees#37]
The Zinc Bee requires a Tin Bee to be bred. However in a mod that adds zinc but not tin (such as Create), breeding a zinc bee is impossible

**Comment by JaisDK** [comment]
Didn't think a mod would  add zinc without tin. I'll change it for the next version.
Until then you can change the recipe with a datapack if you can't wait. The recipe is here https://github.com/JDKDigital/productive-bees/blob/master/src/main/resources/data/productivebees/recipes/bee_breeding/zinc_bee.json

**Comment by JaisDK** [comment]
Recipe has been changed
