### ISSUE TITLE
Advanced hive allows overstacking 

### ISSUE THREAD

**Issue by Saereth** [JDKDigital/productive-bees#370]
Mc 1.19.2
Force 43.2.6
productive bees: productivebees-1.19.2-0.10.5.3

Describe the bug
Productive Bees can be used to force any item to stack. This lets you not only bypass Minecraft's 64 stack limit, but stack unstacakables. With very little effort. This opens up a whole list of dupes. Which I wont explain for obvious reasons.

Steps to reproduce
Shift click any identical item into the advanced hive block.
Pick up both items with your mouse, they are now stacked.
Drop the item on the ground
Pick it up to maintain stack.
Expected behaviour
Only take out a maxStack of item

Originally reported here:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3040

**Comment by JaisDK** [comment]
Thanks for reporting. I guess I better get it fixed if it can be used for duping.
