### ISSUE TITLE
Upgrade: Filter seems unresponsive and will not add a Bee when playing RAD2-1.16.5-1.1

### ISSUE THREAD

**Issue by TA-stabby-dagger** [JDKDigital/productive-bees#374]
I searched open and closed issues and could not find an answer to my issue, and I apologize profusely if I have somehow missed it.

I am playing RAD2-1.16.5-1.1, using Productive Bees.  Currently housing Diamond and Ender bees.  I am trying to use filter upgrades to keep the community bees together in one enclosure, but keep hives separate for processing reasons, and I am running into an issue.  Both the upgrade filter item, and the book, say to right-click the bee to add it to the filter (I assume while holding the filter) however when I do this, there is no indication that the filter has changed or added a bee, and if I apply that filter then to a hive (advanced with expansion ofc), no bees of any kind are able to enter that hive.  On one hand, it's great to know that a blank filter will basically blacklist all bees and keep the hive box empty, but I am unable to figure out how to add a bee to the filter at all.  I have scoured the internet and cannot seem to find any mention of this issue for anyone else.  I am hoping someone can provide some insight.

**Comment by JaisDK** [comment]
Where are you right clicking the bee? It has to be on the actual bee entity when it's flying around outside the hive. Also I don't think you can be in creative while doing it.
Once it works the item tooltip will list the bees in the filter.

**Comment by TA-stabby-dagger** [comment]
I was clicking the bee entity while it was out flying, however, i was _also_ in creative!  Thank you so much!  I feel silly having not realized that myself.  I appreciate your time!
