### ISSUE TITLE
JEI Recipe integration is backwards

### ISSUE THREAD

**Issue by vadcx** [JDKDigital/productive-bees#377]
JEI supports two kinds of lookups:

- How to craft \_ITEM\_ (default: Left-Click or "R" key for "Recipe")
- What can be crafted using \_ITEM\_ (default: Right-click or "U" key for "Usage")

For example, Recipe for a MC Furnace is 8 cobble → Furnace. Usage for an MC Furnace is 1 furnace, 4 logs → Smoker

If you click for Recipe on a Carpenter bee, all you see is its description (tab "Information"):

> This bee is solitary and can be found living alone in nests around the overworld. **Look up recipe for this bee** to see which nests it can spawn in.

Ok how do I look up the recipe to make this bee? Of course, I left-click (R) it to see how it's crafted... but instead I'm brought to the same info tab. Misleadingly, the BREEDING RECIPES for bees are in their "Usage" section. So instead of Recipes, I must look them up in Usages.

**Solution:** Move _Bee Breeding_ and _Bee Spawning_ to the recipe section. The _Bee Flowering_ is already in the correct JEI section (Usage), because that's how you "use" a given bee.

If you're still not convinced, I will explain better :)

productivebees-1.19.2-0.10.5.3.jar

**Comment by JaisDK** [comment]
I am convinced, I just forgot to fix it in the latest release

**Comment by Nekosity12** [comment]
I'm not convinced! I want to see this amazing explanation 👀(i kid btw)

**Comment by JaisDK** [comment]
Only the spawning recipe is incorrect, for breeding recipes the two parent bees are listed as inputs and the offspring is listed as an output.
Was there a specific bee you had trouble looking up the breeding recipe for?
The info tab is shows on both recipe and usage lookups and it's possible it's the first one shown sometimes.

**Comment by vadcx** [comment]
You're right. I just checked and the Bee Breeding is correct... I don't know why I wrote it down? :sweat_smile:
