### ISSUE TITLE
Crash when trying to render item

### ISSUE THREAD

**Issue by selened** [JDKDigital/productive-bees#38]
There's a crash that happens when I open the creative inventory for productive bees and the game tries to render an item. From skimming through the crash report it might be a wood chip for a wood added by Atmospheric. Here's the full crash report:
https://pastebin.com/BWCUGcws

**Comment by JaisDK** [comment]
Thank you for your report. The problem seems to be with Crustose Log from Atmospheric. Don't put any next to a LumberBee until I work out a fix ;)

**Comment by COLDW0LF** [comment]
Just to add info to this, I'm having the same issue with Forbidden & Arcanus; Edelwood logs cause the same rendering crash.

**Comment by JaisDK** [comment]
Thanks for the info. The new version has a check that will prevent crashing. The blocks will still not render, but they will still be usable.
