### ISSUE TITLE
Bees taking damage and dying

### ISSUE THREAD

**Issue by Nhune** [JDKDigital/productive-bees#380]
the bees take damage when entering the hive I've tried using the simulation upgrade but it still loses life.
![image](https://github.com/JDKDigital/productive-bees/assets/94803711/adfd6e36-3b9e-4796-b9d9-027e9d9e6a6f)

**Comment by Nhune** [comment]
Minecraft 1.18.2
Forge 40.2.0
Productivebees 1.18.2-0.9.3.0

**Comment by JaisDK** [comment]
they are not taking damage, but the health increase is temporarily removed which sets them down to vanilla level health
