### ISSUE TITLE
1.18.2-0.9.3.0 - Upgrade Simulator not working with either Flower or Feeding Slab

### ISSUE THREAD

**Issue by Bauws** [JDKDigital/productive-bees#381]
Hey, 

I will skip the part with the screenshots for now. I have seen a post about the same issue in 1.19 and I bet you already know how to fix it. The issue is basically the same. If you put an Upgrade Simulator inside the advanced beehive the bees will stay inside the hive but not recognize flowers on any level or feeding slabs with items in it.

If you need screenshots lmk :)

Greetings and thanks for all the effort with this awesome and super fun mod!

**Comment by JaisDK** [comment]
Hey,

I will definitely need a screenshot of your hive setup as well as some info on which bees and flower blocks you're using.
