### ISSUE TITLE
[1.19.2] Can't pipe out of Gene Indexer

### ISSUE THREAD

**Issue by Schevv** [JDKDigital/productive-bees#382]
Hi,

it looks like the GeneIndexer cannot output items (through pipes) anymore since the last update. Before I had a Pipez-Pipe with a filter to remove the 100%-genes. 

This stopped working. And it seems like I can't use other pipes to access the Genes as well (UI works fine, though).

Anyway let me take this oportunity to thank you for the great mod :)

**Comment by JaisDK** [comment]
The last update you're referring to is 1.19.2-0.10.7.0?

**Comment by Schevv** [comment]
Yes, sorry for not specifying. Its 1.19.2.-0.10.7.0 as contained in ATM-8 1.0.19b.

(If I had to guess, I assume its the change in GeneIndexerBlockEntity:60 (in isInputSlot()), but the days when I last saw Minecraft code are long gone :s )

**Comment by JaisDK** [comment]
fixed
