### ISSUE TITLE
[1.19.2] Editing of flowering block

### ISSUE THREAD

**Issue by ThisisCanada98** [JDKDigital/productive-bees#383]
I'm trying to cut down on entity lag by giving my wasted radioactive bees a flowering block of say just the wasted comb block. It seems like currently by using an edited json just disables the bee. Am I missing a way of adding to allow them to be used with the simulation block?

**Comment by JaisDK** [comment]
if the bee disappears then your json is probably invalid. What did you change it to?

**Comment by ThisisCanada98** [comment]
Seems the deleting of the bee was a typo on my end, but the Wasted bees don't seem to be able to use "productivebees:flowers" as a flower type

This is the json as of now

{
    "primaryColor": "#80B425",
    "secondaryColor": "#bb8d23",
    "particleColor": "#80B425",
    "flowerTag": "productivebees:flowers",
    "description": "productivebees.ingredient.description.wasted_radioactive_bee",
    "irradiated" : true,
    "particleType": "pop",
    "useGlowLayer": true,
    "conditions": [
        {
            "type": "forge:mod_loaded",
            "modid": "mekanism"
        }
    ]
}

**Comment by JaisDK** [comment]
`"productivebees:flowers"` is not a thing, it's `"minecraft:flowers"` if you're just going for any flower.

also remove `"irradiated" : true,` if you don't want it to pollinate from radiation damage

**Comment by ThisisCanada98** [comment]
Thank you very much got it solved. Appreciate it!
