### ISSUE TITLE
[1.19.2] Ars Nouveau arcane bee spawn egg crafting needs updated to new recipe format

### ISSUE THREAD

**Issue by DelviousCrafts** [JDKDigital/productive-bees#385]
Ars Nouveau recently updated its crafting recipe format for the enchanting apparatus. This caused the recipe in productive bees to break for the arcane bee. The pedestal ingredients no longer need the item wrapper before the actual ingredient.

Versions: 
- Minecraft: 1.19.2
- Forge: 43.2.11
- Productive Bees: 0.10.7.0
- Ars Nouveau: 3.15.1

**Comment by JaisDK** [comment]
fixed
