### ISSUE TITLE
Quartz Enriched Iron has incorrect conditions produce

### ISSUE THREAD

**Issue by asantmier** [JDKDigital/productive-bees#386]
Minecraft 1.19.2 Forge 43.2.11
Productive Bees 0.10.7.0

I was having issues disabling the quartz enriched iron bee for Refined Storage on my modded server because the server kept giving me this error when I tried connecting:
![image](https://github.com/JDKDigital/productive-bees/assets/91630046/74a2aaab-c7f1-47b8-a84f-ced55e8db98b)

Upon closer inspection, I found that the recipe `productivebees:bee_produce/refinedstorage/quartz_enriched_iron` 's conditions are:
```
"conditions": [
    {
        "type": "forge:mod_loaded",
        "modid": "refinedstorage"
    }
]
```
only checking if the mod is loaded rather than the bee, like in other recipes. This is what the bee from Spirit looks like for example:
```
"conditions": [
    {
        "type": "productivebees:bee_exists",
        "bee": "productivebees:spirit"
    }
]
```
I simply disabled the recipe to get it working on my end, but that condition needs to be be changed to conform with the others and fix this error.

**Comment by JaisDK** [comment]
👍

**Comment by JaisDK** [comment]
fixed
