### ISSUE TITLE
It's unclear what the blood magic "regeneration bee" does - improved documentation?

### ISSUE THREAD

**Issue by andrewjbennett** [JDKDigital/productive-bees#388]
Hi there,

I'm playing ATM7 (1.18.2), which includes Productive Bees 0.9.1.6. 

The modpack includes Blood Magic, which means that there are the two blood magic bees: hematophagous and regenerative. The hematophagous bee makes combs which can be turned into life essence -- makes sense. 

The regenerative bee doesn't make combs, and doesn't seem to have any other effects that I can find, either from playing around with the bee in various places or from reading the source code.

I'm not sure if the bee is meant to do something but it's broken, or if it's just doing something subtle and non-obvious so I can't work out what it's doing.

Would you be able to add documentation about what it's meant to do? (or even just respond here so that other people can find the info by searching the github issues)

Thanks :)

**Comment by JaisDK** [comment]
The idea is that it can bee used in the sacrifice ritual just like witches because they regenerate health on their own.
