### ISSUE TITLE
Feature request: work with the ElementalCraft "sweet shrine" with nectar upgrade

### ISSUE THREAD

**Issue by andrewjbennett** [JDKDigital/productive-bees#389]
The mod ElementalCraft has "shrines" which provide some effect over an area; it includes the "sweet shrine" which will feed players, which can be upgraded with a "nectar upgrade" to instead feed bees.

In my experiments, it will feed vanilla bees, but not productive bees.

This is the relevant code ([source](https://github.com/Sirttas/ElementalCraft/blob/81f0359f9dc28d0ca31e324e03640ccd7b18d0a5/src/main/java/sirttas/elementalcraft/block/shrine/sweet/SweetShrineBlockEntity.java#L34-L37)): 

```
getEntities(Bee.class).forEach(e -> {
	if (this.elementStorage.getElementAmount() >= consumeAmount) {
		this.consumeElement(consumeAmount);
		e.setHasNectar(true);
	}
}
```

I'm not an expert at Java, I would've thought that your `public class ProductiveBee extends Bee` ([source](https://github.com/JDKDigital/productive-bees/blob/bb263872594db06d47e9984d4f3181a619fbdfff/src/main/java/cy/jdkdigital/productivebees/common/entity/bee/ProductiveBee.java#LL68C1-L68C39)) would be sufficient for this to include your bees, but in my experiments it hasn't.

It does seem to be triggering the codepath (because it's consuming elements), but the bees don't get pollinated.

I have two questions:

1) Based on the snippets of code here, should this be working on your bees? (i.e. is this a bug with ElementalCraft)

2) If not, is there something that can be changed with the productive bees to allow them to work with the shrines, or would this need to be a feature request for ElementalCraft?

**Comment by JaisDK** [comment]
I have deliberately disabled that shrine from working on my bees because it bypases a lot of progression. 
it’s possible to re-enable it yourself if you want as I added a tag with which bees it does work on.
