### ISSUE TITLE
Advanced Canvas Beehives crashes game

### ISSUE THREAD

**Issue by FoxSketchez** [JDKDigital/productive-bees#390]
**Mod Pack:** All The Mods 9

**Description:** When placing an Advanced Canvas Beehive down,
will crash your client to desktop

(will provide a crash report if needed)

**Comment by JaisDK** [comment]
crash log is needed

**Comment by FoxSketchez** [comment]
Crash Log as requested :

https://pastebin.com/UjxvbmWq

**Comment by JaisDK** [comment]
thanks you, seems to be cooking for blockheads causing it, but I should be able to guard against it

**Comment by FoxSketchez** [comment]
I hate to say this; But the Advanced Canvas Beehive 
is still crashing game 


Mod Pack: All The Mods 9

Description: When placing an Advanced Canvas Beehive down,
will crash your client to desktop (still)

Crash Report
https://pastebin.com/EQM9Pwge

**Comment by JaisDK** [comment]
Did you update to the latest version of the mod that I put up an hour ago?

**Comment by JaisDK** [comment]
now that I'm not on mobile anymore I can see that you did not, the fix is just to update.

**Comment by FoxSketchez** [comment]
ah ok, I was sure the server was using the new update
I'll look into it. Thanks
