### ISSUE TITLE
Nests aren't working

### ISSUE THREAD

**Issue by Dinocraft1515YT** [JDKDigital/productive-bees#393]
Some nests don't let you interact with them to spawn bees, here a picture
![1687701367901998989076268321475](https://github.com/JDKDigital/productive-bees/assets/120250129/3083ce58-9eb0-4a6f-9380-12883b18e270)
The nest that are 2 of that type have that problem

Minecraft version: 1.20
Forge version: 46.0.14
Mod version: 1.20.1-12.1.0

**Comment by JaisDK** [comment]
some nests require specific biomes and some require specific items
