### ISSUE TITLE
Can't feed diamond bees Peridot/Ruby/etc

### ISSUE THREAD

**Issue by stayingarmed** [JDKDigital/productive-bees#395]
I'm playing ATM8 and in the quest book I need to feed a diamond bee a peridot to get a peridot bee or a ruby to get a ruby bee and the diamond bees won't eat/convert.

Using most up-to-date productive bees from Curseforge btw

**Comment by JaisDK** [comment]
right click the bee with the block

**Comment by stayingarmed** [comment]
> right click the bee with the block

Jesus wept....why doesn't it say "feed a diamond bee a peridot block/ruby block" instead of just "peridot/a ruby" 🤦

**Comment by JaisDK** [comment]
because it has to be a block...
