### ISSUE TITLE
[suggestion] add a BooBee that produces milk

### ISSUE THREAD

**Issue by theboo** [JDKDigital/productive-bees#40]
title says it all...(in all honesty, a CowBee would be sweet)

**Comment by JaisDK** [comment]
A bee that can milk nearby cows and deposit the result in the hive instead of honey, would be fun. I would name it differently though :)

**Comment by MokahTGS** [comment]
Moobee

**Comment by JaisDK** [comment]
Added a rancher bee that milks cows and creates milky combs. It's as close to a BooBee as we'll get ;)
