### ISSUE TITLE
Lack of information - Amber Bee

### ISSUE THREAD

**Issue by cwjeff45** [JDKDigital/productive-bees#400]
When looking for information on the Amber Bee it seems like none is available. My JEI has this issue with multiple bees where I get no information about breeding or spawning at all.  It may be an issue with my modpack, but I can also not find anything at all online. Where can you find amber bees? What is used to breed and produce combs? How do you "farm" amber blocks containing entities? If this is a modpack issue, any recommendations as to what can fill the gaps? Thanks

**Comment by JaisDK** [comment]
I can add some info for next update

**Comment by cwjeff45** [comment]
Awesome, thats super exciting! thanks!
