### ISSUE TITLE
1.19.2, Advanced bee hives, bees not producing anything. (Simulator upgrade, feeding slab)

### ISSUE THREAD

**Issue by DigitalWendigo** [JDKDigital/productive-bees#401]
Hello! 
Thank you for making this mod, it's really fun playing with it. 

There seems to be a bit of an issue on my end with the bees and I'm not sure what the issue is. 
I've opted to use the simulator upgrade to temporarily avoid making enclosures for each bee, but can't seem to get the bees to produce anything. 
I began with the regular vanilla minecraft bees and used the advanced oak beehive, and for a while, it worked, even with the sumulator upgrade. 
But recently, it just up and stopped working. 
I've tried just about anything I can think of, like moving them, resetting the beehive by putting it in a crafting grid to empty it of nbt data, using the hive with and without the simulator, but even after several ingame days, the bees just don't seem to produce anything any more. 
Here are some screenshots of my last attempted solution, the feeding slab, which unfortunately did not solve it either. 
I haven't changed anything in the configs, added any new mods or datapacks, or even done anything with the world data, so it can't be that if it has been functioning correctly before, I think?
Am I just issing something or..?

( productivebees-1.19.2-0.10.7.2 )
![2023-07-19_17 57 47](https://github.com/JDKDigital/productive-bees/assets/103202053/0ada1f8b-f31b-4ad0-8203-7fd0ea4b8199)
![2023-07-19_17 57 55](https://github.com/JDKDigital/productive-bees/assets/103202053/7e5d4317-ddd7-40f9-883f-d1e7336cbac9)

**Comment by JaisDK** [comment]
the one you're looking at in the first screenshot is the correct setup, the others have the slab too high up

**Comment by DigitalWendigo** [comment]
Oh darn, that's way off from what I originally understood from the 'tutorial' book of the mod, which says they need to be in front of them. 
I changed the rest of them to one block below and, low and behold, everything functions again. 

Thanks for the reply! 
Closing the issue.
