### ISSUE TITLE
Mystical Agriculture essence bees not producing [SOLVED] [SIMULATOR UPGRADE]

### ISSUE THREAD

**Issue by natattack99** [JDKDigital/productive-bees#402]
I made and maxed out all of the mystical agriculture essence bees because I wanted to mass produce essence, but they bees do not pollinate from the essence blocks as said in JEI. It is expected that they produce their respective combs.

**Comment by JaisDK** [comment]
Which version are you on and can you please show a screenshot of your setup

**Comment by natattack99** [comment]
productivebees-1.20.1-12.1.3, Forge 1.20.1 - 47.1.0, minecraft 1.20.1, MysticalAgradditions-1.20.1-7.0.0

![1 Infernium hive](https://github.com/JDKDigital/productive-bees/assets/59242155/bb975e23-1c46-46f9-b5a8-46c6e91efeb7)
![2 Infernium feeding slab](https://github.com/JDKDigital/productive-bees/assets/59242155/557b314d-2357-4247-ad12-e8ce82f10077)
![3 Infernium centrifuge](https://github.com/JDKDigital/productive-bees/assets/59242155/98ea0ea8-ba88-4370-8f00-cfb90c616159)
![4 infernium buffer chest](https://github.com/JDKDigital/productive-bees/assets/59242155/a1b095ad-6122-4480-99c1-d220f78070c9)
![5 prudentium hive](https://github.com/JDKDigital/productive-bees/assets/59242155/3032ff8d-f9f9-4492-9133-63b9e6f0b9a8)
![6 prudentium not pollinating](https://github.com/JDKDigital/productive-bees/assets/59242155/9fb69d02-6b37-4cc6-95a7-5d5ed2a537ee)
![7 prosperity hive (working)](https://github.com/JDKDigital/productive-bees/assets/59242155/b9ce477f-d53b-4800-b98b-bb1cbaa407c5)
![8 prosperity hive (inside)](https://github.com/JDKDigital/productive-bees/assets/59242155/7a1c743c-cd8b-468d-81c9-7cebb30cac87)
 They are all metaturnial, and they don't seem to recognize their polination block and fly arround ignoring the feeding slab when simulation upgrade is out. Same with the blocks instead of feeding slab. Prosperity and soulium work fine along with all the other bees i have.

**Comment by JaisDK** [comment]
move the slabs down 1 block into the flow

**Comment by natattack99** [comment]
that works! but why are they different? i moved it down and the immediantly pollinated and produced combs but why are they different? anyway thx.

**Comment by JaisDK** [comment]
That’s how the hives are coded, the flowering block has to be in a specific place for simulated hives.

**Comment by natattack99** [comment]
I now realize why I was confused. I am going to use this comment to explain to anyone else who might be confused in the same way as I was.

All of my other hives were designed without the simulation upgrade in mind.
![X1](https://github.com/JDKDigital/productive-bees/assets/59242155/44d7f0c9-73ab-418e-9f14-b33c35f5e363)
But when it started getting laggy, I put in the simulation upgrade for some of them and added a block (thinking it was nessesary)
![X2](https://github.com/JDKDigital/productive-bees/assets/59242155/6e239069-b255-4afa-a119-a52d74e2549b)
(Notice how I don't remove the floor)
Then when I put in the mystical bees, their setup looked like this.
![X3](https://github.com/JDKDigital/productive-bees/assets/59242155/13aa0339-027e-4d85-9499-024595ee2062)
I thought that the mystical bees were different because I didn't realize all the others were using the floor that I didn't remove instead of the block I added for the upgrade.

Thank you for the help.
