### ISSUE TITLE
Productivity upgrade messes up simulator in other dimension, even though the chunk is loaded.

### ISSUE THREAD

**Issue by AnggaKolim** [JDKDigital/productive-bees#409]
Bees put in the end dimension to remove the behavior needs, but when i put productivity upgrade, they didn't produce any comb when i leave the dimension.

when i remove the upgrade it working again.

**Comment by AnggaKolim** [comment]
productivebees-1.19.2-0.10.7.2 ftb-chunks-forge-1902.3.22-build.271

**Comment by AnggaKolim** [comment]
and i also put 3 upgrade each

**Comment by JaisDK** [comment]
I don't see how the productivity upgrade can affect anything about chunk loading, there's really nothing I can change in the code.

Could you test some more to see if it's not just a problem with the setup or the chunk loading mod?
