### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by alsmith23** [JDKDigital/productive-bees#41]
[crash-2020-07-09_21.07.44-client.txt](https://github.com/JDKDigital/productive-bees/files/4900171/crash-2020-07-09_21.07.44-client.txt)

**Comment by JaisDK** [comment]
Hello, thanks for reporting.
When does this happen? Is it when launching the game, opening the world and is it for a fresh or existing world?

**Comment by alsmith23** [comment]
HI. sorry.

occurs when I start the laucher.

**Comment by JaisDK** [comment]
It's an odd one. Is there anything custom about your setup? Can you try to put this mod in instead and see if it also crashes https://www.curseforge.com/minecraft/mc-mods/not-what-it-seems ?

**Comment by alsmith23** [comment]
It worked. thank you very much.

**Comment by JaisDK** [comment]
Wait, what worked? Are you not crashing anymore even with Productive Bees or did it stop crashing when you removed it?

**Comment by alsmith23** [comment]
sorry for not responding correctly. I understand that you use this information to improve the mod. I used the mod you indicated (not what it seems). then there was no problem. Google translator.

**Comment by JaisDK** [comment]
That makes it even more odd :), the mod was not supposed to fix anything, it just uses the same method I am for registering block colors, so I figured it would also crash. But since there's no problem anymore, I will close the isssue.

**Comment by alsmith23** [comment]
actually failed. but as it was in another mod, I let it go. after I removed the other mod, it worked normal. then I can post the error here.

**Comment by JaisDK** [comment]
Ah ok, which mod was causing the issue?

**Comment by alsmith23** [comment]
Melon Golem

**Comment by GP703** [comment]
Also does not work with botany pots.

**Comment by JaisDK** [comment]
@GP703 Can you open a new issue with a crash log please?
