### ISSUE TITLE
Have simulator upgrades not require an upgrade slot somehow

### ISSUE THREAD

**Issue by NathanDSimon** [JDKDigital/productive-bees#411]
Maybe have it be a separate block? I just dislike having to use one of my upgrade slots to reduce server lag since that slot could be used to increase my efficiency by a massive amount instead. Or maybe have it be something that slots into a feeder slab...IDK, just any way so that the super-grindy recipes I use my bees to address can be finished in a reasonable amount of time without lagging SMP servers for everyone else.

**Comment by JaisDK** [comment]
it's already in the latest 1.20.1 version as new tiers of productivity upgrades that also function as sim upgrades
