### ISSUE TITLE
ATM9 bees missing recipes

### ISSUE THREAD

**Issue by Arochio** [JDKDigital/productive-bees#413]
I've noticed a number of bees in the All the mods 9 modpack are missing recipes, such as indium, phosphorus, and a few others. im not sure if this is intentional as i know some recipes are in the chemlib machines without distinct names, but just wanted to report if its not intended. just for clarification, neither the bee nor the spawn eggs have valid recipes.

**Comment by Legorfyr** [comment]
Hello, the easy response is, Alchemistry and chemlib need to push their update.
The bees have recipes, but the old versions of those mods don't support nbt data, ergo, eggs can't be crafted.

**Comment by Arochio** [comment]
gotcha, thank you for the help.
