### ISSUE TITLE
JEI + Productive Bees causes crash on 1.20.1

### ISSUE THREAD

**Issue by suhbean** [JDKDigital/productive-bees#414]
Minecraft Version: 1.20.1
Mod Version: 1.20.1-12.1.8
Forge Versions tried: 47.1.44 and 47.1.1
[crash-2023-08-29_20.53.41-client.txt](https://github.com/JDKDigital/productive-bees/files/12470917/crash-2023-08-29_20.53.41-client.txt)

I let the game load in for about a minute, then I open JEI and start scrolling through the pages with my mouse. Once I get to the page where the Productive Bees items start showing up, the game crashes. According to the crash report, it says there may be an issue with an item called "Diamond Comb".

**Comment by JaisDK** [comment]
It’s Rubidium’s fault
