### ISSUE TITLE
Sussy bees give you "Non World Gen" Suspicious Gravel or Sand so they don't drop anything

### ISSUE THREAD

**Issue by Pilpoh** [JDKDigital/productive-bees#415]
Sussy bees give you "Non World Gen" Suspicious Gravel or Sand so they dont drop any thing just sos you guys know. It's like placing a creative sus gravel and brushing it

**Comment by JaisDK** [comment]
Hey Pilpoh, I enjoy your videos :)

You have to have them operate in a biome where sussy stuff naturally generates, like an ocean biome.

**Comment by Pilpoh** [comment]
My bad! I will add an edit to my video explaining this :)
