### ISSUE TITLE
Crash w/o Pam's Harvestcraft

### ISSUE THREAD

**Issue by WenXin20** [JDKDigital/productive-bees#418]
Minecraft v1.20.1
Forge v47.1.47
Productive Bees v12.2.0

I do not have Pam's Harvestcraft installed and got this crash

[Crash Report](https://gist.github.com/WenXin20/09fe54037b483b801aeb1e3fa7c720be)

**Comment by JaisDK** [comment]
hmm, it was supposed to be a soft dependency.

15-20 minutes and I'll have a new version up

**Comment by WenXin20** [comment]
Thanks!
