### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GP703** [JDKDigital/productive-bees#42]
[crash-2020-07-10_16.10.24-client.txt](https://github.com/JDKDigital/productive-bees/files/4905483/crash-2020-07-10_16.10.24-client.txt)

Game crashes on start up with botany pots.

**Comment by JaisDK** [comment]
Thank you.

Does it also crash if you remove botany pots but keep Bookshelf?

**Comment by GP703** [comment]
No it does not.

**Comment by JaisDK** [comment]
Can you send the latest.log file as well from when it crashed. You'll find it in your .minecraft/log folder

**Comment by GP703** [comment]
[latest.log](https://github.com/JDKDigital/productive-bees/files/4905758/latest.log)

**Comment by JaisDK** [comment]
Thank you, it shows the error is in botany pots. I've opened an issue on their issue tracker. https://github.com/Darkhax-Minecraft/BotanyPots/issues/55
