### ISSUE TITLE
Bloody Bee conflict.

### ISSUE THREAD

**Issue by Kiriao** [JDKDigital/productive-bees#420]
I playing a modpack "ATM 9" and the bloody bee use  to produce blood from evilcraft but i can also produce life essence from bloodmagic, possible to fix this conflict?

**Comment by JaisDK** [comment]
That's for the pack to pick which they want to prioritize, I'll let them know.

**Comment by JaisDK** [comment]
checked again and the bloody bee is not supposed to be producing BM "life essence" as it's not tagged as blood but you can use the Hematophagous Bee for BM as it has automatic regen like witches so it can be used in that ritual that drains nearby entities

**Comment by JaisDK** [comment]
now I know what the problem is, I was just being dumb. I'll remove the extra conflicting recipe.

**Comment by Kiriao** [comment]
sry but went is the new update going to release to fix the conflicting recipe?

**Comment by JaisDK** [comment]
when the rest of the update is ready
