### ISSUE TITLE
Hoarder been genes not sampling with pokey

### ISSUE THREAD

**Issue by McKitten** [JDKDigital/productive-bees#422]
I have been working towards the wannabee and have a hoarder bee with 4 pokey upgrades in its hive for several days now, a few other bees in the same time frame have hit 100% sample size, the lowest being 33% but still nothing from the hoarder.

Will i need to sacrifice and squish them for genes and if so, can JEI be upgraded to indicate this some how?

**Comment by JaisDK** [comment]
You will have to squish those
