### ISSUE TITLE
Wasted Radioactive Bees not working with Simulator Upgrade/Productivity Omega

### ISSUE THREAD

**Issue by YukkiPlays** [JDKDigital/productive-bees#425]
Hi! I don't know if thats the right place to open this issue, but im playing a Modpack (ATM9) and i noticed, that wasted radioactive bees wont pollinate if the hive is equipped with any kind of simulator upgrade. If you try to scale this setup horizontally without a Simulator upgrade it would cause massive TPS Issues on servers.

**Comment by JaisDK** [comment]
I’m not gonna change it unless you can show that it’s worse performance than running the normal mekanism setup for the same production rate

**Comment by YukkiPlays** [comment]
I am confused about this request. Wouldn't it be better to cut server lag either way? Or is this some kind of intentional gamedesign?

**Comment by JaisDK** [comment]
Cutting pathing from all other bees is already plenty, how many wasted bees are you running with to have such a big problem?

**Comment by JaisDK** [comment]
You can also just change the flowering block yourself for your server with a datapack.

**Comment by YukkiPlays** [comment]
None at the moment. I thought this might be a bug, thats why i opened an issue. It seemed to be one because i could add the upgrades but nothing would happen. I merely tested the fuctionality in creative and thought it wouldn't be intentional because of the potential lag that might occur if you would scale it to the limit. I dont know how it would scale in comparison to mekanism. But it would save tps without random pathing entities. If its intentional game design im absolutely fine with not changing it tho :)

**Comment by YukkiPlays** [comment]
Talking about scaling horizontally, i am the author of this farm: https://www.reddit.com/r/allthemods/s/a9qFFSrwdn
I tend to scale things to the absolut limit. Thats why i wanted to resolve this if it was an accidental issue.

**Comment by JaisDK** [comment]
That's a nice looking farm :) good things you don't have trypophobia

I left it unsupported by sim upgrades so keep some balance as using sim upgrades basically makes the resource scaling infinite, plus I like that you have to have a few chunks irradiated at all time

**Comment by YukkiPlays** [comment]
Phahaha. I wouldn't be able to build there any longer :D
I thought about that as well. I like the idea with the irradiated chunks too. Is the simulator upgrade technically able to check for enviromental circumstances like irradiation or is it only working with the feeding slab?

**Comment by JaisDK** [comment]
I could probably make it’s work, but the way I have it now is that the bees need to take radiation damage, not just be in an irradiated area.

**Comment by YukkiPlays** [comment]
Ahh, i see. So it's coded in a way that instead of taking damage from radiation they progress in pollination and remove a little bit of mSv/h. Coding it based on the enviroment would be a completly different approach. Thank you for the insight. I'll try to make it work the intended way and close the issue. It would be a nice improvement if you get a notification when you try to insert a sim upgrade in a hive with wasted radiation bees c:

**Comment by JaisDK** [comment]
I wouldn't be against that, there's a lot of "problems" that could be displayed for the hive, but it's a bigger system which I don't have time to make now.

**Comment by YukkiPlays** [comment]
Well i would love to collaborate but my Java and Minecraft plugin knowledge isn't sufficient for this

**Comment by JaisDK** [comment]
You're always welcome to pop into the Discord server and give feedback if you like :)

I'm gonna close this.
