### ISSUE TITLE
1.20.1 Crashing after pressing Single Player

### ISSUE THREAD

**Issue by yanbotturahidaka** [JDKDigital/productive-bees#426]
After updating to Productive Bees 12.2.5 and loading either Extreme Reactors or Bigger Reactors, the game crashes after pressing the Single Player.

Minecraft Version: 1.20.1
Forge Version 47.2.1
Mod Version: 12.2.5

Bigger Reactors Files:
![Bigger Reactors Mod List](https://github.com/JDKDigital/productive-bees/assets/117532198/588ac9aa-2bac-465a-8c44-679468527f76)
Latest Log:
https://pastebin.com/BTpaCC69
Crash Report:
https://pastebin.com/5h42g715

Extreme Reactors Files:
![Extreme Reactors Mod List](https://github.com/JDKDigital/productive-bees/assets/117532198/3d068a42-5d40-4856-bdb0-b6df5d880375)
Latest Log:
https://pastebin.com/VKBQUkTF
Crash Report:
https://pastebin.com/LzmTwNzk

PS: Reverting back to version 12.2.4, works normal with both mods.

**Comment by JaisDK** [comment]
New version should resolve it

**Comment by yanbotturahidaka** [comment]
Tested here, it works fine. The issue now is just the bees and related blocks/items names:

https://github.com/JDKDigital/productive-bees/assets/117532198/ac7cecf1-0ccc-4c8a-b6c0-b6afbe5947fb

**Comment by JaisDK** [comment]
oopsie :D

**Comment by yanbotturahidaka** [comment]
Should i mark this as closed, since the main issue has been adressed? Or wait till the names get fixed aswell?

**Comment by JaisDK** [comment]
I'll try not to forget
