### ISSUE TITLE
Wasted radioactive bees not producing

### ISSUE THREAD

**Issue by dvdmcwilliams** [JDKDigital/productive-bees#428]
I have since 2 days ago, 2 wasted bees, inside adv beehive with expansion, 1 simulator upgrade and 3 productivity omega.
Since last 3 updates (updated all the 3 at once yesterday on the server I play), These bees stopped working at all. There is a constant amount of radiation around, but still they produce no combs. They have a feeding slab with poppies, tried many other flowers, with no luck at all. Is this a mod bug, or its just me doing something wrong?

**Comment by JaisDK** [comment]
You can’t sim them

**Comment by dvdmcwilliams** [comment]
> You can’t sim them

Well, I dont know if thats an option on the server I play on, but I could, they produced a lot of combs, but as I said before they stopped to do it.

**Comment by JaisDK** [comment]
You had them produce combs while inside a sim hive without them having been outside in radiation before getting in the hive?

**Comment by dvdmcwilliams** [comment]
> You had them produce combs while inside a sim hive without them having been outside in radiation before getting in the hive?

Yes, thats exactly what they were doing the last two days, then the server updated to the new last 3 versions (from 0.2.6 to 0.2.9 ATM9) and they stopped producing when using simulator.

**Comment by JaisDK** [comment]
Did you have a flowerblock for the bees?

**Comment by dvdmcwilliams** [comment]
> Did you have a flowerblock for the bees?

Poppies on a feeding slab.

**Comment by JaisDK** [comment]
that was a bug :D

all bees have their own flowering blocks and wasted needs to fly around in radiation, the bug was that all bees worked with flowers in a feeding slab
