### ISSUE TITLE
Adding compatibility with Minecolonies

### ISSUE THREAD

**Issue by Niduin** [JDKDigital/productive-bees#429]
The Forester from Minecolonies cannot chop the Nest - like Oak Nest - from the trees logs. Would it bee possible to add something like a option in the config, that the nest cannot spawn in specific trees ?

**Comment by JaisDK** [comment]
Don't have flowers near the tree farm

**Comment by Niduin** [comment]
well... when it is this simple - thank you :-D

Which radius for the flowers is needed around a tree that a nest cannot spawn?

**Comment by JaisDK** [comment]
it's a 2-3 blocks radius around the sapling that has to be clear of flowers

thinking about it, cherry leaves are considered flowers, so I can see an issue growing those

**Comment by JaisDK** [comment]
mangrove propagules are also flowers, which is just silly

**Comment by Niduin** [comment]
But Oak, birch, spruce, jungle are not?

**Comment by JaisDK** [comment]
No just the mangrove

**Comment by modsbydreamCritting** [comment]
Adding the nest blocks to a tag at data/minecolonies/tags/blocks/tree.json would allow the forester to chop them down as part of the tree.

**Comment by JaisDK** [comment]
I added them to minecraft:logs not too long ago which is included in the minecolonies tree tag.

**Comment by Devilswarchild** [comment]
> I added them to minecraft:logs not too long ago which is included in the minecolonies tree tag.

the forester still ignores them

**Comment by JaisDK** [comment]
well then there's nothing I can do about it, adding it to the tag should pass this check but if it's still not considered part of the tree then it's on them to fix
https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/core/entity/ai/workers/util/Tree.java#L146

**Comment by Devilswarchild** [comment]
> well then there's nothing I can do about it, adding it to the tag should pass this check but if it's still not considered part of the tree then it's on them to fix https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/core/entity/ai/workers/util/Tree.java#L146

ok started an issue thread with them linking back to this thread
