### ISSUE TITLE
Null Pointer Exception Fails To Load, Object Holder Issue

### ISSUE THREAD

**Issue by DDX5** [JDKDigital/productive-bees#43]
Crash Report: https://pastebin.com/EyNi6Z5v
Mods List: https://pastebin.com/iBJm3tRs
Minecraft Version: 1.16.1
Forge Version: Latest
Mod Version: 1.16.1-0..1.13
OS ,GPU,CPU: Windows 7 Pro, GeForce GXT 1050ti, AMD FX 6100 (6 Core)
Ram: 20GB Dedicated, 24GB installed.

Note: I Did Not Reailize SuperAxes And UnCraftables Were Fabric.

**Comment by JaisDK** [comment]
Hi,
This is not an issue with productive bees, but one of the other mods you have installed. Take a look at the latest.log instead of the crash log, it will show which mod is causing problems.
