### ISSUE TITLE
1.20.2-Crash On Startup ``Forge 48.0.34``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [JDKDigital/productive-bees#432]
productivebees-1.20.1-12.2.6

Fan fact - This what launchers are downloading on 1.20.2

https://gist.github.com/P3rf3ctXZer0/531c81d978f7706e172ec8372ee4ece3

**Comment by JaisDK** [comment]
I don't support 1.20.2

**Comment by P3rf3ctXZer0** [comment]
So fix your mod cause it is tagged for 1.20.2

**Comment by JaisDK** [comment]
![image](https://github.com/JDKDigital/productive-bees/assets/15868585/fc9c6dac-7fb4-4777-9c84-a2cc717fc9ab)
no it's not

**Comment by JaisDK** [comment]
I see Modrinth added that tag on it's own, so thanks Modrinth...
