### ISSUE TITLE
Exclusions from minecraft:flowers for nest spawning

### ISSUE THREAD

**Issue by Eidra** [JDKDigital/productive-bees#433]
Cherry leaves are tagged with **minecraft:flowers** causing undesirable nest spawns in tightly packed farms.

Would it be possible to add a config option to prevent specific blocks from allowing saplings to spawn nests, even if they're tagged with minecraft:flowers?

Or possibly some aggressive bee that would prevent nests from spawning in a radius around its hive?

**Comment by JaisDK** [comment]
In the next update I’ve blacklisted leaves and saplings as valid flowers but it might be a better idea to turn it into a tag.
