### ISSUE TITLE
[1.20] dragon bee with upgrades does not work

### ISSUE THREAD

**Issue by Lucky3228** [JDKDigital/productive-bees#434]
**Dragon bee**. With the improvement in the **Omega** and **Gamma** hive, it does not produce honeycombs
'productivebees:draconic' - bee
'productivebees:upgrade_productivity_4'  - Omega
'productivebees:upgrade_productivity_3' - Gamma

**Comment by JaisDK** [comment]
show your setup, the omega upgrade turns the hive into a sim hive so the flower block must be placed in the right spot

**Comment by Lucky3228** [comment]
![image](https://github.com/JDKDigital/productive-bees/assets/89595522/d765d8b9-6ec3-465f-bdf5-7dce27647c90)

**Comment by JaisDK** [comment]
sink the feeding slab into the ground and face all the entrances towards it

**Comment by Lucky3228** [comment]
Sorry, everything works
