### ISSUE TITLE
Suggestion: Ability to toggle or prevent Simulator Upgrade from being active in a hive

### ISSUE THREAD

**Issue by g45635g** [JDKDigital/productive-bees#435]
Wasted Radioactive Bees are incompatible with Simulator Upgrades, which seems to be intentional. However, because of this, it also makes them incompatible with Productivity Gamma and Productivity Omega, since those automatically apply Simulator Upgrades. What I wanted to suggest is for a way to toggle if Simulator Upgrade is active or not, or another way to prevent it from activating, so that these two upgrades could still be used with just the production output increases.

**Comment by JaisDK** [comment]
Wasted Bees are already powerful enough with simple productivity upgrades imo. If I add sim support or a way to toggle sim on the upgrades then I'll have to nerf the bees too.

**Comment by g45635g** [comment]
> Wasted Bees are already powerful enough with simple productivity upgrades imo. If I add sim support or a way to toggle sim on the upgrades then I'll have to nerf the bees too.

I think that's fair, yeah. If you do go with this, maybe a suggestion I can make is to not have them breedable? I think one of the major reasons they're as good as they are is because you only need to pray to the RNG Lords for two of them, then you can make as many as you want. Otherwise, I'd say things are best left as is then.

**Comment by JaisDK** [comment]
they're not breedable anymore, that was a mistake

it's only fixed for 1.20 though

**Comment by g45635g** [comment]
> they're not breedable anymore, that was a mistake
> 
> it's only fixed for 1.20 though

Odd, I'm using latest version of Productive Bees (1.20.1-12.2.7) and able to breed them just fine...
That being said, if more of a nerf is needed, maybe either the chance of getting a Wasted Bee or how much Nuclear Waste each Comb produces can be reduced? I think that would still make the upgrades worth using.
![2023-11-16_17 47 44](https://github.com/JDKDigital/productive-bees/assets/123435316/133143e5-928d-4f90-8217-4991c272bb4e)
