### ISSUE TITLE
1.20.1 Visual disappearance of vanilla bees

### ISSUE THREAD

**Issue by BloodInAs** [JDKDigital/productive-bees#436]
Vanilla bees visually disappear from the hive and it is not clear whether they are there or not,
Mods work correctly
`minecraft:bee`
`'productivebees:advanced_bamboo_beehive'
'productivebees:advanced_crimson_beehive'
'productivebees:advanced_birch_beehive'
'productivebees:advanced_oak_beehive'
'productivebees:advanced_acacia_beehive'
'productivebees:advanced_warped_beehive'
'productivebees:advanced_jungle_beehive'
'productivebees:advanced_dark_oak_beehive'
'productivebees:advanced_spruce_beehive'
'productivebees:advanced_snake_block_beehive' `
https://drive.google.com/drive/folders/1LHlL_LaZ3gctC6Z25uKBZid-_XenOc22?usp=sharing

Forge Version 47.2.1
minecraft 1.20.1
productivebees-1.20.1-12.2.4

**Comment by JaisDK** [comment]
Are the bees coming out and going back in as they should?

**Comment by BloodInAs** [comment]
yes, they function like mod bees, but sometimes you climb into a hive and there they are invisible

**Comment by JaisDK** [comment]
Don't know what's going on there, it doesn't happen for me. Can you try picking up the bees, break the hive and stick the hive in a crafting grid to reset it?
