### ISSUE TITLE
Draconic bees not producing after converting obsidian into crying obsidian

### ISSUE THREAD

**Issue by RikHov** [JDKDigital/productive-bees#439]
When having draconic bees in an advanced hive they can turn obsidian placed near the hive into crying obsidian. If this happens when more than one obsidian block is near, the draconic bees will stop producing honey and combs. I have not been able to consistently reproduce this with one obsidian block nearby, sometimes they stop sometimes not. I have been able to pretty reliably reproduce it with at least 2 obsidian blocks nearby. In 10 tests only 1 continued producing. Using more obsidian will make it more reliable.
Removing the obsidian blocks once this has happend will not fix the bees, you have to replace the hive.

Steps to reproduce
1. Place advanced oak hive
2. Place oak extension box on top
3. Place a dragon egg 1 block lower than the hive in front of the hive
4. Place 2 obsidian blocks either side of the dragon egg
5. Fill the hive with draconic bees
6. The bees will start to produce
7. Once they convert one of the obsidian blocks they will produce one last batch
8. The bees will now not produce anymore

Personally I think that if a bee tries to convert obsidian into crying obsidian, it gets locked into that state and wont produce anymore. If there is only 1 obsidian block there is a decent chance that one of the 5 bees will convert it before others have a chance to try. Hence why it can keep producing from a few bees, since a few wont be locked into that state. I think that the output from those hives were lower than my control hive, but I cannot say this for certain.
If you have an obsidian floor there will be enough obsidian for every bee to get locked for certain.

**Comment by JaisDK** [comment]
Thank you very much for your detailed description of the issue. I'll take a look at it soon as I can.
