### ISSUE TITLE
[Suggestion] user added bees

### ISSUE THREAD

**Issue by theboo** [JDKDigital/productive-bees#44]
would be super cool if we could add our own bees to the mod using .json (resourceful bees mod has something similar, but i love the way your mod does things xD)... would be super awesome for pack devs

**Comment by JaisDK** [comment]
I've considered it, but I don't think I'm gonna do it. I am planning on having a bee for most resources anyway and having the bees defined by json is either really limiting or requires a lot of specialized code for each "type" of bee that can be generated.
Once I am done adding bees, I might find that I can generalize them and switch to json, but for now it would just hinder the development.
If you have any more ideas for bee types or behavior then I am all ears! The boobee was fun to add :)

**Comment by theboo** [comment]
sounds good, thanks for the reply!
