### ISSUE TITLE
Summoning Configurable Bees with Entity Tags Generates Generic Bees

### ISSUE THREAD

**Issue by DumbXBoxAcct** [JDKDigital/productive-bees#440]
Hi - Fabulous mod!  Took me a little while to get the hang of it, but it is, hands down, the best way to generate resources and the addition of genetics makes it even better.

On to the issue: Using "Productive Bees" v.12.2.26, when I enter the command line "/summon productivebees:configurable_bee ~ ~ ~ {EntityTag:{type:"productivebees:diamond"}}" to try to summon a Diamond Bee,  what I get is a swarm of standard Minecraft bees.  Pretty much happens with any of the bees that use an Entity tag (Copper, Iron, Gold, etc.), the EntityTag seems to be totally ignored.  

I'm pretty sure that the syntax I'm using is correct, because it checks out correctly when I type it in and it actually produces a result, but it's possible that I'm missing something necessary to make it work right, so I hope that you can either correct me or let me know if there are any plans to fix it, if it's the mod.  BTW, configurable spawn eggs with Entity tags work just fine with the "/give" command, so you can get a Diamond Bee spawn egg, but you can't summon a Diamond Bee.

**Comment by JaisDK** [comment]
The command for summoning is different from the egg. 
- `/summon productivebees:configurable_bee ~ ~ ~ {"type":"productivebees:diamond"}`

**Comment by DumbXBoxAcct** [comment]
Hi Jais -Thank you for your quick response, I’ve been using that command to summon them, it’s that when I use it, a whole swarm of regular bees appears, instead of a diamond bee.- GordonOn Nov 22, 2023, at 1:38 AM, Jais Djurhuus-Kempel ***@***.***> wrote:﻿
The command for summoning is different from the egg.

/summon productivebees:configurable_bee ~ ~ ~ {"type":"productivebees:diamond"}

**Comment by JaisDK** [comment]
The command I wrote is different from the one you said you used, can you try with that one please.

**Comment by DumbXBoxAcct** [comment]
Right, you are, sorry that I didn’t notice that.Just used it an a couple of times and it summons a random number of regular bees plus the diamond bee but, hey, I got my diamond bee! Thank you for your help, I appreciate it!- GordonOn Nov 22, 2023, at 3:31 AM, Jais Djurhuus-Kempel ***@***.***> wrote:﻿
The command I wrote is different from the one you said you used, can you try with that one please.

**Comment by JaisDK** [comment]
Sounds like you have a mod that makes bees spawn in higher numbers

**Comment by DumbXBoxAcct** [comment]
Right again, I disabled “Realistic Bees” and now I just get a diamond bee.  I’m all set, thank you again for your prompt response and for all of your help, I really appreciate it.  Feel free to close this ticket out and my compliments, again, on an absolutely fabulous mod!- GordonOn Nov 22, 2023, at 10:26 AM, Jais Djurhuus-Kempel ***@***.***> wrote:﻿
Sounds like you have a mod that makes bees spawn in higher numbers
