### ISSUE TITLE
Nest not working

### ISSUE THREAD

**Issue by SunDrop73** [JDKDigital/productive-bees#442]
the honey treat doesn't work on the glowstone nest. Worked on the oak and i think it was a spruce one i triedbut not the glowstone one? Does it matter what biome it is in in the nether? Running it with ATM9

**Comment by JaisDK** [comment]
check in JEI what item you need for each nest, for glowstone nests it's glowstone not treats.

**Comment by SunDrop73** [comment]
Still right clinking it correct? because that just places the block of glowstone

**Comment by JaisDK** [comment]
glowstone dust

**Comment by SunDrop73** [comment]
oh i understand now. I thought that was for breeding them like in the breeding chamber. not for resetting the nests.
Thank you
