### ISSUE TITLE
1.20.1 stand bee cage spends all the bees at one time, but releases only one

### ISSUE THREAD

**Issue by Lucky3228** [JDKDigital/productive-bees#443]
This thing works with any bee, you just need a stable bee cage
Mod version:1.20.1-12.2.11
'productivebees:sturdy_bee_cage' - stable bee cage
'minecraft:dispenser' - dispenser
![image](https://github.com/JDKDigital/productive-bees/assets/89595522/b0db9d62-ef2a-48f2-b4e8-69fac36bf172)
![image](https://github.com/JDKDigital/productive-bees/assets/89595522/23a5403a-f030-4b61-9e85-6c465b4e53ee)
![image](https://github.com/JDKDigital/productive-bees/assets/89595522/d3d89a8f-6c3c-470c-b0e5-6a223a6ee706)

**Comment by JaisDK** [comment]
Thanks for reporting

**Comment by Lucky3228** [comment]
When it is fixed, write here?
