### ISSUE TITLE
Quartz enriched iron bee not producing (ATM9)

### ISSUE THREAD

**Issue by ferry3009** [JDKDigital/productive-bees#444]
I have 4 Quartz enriched iron bees in an advanced beehive. They wont produce a single comb. I've tried a feeding slab in front (1 block lower than hive entrance) with and without the simulation update. I've tried an iron block, and i've tried placing the blocks in the world with and without the simulation upgrade. The bee's will come out of the hive, dance around on the "flower block" or feeding slab, go in the hive, but when they come out they haven't produced any combs. Tried on a creative flatworld, didn't work either. Im clueless, please help xD

**Comment by JaisDK** [comment]
you need a quartz enriched iron block as flower if you want combs, the iron block it just tries to convert into quartz enriched iron at a 5% chance

**Comment by ferry3009** [comment]
What i meant was both conversion as well as comb production doens't work,

**Comment by Legorfyr** [comment]
Comb production you need a quartz iron block...
For conversion, well it is only 5% chance
Also, no need for a feeding slab with a block you can place.
