### ISSUE TITLE
All bees quit producing

### ISSUE THREAD

**Issue by PureMajor** [JDKDigital/productive-bees#445]
I have about 20 hives set up in the end, I afk over night and have no problems. However, randomly today they stopped working and wont go in there hive. Things I have done differently since my bee farm was set up: I created a steam engine from create mod and made a auto honey block machine

**Comment by JaisDK** [comment]
did you add any mods?

**Comment by PureMajor** [comment]
I am playing on all the mods 9

**Comment by JaisDK** [comment]
have you tried turning it off and on again? aka restart client and server (if you're on one)
