### ISSUE TITLE
Baby bees leaving simulated nests, even when there are only two in there

### ISSUE THREAD

**Issue by knzai** [JDKDigital/productive-bees#447]
Sorry if this is on purpose; I couldn't find a discord link anywhere to ask.

I''m playing FTB Genesis which has a mechanic that makes it quite obvious that all the babies are leaving my simulated nests, since they die off right away in the real world (modpack specific thing, not relevant except it makes it obvious that it is happening every time.

Anyway, maybe a bug, maybe intended?

**Comment by JaisDK** [comment]
it's sort of intended in the way that I didn't want to change it

do they die immediately or could you put a catcher down to catch them as they pop out?

**Comment by Nekosity12** [comment]
(Unrelated to "issue", but if you're still looking to join the discord for any future questions: https://discord.com/invite/x822BKu624)
