### ISSUE TITLE
[Suggestion] Don't add empty ingot tags

### ISSUE THREAD

**Issue by NillerMedDild** [JDKDigital/productive-bees#45]
Hi o/

The empty ingot tags that are in your datapack is making the mod JAOPCA believe those materials exist (tungsten & titanium) even though they don't. It produces some weirdness, so it'd be nice if it could be avoided :)

**Comment by JaisDK** [comment]
I'll see what I can do. I use the tags to check if they are empty, but I might not need to actually define them first.

**Comment by JaisDK** [comment]
Tags have been removed, hopefully it wont cause problems :)

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by NillerMedDild** [comment]
This didn't work I'm afraid, it's no longer possible to make a new world with productive bees in it, due to missing tags.
https://gist.github.com/NillerMedDild/56abe1b2acfe70719912a9c6355ae610

**Comment by JaisDK** [comment]
Could you post the latest.log as well?

**Comment by JaisDK** [comment]
Is it a server? and does it happen when you try to connect with the client? It looks like it happens during a recipe sync event, so let me just fire up a 1.16 server and check. You are running 1.16 right?

**Comment by NillerMedDild** [comment]
That is the latest.log, and it's just singleplayer :)
Yep 1.16, I should've specified that.

**Comment by JaisDK** [comment]
Usually there's a modlist at the end of the log when there's been a crash. Anyways, the tags it's complaining about are definitely mine, I can see a typo in there which I will fix as well. The stacktrace does not mention my mod though, only Rats mod
com.github.alexthe666.rats.client.event.ClientEvents.onOpenGui(ClientEvents.java:104), but I don't think that's the problematic area.
Are you playing Enigmatica 6? If not, can you provide a mod list?

**Comment by NillerMedDild** [comment]
It doesn't crash, it does not allow me to make a world due to datapack errors. Yep it's in Enigmatica 6, development branch though.

I'm fairly certain Productive Bees is the cause, as downgrading to the previous version fixed the issue :)

**Comment by JaisDK** [comment]
Got it reproduced with that modpack. Thank you for you time, now that I get the error too I should be able to figure it out.

**Comment by NillerMedDild** [comment]
And sorry for causing the issue :P

**Comment by JaisDK** [comment]
That's fine, it's far from the only tag problem I've had with 1.16 :)

**Comment by JaisDK** [comment]
Right, the tags are going back in. I'll open an issue with JAOPCA to not include recipes for empty tags if they can.
1.15.2 without tags is fine, but it's no good for the 1.16 version.

**Comment by JaisDK** [comment]
New version is up

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by NillerMedDild** [comment]
I don't think it's fixed, seems like the typo remains :P
https://gist.github.com/NillerMedDild/b0f181e999e21ce45149176e80b8110c

**Comment by JaisDK** [comment]
If at first you don't succeed, try try again :)

https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3011361

**Comment by JaisDK** [comment]
Of course after some sleep I figured out the problem and I can now remove the tags. Release will have to wait a little though

**Comment by NillerMedDild** [comment]
Awesome, nice one :)
