### ISSUE TITLE
Ars nouveau conflict?

### ISSUE THREAD

**Issue by Sultia** [JDKDigital/productive-bees#452]
MC version: 1.20.1
Mod version: 12.2.14
Modpack Orbit cycle
Log file lines 5550 - 5580
[latest.log](https://github.com/JDKDigital/productive-bees/files/13877809/latest.log)

Log file error that might shed light on something conflicting between the two mods

**Comment by JaisDK** [comment]
Do you have an amber bee near a starbuncle?
