### ISSUE TITLE
Possibility to stop generating wax/honey

### ISSUE THREAD

**Issue by Infarctus** [JDKDigital/productive-bees#453]
Either in the config file or an upgrade that would stop generating wax and/or honey.

I'm currently playing modded minecraft and I have 0 uses for the wax nor the honey. So I got pipes to void both wax and honey...

With some omega productivity upgrades I can confidently say that it makes the game more laggy (due to the sheer amount that's being transferred every tick) : it does not come from the bees but the transfer system that must be used to void both and keep productivity.

Would help the game and the comfort of the player if this could be removed.

**Comment by JaisDK** [comment]
You don't need to void the honey as it keeps running even when full.

**Comment by Infarctus** [comment]
If you wanna produce something else than honey, like experience, blood etc.
Unless you void them it doesn't produce it.
And I know what you're gonna say, make separate centrifuge for them.
But if I do I'll have to create filters and a different system which still generates lag (even more than the current one)

**Comment by JaisDK** [comment]
I honestly don't find a big problem with this. You're either using a shit pipe or a shit server or you're producing way more than you could every need. Neither of those are on my side to fix.

**Comment by Infarctus** [comment]
I'm not saying it's a big issue, but from what I have seen, it would not be too much trouble to just add this so that when you're building the centrifuge recipe it removes it, and player & server would (In my opinion) enjoy it more.

**Comment by JaisDK** [comment]
You can change the recipes with a datapack or kubejs and remove the wax easily.

**Comment by Infarctus** [comment]
I would have to reproduce every bee (like a 100) and set it up just to remove that ? I would not call that easily

**Comment by Infarctus** [comment]
If you just don't want to add it okay but don't propose solution that would take me hours.
I'm not the only one with this problem but everyone bears with it. (check reddit etc)

**Comment by JaisDK** [comment]
A little kubejs script doesn't take hours, making a configurable upgrade that voids items and fluids does however take a long time. I understand that you don't want the wax, there's quite a lot of it, but the problem is still with the pipe setup.

**Comment by Infarctus** [comment]
Due to the amount I'm currently producing (I have more than 25 bee nests with full omega upgrades and full bees and they're all needed) whatever mode of transportation I use it'll take some us/t that could be avoided with this config.
