### ISSUE TITLE
Ability to pipe upgrades into a hive

### ISSUE THREAD

**Issue by kevin-meyers** [JDKDigital/productive-bees#456]
Hello! I am playing ATM 9 and they have an insane quest that would require something like 500k bee hives 🤣 feasibility of making that happen aside, i noticed you can only pipe in cages and honey, and I checked the code and saw that is the case. If possible I think the ability to also pipe in upgrades or some kind of mechanism that makes automated applying upgrades possible would be very nice! 

https://github.com/JDKDigital/productive-bees/blob/69a12526399c71e015c8f4033cbba7c9051ad3e0/src/main/java/cy/jdkdigital/productivebees/container/AdvancedBeehiveContainer.java#L26

Let me know if you need any more info from me!

**Comment by JaisDK** [comment]
You can shift right click the upgrades into the hives.

I won't be making them pipeable though, the setup doesn't easily support that as I have a separate inventory handler for the upgrades.

**Comment by kevin-meyers** [comment]
Ah perfect! that is actually good enough for me and for anyone else who stumbles on this ticket, it does work with the player simulator 
![image](https://github.com/JDKDigital/productive-bees/assets/37648386/0796d3ec-c39b-44a8-9af0-cca188cee1f7)
