### ISSUE TITLE
Productive bees combs don't compact.

### ISSUE THREAD

**Issue by HeavyDeception** [JDKDigital/productive-bees#458]
I have kind of guessed why this is, but you can't compact PB combs with some mods like FS or Sophisticated storage compacting upgrade. And this is because they are shapeless recipes and not shaped and the Vannila ones are, the tags are all good its just that one thing lol.

Is there any way to change this in the upcoming updates?

**Comment by JaisDK** [comment]
If I change to shaped recipes it would work?

**Comment by HeavyDeception** [comment]
I think it would I know that both FS and SS look for Shaped 2x2 recipes and not shapeless.

**Comment by HeavyDeception** [comment]
I'm messaging the Sophisticated Storage/backpack guys about it but from my testing this would look like the case so far.

**Comment by JaisDK** [comment]
it's not that simple though since it's not a shapeless recipe right now, but a custom one that behaves like shapeless

I would need to redo all of that I suppose, something that will have to wait for 1.21

**Comment by HeavyDeception** [comment]
@JaisDK Ok I have an update because I have been testing out a few things. The info about Functional Storage drawer is wrong as it was user error that was causing that (I was getting second hand info) now as for the Sophisticated mods that and I quote "I am guessing they use nbt to differentiate between combs and compacting upgrade only really supports items without nbt."
So he's going to look into changing how the Upgrade works maybe, but it looks like you're fine. Sorry about the confusion on my part.

**Comment by JaisDK** [comment]
No worries, thanks for letting me know.
