### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by AndersGroeschel** [JDKDigital/productive-bees#46]
startup crashes both on version 1.15.2-0.1.14 and 0.1.13. I looked through the log and crash report and neither seemed to lead directly to this mod but when I revert to a previous version everything loads fine. I do have many other mods installed but productive-bees seems to be the problem

**Comment by JaisDK** [comment]
I need the latest.log to find out what's causing the crash

**Comment by AndersGroeschel** [comment]
[latest.log](https://github.com/JDKDigital/productive-bees/files/4928854/latest.log)

I know it looks like an issue with cooking for blockheads but I uninstalled it and still got a similar error

**Comment by JaisDK** [comment]
Try updating forge to the latest 31.2.31

**Comment by JaisDK** [comment]
I'm gonna rollback some code changes that only work on later versions of forge so it can run on the recommended version again, but for now, updating will fix it.

**Comment by AndersGroeschel** [comment]
Yeah updating forge worked. I should have thought of that, thanks!
