### ISSUE TITLE
Blazing bees crashing server: ticking entity

### ISSUE THREAD

**Issue by nemulittner** [JDKDigital/productive-bees#460]
Server has been repeatedly crashing due to "ticking entity error", narrowed the room down to my blazing bees. 

[crash-2024-01-20_06.14.35-server.txt](https://github.com/JDKDigital/productive-bees/files/14008100/crash-2024-01-20_06.14.35-server.txt)
[crash-2024-01-20_08.20.08-server.txt](https://github.com/JDKDigital/productive-bees/files/14008101/crash-2024-01-20_08.20.08-server.txt)
[crash-2024-01-20_16.44.04-server.txt](https://github.com/JDKDigital/productive-bees/files/14008102/crash-2024-01-20_16.44.04-server.txt)
[crash-2024-01-22_01.32.18-server.txt](https://github.com/JDKDigital/productive-bees/files/14008103/crash-2024-01-22_01.32.18-server.txt)

**Comment by JaisDK** [comment]
Is anything going on with those hives other than them just working away?

**Comment by nemulittner** [comment]
Nothing else happening with the hives, attempted removing the blazing
flowers (considered maybe the bees being on fire was causing the entity
error) but that only reduced the time between crashes. Server has been
working for 24 hrs seamlessly since removing the blazing beehive from my
system.
