### ISSUE TITLE
Comapatibility Issue: Bumblezone Royal Jelly

### ISSUE THREAD

**Issue by ShapiroDeluxe** [JDKDigital/productive-bees#461]
Hi! I had a strange occurrence recently regarding the compatibility between this mod, the Bumblezone and Extreme Reactors. I recently set up a server and had gotten to a point where I was using the bees that Extreme Reactors adds (e.g. the cyanite bee) to get Royal Jelly from their combs. Suddenly today the extreme reactor bees stopped producing royal jelly and instead produced regular honey! The royal honey output was also deleted from the JEI and replaced with regular honey. It seems like the compatibility got unplugged somewhere.

I'm not sure what happened between today and yesterday that deleted the interaction between these mods! I've been looking through the configs and the files here to see where this interaction happens, but I am having trouble finding any evidence of this interaction even existing. I am not a coder so any help is appreciated!

I also wanted to note that I've been enjoying the hell out of this mod and it's taken up most if not all of my minecraft return recently. It's a blast for bee enthusiasts like myself. 

Thanks ^_^

**Comment by JaisDK** [comment]
Hi,
I'm glad you're enjoying the mod. I haven't had any royal jelly production for any of the bees, the only compatibility I add with bumblezone is pollen production in the hive and that should still be there.

**Comment by ShapiroDeluxe** [comment]
Super strange! I'll turn to the bumblezone mod creator to see if they had anything to do with it. Thank you for the reply!
