### ISSUE TITLE
Vanilla Bees don't produce honeycombs with simulator upgrade

### ISSUE THREAD

**Issue by MikuLittle** [JDKDigital/productive-bees#464]
Playing All The Mods 9, version 0.2.39, vanilla bee's stop producing honeycombs when a simulator upgrade is applied.  Removing the simulator upgrade lets the bees touch the flowers around the hive and then continue on.

This is using an advanced oak beehive with its expansion box.

Picture of said beehive surrounded with cornflowers and Oxeye Daisies.

![image](https://github.com/JDKDigital/productive-bees/assets/35976954/9c5c433a-0f2a-4f0c-8316-220d841f70d5)

**Comment by JaisDK** [comment]
Only one flower counts and it’s the one in front of the hive. It needs to be 1 block further down
