### ISSUE TITLE
Unexpected items cause ticking block entity

### ISSUE THREAD

**Issue by hogbits** [JDKDigital/productive-bees#465]
I made a mistake while using the BaBee Incubator that caused a ticking block entity. 

**Steps to reproduce:**

1. In the first slot, place a caged bee (I used a leafcutter bee).
2. In the middle slot, I placed a treat with the diamond bee gene.
3. In the upgrade slots I placed 4 speed upgrades.
4. When the progress bar hit 100% the game with crash 

**Actual Results**

- Game crashed with the following error. https://mclo.gs/PD2LHJC

**Expected Results**

- Prevent the block from processing if there are no results or the results lead to an error.
- Create new block for creating spawn eggs, and restrict what items can be added. e.g. eggs.

**Comment by JaisDK** [comment]
you're behind in updates, it's already fixed
