### ISSUE TITLE
WannaBee vanishes upon entering Hive.

### ISSUE THREAD

**Issue by Rileythenerd** [JDKDigital/productive-bees#466]
A bug i discovered within ATM9.

I set up an amber block with a wither, and a WannaBee inside the hive.
The WannaBee exited as normal, flew around, flew back into the hive, but upon looking in the hive no bee was to be seen.
It's behaviour seemed just as normal as all bees.

Upon looking through all hives or catchers in my base, nothing was there either, leading me to conclude this is a bug.

Exterior and interior view of this setup provided below:

![2024-02-08_14 40 53](https://github.com/JDKDigital/productive-bees/assets/115500532/287e7d9c-08b8-487c-8a2e-08771dc31380)
![2024-02-08_14 41 00](https://github.com/JDKDigital/productive-bees/assets/115500532/233146bd-60e7-4213-8be5-0aaa97975687)

**Comment by JaisDK** [comment]
that's not gonna be easy to reproduce since there's no real difference between a wannabee and any of the other bees

has it happened multiple times and only for this bee?

if you break the hive and look at its tooltip, does it say it has a bee inside?

**Comment by Rileythenerd** [comment]
It's only happened with this specific bee, all others work as intended.
And upon looking at the tooltip of the broken hive, no, nothing inside.

I understand this is not an easy something to reproduce.
