### ISSUE TITLE
Farmer Bee crash

### ISSUE THREAD

**Issue by amrodir** [JDKDigital/productive-bees#467]
Hi, thank you for your mod.

Farmer Bee crashes the server randomly when harvesting any crop, vanilla included.
Log seem to point to "PamsHarvester"
Let me know if you need more info.
In the meantime my Farmer Bee's gonna take an unscheduled vacation : )

Crashlog attached.

[crash-2024-02-11_12.13.32-server .txt](https://github.com/JDKDigital/productive-bees/files/14232507/crash-2024-02-11_12.13.32-server.txt)

Ty and have a nice day

**Comment by JaisDK** [comment]
It could look the bee is trying to check for harvestables in an unloaded area, did you have them chunkloaded by themselves or at the edge of loaded chunks?

**Comment by amrodir** [comment]
No, I was right beside it when testing the crash on a fresh testing world, no force loaded chunks either.

**Comment by amrodir** [comment]
Hi, saw the fix in the changelog! Tyvm!
Farmer Bee is buzzing away happily crash free ever since!
