### ISSUE TITLE
If you use a Steady Bee Cell in the dispenser, only one bee will fly out

### ISSUE THREAD

**Issue by 4u4aaa** [JDKDigital/productive-bees#468]
If you use a Persistent Bee Cell in the dispenser, only one bee will fly out, but 1 stack of cells can contain a stack of bees.

**Comment by JaisDK** [comment]
which mod version are you using?

**Comment by 4u4aaa** [comment]
12.2.11

**Comment by JaisDK** [comment]
Update to latest and test all you other issues with the latest version to see if they've been fixed already.
