### ISSUE TITLE
Combs dont have an output

### ISSUE THREAD

**Issue by ScoutMaester** [JDKDigital/productive-bees#47]
Most of the production bee combs wont produce anything in the centrifuge. Running in Enigmatica 6 (0.1.17).

Applies to:
> Leaden, nickel, platinum, invar, tungsten, honey (vanilla), lapis, zinc, gold, amber, osmium, bauxite, radioactive, quartz, electrum, iron, steel, fossilised, brazen, withered, diamond, tin, titanium, emerald, silver, copper, bronze.

Working as intended:
> redstone, powdery, draconic, mamatic, bone, ender, milky, blazing, glowing, slimy, rotten,

**Comment by JaisDK** [comment]
Thanks for reporting. I've found the issue and will upload a new version soon.

**Comment by JaisDK** [comment]
0.1.15 should fix the issue
