### ISSUE TITLE
Encasing mob in amber.

### ISSUE THREAD

**Issue by Kiriao** [JDKDigital/productive-bees#471]
Hi,

Was playing ATM9 and trying to encase phantom but doesn't seem to work. how many minutes does it need to be encase?

Cause for the wither boss it encase in amber pretty fast.

And lastly, is it possible to encase ender dragon?

**Comment by JaisDK** [comment]
in the mod update from yesterday, both of those can now be encased

**Comment by Kiriao** [comment]
Oh forgot to mention that I updated the mod to the lastest version but amber bee doesn't seem to encasing phantom.

Haven't try on ender dragon yet

Edit : trying on ender dragon  but it seem in encasing in amber. I put a stasis chamber so that ender dragon wont move and I put the bee in a box near the dragon and not seem to working but it encasing the ender man instead

**Comment by JaisDK** [comment]
new version coming out now

**Comment by Kiriao** [comment]
It work now, but what drop does ender dragon get via wannabee

**Comment by JaisDK** [comment]
I don’t know, it depends on what other mods add to it

**Comment by LeeJiyong9999** [comment]
Now wannabees can work at phantom ambers. But they doesn't make any drops.
What's wrong? I'm playing latest version of this mod.
