### ISSUE TITLE
[Bug] Sim + sturdy bee cage 

### ISSUE THREAD

**Issue by Kiriao** [JDKDigital/productive-bees#472]
It keep crashing my client when i trying to pull out bee via sturdy bee cage, i using the basic sim upgrade and i'm using the lastest version.

it show "The game crashed whilst ticking block entity"

**Comment by JaisDK** [comment]
Do you have a crash report?

**Comment by JaisDK** [comment]
fixed in newest version

**Comment by Kiriao** [comment]
[crash-2024-02-18_19.36.27-server.txt](https://github.com/JDKDigital/productive-bees/files/14330122/crash-2024-02-18_19.36.27-server.txt)


Here the crash report, sry for late reply
