### ISSUE TITLE
Bees in Advanced Beehives are invisible

### ISSUE THREAD

**Issue by 5pHiNxX** [JDKDigital/productive-bees#473]
I've updated to version `productivebees-1.20.1-12.3.1.jar` and when it's night and all bees are in the advanced hives, the bees are invisible. If the sun rises the bees begin to work normally, but in the hive they are invisible and not interactable.

For example: this hive is full of bees, but they are not shown:
![grafik](https://github.com/JDKDigital/productive-bees/assets/287394/a034a81e-375b-4fe7-8d30-6bb3ea958454)

**Comment by 5pHiNxX** [comment]
ok, I was able to track it down further .. the hive seems not to update, if bees go out or in. After reconnecting at nicht, all bees are shown in their hives and after sunrise, the bees begin to work, but are still shown in the hive

**Comment by JaisDK** [comment]
do you have a mod list?

**Comment by 5pHiNxX** [comment]
<ul>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create">Create (by simibubi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/libipn">libIPN (by mirinimi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/journeymap">JourneyMap (by techbrew)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xnet">XNet (by McJty)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops">Pam's HarvestCraft 2 - Crops (by pamharvestcraft)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/notrample">No Farmland Trample (by LobsterJonn)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator">OpenBlocks Elevator (by vsngarcia)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric">Structure Essentials[Forge/Fabric] (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-gamerules">Adaptive Performance Tweaks: Gamerules (by Kaworru)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks">Sophisticated Backpacks (by P3pp3rF1y)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei">Just Enough Items (JEI) (by mezz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2">Applied Energistics 2 (by thetechnici4n)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib">SuperMartijn642's Core Lib (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config">Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider">ExtendedAE (by GlodBlock)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rftools-base">RFTools Base (by McJty)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cofh-core">CoFH Core (by TeamCoFH)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge">FTB Teams (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/architectury-api">Architectury API (Fabric/Forge/NeoForge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/shaders/complementary-reimagined">Complementary Shaders - Reimagined (by EminGTR)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures">Fusion (Connected Textures) (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/allthemodium">Allthemodium (by ATMTeam)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep">Just Enough Professions (JEP) (by Mrbysco)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/corail-tombstone">Corail Tombstone (by Corail_31)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/bossominium">Bossominium (by shaywsgu2)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2-wireless-terminals">Applied Energistics 2 Wireless Terminals (by Mari_023)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/geckolib">GeckoLib (by Gecko)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics">Applied Mekanistics (by ramidzkh)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mekanism-additions">Mekanism Additions (by bradyaidanc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/glodium">Glodium (by GlodBlock)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/trash-cans">Trash Cans (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/lootr">Lootr (Forge & NeoForge) (by Noobanidus)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/collective">Collective (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge">FTB Library (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/ambientsounds-remastered-sounds-pack">AmbientSounds Remastered Sounds Pack (by Lanixius)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rechiseled-fans">Rechiseled: Fans (by RedCraft86)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mekanism-generators">Mekanism Generators (by bradyaidanc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/waystones">Waystones (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/balm">Balm (Forge Edition) (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing">Industrial Foregoing (by Buuz135)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/vegan-delight">Vegan Delight (by ChriSimo)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks">Crafting Tweaks (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-utils">Farmer's Utils (by EndilCrafter)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated">More Overlays Updated (by RiDGo8)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/towns-and-towers">Towns and Towers (by Biban_Auriu)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/extreme-reactors">Extreme Reactors (by ZeroNoRyouki)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jade">Jade 🔍 (by Snownee)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sophisticated-core">Sophisticated Core (by P3pp3rF1y)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/productivebees">Productive Bees (by LobsterJonn)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/citadel">Citadel (by sbom_xela)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks">Mouse Tweaks (by YaLTeR)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge">FTB Essentials (Forge & Fabric) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees">Pam's HarvestCraft 2 - Trees (by pamharvestcraft)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/almost-unified">Almost Unified (by AlmostReliable)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer">Just Enough Resources (JER) (by way2muchnoise)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/zerocore">ZeroCore 2 (by ZeroNoRyouki)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended">Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-mekanism-multiblocks">Just Enough Mekanism Multiblocks (by gisellevonbingen)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty">Biomes O' Plenty (by Forstride)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-archaeology">Just Enough Archaeology (by LobsterJonn)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-delight">Farmer's Delight (by vectorwing)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/terrablender">TerraBlender (Forge) (by TheAdubbz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/everythingcopper">Everything is Copper (by LobsterJonn)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/merequester">ME Requester (by Relentless)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-xmod-compat">FTB XMod Compat (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease">Harvest with ease (by CrystalSpider)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/functional-storage">Functional Storage (by Buuz135)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/konkrete">Konkrete [Forge] (by Keksuccino)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops">Get It Together, Drops! (by bl4ckscor3)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cupboard">Cupboard (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork">AE Additions - ExtraCells2 Fork (by MasterYodAT9G)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rechiseled">Rechiseled (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-core">Adaptive Performance Tweaks: Core (by Kaworru)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay">Fast Leaf Decay (by olafskiii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge">AE2 Things [Forge] (by thetechnici4n)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ender-io">Ender IO (by crazypants_mc_the_second)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mega-cells">MEGA Cells (by ninety)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/immersive-armors">Immersive Armors [Fabric/Forge] (by Conczin)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core">Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/inventory-essentials">Inventory Essentials (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/additional-structures">Additional Structures (by XxRexRaptorxX)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cristel-lib">Cristel Lib (by Cristelknight)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ato">ATO - All the Ores (by ATMTeam)</a></li>
<li><a href="https://www.curseforge.com/minecraft/shaders/complementary-unbound">Complementary Shaders - Unbound (by EminGTR)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/pipez">Pipez (by henkelmax)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/redeco">Re:Deco (by oopsonlydelta)</a></li>
<li><a href="https://www.curseforge.com/minecraft/shaders/makeup-ultra-fast-shader">MakeUp - Ultra Fast | Shaders (by XavierFST)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge">FTB Ultimine (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge">FTB Chunks (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/shaders/sildurs-vibrant-shaders">Sildur's Vibrant shaders (by SildurFX)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next">Inventory Profiles Next (by mirinimi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/patchouli">Patchouli (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/allthecompressed">AllTheCompressed (by Pdiddy973)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jade-addons">Jade Addons (Forge) (by Snownee)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mekanism">Mekanism (by bradyaidanc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mekanism-tools">Mekanism Tools (by bradyaidanc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/alexs-mobs">Alex's Mobs (by sbom_xela)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/appleskin">AppleSkin (by squeek502)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/not-enough-gamerules">Not Enough Gamerules [Forge] (by Reikeb)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/journeymap-integration">JourneyMap Integration (by frankV)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/oculus">Oculus (by Asek3)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/curios">Curios API (Forge/NeoForge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-zoom-forge">Just Zoom [Forge] (by Keksuccino)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing-souls">Industrial Foregoing Souls (by Buuz135)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/flat-bedrock">Flat Bedrock (Forge / Fabric) (by Sunekaer)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/minecraft-dungeons-content">Dungeons Content (by mdechannel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/dungeon-and-taverns">Dungeons and Taverns (by Nova_Wostra)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge">Kotlin for Forge (by thedarkcolour)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/embeddium">Embeddium (by embeddedt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rechiseled-create">Rechiseled: Create (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/shaders/light-shaders">Light Shaders (by Atleeeet)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/titanium">Titanium (by Buuz135)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/additional-lanterns">Additional Lanterns (by SuperMartijn642)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/easier-sleeping">Easier Sleeping (by GeheimagentNr1)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mcjtylib">McJtyLib (by McJty)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib">SuperMartijn642's Config Lib (by SuperMartijn642)</a></li>
</ul>

**Comment by 5pHiNxX** [comment]
What I have changed between the version that worked an this version:


Added:
- Easier Sleeping (`EasierSleeping-1.20.1-2.1.3.jar`)

Updated:
- Almost Unified (`almostunified-forge-1.20.1-0.7.2.jar` -> `almostunified-forge-1.20.1-0.8.0.jar`)
- Applied Energistics 2 (`appliedenergistics2-forge-15.0.20.jar` -> `appliedenergistics2-forge-15.0.21.jar`)
- Collective (`collective-1.20.1-7.30.jar` -> `collective-1.20.1-7.31.jar`)
- Corail Tombstone (`tombstone-1.20.1-8.6.2.jar` -> `tombstone-1.20.1-8.6.3.jar`)
- MEGA Cells (`megacells-forge-2.3.1-1.20.1.jar` -> `megacells-forge-2.3.1-1.20.1.jar`)
- Mekanism (`Mekanism-1.20.1-10.4.5.19.jar` -> `Mekanism-1.20.1-10.4.5.19.jar`)
- Mekanism Additions (`MekanismAdditions-1.20.1-10.4.5.19.jar` -> `MekanismAdditions-1.20.1-10.4.6.20.jar`)
- Mekanism Generators (`MekanismGenerators-1.20.1-10.4.5.19.jar` ->`MekanismGenerators-1.20.1-10.4.6.20.jar`)
- Mekanism Tools (`MekanismTools-1.20.1-10.4.5.19.jar` -> `MekanismTools-1.20.1-10.4.6.20.jar`)
- Productive Bees (`productivebees-1.20.1-12.2.15.jar` -> `productivebees-1.20.1-12.3.1.jar`)

**Comment by JaisDK** [comment]
have you tried rolling back any of those updates to see if it's resolved?

**Comment by 5pHiNxX** [comment]
I'll give it a try and keep you updated

**Comment by 5pHiNxX** [comment]
So I tried removing every other mod and the problem still perists.
My current mods:
![grafik](https://github.com/JDKDigital/productive-bees/assets/287394/a866557f-8b9c-4f72-821f-d46add3d3e94)

**Comment by 5pHiNxX** [comment]
As you can see in this video, there is one bee outside the hive. When opening the hive, it shows another bee inside the hive. After some time the bee outside the hive goes inside but the hive itself still shows only one bee:
https://gyazo.com/658c031fc6266bea8d77ed0abbfe5395

**Comment by JaisDK** [comment]
I must have removed an update call somewhere, I'll take a look for next update

**Comment by condac** [comment]
Same issue for me. Running latest 1.20.1-12.2.15 file on modrinth and bees are not visible in hives.
