### ISSUE TITLE
Please add support for Tin from Create: Dreams & Desires

### ISSUE THREAD

**Issue by bauerwilhelm** [JDKDigital/productive-bees#474]
Hey there, 

the tin bee and all its products are already implemented very well but the heated mixing for the tin combs is missing. So far, tin comb is the only comb that requires the productive bees centrifuge while all other combs can be processed in a heated basin with a mixer. I'd be(e) super duper happy to see tin combs supported as well:)

JEI says, these are Productive Bees recipes, if it's a Create origin, please close :)

**Comment by JaisDK** [comment]
Unfortunately Create doesn't support tag output for recipes so I had to pick a specific mods tin as output and let packs overwrite it as needed. You could try installing this https://www.curseforge.com/minecraft/mc-mods/almost-unified as it might help. If it doesn't the only way is to overwrite the recipe with a datapack.
