### ISSUE TITLE
Productive Bees nests spawning in Create Tree farm causing the farm to stop

### ISSUE THREAD

**Issue by mcdodge34** [JDKDigital/productive-bees#476]
Basically description of the issue is in the title, The create tree farm doesn't count a bee's nest as a valid block that can be chopped down by its saws, which stop the farm from working correctly leaving a ton of bee's nests and bee's in my tree farm area.

Modpack : Direwolf20 1.20.1 version 1.12.1
Neoforge version : 47.1.84
Create version :  0.5.1f
Productive Bees version : 1.20.1-12.2.15
Let me know if you need more information

Also, I couldn't find any configuration in the config folder, so does your mod actually generate configuration files somewhere...

**Comment by JaisDK** [comment]
Remove any flowers near your tree farm

**Comment by mcdodge34** [comment]
In what kind of radius should I do that, I can do it but love to see beautiful landscape around when possible, but I can certainly clear out flowers and such if I know in what kind of area I need to do it, if my tree farm is in 1 chunk, should clearing the flowers in a 3x3 chunk around it work...

**Comment by JaisDK** [comment]
The saplings check 3 blocks away. 

Which version of the mod are you using?

**Comment by mcdodge34** [comment]
Ok so if no flowers are close, should be fine, seems to work now thanks and for version I stated it on my first post but it is Productive Bees version : 1.20.1-12.2.15

I never played with bees because of how tedious it was with Forestry mod, but maybe I'll do something this time, need a good video tutorial to learn how to work with them.

**Comment by JaisDK** [comment]
hah, I'm so used to people never writing what version they're on I completely missed it :D

Check the mod page on CurseForge, I linked some videos there.
