### ISSUE TITLE
ProsperiBee Refuse to Leave Hive

### ISSUE THREAD

**Issue by DerpyPandaKitty** [JDKDigital/productive-bees#477]
ProsperiBee will Enter the Hive then never come out not sure if this is an issue with this mod or Mystical Agriculture but i could really use to the help figuring how to fix this. 

Also this is Version 1.20.1

**Comment by JaisDK** [comment]
show a screenshot of your setup, sounds like you maybe blocked the entrance

**Comment by DerpyPandaKitty** [comment]
![2024-03-10_12 59 30](https://github.com/JDKDigital/productive-bees/assets/39655165/61db88b5-ef28-420c-b6c9-fd8b1c5b807a)
![2024-03-10_12 59 43](https://github.com/JDKDigital/productive-bees/assets/39655165/118fda72-fc4f-4e34-8318-2b4ae6c8e96d)
 here you go

**Comment by JaisDK** [comment]
doesn't look like it's blocked
is the bees maybe nocturnal or something? you can also hit the hive with a stick to force it out

**Comment by DerpyPandaKitty** [comment]
I managed to figure it out x.x apperently one of my upgrades acted like a simulator.
