### ISSUE TITLE
ATM9-NF Server just crash looping 

### ISSUE THREAD

**Issue by MunchyG** [JDKDigital/productive-bees#479]
all the mods 9 no frills server is just stuck crash starting
and all signs indicate it is a bees issue

[crash-2024-03-15_03.08.17-server.txt](https://github.com/JDKDigital/productive-bees/files/14606967/crash-2024-03-15_03.08.17-server.txt)
[crash-2024-03-15_03.04.40-server.txt](https://github.com/JDKDigital/productive-bees/files/14606976/crash-2024-03-15_03.04.40-server.txt)
[crash-2024-03-15_03.02.30-server.txt](https://github.com/JDKDigital/productive-bees/files/14606983/crash-2024-03-15_03.02.30-server.txt)

**Comment by JaisDK** [comment]
You are 5 versions behind on Productive Bees. Try to update first as I think it's already fixed.

**Comment by MunchyG** [comment]
yep that fixed it, guess i shall go report on ATM9 page that they need to update the mod in the pack
