### ISSUE TITLE
Dupe upgrade

### ISSUE THREAD

**Issue by BazZziliuS** [JDKDigital/productive-bees#480]
Shift + right mouse button with hive improvements in the hand, the hive causes a dup of improvements since everything in the hand is put in, but only 1 is taken

productivebees-1.20.1-12.4.2

![javaw_VzGSpRL7vY](https://github.com/JDKDigital/productive-bees/assets/18011884/9c0ac0c9-e5a8-4cf3-a934-b75e807b8259)

**Comment by Gaute945** [comment]
I was gonna report the same issue, this makes it really annoying to put upgrades into multiple hives

**Comment by JaisDK** [comment]
update to 1.20.1-12.4.3
