### ISSUE TITLE
GregTech bees broken crafts

### ISSUE THREAD

**Issue by Snakedon** [JDKDigital/productive-bees#481]
1) Cobaltite bee spawn egg don't craftable in GT mixer.
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/f39f68d0-1893-4940-b658-758eb8fbacb6)
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/f43261a5-e671-412c-b17f-f80c8588538b)
2) Pyrochlore Bee Spawn Egg - to get a bee, he writes to watch the crafting of spawn eggs, but there is no crafting as such.
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/7875310c-6fa1-436c-b690-4a814462e3db)

**Comment by Legorfyr** [comment]
1) Is it the correct programmed circuit ?
2) Yes, that's known, fix next update.

**Comment by Snakedon** [comment]
> 1. Is it the correct programmed circuit ?
> 2. Yes, that's known, fix next update.

1. in jei shows 1 programmed circuit; I tried everything possible circuit, and it doesn’t work(
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/ab79c4a9-153f-4bb5-b676-94ae2d0f5eb8)
2. thanks)

**Comment by Legorfyr** [comment]
Yeah, so the mixer recipes refuse to work, so I remade them for the alloy smelter and those should be in next update.

**Comment by Snakedon** [comment]
thanks)

**Comment by Snakedon** [comment]
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/f928b045-e970-4b08-87ff-70ba01f32874)
neodymium bee too not craft spawn egg((

**Comment by Legorfyr** [comment]
I hate GT xD stupid blast furnace refuses certain temps.

**Comment by Snakedon** [comment]
)))))) GT is great)))
