### ISSUE TITLE
comb

### ISSUE THREAD

**Issue by Snakedon** [JDKDigital/productive-bees#482]
No craftable in centrifuge:
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/7d80187a-152d-4c90-8a51-c334c378e0a7)
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/7cf6435f-4eba-418e-9236-5ef755adeeda)
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/e7842a2a-d798-4f2d-8eac-2bbdba87e245)
I guess I checked all the honeycombs, the rest can be crafted.
Sorry for bothering()

**Comment by Legorfyr** [comment]
Hyper xp is on purpose

**Comment by JaisDK** [comment]
the other two will be fixed in the next version

**Comment by Snakedon** [comment]
thanks)
