### ISSUE TITLE
Restrict Wannabee

### ISSUE THREAD

**Issue by BazZziliuS** [JDKDigital/productive-bees#484]
I suggest adding a blacklist for Wannabee as it is quite unbalanced

**Comment by JaisDK** [comment]
like this one? https://github.com/JDKDigital/productive-bees/blob/dev-1.20.0/src/main/resources/data/productivebees/tags/items/wannabee_loot_blacklist.json

**Comment by BazZziliuS** [comment]
Tell me how to use it
Do I need to go into the mod and change it there, or has this setting been moved somewhere?

**Comment by JaisDK** [comment]
It’s a tag not a setting, works like vanilla tags.
