### ISSUE TITLE
[Bug] Doubling up a Feeding Slab voids contents of the first slab

### ISSUE THREAD

**Issue by Mrminesheeps** [JDKDigital/productive-bees#485]
Exactly as the title states, the version of Prod Bees in the latest ATM9 pack version has this bug. Was putting another slab under the one with my Allthemodium metal bees and the blocks inside the slab got voided. Breaking did not return the items.

**Comment by JaisDK** [comment]
which version of the mod are you on?

**Comment by Mrminesheeps** [comment]
> which version of the mod are you on?

Version 12.4.2
