### ISSUE TITLE
GregStar bee

### ISSUE THREAD

**Issue by Snakedon** [JDKDigital/productive-bees#487]
Only honey can be crafted from GregStar honeycombs, although GregStar fragments should also be
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/8647b2b6-7e59-4c73-8d6c-6ba39cc76a4f)
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/a4f368e4-84bf-4b7a-a393-a705c8fe64dd)
![image](https://github.com/JDKDigital/productive-bees/assets/48630889/905827bc-e5dd-4076-bdc0-48391a659879)

**Comment by JaisDK** [comment]
it's on purpose
