### ISSUE TITLE
Kamikaze bees cause damage to players in foreign regions

### ISSUE THREAD

**Issue by ArtemMASTER** [JDKDigital/productive-bees#488]
n other people's privates, if a player hits you (while you are wearing this helmet), kamikaze bees will fly out, capable of causing damage to players in their private when the PvP flag is turned off.

Metas:
```Item.of('productivebees:bee_nest_diamond_helmet', '{Damage:0}') - Bee's Nest Helmet```

https://www.youtube.com/watch?v=WlkKHvuyfl4

**Comment by JaisDK** [comment]
why is the other player able to hit you if PvP is turned off?

**Comment by ArtemMASTER** [comment]
Players not added to the region may be beaten. PvP is disabled. You cannot defeat players added to the region.

**Comment by JaisDK** [comment]
which mod is responsible for that?

**Comment by ArtemMASTER** [comment]
plugin world guard

**Comment by JaisDK** [comment]
I can't do anything about a plugin, it lives outside the mod world.

**Comment by ArtemMASTER** [comment]
Ok. Thank you
