### ISSUE TITLE
Crash On Launch: Registry Object 'sugar_cane_nest' was not found.

### ISSUE THREAD

**Issue by Keskas32** [JDKDigital/productive-bees#49]
Latest.log is attached.
[latest.log](https://github.com/JDKDigital/productive-bees/files/4945012/latest.log)

**Comment by JaisDK** [comment]
Hello,
The problem is from Bookshelf, you need to update to Bookshelf 6.0.2

**Comment by JaisDK** [comment]
or just latest, 6.0.2 was the one that fixed the issue

**Comment by MorePortal** [comment]
I have this issue without Bookshelf:
[log.txt](https://github.com/JDKDigital/productive-bees/files/4993517/log.txt)

**Comment by JaisDK** [comment]
You have a problem with forbidden_arcanus and a whole bunch of other mods. I recommend installing forge 32.0.75 as .93 has broken a lot of mods.
