### ISSUE TITLE
Bees are upside down and not working correctly

### ISSUE THREAD

**Issue by Koalitions** [JDKDigital/productive-bees#494]
Hello, I'm playing Mods on ATM9. The version of the Productive Bee mod was 12.4.3 when the bug occurred. Then I updated the ATM9 mod pack and Productive Bee went to version 12.4.4.

Unfortunately, it's no longer possible to play the mod.

BUG:
The bees are upside down. They fly with their heads upside down. It seems they continue to gather ressources, but it's impossible to interact with them. They are not attracted to flowers held in hand and cannot breed.

Vanilla bees are not affected.

BUG CONDITIONS : 
I went to the Nether to capture Glowing Bees with Glowstone nests. I had 5 hives.

I captured 4 as they exited the hive. For the last one, I heard it pop, but I didn't see it.

I returned to the Overworld, and all my bees were upside down.

![Bees 1](https://github.com/JDKDigital/productive-bees/assets/137525551/e5d90aa0-42ff-4bb3-b5e2-3601b72c8a00)
![Bees 2](https://github.com/JDKDigital/productive-bees/assets/137525551/6a5e74d0-1740-4c13-9d51-09a49c7996fe)

**Comment by Legorfyr** [comment]
Happy April Fools :D
