### ISSUE TITLE
Productive Bees Combs not showing where you get them in JEI

### ISSUE THREAD

**Issue by realBritakee** [JDKDigital/productive-bees#496]
I have an issue with productive bees 1.19.2-0.10.7.2 if i click on a comb (see picture) is see this and i have no idea why i didnt changed anything in item filters i dont even know there is a config or so any advice what it could be i have a large modpack running wit 500+ mods and dont get anny error message or anything in the logs 

![image](https://github.com/JDKDigital/productive-bees/assets/127439938/8ea18248-bd73-4bf0-b7e0-f2a59a50061b)

[latest.log](https://github.com/JDKDigital/productive-bees/files/15049330/latest.log)
[client.log](https://github.com/JDKDigital/productive-bees/files/15049332/client.log)
[server.log](https://github.com/JDKDigital/productive-bees/files/15049333/server.log)
[startup.log](https://github.com/JDKDigital/productive-bees/files/15049334/startup.log)

**Comment by JaisDK** [comment]
You say it's 1.19 but the latest.log says 1.20.1. Did you send the wrong log?

**Comment by realBritakee** [comment]
sry got ill and needed to go to hospital im back now and yeah i sended the wrong log excuse me i send the new generated here now these are the logs from my 1.29.3 pack i also got a 1.20.1 pack i will try there if it also is the same

![image](https://github.com/JDKDigital/productive-bees/assets/127439938/318a035b-94c7-44a7-b140-2435976a4c93)


[latest.log](https://github.com/JDKDigital/productive-bees/files/15127578/latest.log)
[server.log](https://github.com/JDKDigital/productive-bees/files/15127580/server.log)
[startup.log](https://github.com/JDKDigital/productive-bees/files/15127581/startup.log)
[client.log](https://github.com/JDKDigital/productive-bees/files/15127582/client.log)

**Comment by JaisDK** [comment]
try taking out Essential
