### ISSUE TITLE
Advanced beehive seems to lose its slot for cages

### ISSUE THREAD

**Issue by mberlin1** [JDKDigital/productive-bees#498]
I'm unsure what precipitated this. using modern's monumental modpack (1.20.1), for some reason the slot that used to hold the cages is not visible. While you can put the cages into the slot, they no longer function -- bees cannot be removed or added this way.  Bees can still enter and exit the hive, but there's no way to do it in a simulated hive other than letting each one come out and chasing after it to capture. Putting bees into the hive nets the same problem: The bee may house itself in a hive that doesn't have its food source (simulated hives)

See images attached.
![2024-04-25_12 34 46](https://github.com/JDKDigital/productive-bees/assets/3492348/05df502b-c638-4bd2-be4b-8d8b32b3c13f)
![2024-04-25_12 34 41](https://github.com/JDKDigital/productive-bees/assets/3492348/8e414cbd-960f-4868-a69f-c24d58709eb5)

**Comment by JaisDK** [comment]
you need an expansion box on the hive and a sim upgrade in there for that slot to show

**Comment by mberlin1** [comment]
Sir this is just an example
here's exactly teh same probelm with the expansion box.

![2024-04-25_13 48 16](https://github.com/JDKDigital/productive-bees/assets/3492348/6014bde8-e4c6-4cf8-b6c0-9ca8279349cf)

**Comment by mberlin1** [comment]
and here's the sturdy cage with a skeletal bee sitting in it, doing absolutely nothing
![2024-04-25_13 50 21](https://github.com/JDKDigital/productive-bees/assets/3492348/a7fb3560-27ce-443e-9a20-f2169fdc16d6)

**Comment by JaisDK** [comment]
you're still missing the simulation upgrade
