### ISSUE TITLE
Advanced beeehive no longer works

### ISSUE THREAD

**Issue by mberlin1** [JDKDigital/productive-bees#499]
I'm unsure what precipitated this. using modern's monumental modpack (1.20.1), for some reason the slot that used to hold the cages is not visible. While you can put the cages into the slot, they no longer function -- bees cannot be removed or added this way. Bees can still enter and exit the hive, but there's no way to do it in a simulated hive other than letting each one come out and chasing after it to capture. Putting bees into the hive nets the same problem: The bee may house itself in a hive that doesn't have its food source (simulated hives)

(now with expansion box attached, because that was never the problem)
![2024-04-25_13 48 16](https://github.com/JDKDigital/productive-bees/assets/3492348/9d30c8c8-86cd-4ccd-9ba4-200916e2d8f2)
![2024-04-25_13 49 59](https://github.com/JDKDigital/productive-bees/assets/3492348/4b9a893e-c4a0-4b1b-8680-03ba52ec9f57)

As you can see, the filled sturdy cage sits in its slot doing nothing.

**Comment by JaisDK** [comment]
you need an expansion box and a sim upgrade for that slot to show up
