### ISSUE TITLE
Bee Cage Disappearing

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#5]
When using a bee cage, the cage is removed from my inventory buy no cage with a Bee is added.

Nothing is added to the log on the server or the client. However this appears to work fine for my GF who is playing with the exact same config (as we copy paste our Minecraft builds between each other).

**Comment by JaisDK** [comment]
Can you please post a mod list and do you have a full inventory? The cage is only supposed to disappear after the bee has been release again.

**Comment by mouse0270** [comment]
I purposely even emptied my inventory so the only thing I was carrying was the bee cage. We have tried to keep the mod list fairly short around 50 or so mods, but here is a list of every mod we are running. I would also like to point out that my GF Minecraft all of the sudden started doing this about an hour or so ago.

```
AppleSkin-mc1.15.2-forge-1.0.13.jar
AttributeFix-1.15.2-7.0.2.jar
AutoRegLib-1.5-40.jar
backpacked-1.4.1-1.15.2.jar
beesourceful-1.1.1.jar.disable
BetterAdvancements-1.15.2-0.1.0.96.jar
betterbedrockgenerator-1.15.2-0.0.6.jar
Bookshelf-1.15.2-5.5.33.jar
buzzierbees-1.4.jar
Charm-1.15.2-1.5.7.jar
CHAS v1.3 for 1.15.jar
Clumps-5.0.2.jar
corail_woodcutter-1.1.3-1.15.2.jar
DoubleSlabs-1.15-2.2.7.jar
enchantable-1.3.0-1.15.2.jar
EnchantmentDescriptions-1.15.2-2.0.8.jar
FastFurnace-1.15.1-3.0.0.jar
FastLeafDecay-v22.jar
FastWorkbench-1.15.1-3.0.0.jar
furniture-7.0.0-pre16-1.15.1
glasscutter-1.0.1-1.15.2.jar
goldenhopper-1.1.1-1.15.2.jar
Hwyla-forge-1.10.8-B72_1.15.2.jar
itnc-1.0.8.jar
janoeo-3.4.jar
jei-1.15.2-6.0.0.4.jar
journeymap-1.15.2-5.7.0b2.jar
JRFTL [1.15.2]-1.1.jar
Kottle-1.5.2.jar
Ma-Essentials-1.15.2-3.0.3.jar
MixinBootstrap-1.0.3.jar
MouseTweaks-2.13-mc1.15.1.jar
NetherPortalFix_1.15.2-6.0.2.jar
obfuscate-0.4.3-1.15.2.jar
OptiForge-MC1.15.2-0.1.17.jar
phosphor-forge-mc1.15.2-0.5.2+build.4.jar
Placebo-1.15.2-3.0.2.jar
PrettyPipes-1.3.0.jar
preview_OptiFine_1.15.2_HD_U_G1_pre15.jar
productivebees-1.15.2-0.1.3.jar
Project MMO-1.15-2.30.10.jar
QuarkOddities-1.15.2.jar
Quark-r2.1-235.jar
randompatches-1.15.2-1.21.1.2.jar
redpandas-1.15.2-1.0.2.jar
slabsstairswalls-0.3.jar
StorageDrawers-1.15.2-7.0.2.jar
Strange-1.15.2-1.0.0-beta.3.jar
timber-1.15.2-1.5.jar
torchslabmod-1.15.2_v1.6.8.jar
vehicle-mod-0.43.5-1.15.2.jar
Waddles-1.15.2-0.8.6.jar
```

**Comment by JaisDK** [comment]
Do you know which bee you are trying to catch?

**Comment by mouse0270** [comment]
We replicated this issue with both magmatic, ender, diamond and zombie bees... I am pretty sure once it starts happening it wont let you catch any bee. Not sure if this helps, but I we both just game back from the End?

And if I remember correctly, mine started happening after I returned from the nether, I don't think she ever went to another dimension until we just went to the end.

**Comment by JaisDK** [comment]
I am having trouble reproducing this error. Can you send me a log from the time you were experiencing the issue? Maybe there's an error in there that was not bad enough to crash the game.

**Comment by JaisDK** [comment]
Can't reproduce. If it still happens in the newest version let me know.
