### ISSUE TITLE
Centrifuge recipes not available 

### ISSUE THREAD

**Issue by TH3P1NK5T3R** [JDKDigital/productive-bees#500]
I am unable to add the combs to the input portion of the centrifuge. Also taking a look at JEI the centrifuge recipes are nowhere to be seen. Just earlier in the day (as of making this post) I was playing the game with no problem, so I'm not sure what may have caused this. I have already tried reinstalling the mod (as well as all of the other mods in this modpack).

![uncentrifugable (prosperibee)](https://github.com/JDKDigital/productive-bees/assets/105680957/1f8f4c21-98ba-45e4-a157-af174eafd049)
![uncentrifugable (draconic)](https://github.com/JDKDigital/productive-bees/assets/105680957/97d2624d-52d9-4170-b594-ba09acc4e64f)
![uncentrifugable (diamond)](https://github.com/JDKDigital/productive-bees/assets/105680957/0d5bd52d-d41b-40f2-a11e-0c43f9f47e2b)

https://github.com/JDKDigital/productive-bees/assets/105680957/b2f2452e-3826-473d-9671-648c7fa8e72c

**Comment by JaisDK** [comment]
what happened between earlier and now? did you update or add any mods? are you playing on a server and if so, does it work in single player?

**Comment by TH3P1NK5T3R** [comment]
This is all purely single player. I had very briefly added then removed two mods (Embeddium/Rubidium Extras and TexTrue's Embeddium Options) to show someone else a conflict between just those two, but I wasn't even able to fully open the modpack because of the conflict screen. I had been playing the modpack just fine with those two mods disabled beforehand.

UPDATE: I checked for updates again on ATLauncher and PotionBlender needed an update. This seemed to have fixed the issue. I apologize for any inconveniences.
