### ISSUE TITLE
Issue with JEI

### ISSUE THREAD

**Issue by Faithish2002** [JDKDigital/productive-bees#502]
Hi I am having issues with the JEI for productive bees. I have 188 other mods including MCA which I saw has been a previous problem before. When I first made this modpack I had no issues then all of the sudden all the info on JEI for the productive bee's mod was gone? I have tried older versions, and nothing has worked. Am I doing something wrong?

**Comment by JaisDK** [comment]
It's just not compatible with MCA. You can go tell them to fix their mod.
