### ISSUE TITLE
Missing recipe for advanced beehives

### ISSUE THREAD

**Issue by schmitzrj** [JDKDigital/productive-bees#504]
I just started with this mod and it is so great! Thanks for making it! I've just had a little trouble with the Advanced Beehive. I'm missing the recipe. I have two recipes for beehives in the interface in separate places, and I can only make the advanced beehive by placing the items in the crafting grid manually, so I wonder if there is a bug with the advanced beehive recipe. I'm running Minecraft Java 1.20.1 and Forge 1.20.1 with version 12.5.1 of the Productive Bees mod. Thanks again!

**Comment by JaisDK** [comment]
Do you mean the recipe is working but it's not showing in JEI?

**Comment by schmitzrj** [comment]
It is working and it shows up in JEI, but I can't find it in the regular crafting interface or recipe list. Instead, the regular crafting interface has two recipes for regular beehives, but I don't know if that is related or not.

**Comment by JaisDK** [comment]
The crafting book? That one is usually disabled in mod packs so I don’t pay attention to it. The recipe should show once you’ve crafted it once I think, but it’s not something I’ve used.

**Comment by schmitzrj** [comment]
That makes sense. I'm new to JEI and still use the crafting book for most things, but I guess I need to switch. I've searched the crafting book for the advanced beehive and it is not there even though I've made several. Feel free to close this if you want since it works with JEI. Thanks for your help!
