### ISSUE TITLE
bee model

### ISSUE THREAD

**Issue by MxDeath** [JDKDigital/productive-bees#508]
Sorry to bother, is it possible for one to add another bee model? I was messing around trying to figure it out yet my bee is just invisible, the log doesn't say anything relating to the bee and im quite at a loss. I would appreciate any help 
[latest.log](https://github.com/user-attachments/files/15911411/latest.log)
![strawbee](https://github.com/JDKDigital/productive-bees/assets/85132045/4cd3d74d-0db2-4991-adb9-c27a7512920d)
[strawb.json](https://github.com/user-attachments/files/15911414/strawb.json)

**Comment by Legorfyr** [comment]
You don't need the line: "renderer": "productivebees:models/entity/bee/Strawbee",
Without that line it will then use the base minecraft bee model and overwrite the skin, which should be fine enough.

**Comment by MxDeath** [comment]
![bee](https://github.com/JDKDigital/productive-bees/assets/85132045/6e3da681-da22-4c34-8a03-1c3b3a1c1860)
![Screenshot 2024-06-20 190630](https://github.com/JDKDigital/productive-bees/assets/85132045/304c75fc-548a-499a-8dc2-68981208fc70)
That worked! do you happen to know how to fix this so it forms correctly

**Comment by Legorfyr** [comment]
For that you'll probably have the find the sweet spot in the png for it to render, that I don't know xD

**Comment by JaisDK** [comment]
you want a stalk sticking out of the back?

you could try using `"renderer": "default_foliage",`
you can see the texture area for the sticky-up it on this texture https://github.com/JDKDigital/productive-bees/blob/dev-1.20.0/src/main/resources/assets/productivebees/textures/entity/bee/base/default_foliage/bee.png

**Comment by MxDeath** [comment]
loading in the render for foliage along with your base and the bee still comes up invisible, im not quite sure why if its something im doing wrong or something with the render

**Comment by MxDeath** [comment]
again nothing in the logs that i can see

**Comment by JaisDK** [comment]
show the bee file again

**Comment by MxDeath** [comment]
i found my mistake! running back here i saw i had "default:foliage" instead of "default_foliage" i just have to edit my texture a bit and i should be good to go. 

man i really am not good at this xD i had ideas for particle/animation affects now im thinking maybe i should cut back on that. Thank you so much for your help though!

**Comment by JaisDK** [comment]
I think the bee is very cute. There's a couple of different particle types you can use for when the bee is pollinated, "lava", "pop", "rising" and "portal" as well as the color for it.

```
  "particleColor": "#fcd979",
  "particleType": "lava",
```

**Comment by MxDeath** [comment]
![Screenshot 2024-06-21 211943](https://github.com/JDKDigital/productive-bees/assets/85132045/ab025427-135e-4532-92ce-95577d1986f3)
i have yet to fix up the texture yet, but it works! the bee has the stem now! Thanks for helping and the headsup on the particles!
