### ISSUE TITLE
NeoForge 1.21 bugs

### ISSUE THREAD

**Issue by aAndrew3030** [JDKDigital/productive-bees#510]
Found two bugs so far, 1st, the breeding chamber is crashing the game when it finishes and attempts to create the bee (unable to reopen the world)

Cannot invoke "cy.jdkdigital.productivebees.util.GeneValue.getValue()" because the return value of "java.util.Map.get(Object)" is null

[debug.log](https://github.com/user-attachments/files/16045030/debug.log)

2nd, the bee cages do not capture bees in the nether (not sure about the end), but they work normal in the overworld

NeoForge is .42

**Comment by JaisDK** [comment]
is it a new world on 1.21 or one from 1.20.1?

**Comment by JaisDK** [comment]
found the breeding problem, will put up a new version soon

**Comment by aAndrew3030** [comment]
also, forgot nests do not drop blocks when mined

**Comment by aAndrew3030** [comment]
The update fixed those issues, thanks!

One more issue I found, the recipe for the advanced beehive is broken
![Screenshot 2024-07-01 142055](https://github.com/JDKDigital/productive-bees/assets/84727133/2dacfbec-8bee-4de7-a30a-535b7d28f545)

**Comment by aAndrew3030** [comment]
Using version .2 and NeoForge .43, I am experiencing very random crashes with bees in a advanced hive. I am using the gene upgrade and have a Mekanism pipe extracting into a vanilla chest. 

[crash-2024-07-02_00.07.28-server.txt](https://github.com/user-attachments/files/16061673/crash-2024-07-02_00.07.28-server.txt)

**Comment by aAndrew3030** [comment]
It seems to be the gene sampler upgrade that is causing the crash, when it is trying to output one of the samples

**Comment by aAndrew3030** [comment]
another small one, feeding slab dupes when breaking

https://github.com/AllTheMods/ATM-10/issues/55

**Comment by JaisDK** [comment]
At least it doesn’t dupe the inventory

**Comment by aAndrew3030** [comment]
Has the chance to get a ancient bee always been 1%? If that is not a bug it should be 😆

**Comment by aAndrew3030** [comment]
Are all bee conversions supposed to be 1%?

**Comment by JaisDK** [comment]
that's probably a display thing in JEI, I changed the chance from int to float so 1 means 100%

**Comment by aAndrew3030** [comment]
I right clicked a entire stack of netherite blocks on a diamond bee and it did not convert (haven't tried converting other bees)

**Comment by aAndrew3030** [comment]
Just tested a sweat bee, after 30 blocks of ice it converted to a frosty

**Comment by aAndrew3030** [comment]
New bug, comb blocks don't drop when placed and mined (or mined in the Bumblezone)

**Comment by aAndrew3030** [comment]
I went back threw this thread, and all the issues seem to be fixed. This can be closed, thanks

**Comment by JaisDK** [comment]
Thank you for the reports!
