### ISSUE TITLE
Mod Crashes on Newer NeoForge 1.21 updates

### ISSUE THREAD

**Issue by ModernGamingWorld** [JDKDigital/productive-bees#511]
![Screenshot 2024-07-03 201517](https://github.com/JDKDigital/productive-bees/assets/75923060/1c44fae8-e1de-4967-8400-dfcf2e4d384b)

**Comment by JaisDK** [comment]
I need a full log

**Comment by ModernGamingWorld** [comment]
[latest.log](https://github.com/user-attachments/files/16092191/latest.log)

**Comment by JaisDK** [comment]
mcwdoors is the mod that's crashing
