### ISSUE TITLE
[Enhancement] Honey Bee (Gene Enabled Default Bee)

### ISSUE THREAD

**Issue by vitharr137** [JDKDigital/productive-bees#512]
Adding a new bee possibly converted by feeding a honey block to a default bee that would simply be able to have genes applied to it would be a nice addition to automating standard honeycombs, especially for the 'midgame' stage where treats can be bottlenecked

**Comment by JaisDK** [comment]
![image](https://github.com/JDKDigital/productive-bees/assets/15868585/3a4342fa-469a-47ea-83fc-9ee5d3d99b52)

I have genes on vanilla bees in 1.21, but there's probably not coming anything similar for earlier versions.
