### ISSUE TITLE
Productive Tree wood type hives not working

### ISSUE THREAD

**Issue by FoxSketchez** [JDKDigital/productive-bees#513]
Mod: ATM 10 
Version: 1.21 0.7 (NeoForge)

I've tested two Productive Trees bee hive wood types and both will accept bee cages,
But will not let the hive-type bee in (see pictures)

![2024-07-05_22 45 35](https://github.com/JDKDigital/productive-bees/assets/30120784/04086596-5402-4b00-8bf9-e3c6a01630c5)
Left is Soul wood and the right is beech wood

![2024-07-05_22 46 36](https://github.com/JDKDigital/productive-bees/assets/30120784/6ab26aea-53af-40e9-ba7a-5be8de5bc41e)

**Comment by JaisDK** [comment]
what bee is in the cage?

**Comment by FoxSketchez** [comment]
it was a Crystalline bee

Apologies for the late reply 
![2024-07-06_13 36 09](https://github.com/JDKDigital/productive-bees/assets/30120784/45e7ab3c-5e8f-488c-b75e-0130bb2b8eae)

**Comment by JaisDK** [comment]
fixed
