### ISSUE TITLE
Aluminium Spelling 

### ISSUE THREAD

**Issue by TheBedrockMaster** [JDKDigital/productive-bees#514]
Despite being in the en_us lang file, Aluminium in Aluminium Bee is spelt the British way.

**Comment by JaisDK** [comment]
![image](https://github.com/JDKDigital/productive-bees/assets/15868585/2c8270c8-cfae-447c-a3de-593bc03303ca)

**Comment by TheBedrockMaster** [comment]
Me neither, but its weird that it's inconsistent

**Comment by TheBedrockMaster** [comment]
Can there be lang for en_us and en_gb?

**Comment by JaisDK** [comment]
Technically yes, but how the Americans learn to spell if I did that ;)

**Comment by TheBedrockMaster** [comment]
True, good point :)
