### ISSUE TITLE
Coal Bee Combs do not Produce Anything On Server

### ISSUE THREAD

**Issue by Calouknee** [JDKDigital/productive-bees#52]
Minecraft 1.16.1
Forge 32.0.66
JEI 7.0.0.6
Productive Bees 0.1.15.2

So I tested this out on a singleplayer world and the fossilized combs would always give me coal when I put them into the centrifuge, but for some reason whenever I try it on the server they always disappear. Even JEI changes the recipe to show that nothing comes out of it. Is there any way I can fix this?
[2020-07-23-1.log](https://github.com/JDKDigital/productive-bees/files/4968773/2020-07-23-1.log)

**Comment by JaisDK** [comment]
Thank you, can you provide a modlist as well?

**Comment by JaisDK** [comment]
and is it the same modlist for your single player as for the server?

**Comment by JaisDK** [comment]
Try updating forge to the newest version, there were some recent fixes to recipes.

**Comment by Calouknee** [comment]
The mod list I use is mainly the mods from Enigmatica 6, with some added ones.

**Comment by JaisDK** [comment]
Does it help if you do a /reload on the server?

**Comment by closeshot** [comment]
also having this issue in my own personal modpack for 1.16.1 single player.

**Comment by Calouknee** [comment]
Well doing /reload makes the recipe correct, but still no coal dust comes out of it

**Comment by Calouknee** [comment]
Actually, after reloading I was able to just make a new centrifuge and it started working. Weird, but thanks

**Comment by JaisDK** [comment]
@closeshot What version of forge and the mod are you running and did you try the above?
