### ISSUE TITLE
More 1.21 bugs

### ISSUE THREAD

**Issue by aAndrew3030** [JDKDigital/productive-bees#520]
I am unable to get the neon bee to spawn (even with tick acceleration). Not sure if it is a bug or just exceptionally rare? v13.1.2

Other issues (I have not tested) opened in ATM 10

https://github.com/AllTheMods/ATM-10/issues/85  v13.1.1

https://github.com/AllTheMods/ATM-10/issues/84 v13.1.2

https://github.com/AllTheMods/ATM-10/issues/82 v13.1.1

Also, most of the bee spawn eggs do not show up in EMI, not sure if that is intentional or not v13.1.2

**Comment by JaisDK** [comment]
is this on 13.1.2?

**Comment by aAndrew3030** [comment]
I edited to add mod version numbers

**Comment by JaisDK** [comment]
Tested all of these and they're already fixed or not broken.

For the cuckoo bee please note that each nest can only spawn 2 of them, so if you spawned nomad bees with them before then you need to reset the nests in a crafting grid before they will spawn more.

Can you give an example of a missing spawn egg? I can see them all in EMI.

**Comment by aAndrew3030** [comment]
Thanks for testing them, I did not know the nests needed reset. I will give that a try

I figured out EMI, I had it set to index registered instead of creative. Switching back to creative index and it shows everything again

**Comment by JaisDK** [comment]
odd that it would not show the eggs when I've told EMI that they're defined by components
anyways good to hear that it's working

**Comment by aAndrew3030** [comment]
This is what I see when I switch it to index, but creative is default, so most people probably wont ever change this

![Screenshot 2024-07-12 182320](https://github.com/user-attachments/assets/77dc1cae-3bf1-41cf-bc67-da7563489570)

**Comment by JaisDK** [comment]
so that's all the solitary bees and worker bees, they're all normal entities/items so that makes sense
the last egg probably doesn't have a correct name as that's the item used for all the other ones.

**Comment by JaisDK** [comment]
what are all those items not having a texture?

**Comment by aAndrew3030** [comment]
Those are all the Biomes O Plenty hives, non of them have textures

<img width="629" alt="Screenshot 2024-07-12 202907" src="https://github.com/user-attachments/assets/aa1972c0-be29-40d2-bcaf-baf5c92db814">

**Comment by aAndrew3030** [comment]
They also don't drop, not sure if they work otherwise

**Comment by JaisDK** [comment]
I removed all compat with mods that weren't updated at the time but I guess it's still registering the blocks

**Comment by aAndrew3030** [comment]
I am sure your aware that productive bees .3 crashes with productive trees due to the two mods using a different version of productivelib?

**Comment by JaisDK** [comment]
yea I know, it's very annoying it's using the older version from PTrees instead of the newer one PBees

I have a new build ready, I just haven't uploaded yet
