### ISSUE TITLE
[Suggestion] Add compatibility for Applied Energistics 2

### ISSUE THREAD

**Issue by FoxSketchez** [JDKDigital/productive-bees#524]
Having Applied Energistics 2 compatible with bee hives would make automation much easier.
With items and fluids, 
Currently, the only way to get fluid out is via bottles or Create Mod (not available as yet for 1.21)

**Comment by JaisDK** [comment]
hives don't have fluids, they have a honey level which is just a state
if you want to automate the harvesting of the honey level you can pump empty bottles into the hive

**Comment by FoxSketchez** [comment]
Well, that is something to consider, I'll have to look into that.
Thanks

**Comment by Mithi83** [comment]
My typical setup is to have an export bus (with crafting card to be fancy) to put empty bottles into the hive and an import bus to get back any comb, wax and filled bottles.
