### ISSUE TITLE
Centrifuge honey level flickers

### ISSUE THREAD

**Issue by Mithi83** [JDKDigital/productive-bees#525]
I'm currently playing ATM10 version 0.14. There I have a centrifuge (the plain type, not heated or powered, no upgrades) with a stack of gold combs in the input slot to to process. For every tick filling the white/grey arrow by one pixel on the left between input and 3x3 output slots, the honey level indicator on the right flickers between three states, as seen here:

![honey-100mb](https://github.com/user-attachments/assets/5b2434c7-4d99-47f8-8e34-6305f54e78b2)
![honey-empty](https://github.com/user-attachments/assets/47274f90-26c1-4290-9d2a-0372c2daba04)
![honey-full](https://github.com/user-attachments/assets/fd874b0e-ab7c-4d3a-8fb9-05cdf011f2c9)

Note that these pictures were taken in rapid succession without changing anything in the centrifuge itself. I'm not sure if it is merely a graphical issue or also would have an impact on the actual amount of honey one could obtain.

**Comment by JaisDK** [comment]
do you have other centrifuges next to it?

**Comment by Mithi83** [comment]
Yes, indeed, in fact there are 4 centrifuges in a 2x2 area. Breaking one of them led to a state where the remaining three are all full and void of the honey as expected. A single centrifuge seems to be ok as well. I take it they are somehow pushing the honey in some sort of circle?

**Comment by JaisDK** [comment]
yup, that's exactly what they're doing

**Comment by Mithi83** [comment]
Ok, thanks for the quick response, I guess we can close this then as "works as designed".
