### ISSUE TITLE
Blocks introduced whose base material have unique sounds like Bamboo, Cherry, or Nether Wood don’t have them

### ISSUE THREAD

**Issue by Inonedn** [JDKDigital/productive-bees#529]

**Comment by JaisDK** [comment]
I have no idea what issue you’re reporting. Please elaborate.

**Comment by Inonedn** [comment]
Bamboo Beehives, Cherry Beehives, and the Nether Beehives do not have unique sounds from their woodtype

**Comment by JaisDK** [comment]
do they need to? just put the wood down if you want to play music

**Comment by Legorfyr** [comment]
I mean, consistency between woodtypes, I get what the OP means xD

**Comment by JaisDK** [comment]
are we talking about the walking sound? for some reason I thought you were talking about sound from noteblocks when placed on the hive

**Comment by Inonedn** [comment]
No, place, break, and step sounds

**Comment by Inonedn** [comment]
Bamboo, Cherry, and the Nether Woods all have unique block sounds, but the beehives of those types dont use the correct sound
