### ISSUE TITLE
Crash when collecting honey in the nether

### ISSUE THREAD

**Issue by Raichu026** [JDKDigital/productive-bees#530]
Tried collecting honey from a warped bee nest and the game just crashes to the launcher (on most recent version of the allthemods 10 modpack)

**Comment by JaisDK** [comment]
Do you have a crash report?

**Comment by Raichu026** [comment]
[crash-2024-07-22_14.07.40-client.txt](https://github.com/user-attachments/files/16348029/crash-2024-07-22_14.07.40-client.txt)
