### ISSUE TITLE
CreeBee breeding result in Breeding Chamber not showing

### ISSUE THREAD

**Issue by Shockax** [JDKDigital/productive-bees#532]
If you breed a CreeBee with another CreeBee in the Breeding Chamber the result (CreeBee) is not showed on the right side.

The breeding process is working and new CreeBees are being produced

![image](https://github.com/user-attachments/assets/c68f4c55-28d1-4733-8089-9749638e24e5)

**Comment by fancychain** [comment]
The same with the bees from minecraft and probably with all solitary bees if they're breeding among themselves (if you breed them with other bees and the result bee isn't solitary then the result is shown)

**Comment by JaisDK** [comment]
fixed
