### ISSUE TITLE
In the mod version 13.2.0 almost all combs don't produce honey in a centrifuge

### ISSUE THREAD

**Issue by fancychain** [JDKDigital/productive-bees#536]
In the mod version `productivebees-1.21.0-13.2.0.jar` almost all combs and comb block don't produce honey, in the previous version all bees produce honey. Only 11: (in ATM10 version 0.20) Ribbeet, Magentite, Ludicrite, Experience, Blutonium, Inanite, Insanite, Honeycomb (from minecraft), Cyanite, Graphite and Ridiculite combs and their block versions produce honey, all the other combs do not produce honey.
There are only 6 pages with combs which do produce honey:
![image](https://github.com/user-attachments/assets/5f7d8b3e-7e88-46e3-94c0-f40b13d0d683)
This is the new mod version:
![1](https://github.com/user-attachments/assets/0598c6aa-43f6-473a-a1eb-0f88717db8d9)
And this is the previous version:
![2](https://github.com/user-attachments/assets/4ee45e49-ad8d-4183-a674-5ebdd8b316b4)

**Comment by JaisDK** [comment]
is this only for the recipe viewing or did you try processing some combs to see if they produce?

**Comment by fancychain** [comment]
i did try processing, they don't produce honey
