### ISSUE TITLE
Minecraft 1.20.1, Productive Bees and JEI.

### ISSUE THREAD

**Issue by ceesar1201** [JDKDigital/productive-bees#541]
I create a new world few days ago, and today i was looking for some things. When i was trying to look for the breeding of some bees and their combs, it doesnt show his recipes and how to get it.
Idk if its a JEI problem or an issue from the mod.
I appreciate any type of help.
![fail](https://github.com/user-attachments/assets/bba7aa96-17b0-45ec-b063-5cd212847f36)
![fail2](https://github.com/user-attachments/assets/f662c0b5-eba1-4825-b13f-d32ad9f80330)
Here, i was trying to get the inferium essence, apparently on the JEI menu doesnt appear directly, but when you find how to get the item, it appears.
But then, shows "Unconfigured Comb Block(ignore)" and the "Unconfigured Honeycomb(ignore)". 
Also the bees doesnt show on the JEI.

**Comment by JaisDK** [comment]
Can you provide a debug.log?

**Comment by ceesar1201** [comment]
I only have this on the logs folder, or should i generate one? idk how to do it
![imagen_2024-08-04_030551913](https://github.com/user-attachments/assets/36cf5cef-ed4e-47eb-8a12-f2c92f180661)

**Comment by ceesar1201** [comment]
> Can you provide a debug.log?
I only have this on my logs folder or should i generate one? idk how to do it
![imagen_2024-08-04_030727815](https://github.com/user-attachments/assets/15a0ae18-7469-45e2-b1ad-577e51ece02f)

**Comment by BunnyStardust** [comment]
Having this same issue.

**Comment by JaisDK** [comment]
I need a log, if there's no debug log send latest.log

**Comment by JaisDK** [comment]
and remove Minecraft Comes Alive if you have that installed, it fucks things up

**Comment by BunnyStardust** [comment]
> and remove Minecraft Comes Alive if you have that installed, it fucks things up

Is there any way to fix that? I'm developing a modpack and my players really love both mods and I would love to keep Productive Bees installed :(

**Comment by JaisDK** [comment]
it looks like they're looking into it finally
https://github.com/Luke100000/minecraft-comes-alive/issues/947
