### ISSUE TITLE
Updating productive bees produces error

### ISSUE THREAD

**Issue by alpha-pvp** [JDKDigital/productive-bees#545]
I updated Productive Bees for ATM10 so the upgrades don't crash my game anymore, but now i get this message and can' launch.
I'm using the AT launcher and can't figure out how to update the lib, because it doesn't show up anywhere.
![Screenshot 2024-08-04 125406](https://github.com/user-attachments/assets/895e6c85-1826-49e5-9798-af6c62c9b73b)

**Comment by JaisDK** [comment]
Update productive trees as well
