### ISSUE TITLE
Productivelib?

### ISSUE THREAD

**Issue by Grimm-reaper30** [JDKDigital/productive-bees#546]
I've tried updating Productive bees, but now it say's im missing the ProductiveLib...
Can't seem to find the productivelib

**Comment by JaisDK** [comment]
Update productive trees as well

**Comment by Grimm-reaper30** [comment]
Ah... thank you! I'll try that

**Comment by Grimm-reaper30** [comment]
Jup, that worked.  Thanks for the help
