### ISSUE TITLE
connected textures not working

### ISSUE THREAD

**Issue by ALEILGOD** [JDKDigital/productive-bees#547]
the expansion box connected textures are broken. When placing the boxes adjacent to the advanced beehives all the textures are facing the wrong direction
![Screenshot 2024-08-04 162910](https://github.com/user-attachments/assets/75658697-7419-4bf6-ba39-7e18586f1b64)

**Comment by ALEILGOD** [comment]
i have fusion and modernfix installed as well (along other 89 mods)

**Comment by JaisDK** [comment]
you can only stick one expansion box on a hive

**Comment by ALEILGOD** [comment]
yeah but the textures are broken

**Comment by ALEILGOD** [comment]
i tried removing the others

**Comment by JaisDK** [comment]
it will adjust to the last box you place and the others will look broken, remove what you don't want and place the one you do want

**Comment by ALEILGOD** [comment]
oh, thanks it worked
