### ISSUE TITLE
Unable to pull out items from canvas hives with automation (Pipez etc)

### ISSUE THREAD

**Issue by Uncraftbar** [JDKDigital/productive-bees#548]
![grafik](https://github.com/user-attachments/assets/65b742d5-f49f-44c3-a666-05db92953f46)
Basically title. Trying to pull out items from a canvas hives doesnt work. Drawer pull upgrades just ignore the inventory, and Pipez act as if it wasnt even there. Am on productivebees-1.21.0-13.3.2 using the atm10 modpack. The comb blocks that are in the drawer have been put in by me manually, no more get put in via the puller upgrade or pipez

**Comment by MarianNapi** [comment]
Seems fixed in 1.21.0-13.3.3
