### ISSUE TITLE
Canvas hives losing color after relog

### ISSUE THREAD

**Issue by Uncraftbar** [JDKDigital/productive-bees#549]
If you paint a canvas hive with a color, then leave the world or server (works both in single and multiplayer) the color gets reset. tested in version productivebees-1.21.0-13.3.2 in the atm10 modpack.

**Comment by JaisDK** [comment]
I can't recreate this, it keeps the color just fine when I relog

**Comment by Uncraftbar** [comment]
Seems to have been fixed with the same update that fixed the canvas hives not connecting to any pipez or other options.
