### ISSUE TITLE
end bee nest prevent end city spawning

### ISSUE THREAD

**Issue by minecrafterseppe** [JDKDigital/productive-bees#55]
end bee nests seem to take priority over end city's 

how to replicate 
use this website to locate ur end city's
i can confirm it works  100% of the time the thing that also overwrites is 
empty island    end city exit portals (have an area around them notning spawns)    
most of the end city spawns get overwriten by the bee nests
on every location on island not near exit portals are where end city's are supposed to spawn are bee nests in the ground

**Comment by JaisDK** [comment]
Thanks for reporting, I'll look into it.

**Comment by JaisDK** [comment]
What website are you using to locate the cities? In my tests I am not having any problem with missing structures.

**Comment by minecrafterseppe** [comment]
chunkbase  
most of the time they get overwritten 
like 80%

**Comment by JaisDK** [comment]
Which MC version are you using? I don't see support for 1.15.2 or 1.16.1 Java on ChunkBase.

If you take out Productive Bees and recreate the same seed, do the structure spawn?

**Comment by minecrafterseppe** [comment]
they do spawn then and that thing is outdated because notning has changed since that version  in the end

**Comment by JaisDK** [comment]
Can I have the seed you are testing with, and which version of the mod are you using?

**Comment by minecrafterseppe** [comment]
if its not with all seeds then i gues its not an issue sorry for bothering then  
-246448053321439694
1.16.1-1-2.0.0
