### ISSUE TITLE
NeoForge 1.21.1 Crash on world Load 

### ISSUE THREAD

**Issue by Zelioth** [JDKDigital/productive-bees#551]
Minecraft 1.21.1
NeoForge 21.1.2
PB - 1.21.0-13.3.3

Appears on world load the game crashes due to an issue spawning bee hives just from what I can take from the crash report. I attempted to report to your discord but didn't see a channel for PB. Sorry for posting in the JEIA channel. 

[latest.log](https://github.com/user-attachments/files/16561786/latest.log)

[crash-2024-08-09_08.32.20-server.txt](https://github.com/user-attachments/files/16561783/crash-2024-08-09_08.32.20-server.txt)

**Comment by Gbergz** [comment]
Can confirm.

**Comment by JaisDK** [comment]
1.21.1 versions for bees and trees are up, they do not work on 1.21.0
