### ISSUE TITLE
Wrong names showing in tooltip mods

### ISSUE THREAD

**Issue by BelleBernice** [JDKDigital/productive-bees#554]
I thought this was a problem from the Jade mod, since it works fine with The One Probe, but the dev team told me this was a productive bees fix. 

> [Snownee's respponse:](https://github.com/Snownee/Jade/issues/451#issuecomment-2282372501)
TOP's implementation is wrong. You should contact the devs of Productive Bees to fix this issue: https://github.com/TehNut-Mods/HWYLA/issues/257

### Modpack
[All the Mods 10-0.30](https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/5613117)

### Minecraft version
1.21

### Mod loader
Neoforge v21.0.167

Issue description
The name of all the Comb Blocks from the mod '[Productive Bees](https://www.curseforge.com/minecraft/mc-mods/productivebees)' isn't correct!

I compared Jade with the '[WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit)' mod and the '[One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)' and only the one probe have the correct block names. Is it fixable for Jade maybe?

![javaw_nFDFGuhJxe](https://github.com/user-attachments/assets/f94e5ee0-fd6b-476e-ae80-67e9b4b07333)

**Comment by JaisDK** [comment]
I replied on their issue https://github.com/Snownee/Jade/issues/451

![image](https://github.com/user-attachments/assets/3dedd035-d632-4caa-9596-7087e61045f4)
