### ISSUE TITLE
[Suggestion] Output mod priority config

### ISSUE THREAD

**Issue by NillerMedDild** [JDKDigital/productive-bees#56]
I suggest that you guys add a config for specifying which mods the output of your tag based recipes should prioritize being from. 

It has been done by Immersive Engineering, and their datapack recipe structure looks almost identical to yours, so my guess would be that there's not a ton of work in it. I could very well be wrong though :P

I hope you'll consider it!

**Comment by JaisDK** [comment]
I could do that pretty easily. thanks for the recommendation. It would be empty by default though as I don't provide any of the resources myself.

**Comment by NillerMedDild** [comment]
That would be perfect :)

**Comment by JaisDK** [comment]
I forgot to add it to the release notes, but there's a config for the mod order now.

**Comment by NillerMedDild** [comment]
I know, it works great, thanks :D
