### ISSUE TITLE
Some combs have incorrect outputs when multiple items by the same tag exist.

### ISSUE THREAD

**Issue by TheGameAce** [JDKDigital/productive-bees#561]
Title. For an example, I have Gems N Jewels mod as part of the pack I'm using, which has quite a few bees. Unfortunately, if another mod has gems/items by the same ID, it gives me those instead for some reason. For instance, More Mekanism Processing causes Peridot bees to produce that mod's version of Peridot. With Thermal Expansion, Rubies & Sapphires from that mod are gotten from the respective bee combs.

Any chance this could be adjusted so that the tag of the item produced matches the mod it comes from?

**Comment by JaisDK** [comment]
there's a config called prefferedModList or something like that where you can specify which mods items you want to prioritize when an output is picked

**Comment by TheGameAce** [comment]
> there's a config called prefferedModList or something like that where you can specify which mods items you want to prioritize when an output is picked

Gave it a try, doesn't seem to change anything. Removed Thermal from the list, for instance, while adding Gems N Jewels, but the comb outcomes are still the game after a restart. Confirmed I input the proper mod ID, still outputs as I mentioned above.

**Comment by JaisDK** [comment]
Install Almost Unified, they do a better job at that task

**Comment by TheGameAce** [comment]
Well, Almost Unified was a nice addition that cleaned up a few other things for me, but it only partially fixed the comb outputs. Peridot is fixed to Gems & Jewels' version now, but Rubee & Sapphire comb outputs are still showing as Thermal's variants. But at least the crafting recipes were fixed for the thermal versions to be usable for Gems & Jewels versions at least, so I guess that technically fixes it?
