### ISSUE TITLE
Experience comb 1.21

### ISSUE THREAD

**Issue by wallacesivirino** [JDKDigital/productive-bees#562]
"Experience comb in 1.21 has nothing to be done, it cannot be processed."

**Comment by Saereth** [comment]
Also have this issue, currently installed c:experience fluids are being added from both pnuematiccraft and sophisticatedstorage, if relevant (noticed a neoforge conditional on the recipe)

**Comment by Saereth** [comment]
looks fixed in the latest build, thanks!
