### ISSUE TITLE
Looking for txt file (or something similar) for Big Book of Bees

### ISSUE THREAD

**Issue by thatdudeaustin** [JDKDigital/productive-bees#563]
MC Version: 1.21.1
Modloader: Neo 21.1.12

I am playing the TNP Limitless 8 modpack and cannot find the Big Book of Bees in the JEI. I cannot craft the book so I was hoping there is a txt file or something of the sort to read alternatively. Most of the bees have information in this modpack but there are a few that I can't figure out how to create/breed/feed (plastic bee, arcane bee, etc). This could be chalked up to user error as I am fairly new to modded minecraft. 

Happy to hear your thoughts and advice. Thank you for creating this awesome mod!

**Comment by JaisDK** [comment]
The guide book doesn't contain bee recipes. If the bee itself does not show a recipe then look for a recipe for the spawn egg.

**Comment by thatdudeaustin** [comment]
How do you get the gene for the spawn eggs?

**Comment by JaisDK** [comment]
if there's only the incubation recipe then the spawn egg is not the primary way to get the bee
