### ISSUE TITLE
Possible to change output fluid from centrifuges?

### ISSUE THREAD

**Issue by trav90** [JDKDigital/productive-bees#565]
Hello,

Is it possible to change the fluid outputted from the centrifuge? Basically I want to change the centrifuges to output honey fluid from another mod if possible.

Thanks for your time.

**Comment by JaisDK** [comment]
Yes it is. Which version are you using?

**Comment by trav90** [comment]
Sorry, I should have listed that information.

Minecraft 1.20.1
Forge 47.3.7
Productive Bees 1.20.1-12.6.0

**Comment by JaisDK** [comment]
It's probably easiest to use KubeJS If you don't want to change all recipes manually

<https://github.com/JDKDigital/productive-bees/tree/dev-1.20.0/src/main/resources/data/productivebees/recipes/centrifuge>

<https://github.com/JDKDigital/productive-bees/blob/dev-1.20.0/src/main/resources/data/productivebees/recipes/centrifuge/honeycomb.json#L14>

**Comment by trav90** [comment]
Awesome thanks! This is probably the wrong place to ask this question but is it possible to do with CraftTweaker instead of KubeJS (I've already used CraftTweaker to modify a bunch of other things in my pack)?

Really appreciate your help and time!

**Comment by JaisDK** [comment]
They are just recipes so it should be possible

**Comment by trav90** [comment]
Thanks! I wasn't able to get CraftTweaker's Replace() to work so I ended up extracting the json recipes from the mod jar and creating a datapack instead where it outputs the fluid I want.

Thanks again for the help!
