### ISSUE TITLE
Incorrect chance output for bee spawn egg recipe for GTCEu Modern

### ISSUE THREAD

**Issue by Bosspc1234** [JDKDigital/productive-bees#566]
**GregTech CEu Version**
gtceu-1.20.1-1.4.0-build_1067-SNAPSHOT

**Minecraft Version**
1.20.1

**Recipe Viewer Installed**
EMI

**Environment**
Singleplayer

**Other Installed Mods**
Gregtech Community Pack Modern with added Productive Bee

**Expected Behavior**
Bee egg recipe in GT machine has guaranteed input+output

**Actual Behavior**
Bee egg recipe in GT machine has 0.01% input+output
![Screenshot 2024-09-08 203349](https://github.com/user-attachments/assets/83a3003a-2912-4c2f-ac03-56a85b7a03b4)

**Additional Information**
`"chance": 1 `might equal to 0.01% in src/main/resources/data/gcteu/recipes files
Since GTCEu use `.chancedOutput` 10000 for 100%

**Comment by Nemesis2401** [comment]
I am encountering this issue too. At the moment I fixed it by manually building a new jar of productive bees with the recommended change.

**Comment by JaisDK** [comment]
this one? https://www.curseforge.com/minecraft/modpacks/gregtech-community-pack-modern

**Comment by JaisDK** [comment]
fixed in the pack
