### ISSUE TITLE
[1.21.1-13.5.1] Comb Blocks not accepted in centrifuge

### ISSUE THREAD

**Issue by srob650** [JDKDigital/productive-bees#569]
Playing in ATM10 v0.55 and comb blocks don't seem to be accepted into centrifuges, I have to uncraft into combs first.

**Comment by JaisDK** [comment]
Which centrifuge? They only go into heated centrifuges

**Comment by srob650** [comment]
Ah my mistake, I didn't realize that.  Tested and it indeed works, thank you.
