### ISSUE TITLE
unable to get the guide book

### ISSUE THREAD

**Issue by VaporeonScripts** [JDKDigital/productive-bees#572]
i tried crafting it but nothing
i tried giving it on first launch with kube js, but doesnt work, i need that book
![image](https://github.com/user-attachments/assets/ae875183-98ee-4a57-b1e2-c5f1c1ebca23)

**Comment by JaisDK** [comment]
version?

**Comment by VaporeonScripts** [comment]
1.21.1 neoforge
altough i tried on  a new world in creative by crafting and it gave me it?

**Comment by VaporeonScripts** [comment]
idk how that is possible

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/d8e1e512-2dee-4c1e-8477-d77f04b8a2d2)
that might be why lmao

**Comment by VaporeonScripts** [comment]
lemme remove that error : and make a new world

**Comment by VaporeonScripts** [comment]
yeah, it doesnt give the book

**Comment by VaporeonScripts** [comment]
the code in kube js is right but doesnt give it anyway :C

**Comment by JaisDK** [comment]
the item is not called `productivebees:guide`, it's a patchouli guide book with `productivebees:guide` as the data

**Comment by JaisDK** [comment]
once you have the book from crafting hold it in your hand and run the cmd `/data get entity @p SelectedItem` to get the ID and data

**Comment by VaporeonScripts** [comment]
alright,sec

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/77388d58-4dba-4e85-9bf2-bf6f01fbfc87)
here

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/dcd4def2-334d-48b7-a945-6501a3fbc32e)
what would i need to write there to give myself the book on first launch?

**Comment by JaisDK** [comment]
I don't know, I'm guessin Item.of takes a second param which would be for the component data

**Comment by VaporeonScripts** [comment]
bruh

**Comment by VaporeonScripts** [comment]
altough other books such as this one 
![image](https://github.com/user-attachments/assets/214b07ef-2cd5-476e-9087-8ed159559b6d)
worked with the code

**Comment by VaporeonScripts** [comment]
and it was the correct id

**Comment by JaisDK** [comment]
the book in your screenshot would not work, it's also one with a component
the three other guide books in your script uses their own item instead of the patchouli one and do not require a component

https://wiki.latvian.dev/books/kubejs-legacy/page/starting-items

it shows the second param in the example so it would be something like `Item.of('patchouli:guide_book', '{components:{"patchouli_book": "productivebees:guide"}}')`

**Comment by VaporeonScripts** [comment]
lemme try that

**Comment by VaporeonScripts** [comment]
doesnt work

**Comment by JaisDK** [comment]
what do you expect me to do? I don't make kubejs and you give me no info on _how_ it's not working. check the kjs logs or something

**Comment by VaporeonScripts** [comment]
dont u know the exact id of the book or wth?, anyways im asking in the kubejs discord

**Comment by JaisDK** [comment]
![image](https://github.com/user-attachments/assets/a13a99ed-8e5b-4db9-8955-15a8546ad271)

Exact ID ^

**Comment by VaporeonScripts** [comment]
Yeah but that's gives an empty useless patchouli book

**Comment by VaporeonScripts** [comment]
That*

**Comment by JaisDK** [comment]
that's why you need to add the component (what was NBT in pervious versions) as the second param

**Comment by VaporeonScripts** [comment]
I did,but it didn't give me the book

**Comment by VaporeonScripts** [comment]
![Screenshot_20240928-233640_Discord.png](https://github.com/user-attachments/assets/b9ffdde6-c995-42ae-bbaa-c1c14b5eab80)

Ima try what the neoforge server manager said ig,ima let U know

**Comment by VaporeonScripts** [comment]
the id for the book is patchouli:guide_book[patchouli:book="productivebees:guide"]

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/32980f2f-9604-4114-91b7-9f9325b43259)
this works now
