### ISSUE TITLE
Multiple expansion hive crashes the game

### ISSUE THREAD

**Issue by VoidTest** [JDKDigital/productive-bees#574]
When 2 expansion boxes are placed next to a hive and one is broken when opening the hive you get kicked and given a "Network protocol error".

**Comment by JaisDK** [comment]
can you provide a log?

**Comment by ghost** [comment]
> can you provide a log?
(this is from .minecraft/debug)
[disconnect_2024_10_10.txt](https://github.com/user-attachments/files/17331258/disconnect_2024_10_10.txt)
