### ISSUE TITLE
Honey Bottle in the Honey Generator creates Infinite Energy.

### ISSUE THREAD

**Issue by dba9514** [JDKDigital/productive-bees#575]
Honey Bottle in the Honey Generator creates Infinite Energy. The bottle is never depleted and is quite game-breaking.
![HoneyBottleInGenerator](https://github.com/user-attachments/assets/366f4bf4-54c8-4537-a00d-6c8c184847cb)

**Comment by JaisDK** [comment]
are you sure this is on the latest?

**Comment by dba9514** [comment]
> are you sure this is on the latest?

Not entirely sure. I reviewed the code for the entity and it seemed to be properly processing honey bottles providing 250mb and returning a glass bottle.

This issue was created as a prerequisite of the issue on the ATM 10 page. (They require an issue to be created on the actual mod's github as well.)

I have not had a chance to test the latest build. Most particularly in the context of the ATM 10 pack.
