### ISSUE TITLE
"Errors in currently selected datapacks prevented the world from loading You can either try to load it with only the vanilla datapack ("safe mode"), or go back to title screen and fix it manually"

### ISSUE THREAD

**Issue by ZombieSmile0** [JDKDigital/productive-bees#576]
Hi there, im new to this and have been having trouble getting into the world since i updated them last. Im using a modpack i found called cave horror project and added 3 mods into it myself like essential, Slabs extended, and 2 other scp mods.

everytime i try to load it up it says Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually.

Version 1.20.1
Forge 47.3.7

[latest.log](https://github.com/user-attachments/files/17270130/latest.log)

**Comment by JaisDK** [comment]
Why are you posting here? You don't have productive bees installed

**Comment by ZombieSmile0** [comment]
i just realized that i apologize im new where should i post?

**Comment by JaisDK** [comment]
the problem is The-Man-From-The-Fog

**Comment by ZombieSmile0** [comment]
Thank you!
