### ISSUE TITLE
config key collision on BeeAttributes

### ISSUE THREAD

**Issue by HalcyonSuoh** [JDKDigital/productive-bees#577]
https://github.com/JDKDigital/productive-bees/blob/b5a92df38de500d0f063630812f39ee97ebc61fa/src/main/java/cy/jdkdigital/productivebees/ProductiveBeesConfig.java#L234-L236

https://github.com/JDKDigital/productive-bees/blob/b5a92df38de500d0f063630812f39ee97ebc61fa/src/main/java/cy/jdkdigital/productivebees/ProductiveBeesConfig.java#L252-L254

both entry use `ticks` as key, causing the latter to override the former

**Comment by JaisDK** [comment]
thanks
