### ISSUE TITLE
[1.21.1] Error with latest mod version, connection lost world does not load.

### ISSUE THREAD

**Issue by Periam** [JDKDigital/productive-bees#579]
After installing the latest version available of the mod the game load but the world, saved or new, does not load.
There is an error on connection with a server and it seems to be related to recipes. The game is always single player.

MC 1.21.1
Neoforge - 21.1.66
Forbidden and arcanus 1.21.1-2.5.6
valhesia core -neofroge-1.21-1.1.3
Productives bees 1.21.1-13.6.0
Jei 1.21.1-neoforge-19.21.0.244

Logs

[latest.log](https://github.com/user-attachments/files/17335139/latest.log)

[disconnect-2024-10-10_19.51.54-client.txt](https://github.com/user-attachments/files/17335141/disconnect-2024-10-10_19.51.54-client.txt)

![image](https://github.com/user-attachments/assets/bef86c8b-931a-4731-92b1-9f5ad8d2e132)

**Comment by JaisDK** [comment]
This is on Forbidden and arcanus. I've written to the dev to get it sorted out.

**Comment by Periam** [comment]
Hi, do you want me to open a ticket to them???

**Comment by JaisDK** [comment]
nah I wrote on Discord
