### ISSUE TITLE
forbidden and arcanus recype sinc problem with new arcanus update

### ISSUE THREAD

**Issue by VaporeonScripts** [JDKDigital/productive-bees#580]
https://mclo.gs/jO78Wtv
neoforge 1.21.1 .68

**Comment by VaporeonScripts** [comment]
https://github.com/stal111/Forbidden-Arcanus/issues/443#issuecomment-2408044642

**Comment by VaporeonScripts** [comment]
(makes emi/rei/jei unable to show/show recipes on how to craft items)

**Comment by VaporeonScripts** [comment]
this is caused by a productive bee

**Comment by JaisDK** [comment]
#579

**Comment by VaporeonScripts** [comment]
alright

**Comment by VaporeonScripts** [comment]
the issue got fixed?

**Comment by JaisDK** [comment]
No, I just changed the recipe

**Comment by VaporeonScripts** [comment]
oh, so it shouldnt cause issues with recipe viewers or what

**Comment by JaisDK** [comment]
Yes the problem is f&a recipe serializer can’t handle component ingredients, only simple items

**Comment by VaporeonScripts** [comment]
so this means i can update forbidden and arcanus now
