### ISSUE TITLE
Log spam from ProductiveLib

### ISSUE THREAD

**Issue by Quinteger** [JDKDigital/productive-bees#581]
This started on one of the recent versions and is still happening on 1.21.1-13.6.1 despite the [changelog](https://www.curseforge.com/minecraft/mc-mods/productivebees/files/5806645) stating that it removed some of the output.
![image](https://github.com/user-attachments/assets/a92967fd-28ba-4243-a890-5763a45584c8)
The ProductiveLib repo looks outdated and this project seems to use some internal unreleased version of it, so I figured I'll leave it here.

**Comment by JaisDK** [comment]
update productive trees

**Comment by Quinteger** [comment]
@JaisDK To what version? It's already 1.21.1-13.6.1
