### ISSUE TITLE
[Suggestion]: Add a fourth tier of centrifuge

### ISSUE THREAD

**Issue by MarwenX3M** [JDKDigital/productive-bees#590]
I love playing with the Productive Bees mod, obtaining all of the bees I am able to get my hands on. Playing in packs like the ATM packs, the resource demands are high and I find myself often opting for the Omega Upgrades. This does however put a strain on the amount of centrifuges needed, and I have found myself needing to construct systems of almost 100 heated centrifuges. 

Because of this I suggest that a fourth tier of centrifuge could be added, to alleviate lag as well as logistical matters when it comes to construction. I don't want to put a bunch of demands around how this could be achieved, I will however say that one idea could be a centrifuge that can centrifuge in batches whenever possible.

**Comment by JaisDK** [comment]
do you put speed upgrades in your centrifuges?

**Comment by MarwenX3M** [comment]
I do yes, I should have noted that, my apologies.

**Comment by JaisDK** [comment]
![image](https://github.com/user-attachments/assets/39a2a73c-ad57-412b-aa13-97081253fd68)

that should do

**Comment by MarwenX3M** [comment]
Awesome, this looks great :). Exactly what I was going after, this will be a perfect addition imo. Really appreciate it
