### ISSUE TITLE
:[Bug]: Crash when bee is placed in a spawner

### ISSUE THREAD

**Issue by manmaed** [JDKDigital/productive-bees#592]
**Modpack**
FTB Evolution

**Modpack version**
1.0.3

**Mod Version**
Minecraft: 1.21.1
Neo: 21.1.72
PB: 13.6.2

**Steps to reproduce**
1. Place Spawner (Used Minecraft one)
2. Get Bee Spawn Egg (Used diamond bee spawn egg)
3. right click spawner with bee egg

could be related to #589 
Link to FTB: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6075

**Comment by Nekosity12** [comment]
For reference, productive bees are all the same bee just with different data. Even if you tried to use a spawner, it would not spawn a diamond bee anyway. Ofc you wouldn't want it to crash either way tho. In earlier versions (where it didn't crash) for example, it would just spawn "configurable bee"

**Comment by JaisDK** [comment]
I thought I fixed that in 13.6.2

**Comment by JaisDK** [comment]
it's a different crash :doompaste:
