### ISSUE TITLE
[ATM10] Vanilla Bee Duplication

### ISSUE THREAD

**Issue by DarksKami** [JDKDigital/productive-bees#594]
hi,

using Productive Bees 1.21.1-13.6.4 (productivebees)
		Productive Lib 1.21.0-0.1.8 (productivelib)
		Productive Trees 1.21.1-0.5.6 (productivetrees)

Yesterday evening i placed 3 advanced beehives with expansion inside a closed cave and got there 15 vanilla bees (without simulator, using normal flowers on dirt to get honey).

After relaunching the game today i discover 23 vanilla bees (15 in the hives and 8 more wandering in the cave) without any kind of breeding.

i do not find anything in the logs, neither a way to reproduce it.

**Comment by JaisDK** [comment]
if your game did not shut down correctly then bees can duplicate or disappear, it's a vanilla bug

**Comment by DarksKami** [comment]
oh thanks, i did not know that ^^

**Comment by DarksKami** [comment]
Vanilla bug
