### ISSUE TITLE
Twitch thinks BeeSourceful is also Productive Bees

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#6]
Why does twitch think "Beesourceful" and "Productive Bees" is the same mod? If I disable "Beesourceful" on twitch it also disabled "Productive Bees"

**Comment by JaisDK** [comment]
I have no idea how the twitch client works in this regard, the only references I have to that mod is when I check if it's loaded.
Can you enable Productive Bees without enabling BeeSourceful?

**Comment by mouse0270** [comment]
I actually can't install the mod via the twitch client and have to manually download it and add it to the mods folder. It wont show up when you try searching for your mod using the client. I actually would have never found your mod if I hadn't search using the website.

**Comment by JaisDK** [comment]
It is still listed as experimental, so it won't show in the client.

**Comment by mouse0270** [comment]
Still find it weird that the client thinks its the same mod. This is the only mod I've see this happen to. Well unless you have BeeSourceful listed as a dependency on twitch it would also do this.

**Comment by JaisDK** [comment]
It's listed as an optional dependency, just as buzzierbees and biomesoplenty. I've requested a review to get it out of experimental, maybe that will help.

**Comment by mouse0270** [comment]
That is why it is being disabled. If you disable a dependent mod on the client it disables all mods dependent on it to help prevent people from breaking there mod list.

**Comment by JaisDK** [comment]
I see, that's pretty dumb when it's listed as an optional dependency and not a required dependency. I'll remove the dependencies in the next update, to prevent this in the future. Thanks for reporting.
