### ISSUE TITLE
[BUG] NEO 1.21.1 Crash - Exception while adding particle - 13.6.6

### ISSUE THREAD

**Issue by Soforak** [JDKDigital/productive-bees#605]
I crashed after spawning two prosperity bees with eggs
And now I randomly crash when I see them
![image](https://github.com/user-attachments/assets/4a834fda-99bc-4a71-9855-c1f54abe80d0)
[crash-2024-12-18_18.16.39-client.txt](https://github.com/user-attachments/files/18186953/crash-2024-12-18_18.16.39-client.txt)

Neoforge 21.1.89
Productive Bees 13.6.6

**Comment by JaisDK** [comment]
How did you spawn them?

**Comment by Soforak** [comment]
Right clicking with a prosperity bee egg

**Comment by JaisDK** [comment]
You have a mod that messes with the particle engine, I don't know which one

**Comment by Soforak** [comment]
Seems like it's [Fancy Block Particle](https://modrinth.com/mod/fbp-renewed)
I disabled it and when a bee leave a prosperity block there is some particles under, like pollen
And enabling it again, when the bee leave the block, i instantly crash without seeing any particle under (no time)
I'm gonna test it again to confirm

**Comment by Soforak** [comment]
I confirm this is this mod, I tested Productive Bees with only Fancy Block Particle together with Mystical Agriculture for the properibees and I crashed as soon as the bee started to fly after leaving the prosperity block
I don't know if it's only the prosperibees, but seems like redstone bees and magmatic bees don't have any problem
I'm gonna report this to the Fancy Block Particle creator
Thanks for the help!

**Comment by JaisDK** [comment]
glad you found it :)
