### ISSUE TITLE
Cannot make custom bees to work

### ISSUE THREAD

**Issue by BitDanee** [JDKDigital/productive-bees#608]
Minecraft version: 1.21.1
Mod loader: NeoForge (21.1.90)
Productive bees: 13.6.7

I was able to add a custom bee through datapack, but it doesn't produce the right honeycomb (it produces the vanilla one) when in the advanced beehive and the custom honeycomb cannot be used in the centrifuge.
I also copy-pasted the datapack (the one about the bacon bee) from the github repository but it doesn't work. Same issues.

I double-checked where I put the files, the datapack structure and the JSON files and everything seems right to me.
I tried different things, but nothing seems to work.

**Comment by JaisDK** [comment]
share what you made and I'll take a look

**Comment by BitDanee** [comment]
[productivebees.zip](https://github.com/user-attachments/files/18220456/productivebees.zip)
Thanks

**Comment by JaisDK** [comment]
on 1.21.1 the `recipes` folder needs to be called `recipe`

**Comment by BitDanee** [comment]
Now it seems to work. Thank you.
Just remember to update the [sample datapack](https://github.com/JDKDigital/productive-bees/tree/dev-1.21.0/pb_datapack).

While I'm here, any way to display just the bee name?
![custom-bee-name](https://github.com/user-attachments/assets/fc758d5c-6ebf-4c25-9711-03e65e136fb2)

**Comment by JaisDK** [comment]
you need a lang file https://github.com/JDKDigital/productive-bees/tree/dev-1.21.0/pb_resourcepack

you might be able to put it in the same datapack

**Comment by BitDanee** [comment]
Now everything's fine.
Thank you very much.
