### ISSUE TITLE
[1.16.1] Buzzier Bees hive recipes wont load

### ISSUE THREAD

**Issue by WhitePhant0m** [JDKDigital/productive-bees#61]
Buzzier Bees hives and expansion box recipes wont load, ~~took a look at the recipes and saw that the mod id you are using in the recipes is buzzierbees while it's actually buzzier_bees~~ ignore that looked at the wrong branch. But there aren't any recipes for the variant hives. They can be spawned with /give

**Comment by JaisDK** [comment]
In 1.16.1 buzzierbees was changed to buzzier_bees, so all the interconnection is lost. Now that BB is out for 1.16 I can fix it for the next version. In 1.16 BB has removed all non-vanilla style beehives, so they will not be available yet.

**Comment by JaisDK** [comment]
The new update has the BB hives again, at least the ones BB has kept.
