### ISSUE TITLE
Fix Gene Purity Filtering in version 1.21.1

### ISSUE THREAD

**Issue by Vortiporius** [JDKDigital/productive-bees#610]
I'm playing this in ATM10, and it seems in this version to Pipez filter:
 Item/Tag: productivebees:gene

NBT Data: {productivebees_gene_purity:100} 

No longer works to pull out 100% purity genes from the Gene Indexer.

It would be nice to have this fixed, or an alternative.

**Comment by JaisDK** [comment]
`{"productivebees:gene_group":{purity:100}}`
