### ISSUE TITLE
Christmas Render Crash GeckoBeeRenderer

### ISSUE THREAD

**Issue by phit** [JDKDigital/productive-bees#612]
FTB Evolution with EMI added, just searching for bee and scrolling through EMI

[crash-2024-12-23_15.10.46-client.txt](https://github.com/user-attachments/files/18230295/crash-2024-12-23_15.10.46-client.txt)

geckolib-neoforge-1.21.1-4.7.jar 
productivebees-1.21.1-13.6.6.jar

**Comment by JaisDK** [comment]
Update the mod

**Comment by phit** [comment]
derp, should have checked that first.. fixed!
