### ISSUE TITLE
Crash on Feature placement

### ISSUE THREAD

**Issue by ghost** [JDKDigital/productive-bees#613]
Users crashing with null pointer exceptions blaming productive bees on terrain generation, owing to WoodSolitaryNestFeature.
Latest.log 1: https://mclo.gs/UzL0gG8
Latest.log 2: https://mclo.gs/F6xZjqX
Issue on ATM10 github: https://github.com/AllTheMods/ATM-10/issues/1513

**Comment by JaisDK** [comment]
you can just ping me in atm10 dev when there's an issue for me you know

**Comment by ghost** [comment]
Someone reported it on the github so i just wanted to be able to link that somewhere
