### ISSUE TITLE
[1.15] Random crash during worldgen

### ISSUE THREAD

**Issue by NillerMedDild** [JDKDigital/productive-bees#62]
I crashed randomly during exploration. Fresh world, nothing is built, singleplayer.

https://gist.github.com/NillerMedDild/560e6460aca8706f299fac1485551612

**Comment by JaisDK** [comment]
Thanks for reporting. Does it always crash for the same area or does it generate properly next time you open up the world?

**Comment by NillerMedDild** [comment]
Not sure, I'll have a look this evening :)

**Comment by JaisDK** [comment]
I will close this. It seems this kind of issues are forge related and are usually fixed by updating. If it happens again let me know.

**Comment by NillerMedDild** [comment]
Will do, sorry for not following up, I didn't become less busy :P

**Comment by JaisDK** [comment]
I can imagine maintaining a modpack is a lot of work :)
