### ISSUE TITLE
[1.16] Possible recipe issue, possibly just a question

### ISSUE THREAD

**Issue by NillerMedDild** [JDKDigital/productive-bees#64]
Iron Bee and Tin Bee have the same recipe (combining a crystalline bee and an ashy mining bee) not sure if that's deliberate? :)

**Comment by JaisDK** [comment]
Yes, this is on purpose. It should choose one of the valid breeding results at random.

**Comment by NillerMedDild** [comment]
Cool, thanks!

**Comment by JaisDK** [comment]
Copper bee is the same recipe as well
