### ISSUE TITLE
Client crash when interacting with some Gui

### ISSUE THREAD

**Issue by KrAzYGEEK32** [JDKDigital/productive-bees#67]
MC version: 1.16.1
mod version: MC version: 1.16.1
mod version:0.2.2
issue: client seems to crash (sometimes) when interacting with inventories.
crash report:
crash-2020-08-06_13.18.26-client.txt

Tbh i didnt know it was productive bees causing the issue, i was redirected to dank storage from pneumaticraft git and they redirected me here(coz im dumb with reading logs), i just wanna help improve the mod thats why im bothering to post this  hope the crash report helps :)

**Comment by JaisDK** [comment]
It doesn't look like the log was uploaded. Can you try again?

**Comment by KrAzYGEEK32** [comment]
oh my bad, here you go
[crash-2020-08-06_23.45.24-client.txt](https://github.com/JDKDigital/productive-bees/files/5037292/crash-2020-08-06_23.45.24-client.txt)

**Comment by KrAzYGEEK32** [comment]
this is the most recent crash, which occured in a similar way
this
[crash-2020-08-06_13.18.26-client.txt](https://github.com/JDKDigital/productive-bees/files/5037311/crash-2020-08-06_13.18.26-client.txt) is the actual one

**Comment by JaisDK** [comment]
Found the log on dank storage too. What is the setup you are having involving pneumaticraft, dank storage and productive bees?

**Comment by KrAzYGEEK32** [comment]
i am not using productive bees at all, i dont have a bee anywhere near my area, thats the issue

**Comment by JaisDK** [comment]
which block are you interacting with when you crash?

**Comment by KrAzYGEEK32** [comment]
whenever i try to edita logistics filter from pneumaticraft and game crashes

**Comment by KrAzYGEEK32** [comment]
GUI of a logistics requester frame

**Comment by JaisDK** [comment]
It makes sense, the logistics stuff iterates all the items in the game, makes a stack of them and gets the name. The Gene item in my mods expects some extra data which is displayed in the name and therefore it crashes. It's an easy fix I might be able to have it ready tonight.

**Comment by KrAzYGEEK32** [comment]
happy to have helped :)

**Comment by JaisDK** [comment]
Thank you for reporting :) I put the new version up, it should be ready in a couple of minutes.
