### ISSUE TITLE
Bees 'disconnect' from housing extremely easily

### ISSUE THREAD

**Issue by WilliamHarer** [JDKDigital/productive-bees#68]
cage-ing or accidentally distracting a hive bee with a flower, while they are pollen covered seems to keep them from entering any hive, leaving them essentially useless, maybe having the cage remove the pollen status on productive bees?

It seems like I may have been wrong and for some reason hives become unusable by the bees for some reason? I have a couple hives that the bees never enter, but are above honey level 0

**Comment by JaisDK** [comment]
This is inherited from the vanilla bees unfortunately. Are you using 1.15.2 or 1.16.1? In 1.16 Mojang added a max distance bees would fly from their hive, so it should not be such a big problem in that version.

**Comment by WilliamHarer** [comment]
Its solved now, but the cause of it was having other nests available behind closed doors or walls. The bees would decide they wanted to nest there instead of in a hive, and destroying all nests in the chunk seemed to fix it. Definitely a frustrating issue that screwed up some plans i had. Is it possible to change world generated productive nests, such as glowstone, nether quartz etc., to have a seperate tag than hive or nest. This would prevent solitary bees from using these 'rarer' nests instead of the desired bee, and could also allow you to remove regular solitary nests as Points of interest for the productivebee entities. Also I saw in the code that solitary bees dont prefer different nests when finding a nest, I'd be interested in taking a look and maybe making a push such that wood bees only go in woodbased nests, digging bees only go in dirt/gravel nests, and specific bees like glow or crystaline only go in glowstone or quartz nests if youd be open to the idea? It would make organization much easier i think.

**Comment by JaisDK** [comment]
You are very welcome to make a PR with improvements. Glowing and Crystalline bees already only go for their own nest and hives, but the solitary bees will go for any solitary nest. There's also not any preference for hives over nests for those bees that can live in both.
Bees wanting to go to nests and hives that they can't reach should be fixable, I'll add it to my list.
