### ISSUE TITLE
Internal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#7]
When trying to sign into a server that is running version 0.1.3 the user recieves the following error: Reverting back to 0.1.2 and everything works fine.
```
[minecraft/ServerPlayNetHandler]: mouse0270 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
```

**Comment by JaisDK** [comment]
I'll need the full stack trace from the server log, can you provide this?

**Comment by mouse0270** [comment]
Here is the server log.

[2020-05-08-2.log](https://github.com/JDKDigital/productive-bees/files/4601404/2020-05-08-2.log)

**Comment by JaisDK** [comment]
Thank you, but can't say it reveals much. Could you try deleting the config file for productive bees both on your client and on the server and see if that helps?

**Comment by mouse0270** [comment]
I did fresh configs for all mods loaded. I deleted the configs on both client and server for all mods before reporting the issue.

**Comment by JaisDK** [comment]
I got the same error now when updating to forge .77, try reverting to .75

**Comment by mouse0270** [comment]
We're on 70. I'll try updating to 75.

**Comment by mouse0270** [comment]
Alright, setup a brand new server today, running 31.1.75 and a new instance of minecraft. I was only going to run Productive Bees but I was getting server errors because JEI was not installed. So I have only JEI and Productive Bees 0.1.3 installed on both the server and the client and I still get this issue.

Though I suspect it wont help, here is the server log
[latest.log](https://github.com/JDKDigital/productive-bees/files/4603932/latest.log)

And here is the client log
[latest.log](https://github.com/JDKDigital/productive-bees/files/4603936/latest.log)

**Comment by mouse0270** [comment]
Alright, downgraded from 0.1.3 to 0.1.2 on the client side, I get a bunch of errors in the console about honeycomb not existing type thing (As currently I only have JEI and Productive bees installed). But ignoring those errors I can join the world
