### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Ibirtem** [JDKDigital/productive-bees#70]
Friends try connect to the server, but nO. They see only: "Server mod list is not compatible" or something. They have every mods and necessary versions. 

1.16.1
Forge 32.0.106

https://gist.github.com/Ibirtem/0013a5c0df160712c4c3b43b946eb87d

**Comment by JaisDK** [comment]
I think this is a forge issue, but I will ask them and get back to you.

I'm guessing it works if you make a new world, but that's not really a solution. I've seen problems like this with removed blocks not being communicated properly to the client if the world was saved with an "old" set of blocks.

**Comment by JaisDK** [comment]
Can you provide the server log, your client latest.log and debug.log? I'll open a forum support post for this.

**Comment by Ibirtem** [comment]
Seems creating new world not helpful. All my friend go sleep and i cant check right now. A little bit later. I also try bit by bit removing mods, maybe i can find what mod can be cause this problem. I will definitely report the result. And thanks in advance for your help!

**Comment by Ibirtem** [comment]
Welp, sorry for this unhelpful issue. it's LAN connecting, so here we go i found:
1. I have two friend and first can connect to the new world (in old world - no), but second cant in both (Why? idk and it doesn't matter yet)

2. This friend gebug: 
https://gist.github.com/Ibirtem/50a2fcfc64f377c48697bca5cd17aa41
and latest:
https://gist.github.com/Ibirtem/bc903bc36c55d0479b3f1e272bceb830
(This not clear files, bcz there try to connect in new world and then in old)

AND ther is my debug, when friend try to connect in old world: https://gist.github.com/Ibirtem/6601682c4a3a79e1ed5e8bbeb801e407

Server log i cant give, how i say, it's LAN connection and i dont know how to open console in this way. I hope this all is not useless information Xd
