### ISSUE TITLE
Breeding Bees results in the wrong bee (e.g. Mason+Crystalline gave Lumber Bee)

### ISSUE THREAD

**Issue by demfels** [JDKDigital/productive-bees#73]
Running Minecraft 1.15.2 and using mod version 0.2.5.1.jar.

All bees when breeding with another bee type are giving a random version bee.  Similar issue to https://github.com/JDKDigital/productive-bees/issues/71, but instead of it giving a random comb on restart it is giving a random bee type after breeding, changes type given upon restart.

**Comment by JaisDK** [comment]
Lovely, I'll change all the recipe lookups to be like the comb in the next version.

**Comment by JaisDK** [comment]
You have a messed up world :) but anyway I have it fixed in the next version
