### ISSUE TITLE
[1.16.1] Suggestion: Config for turning off automatic reproducing

### ISSUE THREAD

**Issue by NillerMedDild** [JDKDigital/productive-bees#74]
I would like to suggest a config for turning off automatic reproduction of bees. The amount of bees can get a bit out of hand on servers I've been told. 

I hope you'll consider it :)

**Comment by JaisDK** [comment]
I'll see what I can do. That mechanic is the only way to get Neon Cuckoo Bees and Nomad Bees, so I'll nee to think of another way to get them.
Right now any extra solitary bees that do not find a home within 10 minutes will die automatically.

**Comment by NillerMedDild** [comment]
Thank you :) I hope it's clear that I'm talking about breeding, and not nest spawning.

**Comment by JaisDK** [comment]
Bees don't breed automatically. Only the solitary bees when living in nests produce offspring automatically.

**Comment by NillerMedDild** [comment]
I see, my bad for not double checking, closing the issue :)

**Comment by JaisDK** [comment]
No problem ;) If you have any other suggestions to make the mod better in a modpack, let me know!

**Comment by NillerMedDild** [comment]
Will do, thanks!
