### ISSUE TITLE
reed nest crashes game

### ISSUE THREAD

**Issue by name2029** [JDKDigital/productive-bees#75]
reed nest will crash the game a few seconds after placement

**Comment by name2029** [comment]
crash log 
 ok here it is 

-- Head ---- Head --Thread: Server threadStacktrace: at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.getBeeList(AdvancedBeehiveTileEntityAbstract.java:326) at cy.jdkdigital.productivebees.tileentity.AdvancedBeehiveTileEntityAbstract.func_226969_f_(AdvancedBeehiveTileEntityAbstract.java:145) at cy.jdkdigital.productivebees.tileentity.SolitaryNestTileEntity.canRepopulate(SolitaryNestTileEntity.java:118) at cy.jdkdigital.productivebees.tileentity.SolitaryNestTileEntity.func_73660_a(SolitaryNestTileEntity.java:50)
-- Block entity being ticked --Details: Name: productivebees:solitary_nest // cy.jdkdigital.productivebees.tileentity.SolitaryNestTileEntity Block: Block{productivebees:sugar_cane_nest}[facing=up] Block location: World: (-27,63,50), Chunk: (at 5,3,2 in -2,3; contains blocks -32,0,48 to -17,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511) Block: Block{productivebees:sugar_cane_nest}[facing=up] Block location: World: (-27,63,50), Chunk: (at 5,3,2 in -2,3; contains blocks -32,0,48 to -17,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)Stacktrace: at net.minecraft.world.World.func_217391_K(World.java:491) at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366)
-- Affected level --Details: All players: 1 total; [ServerPlayerEntity['Aedancian'/226, l='ServerLevel[New World]', x=-28.05, y=63.00, z=49.95]] Chunk stats: ServerChunkCache: 2386 Level dimension: minecraft:overworld Level spawn location: World: (-64,67,112), Chunk: (at 0,4,0 in -4,7; contains blocks -64,0,112 to -49,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511) Level time: 1003 game time, 1003 day time Level name: New World Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true Level weather: Rain time: 105089 (now: false), thunder time: 70582 (now: false) Known server brands: forge Level was modded: true Level storage version: 0x04ABD - AnvilStacktrace: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:120) at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) at net.minecraft.server.MinecraftServer$$Lambda$6929/852341295.run(Unknown Source) at java.lang.Thread.run(Thread.java:745)
-- System Details --Details: Minecraft Version: 1.16.2 Minecraft Version ID: 1.16.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_51, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 766901296 bytes (731 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB) CPUs: 8 JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M ModLauncher: 6.1.1+74+master.966c698 ModLauncher launch target: fmlclient ModLauncher naming: srg ModLauncher services:  /mixin-0.8.jar mixin PLUGINSERVICE  /eventbus-3.0.3-service.jar eventbus PLUGINSERVICE  /forge-1.16.2-33.0.22.jar object_holder_definalize PLUGINSERVICE  /forge-1.16.2-33.0.22.jar runtime_enum_extender PLUGINSERVICE  /accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE  /forge-1.16.2-33.0.22.jar capability_inject_definalize PLUGINSERVICE  /forge-1.16.2-33.0.22.jar runtimedistcleaner PLUGINSERVICE  /mixin-0.8.jar mixin TRANSFORMATIONSERVICE  /OptiFine_1.16.2_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE  /forge-1.16.2-33.0.22.jar fml TRANSFORMATIONSERVICE  /OptiForge-MC1.16.2-0.2.3.jar FakeOptiFine TRANSFORMATIONSERVICE  /OptiForge-MC1.16.2-0.2.3.jar optiforge TRANSFORMATIONSERVICE  FML: 33.0 Forge: net.minecraftforge:33.0.22 FML Language Providers:  javafml@33.0 minecraft@1 Mod List:  forge-1.16.2-33.0.22-client.jar Minecraft {minecraft@1.16.2 DONE} OptiForge-MC1.16.2-0.2.3.jar OptiForge {optiforge@0.2.3 DONE} structurize-0.13.57-ALPHA.jar Structurize {structurize@0.13.57-ALPHA DONE} planttech2-0.02.16.jar PlantTech 2 {planttech2@0.02.16 DONE} forge-1.16.2-33.0.22-universal.jar Forge {forge@33.0.22 DONE} VendingMachine-1.16.2-1.0.0.1.jar Vending Machine {vm@1.0.0.1 DONE} minecolonies-0.13.197-ALPHA-universal.jar Minecolonies {minecolonies@0.13.197-ALPHA DONE} refinedstorage-1.9.3.jar Refined Storage {refinedstorage@1.9.3 DONE} Weeping-Angels-1.16.2-1.0.0.jar Weeping Angels {weeping_angels@3.0.0 DONE} SaveYourPets-1.16.2-1.0.0.3.jar Save Your Pets {syp@1.0.0.3 DONE} RingOfRepair-1.16.2-1.2.2.jar Ring of Repair {ring_of_repair@1.2.2 DONE} productivebees-1.16.2-0.2.5.jar Productive Bees {productivebees@1.16.2-0.2.5 DONE} jei-1.16.2-7.1.3.20.jar Just Enough Items {jei@7.1.3.20 DONE} Player Count: 1 / 8; [ServerPlayerEntity['Aedancian'/226, l='ServerLevel[New World]', x=-28.05, y=63.00, z=49.95]] Data Packs: vanilla, mod:optiforge (incompatible), mod:structurize, mod:planttech2 (incompatible), mod:forge (incompatible), mod:vm, mod:minecolonies (incompatible), mod:refinedstorage, mod:weeping_angels (incompatible), mod:syp, mod:ring_of_repair (incompatible), mod:productivebees (incompatible), mod:jei Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'forge' OptiFine Version: OptiFine_1.16.2_HD_U_G3 OptiFine Build: 20200829-104659 Render Distance Chunks: 12 Mipmaps: 4 Anisotropic Filtering: 1 Antialiasing: 0 Multitexture: false Shaders: BSL_v7.2.zip OpenGlVersion: 4.6.0 NVIDIA 432.00 OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2 OpenGlVendor: NVIDIA Corporation CpuCount: 8

**Comment by JaisDK** [comment]
New version is up, can you check if this resolved your issue?

**Comment by name2029** [comment]
k ill check

**Comment by name2029** [comment]
it works tysm

**Comment by JaisDK** [comment]
Awesome :)
