### ISSUE TITLE
[1.16.2] Gold Honeycomb looks extremely green 

### ISSUE THREAD

**Issue by TelepathicGrunt** [JDKDigital/productive-bees#76]
Not sure if this was an intended change but in 1.16.2, Productive Bees's gold honeycomb now looks green and I thought it was the emerald honeycomb at first lol. Was a bit odd. The other honeycombs looks fine

![image](https://user-images.githubusercontent.com/40846040/91907669-4240e000-ec78-11ea-8ec7-349021608e30.png)

**Comment by JaisDK** [comment]
I'm color blind. Is this better?
![2020-09-02 04_51_31-Minecraft_ 1 16 2 - Singleplayer](https://user-images.githubusercontent.com/15868585/91923038-10f7fc80-ecd8-11ea-90a7-20a5ecf82b85.png)

**Comment by TelepathicGrunt** [comment]
Oh I didn't know you were colorblind! To me, it still seems a bit too green which regular gold doesn't have. I can try cloning your repo to try and experiment with the colors more to find one that looks very gold-like. Maybe try #fdf55f or #fad64a ? I think somewhere around there would look good as that's the color from the gold ingot

**Comment by JaisDK** [comment]
The problem is that I am using the tint method, like grass and leaves, so I might have to adjust the base layer. I'll find a proper color, my gf is not color blind so I'll enlist her as test subject :)
