### ISSUE TITLE
[1.16.2] Right clicking any Productive Bees's nest blocks crashes the game

### ISSUE THREAD

**Issue by TelepathicGrunt** [JDKDigital/productive-bees#77]
Here's the logs:
https://hatebin.com/shhvmkknnb

There's not much else to say lol. All I did was place the oak nest, right clicked it, and the game crashed. Tried again with the End Stone Nest and same result. Should be easily reproducible

**Comment by JaisDK** [comment]
Hopefully it's fixed in the new version
