### ISSUE TITLE
0.3.0.jar

### ISSUE THREAD

**Issue by nanonestor** [JDKDigital/productive-bees#78]
I'm running a 1.15.2 dedicated server and forge 31.2.31.

When I updated Productive Bees to 0.3.0 the server would still load - however clients attempting to join world would permanently hang trying to load in.  Unfortunately there is no relevant log information I could see that would be helpful.  Reverting to the previous version available to 1.15.2 resulted in clients successfully logging in.

**Comment by JaisDK** [comment]
Thank you for reporting. Do you still have the server log from when the clients could not log in?

**Comment by JaisDK** [comment]
I've uploaded a hotfix 0.3.1, can you check if that solves your issue?

**Comment by JaisDK** [comment]
0.3.2 has more fixes which should let the clients connect now.

**Comment by nanonestor** [comment]
The 0.3.2 patch seems to fix the issues - i see there was another thread here that got addressed the same thing.  We'd had difficulty logging into the modpack previous to the breaking update here and now login goes through 100% of time - so was something from this mod previously most likely also.  Thanks for clearing up the issues so far!
