### ISSUE TITLE
Forge Server: Netty error; Malformed Byte around Byte 44.

### ISSUE THREAD

**Issue by GradiusLover2000** [JDKDigital/productive-bees#79]
Error reading bee conversion recipe to packet causes multiplayer servers to misbehave, always resulting in a disconnect on the client side, or even a memory leak that OOM's the client.

[debug.log](https://github.com/JDKDigital/productive-bees/files/5170110/debug.log)

Productive Bees 1.16.2 (newest)
Forge (on server) 33.0.22 (on client) 33.0.32
Optifine installed on client

**Comment by JaisDK** [comment]
Thank you for reporting. Do you have a modlist I can see?

**Comment by GradiusLover2000** [comment]
It is a custom modpack.  the mods list can be found in the debug log at the top (scroll down some, look for "found valid mod" lines in the forge debug, that will list all of them for you)

I haven't bothered to write down 102 mod names so...

**Comment by JaisDK** [comment]
That's perfect, I hadn't seen that.

**Comment by JaisDK** [comment]
Could you check if you still have the issue with the hotfix 0.3.1 I just put out? In any case it should provide some better debug info.

**Comment by GradiusLover2000** [comment]
The issue persists, however it is a completely new error message this time (Port closed)

new client-side log:
[debug.log](https://github.com/JDKDigital/productive-bees/files/5171176/debug.log)

The registry loaded and everything, the server simply gave up.

**Comment by JaisDK** [comment]
I am not seeing any errors from my mod anymore, but the file ends in three error from BYG. Did you update this mod recently?
Is it possible to see the server log too? It might have more info.

**Comment by GradiusLover2000** [comment]
the server log does not provide basically any error info at all, not even the debug.

BYG has been the same version whilst testing your mods.  I have a feeling BYG is somehow incompatible with your mod.

**Comment by JaisDK** [comment]
Does everything work without Productive Bees installed?

**Comment by GradiusLover2000** [comment]
yes they do, so, I'm pretty sure now it's a biome's you'll go conflict.

**Comment by JaisDK** [comment]
I'll load up BYG and see if I have any problem. In the meantime there's one more thing to try. In the debug log it looks like there's a discrepancy in the mod list between the server and the client and I am not seeing a mod version check for productive bees
like this one:
`[03Sep2020 22:14:38.075] [Netty Client IO #1/DEBUG] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: Channel 'minecolonies:net-channel' : Version test of '1.0' from server : ACCEPTED`

**Comment by GradiusLover2000** [comment]
to clarify, my modpack works fine on single player, just not via multiplayer.

The server does indeed go through a version check.
![Capture](https://user-images.githubusercontent.com/29958484/92176586-aad5bb80-ee36-11ea-801b-ec00740a64e5.PNG)

**Comment by JaisDK** [comment]
The version check I mean is the one between the client and the server, but it looks like they both have the mod.

**Comment by JaisDK** [comment]
With just BYG and PB 1.16.2 is running fine in SSP. Are you only having issues with server connection or does SSP not work either?

**Comment by GradiusLover2000** [comment]
![image](https://user-images.githubusercontent.com/29958484/92184468-348e8480-ee49-11ea-9667-bfd360c65cdb.png)

you will need to install the mod on a custom forge server on your machine in order to replicate the issue

**Comment by JaisDK** [comment]
I was very tired yesterday :) Got it fixed today and a new version will be approved in just a few minutes.

**Comment by GradiusLover2000** [comment]
Okay, I will install the new update once it's out, and will let you know if it's fixed.

**Comment by JaisDK** [comment]
https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3049559

**Comment by JaisDK** [comment]
I am guessing without PB it works fine?

Do the logs have anything?

**Comment by GradiusLover2000** [comment]
without productive bees it works fine yeah.  the logs seem to say the client gives up sending handshake replies after the "registry: entity type" packet gets sent

![image](https://user-images.githubusercontent.com/29958484/92257675-90025600-eecd-11ea-8b7c-58c4d76b3a01.png)

**Comment by GradiusLover2000** [comment]
![image](https://user-images.githubusercontent.com/29958484/92257849-c9d35c80-eecd-11ea-8046-543512a4dc11.png)

**Comment by GradiusLover2000** [comment]
full client log:
[debug.log](https://github.com/JDKDigital/productive-bees/files/5175757/debug.log)

full server log:
[debug.log](https://github.com/JDKDigital/productive-bees/files/5175758/debug.log)

**Comment by JaisDK** [comment]
Thank you. I will start adding mods from your list to my server and see when it breaks.

**Comment by JaisDK** [comment]
Unable to reproduce, if it still happens with the latest version let me know.
