### ISSUE TITLE
Cuckoo bees

### ISSUE THREAD

**Issue by douyabian** [JDKDigital/productive-bees#81]
Version: productivebees-1.16.1-0.3.2

Hey there, been trying for 2 days to get a nomad bee and was just wondering about what the behaviour for cuckoo bees are as the documentation was abit vague, from what I understood it seems like if a nest is empty and is able to spawn e.g. ashy mining bee, there is a chance for it to spawn a nomad bee instead. 

![2020-09-07_00 18 37](https://user-images.githubusercontent.com/30873473/92330387-20dd5b00-f0a1-11ea-9645-2bcd204f4dab.png)

as you can see, i have 16 sand nests, and all i've been getting are ashy mining bees, so i'm just wondering if I got something wrong or if i'm just unlucky

**Comment by JaisDK** [comment]
Every time the ashy mining bee (or any other solitary bee) return to the nest with pollen it will lay an egg (up to three). The eggs hatch after a while and has a chance to spawn a cuckoo bee instead.

**Comment by douyabian** [comment]
Thank you for the verification, was wondering whether it had to be a fresh nest or egg-ed nest
