### ISSUE TITLE
[1.16.1] Solitary Bees won't leave nest so I can breed them

### ISSUE THREAD

**Issue by Dragnier** [JDKDigital/productive-bees#83]
Could you maybe add an item that would eject all bees from the nest/hive you hit with it but without making them angry?

**Comment by demfels** [comment]
A tip for you on this, is usually right away in the morning all bees will leave their nests.  Therefore sleeping next to the nest is a sure fire way to get the bee to eject from it.

That said, I think this is an awesome enhancement request.  It would be nice to have a smoke gun or something that uses coal and is crafted with a flint/steel.  When you activate it could eject smoke and eject the bees giving them a debuff unable to return to a nest for so many seconds. I just wanted to add my thoughts to your already good idea.  :)

**Comment by JaisDK** [comment]
Solitary bees stay in their nests longer than hive bees stay in hives and they will also not exit during the night.

I'll have a though on how I could force them to exit, the same would be nice for hive bees. This would of course cause them to skip the production for that home trip.

**Comment by JaisDK** [comment]
In the new release you can whack a nest with a stick and get the bee out. It might get angry though so have some honey treats handy.
