### ISSUE TITLE
[1.16.1-0.3.3] typo in datapack json

### ISSUE THREAD

**Issue by bessiq** [JDKDigital/productive-bees#84]
Hey there,

Just wanted to let you know there is a non-allowed character (capital F) in the first line of the following file:
"data\productivebees\recipes\centrifuge\honeycomb_amber.json"
`"type": "pFroductivebees:centrifuge",`

I was able to work around it by overriding it with a datapack, but I imagine many people may not know how to do that. Thanks for the groovy bees!

**Comment by JaisDK** [comment]
nice catch, I'll get that fixed
