### ISSUE TITLE
[1.15.2] Crash with Immersive Engineering

### ISSUE THREAD

**Issue by SonicSpeedster16** [JDKDigital/productive-bees#87]
### Description of the issue:
After creating a new world with both Productive Bees and Immersive Engineering after a few minutes of playing the game will crash to desktop. Removing Productive Bees solves the crash.

### Crashlog:
https://pastebin.com/93bnkVjy

### Versions & Modlist
Minecraft 1.15.2
Forge 31.2.41
Productive Bees 1.15.2-0.3.5
Immersive Engineering 1.15.2-4.0.1-119
Full system info and modlist: https://pastebin.com/fZ8DPQdb

This appears to be similar to #86, but I have created a separate issue since I am running a different version of Minecraft and am getting a different crash. Will also be opening an issue on Productive Bees repo also.

**Comment by SonicSpeedster16** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4328

**Comment by JaisDK** [comment]
I haven't made a 1.15.2 fixed version yet, but I'm working on it, assuming it's the same problem as #86.

**Comment by JaisDK** [comment]
https://www.curseforge.com/minecraft/mc-mods/productivebees/files/3065911

**Comment by SonicSpeedster16** [comment]
Thanks. I tested the new version and it does seem to be fixed (after about 10 minutes of testing), however I encountered a different problem that I will open a new issue for. Thanks!
