### ISSUE TITLE
[1.15.2] Hard lockup using CraftTweaker /reload command

### ISSUE THREAD

**Issue by SonicSpeedster16** [JDKDigital/productive-bees#88]
### Description of the issue:
Modifying CraftTweaker scripts and then issuing a /reload command in game causes a hard lockup. I had to kill the process to be able to get back to the desktop. Removing Productive Bees allows the /reload command to work normally.

### Crashlog:
None, as it did not generate one due to the process being killed.

### Versions & Modlist
Minecraft 1.15.2
Forge 31.2.41
Productive Bees 1.15.2-0.3.5.1
CraftTweaker 6.0.0.44
Full system info and modlist: https://pastebin.com/mpWgmk9i

**Comment by JaisDK** [comment]
Is this why it takes forever to issue the command and adds a lot of memory use?

**Comment by SonicSpeedster16** [comment]
The initial load of the world seems to be fine. I only noticed a problem after tweaking a script and trying to issue a /reload command.

**Comment by JaisDK** [comment]
Found the error, I am doing a recipe reload for each existing bee instead of only once. 0.3.5.2 fixed that.

**Comment by SonicSpeedster16** [comment]
Sorry for the delay in getting back to this.

I just tried 0.3.5.2 and while there is still a slight freeze while the game reloads the recipes, it does not lockup my client like the previous version did.
