### ISSUE TITLE
over generating of bees 1.16.1

### ISSUE THREAD

**Issue by SDUBZ** [JDKDigital/productive-bees#89]
pb: productivebees-1.16.1-0.3.5
forge: 1.16.1-32.0.1085

bees that seem to be affected
/kill @e[type=productivebees:digger_bee]

/kill @e[type=productivebees:sweaty_bee]

14:21:26.435
net.minecraft.client.gui.NewChatGui
Render thread
[CHAT] Killed 1210 entities
14:22:08.007
net.minecraft.client.gui.NewChatGui
Render thread
[CHAT] Killed 1236 entities
14:22:47.944
net.minecraft.client.gui.NewChatGui
Render thread
[CHAT] Killed 1222 entities

**Comment by JaisDK** [comment]
Do you know where they are spawning? It would be interesting to see what is near the nests producing all those bees. There should not be a natural way for the bees to be produced in such numbers.

**Comment by SDUBZ** [comment]
theres just a single nest and a stone mountain , nothing really out of the normal

**Comment by JaisDK** [comment]
can you see where the bees are coming from? Bees don't spawn like other passive mobs, they only spawn from nests. With more than a thousand bees spawning every minute it should be visible where they are coming from.

**Comment by SDUBZ** [comment]
could it be a mod conflict with resourceful bees 
maybe they interacting weirdly 🤔

**Comment by JaisDK** [comment]
There shouldn't be a problem running with Resourceful Bees, they have their own system in place for spawning.

Is it a world that has been running for a long time? In previous versions the solitary bees would fly off to unloaded chunks and they would gather in huge numbers. In the later version though they are set to die off after 10 minutes if they do not find a nest to live in.

Do you need to kill off bees every few minutes or was it a one time thing for each of the solitary bees?

**Comment by SDUBZ** [comment]
![2020-10-07_01 22 21](https://user-images.githubusercontent.com/14084377/95216230-8c9c1a80-083d-11eb-8435-c8702fd63824.png)
![2020-10-07_01 22 37](https://user-images.githubusercontent.com/14084377/95216244-90c83800-083d-11eb-87a3-23c13f2740bd.png)

the spawning was happening after a week to that size and yes the world is old now

**Comment by SDUBZ** [comment]
the yellow dots is bees n the map

**Comment by JaisDK** [comment]
So it takes a week to reach 1200 of each of the bees, but the number will keep going up?

The bees should die off after 10 minutes if they don't have a nest to live in, but clearly that part is not working out. The only thing I can think of is that all the bees that are spawning get to have a go at the nest and therefore will be marked as having a home. This mark will prevent them from dying.
I will need to do some testing to find out why this could be happening.

**Comment by JaisDK** [comment]
You can safely destroy the nests for now to stop further spawns. If you use the right tool it will drop with the bee inside.

**Comment by SDUBZ** [comment]
i put a chunk loader in the area to test if they die off and it seems they do after awhile
![2020-10-07_02 12 04](https://user-images.githubusercontent.com/14084377/95220755-8492a980-0842-11eb-8ec3-b8423dd51f0a.png)

**Comment by JaisDK** [comment]
there might be a problem if the nests are right at the edge of the loaded chunks, the bees would be able to spawn and then get unloaded when flying around a little and then not die off

**Comment by kwg** [comment]
I put 3 nests in cells, each cell was 3x3x3, in the nether. Each cell was entirely inside of the chunk (2 in one, 1 in another) and the chunks were not force loaded. If I stay in the nether it takes a long time (many minutes) for a bee to spawn. If I stay in the overworld for a few hours, each cell is packed with bees. 30+

Not sure if this can help. I can dig more into it later today.

productivebees-1.16.1-0.3.3
(Enigmatica 6 - 0.2.17)

**Comment by JaisDK** [comment]
Bee eggs have been removed in 0.4.1
