### ISSUE TITLE
Can't craft sand nest

### ISSUE THREAD

**Issue by mouse0270** [JDKDigital/productive-bees#9]
This might be fixed in 0.1.3 but in 0.1.2 the reed nest and sand nest both use a wooden sword and sand block, so when trying to craft a sand nest you instead craft a reed best.

**Comment by mouse0270** [comment]
Also, I can't seem to place a reed nest... might be doing something wrong though.

**Comment by JaisDK** [comment]
Damn, wish i had seen this earlier so I could get a fix for 0.1.4. 
The reed nest needs to be placed on top of a sugar cane.
The sand nest does not spawn any unique bees, so you can substitute with coarse dirt or gravel as they spawn the same bees as sand. Note that gravel nests has to be placed in river biomes, but coarse dirt can spawn bees anywhere.
Next version will have some improved JEI integration for nests to show exactly which bees spawn in which nests etc.
