### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alxpettit** [JDKDigital/productive-bees#91]
Would you consider releasing the source under an open license such as GNU GPLv3 or MIT?

**Comment by JaisDK** [comment]
Sure thing

**Comment by alxpettit** [comment]
@JaisDK Awesome! Thanks, GNU GPLv3 is my favorite. I'm assembling a modpack of only open-source licensed mods and I'll be sure to include yours :D

**Comment by JaisDK** [comment]
Souns good, which modpack are you working on?

**Comment by JaisDK** [comment]
If you need help adding your own bees, just drop into the discord.

**Comment by alxpettit** [comment]
I'm making a fabric modpack called 'weebcraft', but...

Sadly it turns out for some reason I thought this was a fabric mod, but it's forge. I am really sundowning lately it seems. :sweat_smile:

Still, it's an awesome mod. Maybe I should take a crack at porting it to Fabric some time, if you don't mind :D

**Comment by JaisDK** [comment]
Porting to Fabric would be too much work now, I am not even done with the Forge version. Maye some day in the future.

**Comment by alxpettit** [comment]
No, I meant that *I* would port it. :P
