### ISSUE TITLE
[1.16.3] changing worldgen config doesn't affect worldgen

### ISSUE THREAD

**Issue by PixiuFox** [JDKDigital/productive-bees#93]
Minecraft version: 1.16.3
Forge Version: 34.1.18
Productive Bees Version: 1.16.3-0.4.0.1

I prefer playing productive bees with all nest worldgen config off. However, with all worldgen config set to false, I still got worldgen such as reeds nest in a brand new world. It seems like actual wolrdgen is unaffected by config. Is there another way to turn off the worldgen?

Thank you for making such a great mod!

<img width="489" alt="Screenshot 2020-10-12 at 2 48 42 PM" src="https://user-images.githubusercontent.com/6300992/95714820-5de9ce00-0c9b-11eb-8759-6484a1ccdc73.png">
![2020-10-12_14 39 05](https://user-images.githubusercontent.com/6300992/95714833-63471880-0c9b-11eb-87ad-e55cd34a4f61.png)

**Comment by JaisDK** [comment]
I can see that two of the nest generation features do not check for the config, this would be reed nests and nether quartz nests. I'll get that sorted in the minor release coming out this week. Unfortunately there's no other way of preventing the world gen.

Thanks for reporting, I'm glad you like the mod :)

**Comment by JaisDK** [comment]
Fixed in 0.4.1
