### ISSUE TITLE
Ocassional crash caused by bee rendering

### ISSUE THREAD

**Issue by CorgiZero** [JDKDigital/productive-bees#95]
I'm not sure what's causing the issue beyond the crash being due to an entity being rendered and that the crash happens infrequently, most likely when the problem bee exits the hive.

[crash-2020-10-15_19.36.38-client.txt](https://github.com/JDKDigital/productive-bees/files/5388610/crash-2020-10-15_19.36.38-client.txt)

**Comment by JaisDK** [comment]
Do you know which bee this could be?

**Comment by CorgiZero** [comment]
No, all I know is from what I could understand from the crash log. The crash doesn't happen immediately upon entering the game, but usually 5 - 10 min after playing. I've got crystalline, iron, tin and vanilla bees and had two dirt hives until after the first crash.

**Comment by JaisDK** [comment]
I don't know why there was a problem, but in the latest version I did include a check so it should not crash anymore.

**Comment by CorgiZero** [comment]
That's great to hear! Thanks for responding and making such a fun mod.
