### ISSUE TITLE
1.15.2-0.4.1.3 Fails to load world on dedicated server

### ISSUE THREAD

**Issue by nanonestor** [JDKDigital/productive-bees#99]
As mentioned in subject line - version 1.15.2-0.4.1.3 fails to have a dedicated server world load properly.  The run doesn't crash - it hangs up at some point on load.  Pastebin of latest.log below.  Forge version used 31.2.45.  Reverting to 0.4.1.1 world loads.  Tested half a dozen times.

I really do like this mod and would like to continue adding it to my curseforge modpack, but 50% of the time these builds are not compatible with dedicated servers working correctly.

[https://pastebin.com/PMsrQDtR](url)

**Comment by JaisDK** [comment]
Can you provide the debug.log file instead of latest.log, it might have some more info.

**Comment by nanonestor** [comment]
[debug-4.log](https://github.com/JDKDigital/productive-bees/files/5398144/debug-4.log)

Does this work? It's too big of a file to put on pastebin unless several pastes are done.

**Comment by JaisDK** [comment]
There's not a whole lot changed between those versions and my server is not throwing up on the latest version. What about 0.4.1.2?

There was a config value that was renamed, a new block added and some recipe changes. If the recipes had problems you would see clients not being able to connect, not a world load problem.

**Comment by JaisDK** [comment]
Looks like there's a general problem with v0.4.1.3

**Comment by JaisDK** [comment]
new version is out with a fix
